### ISSUE TITLE
Unwanted babel-jest dependency

### ISSUE THREAD

**Issue by saitonakamura** [erikras/redux-form#3542] opened 2017-10-18 17:52 UTC
Current package depends on `babel-jest` as dependency (not a `devDependency`), but I believe it's a mistake. Dependency was introduced somewhere between `7.0.4` and `7.1.1`

**Comment by carlosrberto** [comment] 2017-10-18 19:26
Same problem here! I've some conflicts with my dependencies.

**Comment by gustavohenke** [comment] 2017-10-18 21:02
This is fixed, but unpublished yet.
Please look at closed issues before opening.

Duplicate of #3527
Duplicate of #3498

**Closed by gustavohenke** 2017-10-18 21:02 UTC

**Comment by saitonakamura** [comment] 2017-10-19 08:54
Sorry I looked just for the opened issue. Maybe it's a good idea to keep issue open until it's published? Cause most of the users of this package will get it through the npm registry, hence they'll be unable to fetch updated version until it'll be published?

**Comment by brucewpaul** [comment] 2017-10-19 20:47
is there another release scheduled?
