### ISSUE TITLE
Return warnings from asyncValidate

### ISSUE THREAD

**Issue by nfort** [erikras/redux-form#2977] opened 2017-05-29 10:53 UTC
### Are you submitting a **bug report** or a **feature request**?

**feature request**

### What is the expected behavior?
Now function asyncValidate return Promise with errors

```
asyncValidate : (values:Object, dispatch:Function, props:Object, blurredField:String) => Promise<undefined, errors:Object> [optional]
```

I would like to suggest you to extend this behaviour. If you get warning message for a field, then it would be nice to return object with properties { errors: Object, warning: Object }

i.e.

```
asyncValidate : (values:Object, dispatch:Function, props:Object, blurredField:String) => Promise<undefined, fields: {errors: Object, warnings: Object }> [optional]
```

**Comment by gustavohenke** [comment] 2017-05-29 12:23
Duplicate of #2827.

**Closed by gustavohenke** 2017-05-29 12:23 UTC
Labels: duplicate
