### ISSUE TITLE
int  always convert  string

### ISSUE THREAD

**Issue by qq645381995** [erikras/redux-form#1852] opened 2016-09-23 06:37 UTC

**Comment by qq645381995** [comment] 2016-09-23 06:38
{id:1}   -->  {id:"2"}

**Comment by qq645381995** [comment] 2016-09-23 06:39
send need  parseInt(id)

**Comment by erikras** [comment] 2016-09-23 20:28
Low English, ok. 👍 [`parse` prop](http://redux-form.com/6.0.5/docs/api/Field.md/#-parse-value-parsedvalue-optional-)

```jsx
const parse = value => value === undefined ? undefined : parseInt(value)

...

<Field name="id" parse={parse}/>
```
Does that help?

**Comment by gustavohenke** [comment] 2016-12-27 13:28
> Does that help?

As it's been a while, I will consider this as "yes".
Also this issue seems like a duplicate of #1377

**Closed by gustavohenke** 2016-12-27 13:28 UTC

**Comment by Noitidart** [comment] 2017-05-21 11:01
@erikras is there any way to parseOut and parseIn? Because in react native the `<TextInput>` element requires a string value, if it doesn't it throws a warning. So when coming in I need to do a `.toString()` and when going to submit I need to do `parseInt()`

**Comment by Noitidart** [comment] 2017-08-04 13:42
Bump on `parseIn` vs `parseOut`. Is this possible folks?

**Comment by erikras** [comment] 2017-08-04 14:07
@Noitidart Isn't `format()` what you need? See [Value Lifecycle](http://redux-form.com/7.0.3/docs/ValueLifecycle.md/).
