### ISSUE TITLE
Caret position goes to the end when clicked and typed in the middle or start

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#2049] opened 2016-10-31 03:47 UTC
I see a very weird thing - when I write anything in the form field, click in the middle or start and start typing again, the caret goes to the end of the string. 

I found similar issue with normalization ( #1396 ), but I don't use any. The only message I found - [this one](https://github.com/erikras/redux-form/pull/1896#issuecomment-255677441) in PR.

I noticed that `Field` component is rerendered on every value change / focus / blur, maybe this is somehow related. I don't see this effect in the docs page though.

<details>
  <summary>Issue gif</summary>

  ![redux-form](https://cloud.githubusercontent.com/assets/6711845/19843179/e7d1767c-9f30-11e6-8173-4ea9672b05c4.gif)

</details>

<details>
  <summary>Form component (from getting started)</summary>

```jsx
import React, { Component } from 'react'
import { Field, reduxForm } from 'redux-form'

class ContactForm extends Component {
  render() {
    const { handleSubmit } = this.props
    return (
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="firstName">First Name</label>
          <Field name="firstName" component="input" type="text" />
        </div>
        <button type="submit">Submit</button>
      </form>
    )
  }
}

ContactForm = reduxForm({
  form: 'contact' // a unique name for this form
})(ContactForm)

class FormComponent extends React.Component {
  handleSubmit = (values) => {
    // Do something with the form values
    console.log(values)
  }
  render() {
    return (
      <ContactForm onSubmit={this.handleSubmit} />
    )
  }
}

export default FormComponent
```

</details>

<details>
  <summary>Index file</summary>

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import { combineReducers, createStore } from 'redux'
import { Provider } from 'react-redux'
import { Router, Route, browserHistory } from 'react-router'
import { reducer as formReducer } from 'redux-form'
import FormComponent from './FormComponent'
import './styles.scss'

const reducers = combineReducers({
  form: formReducer
})

const store = createStore(reducers)

ReactDOM.render(
  <Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/test" component={FormComponent} />
    </Router>
  </Provider>,
  document.getElementById('app')
)
```

</details>

<details>
  <summary>Package versions (latest)</summary>

  - react 15.3.2
  - react-router 3.0.0
  - redux 3.6.0
  - react-redux 5.0.0-beta.3
  - redux-form 6.1.1
  - node 7.0.0
  - npm 3.10.8
  - macOS 10.12.1
  - chrome / safari

</details>

**Comment by Niondir** [comment] 2016-10-31 14:41
I have the same issue. I use textarea and innput components in the same way and the issue only comes for  input fields:

```
case "text":
                return <Field name={setting.id} component="textarea" rows="3" placeholder={setting.description}/>;
            case "string":
                return <Field name={setting.id} component="input" type="text" placeholder={setting.description}/>;
```

I was tracking `render` and `componentWillUpdate` on the level of my component and there is no unnecessary calls from my side. So I guess the issue is somewhere in the implementation of the input component.

**Comment by andresgutgon** [comment] 2016-11-02 09:13
Same here. I just notice in my code a plain redux-form input field like this:
``` javascript
<Field name='email' type='text' component='input' />
```

Works as expected. The caret position works like a plain DOM input. But when I change `react-router` and back to the form caret position jumps to the end

Example:
![plainreduxform](https://cloud.githubusercontent.com/assets/49499/19922869/ddb92efe-a0e4-11e6-8f10-64664c520ddb.gif)

**Comment by enricostano** [comment] 2016-11-02 13:44
Same here.

As a side note I can reproduce the issue only in Chrome 54, Firefox 49 works as expected (Linux).

**Comment by andresgutgon** [comment] 2016-11-02 20:49
After fighting all day with the annoying jumping cursor :/ 

The bug has disappear after upgrade:

1. `react-router` from `2.0.0` => `3.0.0` 
2. `react-router-redux` from `3.0.0` => `4.0.6`.
3. `react` from `15.0.0` => `15.3.2`

New version of router touch less redux state. Could be related in some way with re-render and jumping caret?

As I said the bug occurred when I navigated. 

I hope this can help someone or least be a clue :)

**Comment by erikras** [comment] 2016-11-02 21:32
This is very bizarre. If the bug went away when upgrading other libraries, the fault must lie with the other libraries, no?

**Comment by andresgutgon** [comment] 2016-11-02 21:35
> If the bug went away when upgrading other libraries, the fault must lie with the other libraries, no?

Maybe. But why/how can affect react-router or react to caret position. 

I can understand react. Maybe they changed some DOM/input internal. But react-router? I don't know. All this caret thing has been very frustrating. The only positive think is that I've studied all react-forms files :)

**Comment by erikras** [comment] 2016-11-02 21:42
> But why/how can affect react-router or react to caret position.

I think it could if it rerendered a new fresh set of DOM nodes, since the caret position is kept in the DOM node. If you remove your `<input/>` and add it again to the DOM, your caret position will be reset.

**Comment by andresgutgon** [comment] 2016-11-02 21:48
I think that was the issue. On a fresh browser refresh the jumping caret bug was not happening. But when I navigated with react-router the bug appeared.  Something happened and my app started to do extra renders.

**Comment by Niondir** [comment] 2016-11-04 09:19
I can confirm that updating react from `15.0.0`=> `15.3.2` fixes the issue. Thanks a lot for testing this.

So it seems to be just a React related issue between this version.

**Comment by andresgutgon** [comment] 2016-11-04 10:19
Nice! :)

**Comment by VladShcherbin** [comment] 2016-11-11 05:56
Unfortunately, I used react 15.3.2 when I found this bug. It can be related to `react-redux 5.0.0-beta.3`.

Issue - https://github.com/reactjs/react-redux/issues/525

**Comment by Niondir** [comment] 2016-11-11 10:01
Or a mixture. For me the react upgrade was sufficient. But you can have a look of the full list of dependencies here: https://gitlab.com/lobaro/iot-dashboard/blob/master/package.json

I do not use the latest `react-redux` so it could be that something breaks with that again.

**Comment by davidfurlong** [comment] 2016-11-24 20:54
this thread was really hard to find despite it being exactly the issue I was encountering. (1 day of debugging) - Adding the word "Cursor" in the hopes that search for this bug improves

**Comment by davidfurlong** [comment] 2016-11-24 20:59
> think that was the issue. On a fresh browser refresh the jumping caret bug was not happening. But when I navigated with react-router the bug appeared. Something happened and my app started to do extra renders.

I had this bug regardless of react-router navigation. I have tried everything and simplified the code to be identical to the example (no normalization)

**Comment by nktssh** [comment] 2017-01-22 19:17
This behavior is also reproducible when you attaching `normalize` lifecycle hook to `Field`, e.g. uppercase all the values.

**Comment by mattkrick** [comment] 2017-03-18 01:12
this just started happening & i have no idea why.

react: 15.4.2
react-router: 2.8.1
react-redux: 4.4.6 and 5.0.3 (tested both)

an ugly hacky solution:
```
<Textarea {...input} defaultValue={input.value} value={undefined}/>
```

**Comment by Niondir** [comment] 2017-03-22 12:01
Give it a try with other versions. Maybe we can narrow down the reason.

**Comment by AlexJF** [comment] 2017-05-15 13:17
Just noticed this on my app with latest versions of react (15.5.4), react-redux (5.0.4), react-router-dom (4.1.1) and react-router-redux (next).

In the end, the culprit had been a thunk-like middleware we were using that made dispatch consistently return a promise so you could use `dispatch(...).then()` without having to worry if the parameter to `dispatch` was a simple object or a thunk action:

```
export default function thunk(thunkArgument: any = undefined) {
  return ({ dispatch, getState }: Object) => (next: F) => (action: F) => {
    return Promise.resolve(action)
        .then(resolvedAction => {
          if (typeof resolvedAction === 'function') {
            return resolvedAction(dispatch, getState, thunkArgument);
          } else {
            return next(resolvedAction);
          }
        });
  };
}
```

Making the middleware return `next(action)` with simple action objects fixed it for me:

```
export default function thunk(thunkArgument: any = undefined) {
  return ({ dispatch, getState }: Object) => (next: F) => (action: F) => {
    if (typeof action === 'function') {
      return Promise.resolve(action(dispatch, getState, thunkArgument));
    } else {
      return next(action);
    }
  };
}
```

Wrapping next(resolvedAction) in a promise was apparently breaking what would otherwise be an atomic store update into a series of asynchronous store updates and thus breaking some of the update/rerender checks. For instance, when initializing the form I'd see the following prints inside the reduxForm's componentShouldUpdate:

```
client.js:75744 registeredFields changed undefined ==> Object {name1: Object}
client.js:75744 registeredFields changed Object {name1: Object} ==> Object {name1: Object, name: Object}
client.js:75744 registeredFields changed Object {name1: Object, name: Object} ==> Object {name1: Object, name: Object, email: Object}
client.js:75744 registeredFields changed Object {name1: Object, name: Object, email: Object} ==> Object {name1: Object, name: Object, email: Object, password: Object}
client.js:75744 registeredFields changed Object {name1: Object, name: Object, email: Object, password: Object} ==> Object {name1: Object, name: Object, email: Object, password: Object, passwordRepeat: Object}
client.js:75744 registeredFields changed Object {name1: Object, name: Object, email: Object, password: Object, passwordRepeat: Object} ==> Object {name1: Object, name: Object, email: Object, password: Object, passwordRepeat: Object…}
```

Compared with the following when using redux-thunk or the modified thunk code mentioned above:

```
client.js:75740 registeredFields changed Object {name1: Object, name: Object, email: Object, password: Object, passwordRepeat: Object…} ==> Object {name1: Object, name: Object, email: Object, password: Object, passwordRepeat: Object…}
```

Sharing this in case someone else is also doing some kind of non-standard thunk shenanigans. I've since reverted our thunk to `redux-thunk`'s implementation and everything is working fine :)

**Comment by linde12** [comment] 2017-06-07 13:35
I've got the same problem as described with the jumping cursor(without e.g. number formatting). For me it works using react-redux@5.0.0-rc.1 but breaks again in rc.2(since they replaced the previous fix with another one). It's also rumored that it will be fixed in React with version 16. But seeing that the temporary fix in react-redux still doesn't play well with redux-form, there has to be some other problem making them incompatible?

I'm not sure how to reproduce it without using redux-form, as i have only seen the bug in combination with redux-form :confused:

**Comment by gustavohenke** [comment] 2017-12-06 23:21
Because this issue saw almost no activity for a few months, I'm closing it.

**Closed by gustavohenke** 2017-12-06 23:21 UTC
