### ISSUE TITLE
Normalize doesn't work when dropping text to field

### ISSUE THREAD

**Issue by likerRr** [erikras/redux-form#3916] opened 2018-03-15 13:00 UTC
### What is the current behavior?
Type something in "Username" field, then select that text and drag it to "Shout" field then drop it.
![normalize doesn t work on text drop](https://user-images.githubusercontent.com/1290558/37464541-aeb06e52-2869-11e8-9812-70cf0700950c.gif)

### What is the expected behavior?
Dropped text becomes uppercased

### What's your environment?
It reproduces right on documentation page. Ubuntu 16.04
https://redux-form.com/7.3.0/examples/normalizing/

**Comment by gustavohenke** [comment] 2018-03-15 13:10
Duplicate of #3375

**Closed by gustavohenke** 2018-03-15 13:10 UTC
