### ISSUE TITLE
Unregistered then reregistered fields lose validation status

### ISSUE THREAD

**Issue by Elliot128** [erikras/redux-form#3757] opened 2018-01-15 23:34 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

Have a redux form using form level validation that has a dropdown that defines which component to render to the form. Each of the components shares a field. When I choose a different dropdown, the validation runs and saves to state and then is erased during the`UNREGISTER_FIELD` action for the common field.

In this case, the unregistered common field loses its syncErrors because it is unregistered first, then reregistered. 

Everywhere else in my forms I see registered field actions before unregister and validations work as expected. In this case I see that one common field unregistering before anything else.

### What is the expected behavior?
As I understand, if there are multiple input looking to the same field, unregistering one of them should not remove the sync_errors, so I might expect redux-forms to register the new field for the common component first to avoid losing syncErrors.

### What's your environment?

Redux Form version: 7.2.0

### Other information

Looks related to https://github.com/erikras/redux-form/issues/3566

**Comment by Elliot128** [comment] 2018-01-16 21:34
I have tried passing in field level validations as a workaround but ran into the same issue  as in https://github.com/erikras/redux-form/issues/3566

**Comment by sartios** [comment] 2018-01-30 14:25
I use an older version v6.8.0 and have the same issue. A workaround to force sync validation on submit is to provide your form the following function:

shouldValidate: () => true

const mapDispatchToProps = (dispatch) => ({
.....
shouldValidate: () => true
})

**Comment by Elliot128** [comment] 2018-02-06 02:11
Interesting, we ended up putting a duplicate of the common field at the top of the form so it wouldn't unregister.

**Comment by jpolo** [comment] 2018-03-20 09:16
I had the same problem using validate=[...]. I used a validator that returns a new validator closure. The consequence is that the field is always unregistered then registered.
Although creating closure in the render is not recommended for performance, but it should not provoke such kind of behavior...

**Comment by k4st0r42** [comment] 2018-03-28 09:47
I have the same problem #3940
Do you have a solution ?

**Comment by danielrob** [comment] 2018-05-05 06:15
@jpolo see #4017, your issue is unrelated. 

@Elliot128 could you please provide a sandbox reproduction?

**Comment by danielrob** [comment] 2018-05-05 08:32
@jpolo, yes and that's what #4017 addresses but it's not what @Elliot128 was raising here (as far as I can tell) (even if it is related). It's best to keep distinct issues distinct.

**Comment by ldanet** [comment] 2018-07-24 23:58
I created a sandbox that shows the form level validation failing when unmounting/mounting fields which share the same name:
https://codesandbox.io/s/l5l5mzoqj9

If you select a colour and try to submit the form straight away, it won't let you and it will show the required fields error.
If you then switch colour, validation errors get removed from the state when the fields are unregistered, and registering the fields again doesn't put the errors back. We are able to submit the form without filling the required fields.

**Comment by danielrob** [comment] 2018-07-28 11:18
@idanet I opened your sandbox and followed your instructions, and I cannot reproduce the results you suggest. 

Regardless this was fixed in 7.4.2 by #3909.

**Closed by danielrob** 2018-07-28 11:18 UTC
Labels: c:form-level-validation, needs sandbox
