### ISSUE TITLE
Form stays invalid after correcting errors during submit validation

### ISSUE THREAD

**Issue by ericvaladas** [erikras/redux-form#1622] opened 2016-08-25 16:08 UTC
This issue appears to be new in v6 and did not exist in 6.0.0-rc.5. 

You can reproduce this issue on the [Submit Validation example](http://redux-form.com/6.0.1/examples/submitValidation/).

Steps to reproduce:
1. Do not fill out any fields.
2. Click the Log In button to submit the form. You should have the "User does not exist" error.
3. Correct the error by adding a value to the Username field.
4. Click the Log In button again. The form does not submit or re-validate. 

It looks like the `valid` prop on the form is still `false` after correcting the errors. Is it possible the special form error "Login failed!" is counting towards remaining errors, preventing valid from becoming `true`?

**Comment by jmeas** [comment] 2016-08-25 16:31
Please teach me things

**Comment by JSHARP-** [comment] 2016-08-25 21:35
+1

**Comment by erikras** [comment] 2016-08-25 22:06
Well, finding the first post-release bug didn't take long. 😄  Will investigate tomorrow. 🔍

**Comment by cruciux** [comment] 2016-08-26 19:31
@erikras I'm also getting this, but I think the bug is actually simpler. If I submit a form and throw a SubmissionError (or reject and pass back the error), my error will get shown successfully on the page, but I can **never** submit the form again after that first rejection.

If I resolve the promise instead, I can continually re-submit the form fine.

**Comment by larkintuckerllc** [comment] 2016-09-04 11:06
I ran into what appears to be similar troubles and have worked around it.  On some earlier documentation (not sure where), I saw an example where I was to throw a SubmissionError with the content of {  _error: 'message' } and I could detect the error in my component with the property of "error".

When used this technique on an earlier version of redux-form, I got my expected behavior, i.e., I get the error property set but the form itself stays valid.  This means that I could try to submit the form again right away.

On this newer version (was 6.0.1 and now upgraded to 6.0.2), the behavior is different.  It appears the object that you send back on SubmissionError is actually used as a validation result (much like the sync validation).  I was still getting the "error" property as expected but the form was being flagged as invalid (and I could not post because I was disabling my submit button on invalid).

The work-around that I used was that I observed that my form was getting a "submitFailed" property that I could use to detect the submit failure (instead of looking for "error").  So now I submit the error with an empty object (just like a successful sync validation) and now the form stays valid after the failure.

The added bonus is that I can now send back targeted validation errors on a failed submit, e.g.,. { id: 'duplicate id' }.  This error can then also show next to the field in question.

I have incorporated this change into my react-redux-boilerplate project that I use to start up my projects.

https://bitbucket.org/sign_age/react-redux-boilerplate

**Comment by alvelig** [comment] 2016-09-15 03:11
@larkintuckerllc you saved my day!

In my opinion there should be a way to update errors and thus make the form revalidate, or clear errors manually. 

For example, I submit the form, get SubmissionError, do some external stuff to complete the submission requirements (in a modal for instance) and when completed set the form valid and submit it again (from the modal)...

**Comment by wlingke** [comment] 2016-09-16 00:52
any movement on this issue yet?

**Comment by alexscarlett** [comment] 2016-12-16 23:50
Anybody still experiencing this issue with 6.2, set `persistentSubmitErrors` to `true` and the form will never fail to submit.

**Comment by Amurmurmur** [comment] 2017-04-03 20:43
Having this issue :/

SyncValidation will never let me post the form. copied example of syncvalidation form, it just says required on all fields.

using react-boilerplate as a base for my project,

Also using 
`import { Field, reduxForm } from 'redux-form/immutable'`
As it is needed by the react-boilerplate.

Any help will be greatly appreciated!

**Comment by danielrob** [comment] 2017-08-04 04:42
Closing this issue as I followed the reproduction steps to verify the bug on 6.0.1 but cannot reproduce on 7.0.3 (was probably fixed on 6.0.5 as @wlingke mentioned). 

@Amurmurmur, @alexscarlett if you are still facing those issues, please raise a bug report with reproduction steps and / or reproduction sandbox. Thanks!

**Closed by danielrob** 2017-08-04 04:42 UTC
