### ISSUE TITLE
[6.0.1] Dependent Input Field loses focus 

### ISSUE THREAD

**Issue by sbondaryev** [erikras/redux-form#1672] opened 2016-08-31 23:22 UTC
I try to use dependent fields (field2 depends of the value of field1) so I wrote a snippet
```
const Form = () =>
  <form>
    <Field name={'field1'} component="input" type="text" />
    <Field name={'field1'}
        component={field => <Field name={'field2'} component="input" type="text" /> } />
  </form>

const Test = reduxForm({form: 'test'})(Form)
```
Field2 input loses the focus when I write in a first symbol, after input works fine
Here it is a screen
![git](https://cloud.githubusercontent.com/assets/2843147/18149733/46342fd0-6fe2-11e6-9b1b-b466dbe85c2f.gif)

UPD: The same when I try to use ```<Fields/>``` as a wrapper

**Comment by jamashita** [comment] 2016-09-01 06:46
I have the same probelm 👍

**Comment by JakeLin1024** [comment] 2016-09-01 06:59
Duplicate of [https://github.com/erikras/redux-form/issues/1094](url) 

<Field name={'field1'}
        component={field => <Field name={'field2'} component="input" type="text" /> } />
This is heavily discouraged.

**Comment by sbondaryev** [comment] 2016-09-01 07:54
@JakeLin1024  I want to refer a value of a field from another one. (For example show the second field only when the first is filled). What is the idiomatic way to do this?

**Comment by Sir4ur0n** [comment] 2016-09-01 08:15
Have you considered using [Fields](http://redux-form.com/6.0.1/docs/api/Fields.md/)?

**Comment by sbondaryev** [comment] 2016-09-01 08:33
@Sir4ur0n : yes, it's the same - actual problem is  using inline arrow functions in component 
@JakeLin1024 : Thanks, after reading https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.14
I rewrote the code with external rendering
```
const depebdentInput = (field) => <Field name={'field2'} component="input" type="text" />
const Form = () =>
  <form>
    <Field name={'field1'} component="input" type="text" />
    <Field names={'field1'} component={depebdentInput} />
  </form>
```
Works fine now.

**Closed** 2016-09-01 08:34 UTC

**Comment by cpsubrian** [comment] 2016-09-07 20:05
👍  Thanks @sbondaryev ! This bit me recently.
