### ISSUE TITLE
Calling `reset` outside onSubmitSuccess and clear value in Redux way will reset the form values but the validation will not kick in

### ISSUE THREAD

**Issue by kinyat** [erikras/redux-form#3112] opened 2017-06-27 04:00 UTC
### What is the current behavior?
If you call `reset` after form submit but outside onSubmitSuccess, you will see your from values are reset. However, if you then submit the form straight away without putting any values in the form, you will see the validation is not triggered and this allow handleSubmit to be triggered with invalid values.

Same thing for using the Redux way (see: http://redux-form.com/6.8.0/docs/faq/HowToClear.md/)

I make the validation work by putting reset inside onSubmitSuccess.

```javascript
onSubmitSuccess: (result, dispatch, props) => {
    dispatch(reset(props.form)) // This will clear the value and tigger the validation
}
```

### What is the expected behavior?
Validation should be trigger after form submit, even if the user doesn't touch the form after submit.

### What's your environment?
Redux Form version: 6.8.0
Node: 7.10.0
OS: Mac OS X

**Comment by danielrob** [comment] 2017-08-07 05:11
I think this is a duplicate of [#2971](https://github.com/erikras/redux-form/issues/2971#issuecomment-309595132). Agreed?

**Closed** 2018-05-17 02:25 UTC
