### ISSUE TITLE
Infinite loop when dynamically building form component

### ISSUE THREAD

**Issue by anyong** [erikras/redux-form#1060] opened 2016-05-27 10:27 UTC
It took me ages to figure this bug out, I guess ultimately the bug was in my code but I think this use case could be better handled by redux-form either to provide an error message or work "as expected".

In this snippet, I'm trying to make a form on the fly either for creating a new object, or editing an existing one:

```js
handleEdit (id) {
    return data => this.props.actions.edit(id, data);
}

handleCreate (data) {
    return this.props.actions.create(data);
}

render () {
    const {
        dialogOpen,
        editById,
        dataSet,
    } = this.props;

    let handleSubmit;
    let formName;
    let initialValues;

    if (editById === false) {
        formName = 'create';
        handleSubmit = this.handleCreate;
        initialValues = {
            // some junk
        }
    } else {
        formName = `edit/${editById}`;
        handleSubmit = this.handleEdit(editById);
        initialValues = dataSet[editById];
    }

    return (
        <FormDialog // redux-form connected component
            form={formName}
            open={dialogOpen}
            onSubmit={handleSubmit}
            initialValues={initialValues}
        />
    );
}
```

There are buttons elsewhere that set `dialogOpen` and `editById`. If I change `editById` from whatever it was set to initially, the form re-renders in an infinite loop. I'm not sure which properties cause this exactly, either `form`, `onSubmit` or `initialValues`, but in any case, the form must be destroyed before it can be re-used, so I would suggest the following fix in redux-form:

For whatever properties cannot be altered without destroying and re-creating the form, if any of those props are altered during runtime, either:

A) destroy and recreate the form automatically or
B) log an error to the console that those properties may not be altered dynamically and stop re-rendering

I'm not sure which solution is better, because (B) is apparently simpler for the user but could potentially lead to unexpected behavior. In my case, I modified the `render` method like this to cause the form to self-destruct when the dialog closes:

```js
render () {
  // ...
  if (!dialogOpen) return null;
  // rest as before
}
```

**Comment by erikras** [comment] 2016-05-27 21:22
[I've made a JSBin](http://jsbin.com/roqikuzoxa/edit?js,output) to attempt to replicate this, but I'm not seeing the behavior you describe.

See if you can replicate it.

**Comment by ooflorent** [comment] 2016-06-25 17:58
I'm closing this since we are unable to reproduce the issue. If I'm wrong, please reopen and provide a sample to highlight the bug.

**Closed by ooflorent** 2016-06-25 17:58 UTC
