### ISSUE TITLE
throw new SubmissionError() causing Uncaught (in promise) error.

### ISSUE THREAD

**Issue by JensenTStava** [erikras/redux-form#2269] opened 2016-12-12 16:43 UTC
Hello! I am using Redux Thunk and React Form to do submission validations against my signup form. I want the errors returned by my API endpoint to appear inline in my form. Hence why I need SubmissionError. Everything works great without throwing a new submission error, the form does exactly what I need it to do. The problem is, when I put in the single line to `throw new SubmissionError()` I get the following error:

![image](https://cloud.githubusercontent.com/assets/4657668/21107356/4094d124-c046-11e6-8c70-2de61769f15d.png)

Here is my Action creator (using Redux Thunk):

```
import axios from 'axios';
import { browserHistory } from 'react-router';
import { CTAButtonUnload } from '../../buttons/CTAButton/CTAButtonUnload'
import { SubmissionError } from 'redux-form'

const ROOT_URL = 'XXXXXXXXXXXXXX';

export const signupUser = (formData) => {
    return function(dispatch) {
        axios.post(ROOT_URL + '/v1/user', {
                firstName: formData.firstName,
                lastName: formData.lastName,
                email: formData.email,
                password: formData.password
            })
            .then(response => {
                dispatch({
                    type: 'CTAButtonUnload',
                    payload: {
                        hover: false,
                        click: false,
                        loading: false
                    }
                })
                browserHistory.push('/signup/workspace');
            })
            .catch(response => {
                if(response.response.data.code == 403){
                    throw new SubmissionError({email: null, _error: response.response.data.description})
                }
                dispatch({
                    type: 'CTAButtonUnload',
                    payload: {
                        hover: false,
                        click: false,
                        loading: false
                    }
                })
            });
    }
}
```

Could this error be caused by a promise inside of `SubmissionError()`? I saw that others have had similar problems with this error, but they look to be using the Async validation option, I am not, so I am wondering if I am doing something wrong or if this is something with reduxForm?

**Comment by dabrowski-adam** [comment] 2016-12-13 14:55
Sorry for being off-topic — but how did you manage to make the thunk work? I didn't see any way to do it and I resorted to passing `dispatch` as a second argument, e.g.


```javascript
export const submitMessage = async (data, dispatch) => {
  try {
    dispatch({ type: SUBMIT_MESSAGE_START });
    await formspree(data);
    dispatch({ type: SUBMIT_MESSAGE_SUCCESS });
  } catch (error) {
    if (error instanceof SubmissionError) {
      dispatch({ type: SUBMIT_MESSAGE_FAIL });
    } else {
      dispatch({ type: SUBMIT_MESSAGE_ERROR });
    }
    throw error;
  
};    
```


However, I did not have any issues with `SubmissionError`. :P

**Comment by JensenTStava** [comment] 2016-12-14 03:25
I think your implementation of Thunk is failing because you are passing dispatch with your data. You need to return it as a promise. But, I think if you do that you are going to run into the same submissionError problem that I have...

**Comment by MikeBarnhardt** [comment] 2016-12-20 17:28
Are you calling `signupUser` from a `reduxForm()`?

You need to either 
* pass `onSubmit={signupUser}` to the component and then put `onSubmit={this.props.handleSubmit}` on the `<form>` 
* **or** call `onSubmit={this.props.handleSubmit(this.props.signupUser)}` directly on `<form>`.

If you are calling it from a `<button>` with `onClick={() => this.props.signupUser()}` it will not work.

**Comment by francosioquim** [comment] 2017-01-25 23:35
I encountered a similar problem and managed to fix this by adding a return on the submit handler.

from 

```javascript
handleSignup = (data) => {
        this.props.actions.signup(data).then((result) => {
            ...
        }).catch((error) => {
            if (error.data.status === 'XXXXXX') {
                throw new SubmissionError({
                    email: 'This email is already registered'
                })
            }
        })
    }
```

to


```javascript
handleSignup = (data) => {
        return this.props.actions.signup(data).then((result) => {
            ...
        }).catch((error) => {
            if (error.data.status === 'XXXXXX') {
                throw new SubmissionError({
                    email: 'This email is already registered'
                })
            }
        })
    }
```
I'm calling `handleSignup()` from my redux form component:


```html
<SignupForm onSubmit={this.handleSignup} />
```

**Comment by devmarwen** [comment] 2017-02-12 19:07
@JensenTStava In your `mapDispatchToProps` you should have this format:

```javascript
const mapDispatchToProps = function(dispatch) {
  return {
    signupUser: (formData) => {
      return dispatch(signupUser(formData)); // Notice the return
    }
  };
};
```

**Comment by kylanhurt** [comment] 2017-02-19 09:05
@JensenTStava  I was under the impression that 'mapsDispatchToProps' was only for version 5 and older.

I would love to see a solution to this issue because I am having a similar problem as the OP.

**Comment by PatrickStrz** [comment] 2017-03-30 04:41
having same issue as OP with version 6.5.0 and 6.6.1

**Comment by valeriisukhov** [comment] 2017-03-30 11:59
@JensenTStava 
I had such bug. 
History:
Everything was cool in dev mode, but after build error was always uncaught. I happened because my builded environment didn't pass 'redux-form' as externals in webpack, so there were issue in reference to SubmissionError object (my action creator went to node_modules for that & form goes to builded stuff inside my index.js).
Find this part of redux-form code and try to debug:
`     try {
        result = submit(values, dispatch, props);
      } catch (submitError) {
        var error = submitError instanceof _SubmissionError2.default ? submitError.errors : undefined;
        stopSubmit(error);
        setSubmitFailed.apply(undefined, _toConsumableArray(fields));
        if (onSubmitFail) {
          onSubmitFail(error, dispatch, submitError, props);
        }
        if (error || onSubmitFail) {
          // if you've provided an onSubmitFail callback, don't re-throw the error
          return error;
        } else {
          throw submitError;
        }
      }`

**Comment by aq1018** [comment] 2017-04-01 02:21
I just encountered this bug today as well. However, the issue is not from `redux-form` but `webpack 2` and / or `babel`.

My code breaks if I imported `SubmissionError` like this:

```
import { SubmissionError } from 'redux-form';

// somewhere in promise chain:
throw  new SubmissionError({errors});
```

But works if I import it like this:

```
import SubmissionError from 'redux-form/lib/SubmissionError'
```

I was able to figure out [this line](https://github.com/erikras/redux-form/blob/master/src/handleSubmit.js#L42
) does `error instanceof SubmissionError` and returning false.

It lead me to believe somehow `webpack 2` is generated two copies `SubmissionError`s...

**Comment by aq1018** [comment] 2017-04-03 17:31
I had some progress on this one. As it turned out, I was using `redux-form/immutable` all over my code, except when importing `SubmissionForm`, I did:

```es
import { SubmissionForm } from 'redux-form';
```

But if you are using `redux-form/immutable`, you need to use:

```es
import { SubmissionForm } from 'redux-form/immutable';
```

Apparently they are two different classes.

**Comment by aq1018** [comment] 2017-04-03 17:33
I think we can close this one now

**Comment by aq1018** [comment] 2017-04-03 17:46
As a suggestion, maybe we can somehow print out warnings in development mode to prevent people from mixing `redux-form` and `redux-form/immutable`? This will probably help a lot of people in this case...

Another possible "solution" is to not use `instanceOf`, but checking via interface such as `error.isReduxFormSubmissionError()` or something...

**Comment by asherwebb** [comment] 2017-05-16 19:35
For me this issue was caused by not adding a return declaration before my ajax call. So instead of `axios.post(URL, payload)` I had to make sure `return axios.post(URL, payload)` was used. The `throw new SubmissionError(…)` call was in the `.catch( error => …` block of the axios call.

**Comment by prattl** [comment] 2017-07-12 16:13
I ran into this problem several times during the upgrade from v5 to v6. For me, this turned out to be an issue between some combination of `webpack-dev-server` and `react-hot-loader`.

After refactoring a form's `submit` function to include the use of `SubmissionError`, I would experience the `Uncaught (in promise) SubmissionError` error until the `webpack-dev-server` was restarted completely. It seems that `react-hot-loader` was not able to pick up the `SubmissionError` import, even after following the migration path to 3.X as outlined in the docs.

**Comment by gustavohenke** [comment] 2017-07-13 00:35
@prattl if you could reduce your issue to something reproducible on redux-form side, it would be great to fix that bug. In this case, please open a new issue.

Since the problem of the OP was related to not returning a promise, I'll close this issue.

**Closed by gustavohenke** 2017-07-13 00:35 UTC

**Comment by StevenXL** [comment] 2017-08-17 15:24
@francosioquim your solution was it. The `handleSubmit` function that `redux-form` defines probably look (conceptually) something like this:

```javascript
function handleSubmit(event) {
   const formValues = getFormValues(event);
   userDefinedSubmit(formValues).catch(
      submissionError => putErrorsInFormState(submissionError)
   )
}
```

I'm abstracting away a lot, but the idea is that `handleSubmit` function will only work if the `userDefinedSubmit` function returns a `thenable`. Thank you!

**Comment by alxvallejo** [comment] 2018-04-10 19:01
@StevenXL What do you mean by `putErrorsInFormState`? Isn't that what `throw new SubmissionError` does?

**Comment by michalica** [comment] 2018-07-06 08:56
I was stuck for one day with this Error. I was returning all promises in Project and I still couldn't figure it out. Then I ran into this https://stackoverflow.com/questions/38481857/getting-cannot-call-a-class-as-a-function-in-my-react-project

I was using react router 4 like this:
`<Route exact path="/events/checkout/:id/" render={(props) => <CheckoutContainer {...props} lang="de" />} />} />`

then I change it into this:
`<Route exact path="/events/checkout/:id/" component={(props) => <CheckoutContainer {...props} lang="de" />} />} />`

So, I just changed `render` to `component` and It is working!
Problem is that `render` most likely treat all components as functional.
