### ISSUE TITLE
Setting initialValues field-by-field like validation?

### ISSUE THREAD

**Issue by timhwang21** [erikras/redux-form#2391] opened 2017-01-05 01:38 UTC
With 6.3.0 we got the awesome feature of writing field-level validations, which is great for making forms more composable. 

Would it be possible to have such a behavior for field-level `initialValues`?

I haven't had the time to dig into it, but I see in [`reduxForm.js`](https://github.com/erikras/redux-form/blob/master/src/reduxForm.js#L182) the field level validators are being combined with the validator passed as a prop:

```javascript
                const { _error, ...nextSyncErrors } = merge(
                  validate ? validate(propsToValidate.values, propsToValidate) || {} : {},
                  fieldLevelValidate ?
                  fieldLevelValidate(propsToValidate.values, propsToValidate) || {} : {}
                )
```

Would the same approach work for `initialValues`? I think this would also really help with reusable fields.

**Comment by rabaut** [comment] 2017-01-05 14:11
+1

**Comment by danielrob** [comment] 2017-08-06 22:44
Closing this as it is a duplicate of #1964. Please continue with this idea there!

**Closed by danielrob** 2017-08-06 22:44 UTC
