### ISSUE TITLE
6.0.0-alpha.15 input file can not set value

### ISSUE THREAD

**Issue by nodeman777** [erikras/redux-form#1143] opened 2016-06-12 13:03 UTC
Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.setValueForProperty @ DOMPropertyOperations.js:140updateWrapper @ ReactDOMInput.js:153forceUpdateIfMounted @ ReactDOMInput.js:36notifyAll @ CallbackQueue.js:66flushBatchedUpdates @ ReactUpdates.js:185closeAll @ Transaction.js:202perform @ Transaction.js:149batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150

any suggestions?

**Comment by eloytoro** [comment] 2016-06-12 13:20
Could you be more specific? Maybe show us your implementation. Also the error message gives you a clue here

**Comment by nodeman777** [comment] 2016-06-12 13:32
@eloytoro 
you can add those code in the example/simple/simpleForom.js

```
<div>
        <label>uploadfile</label>
        <div>
          <Field name="file" component="input" type="file"/>
        </div>
 </div>
```
then,when you click then input,the error will show on your console .

**Comment by eloytoro** [comment] 2016-06-12 16:39
@nodeman777 this is not an issue with redux-form, its something inherent to browser environments.
Steps to reproduce
```javascript
var input = document.createElement('input')
input.setAttribute('type', 'file')
input.value = 'some text' // <- this throws the error you posted above
```
Use an input that allows its value to be modified programatically or write an interface for your input that allows this behaviour

**Comment by nodeman777** [comment] 2016-06-13 01:53
@eloytoro thanks for reply, i know that,but it should cased by redux-form. why redux-form set text value to a file input ?

**Comment by nodeman777** [comment] 2016-06-13 02:02
@eloytoro i set the input readOnly solve this issue, but i still confuse why redux-form set the test value to a file input .

**Comment by chelzwa** [comment] 2016-06-16 21:15
@nodeman777 Have you read this: http://redux-form.com/5.2.5/#/examples/file?_k=z12d2f

Basically, if you remove the value property before passing the redux-form field props to your file input, this should be fixed.

**Comment by erikras** [comment] 2016-06-24 18:24
If someone could write a test case or just share some code to recreate it, that would be very helpful.

**Comment by HriBB** [comment] 2016-06-28 19:17
@erikras I have the same problem with latest beta. It is very easy to reproduce https://github.com/HriBB/redux-form/commit/ab5e5c6b69af5a64d8dd305a019777d538ac3c93

Not really sure how to write a test for input field.

**Comment by erikras** [comment] 2016-06-28 19:38
Well, it turns out we have [a well documented description of how to do this in `v5`](http://redux-form.com/5.2.5/#/examples/file). I have never used file inputs in `redux-form` before (I have used, and recommend [`react-ropzone`](https://github.com/okonet/react-dropzone)), but it looks like React won't let a file component be "controlled", i.e. the `value` must be `null`.

```js
<Field name="file" component="input" type="file" value={null}/>
//                                               ^^^^^^^^^^^^
```
If one of you would confirm that this fixes the problem, I will teach `redux-form` to do it by default in `v6`.

**Comment by HriBB** [comment] 2016-06-28 20:15
I am well aware of the `value={null}` solution, but unfortunately it does not work for me anymore in v6. I tried just about everything now.

```
<Field name="file" type="file" multiple component={(props => (
    <input {...props} value={null} />
))}/>
```
Gives me
```
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
```
Even if I change it to undefined it does not work

**Comment by HriBB** [comment] 2016-06-29 10:35
@erikras can you please take a look a this commit https://github.com/HriBB/redux-form/commit/db49c67718c36ebb2fd6f40ee6485863321e14ba

In this very naive commit I simply delete props.value in ConnectedField render() if type is file
```
if (props.type === 'file') {
    delete props.value;
}
```
This only works when I use `<Field name="file" component="input" type="file"/>`, if I nest input field further down, it does not work.

**Comment by erikras** [comment] 2016-06-29 15:05
@HriBB That's sort of what I had in mind, yes.

**Comment by erikras** [comment] 2016-07-28 08:43
This was fixed by #1265, I think.

**Closed by erikras** 2016-07-28 08:43 UTC
Labels: bug

**Comment by zxydaisy** [comment] 2017-03-16 09:48
<Field
        name="file"
        component={renderInput}
        validate={[ required ]}
        type="file"
      />
![image](https://cloud.githubusercontent.com/assets/16076546/23990338/b1376da0-0a70-11e7-90b8-13f01fbb8b24.png)

**Comment by summerinsect** [comment] 2017-10-13 12:55
i got same problem

```javascript
const renderFilepics = ({
	fields,that
}) => (
  <div id='list'>
	<List selectable ripple className={theme.
		<ListItem
			// avatar='https://dl.dropboxusercontent.com/u/2247264/assets/m.jpg'
	      	caption='add'
	      	rightIcon={'add'}
	      	key={-1}
	      	onClick={() => {if (fields.length<6) fields.push(),addInput(that)}}
      	/>
      	{fields.map((member, index) =>
        <ListItem
          itemContent={<div style={{display:'flex',flex:'1 1 100%',flexWrap:'wrap'}} key={index}><Field style={{display:'flex',flex:'80%'}} name="Filepic" value={null} component="input" type="file"/><FontIcon style={{display:fields.length==index+1?'block':'none'}}onClick={() => fields.remove(index)}>{'clear'}</FontIcon></div>}
          key={index}
            />
	      )}
	</List>
  </div>
)

![image](https://user-images.githubusercontent.com/6075540/31547108-ae342dee-b058-11e7-9c48-23248ce1d020.png)

**Comment by MaxInMoon** [comment] 2018-01-03 15:41
I handled it checking if `value` is not empty:

```jsx
<input
  value={_.isEmpty(input.value) ? null : input.value}
  ...
/>
```

**Comment by nitin-jotwani-iconnect** [comment] 2018-08-02 06:09
Using version `6.5.0`, none of the above solutions works. Any help would be appreciated.

**Comment by nitin-jotwani-iconnect** [comment] 2018-08-02 06:17
`this works` 
https://github.com/erikras/redux-form/issues/1989#issuecomment-287552919
