### ISSUE TITLE
_error key inaccessible outside of form

### ISSUE THREAD

**Issue by TrevorHinesley** [erikras/redux-form#2872] opened 2017-05-01 01:11 UTC
As the title suggests, if stopSubmit is called, I can call it like:

`stopSubmit(FORM, {_error: err.message})`

The form will receive the error in its props, but the wrapper component of my form (which uses the selector `getFormSubmitErrors`), will be undefined. If I change the key from `_error` to anything else, it will work properly.

**Comment by mitas1** [comment] 2017-08-11 13:02
Can you send a pull request @tgallacher please?

**Comment by gustavohenke** [comment] 2017-08-16 16:40
Duplicate of #3325

**Closed by gustavohenke** 2017-08-16 16:40 UTC
Labels: enhancement
