### ISSUE TITLE
4.0.0 breaks when passed initialValues

### ISSUE THREAD

**Issue by ekosz** [erikras/redux-form#427] opened 2015-12-15 23:14 UTC
Given I have a form:

```js
@reduxForm({
  form: 'myForm',
  fields: ['foo'],
})
class MyForm extends Component {
  ...
}
```

When I try to initialize my form with some default values:

```js
render() {
  return <MyForm initialValues={{foo: 'bar'}} />;
}
```

I get the error: 

```
Error: must provide fields array to initialize() action creator at initialize
```

Offending line of code: 

<img width="888" alt="screen shot 2015-12-15 at 3 14 13 pm" src="https://cloud.githubusercontent.com/assets/212829/11827099/8c477d90-a33e-11e5-97e3-164299cb3131.png">

**Comment by theaqua** [comment] 2015-12-16 01:43
Yeah, have same problem. I didn't use `initialize` action.

**Comment by neverfox** [comment] 2015-12-16 04:09
Yeah, looks like it needs the fields array as required by the breaking change in the action creator.

**Comment by slybridges** [comment] 2015-12-16 12:13
Same issue with the example at http://erikras.github.io/redux-form/#/examples/initializing-from-state
Clicking on Load fails with `Uncaught (in promise) Error: must provide fields array to initialize() action creator(…)`

**Comment by erikras** [comment] 2015-12-16 13:26
Thanks for this.

**Comment by tomduncalf** [comment] 2015-12-16 15:47
Confirmed here, rolled back to 3.1.7

**Comment by erikras** [comment] 2015-12-16 17:13
Fixed in [`v4.0.1`](https://github.com/erikras/redux-form/releases/tag/v4.0.1). Thanks again.

**Closed** 2015-12-16 17:12 UTC

**Comment by raymondlukanta** [comment] 2016-01-16 02:03
If I use version 4.1.2, do I have to pass the fields?

Because I get an error: `Uncaught Error: must provide fields array to initialize() action creator` if I don't pass it.
My code: `this.props.initialize('companiesForm', {someField:"initialValue"})`

I also get the same error if I write `this.props.initialize('companiesForm', {someField:"initialValue"}, this.props.fields)`
I think this is because `this.props.fields` return `object` instead of `array`..

The error disappear if I write `this.props.initialize('companiesForm', {someField:"initialValue"}, Object.keys(this.props.fields))`

So, is `Object.keys(this.props.fields)` the intended way for it?

**Comment by gabrielpugliese-luizalabs** [comment] 2016-02-01 20:52
I'm facing the same as @raymondlukanta with redux-form@4.1.1
Is this intended?

**Comment by erikras** [comment] 2016-02-02 01:21
The intended way is to pass the same `fields` array given to the decorator.
