### ISSUE TITLE
Set error to a field without submitting the form

### ISSUE THREAD

**Issue by vctormb** [erikras/redux-form#3957] opened 2018-04-02 22:23 UTC
**Feature request**

I have a form that is loading data from an API. I'm trying to set manually an error to the field if occurs some error in the api call.

```
// This is the input that I'm trying to set the error message
<Field
   name="username"
   component={CustomCombobox}
 />
```

```
try {
   const { data } = await UserService.getUser();
  } catch (e) {
     // here I'm trying to set an error to "username" field
     stopSubmit('myFormName', { username: 'Something wrong happened.' })
}
```

But here's is the problem. I'm not submitting the form, so the stopSubmit does not work. I'm just receiving data from an API to fill the options, and if some error happens I want to set the error manually.

**Comment by gustavohenke** [comment] 2018-04-27 11:14
Duplicate of #3992

**Closed by gustavohenke** 2018-04-27 11:14 UTC
