### ISSUE TITLE
[v6] invalid, valid, error props don't change

### ISSUE THREAD

**Issue by tajo** [erikras/redux-form#1420] opened 2016-07-28 22:09 UTC
**version:** 6 RC3

The sync validation works. If I leave the input name empty it displays the `field.error`.  I would like to disable submit button when there are some errors, but props `invalid`, `valid` and `error` never change.

```
console.log(error)
```

is always undefined.

**Simplified example:**

``` jsx
import React from 'react';
import { Field, reduxForm } from 'redux-form/immutable';

const validate = values => {
  const errors = {};
  if (!values.name) {
    errors.name = 'Required';
  }
  return errors;
};

const renderField = field => (
  <div>
    <input {...field.input} />
    {field.touched && field.error &&
      <span>{field.error}</span>}
  </div>
);

const AddPlan = ({ handleSubmit, error }) =>
  <tfoot>
    <tr>
      <td>
        <Field
          component={renderField}
          name="name"
          type="text"
        />
      </td>
      <td>
        <button
          onClick={handleSubmit(data => {
            console.log(error);
          })}
        >
          Add new plan
        </button>
      </td>
    </tr>
  </tfoot>;

export default reduxForm({
  form: 'addPlan',
  validate,
})(AddPlan);

```

**Comment by JakeLin1024** [comment] 2016-07-29 03:01
Would it help if you remove immutable?

**Comment by JakeLin1024** [comment] 2016-07-29 03:33
```<button onClick={handleSubmit(data => {
  // do something with data. validation will have been called at this point,
  // so you know the data is valid
  // error is undefined here since data is valid I think.
})}>Submit</button>```

**Comment by erikras** [comment] 2016-07-29 12:58
The `error` prop is for the form-wide error that can be placed under the `_error` key in the object returned from your validation function.

This should work:

```jsx
const AddPlan = ({ handleSubmit, invalid }) =>
  <tfoot>
    <tr>
      <td>
        <Field
          component={renderField}
          name="name"
          type="text"
        />
      </td>
      <td>
        <button
          disabled={invalid} // <---------------
          onClick={handleSubmit(data => {
            console.log(error);
          })}
        >
          Add new plan
        </button>
      </td>
    </tr>
  </tfoot>;
```

**Comment by steida** [comment] 2016-07-29 16:48
@tajo Give up this shitty always broken always API changing library, and use https://github.com/este/este/tree/master/src/common/lib/redux-fields It's simple, fast, and without breaking changes from day zero. I tried to help @erikras but his EGO is too BIG to accept reality.

**Comment by davidkpiano** [comment] 2016-07-29 19:34
@steida That's completely uncalled for. @erikras works extremely hard on this, have a little bit of respect.

**Comment by steida** [comment] 2016-07-29 20:58
I would say he tortures community with a wrong brittle design. I suggested a solution I am using in Este several months ago and he even didn't answer. Look https://este.firebaseapp.com/fields It's minimal, it works. No breaking changes, no bloatware, no API madness, no monolith, no problems. https://medium.com/@steida/why-validation-libraries-suck-b63b5ff70df5

**Comment by davidkpiano** [comment] 2016-07-29 21:17
Also:

- No documentation
- Not installable (https://www.npmjs.com/package/redux-fields - `npm install redux-fields` doesn't install anything besides a README file)
- No management of actual form state, such as focus, pristine, etc. (which is what's actually important)
- No validation
- Etc.

If you really want to market this as a redux-form replacement, there's still a lot to be done.

**Comment by steida** [comment] 2016-07-29 21:24
It's all about priorities. For me, building the Este is priority number one. That's why I wanted to help here. redux-fields was an attempt of one of Este users. Also, the implementation is so simple that anyone can copy past it to the own project.

As for validation: Read my article. Check Este examples, for example, browser auth and React Native auth https://github.com/este/este/blob/master/src/native/auth/Email.react.js

I strongly believe that small composable components and utils are all we need. For example, if someone doesn't like current Este one by one validation, he can replace it with the own solution easily. React forms and validation should be build like Redux - simple core pluggable everywhere.

As for "No management of actual form state, such as focus"
I think everything is there. Actual form state, focus, custom fields, etc. Check both browser and native examples.

**Comment by steida** [comment] 2016-07-29 21:28
Note browser and Native uses different validation error showing to the users. https://github.com/este/este/blob/master/src/native/auth/SignInPage.react.js#L56
And I haven't to change anything in the fields core.

**Comment by ivarni** [comment] 2016-07-30 17:58
> Also, the implementation is so simple that anyone can copy past it to the own project.

That would be a huge step backwards. How would they get updates? bug-fixes? Aside from the fact that the GitHub page linked from the npm page 404s the idea of copy pasting in dependencies and mixing it with application code is not very viable. It's just over 24 hours since you suggested people use your library over this and it's already impossible to find the source code. In what universe is that not problematic?

**Comment by steida** [comment] 2016-07-31 02:22
> That would be a huge step backwards. How would they get updates? bug-fixes?

No updates. It's done. I know it's hard to believe, but it is. Having such tiny dependencies inside the project is actually very common. It's called a mono repo. React is using it as well.

https://github.com/babel/babel/blob/master/doc/design/monorepo.md
http://danluu.com/monorepo/

The code is here.
https://github.com/este/este/tree/master/src/common/lib/redux-fields

**Comment by th3fallen** [comment] 2016-08-17 00:10
@steida first off i think it's highly inappropriate how you advertised this. but as for your library, it seems interesting but i can guarantee you with absolute certainty that NO ONE is going to copy and paste your code to use it as a library. not going to happen. while i would be interested in trying it out since i am having issues with redux-forms but the lack of npm installation is a deal breaker.

**Comment by steida** [comment] 2016-08-17 00:19
Sure, it's the trade-off. I can't do everything. Even this conversation is time-consuming. All I did is I wrote my own solution which works well on my projects and mentioned it here so maybe it attracts some attention. I can't do more. Sorry for my tone, arrogance saves time. Happy codding.

**Comment by andreapier** [comment] 2017-02-03 13:51
I have the very same issue.
I'm using `immutable.js`
My validation function works as expected, but `props.invalid` is always `false`.
Can someone confirm this is a bug with `immutable.js` integration?

**Comment by sea129** [comment] 2017-02-17 01:18
having the same issue with v6.5.0. invalid and valid props not updating

**Comment by andreapier** [comment] 2017-02-17 13:13
It is working for me now.
My issue was caused by a wrong import of `reducer` from `redux-form` instead of `redux-form/immutable`:
`import { reducer } from 'redux-form'`
instead of
`import { reducer } from 'redux-form/immutable'`
It was not clear to me that I need to use everything from `redux-form/immutable` but it makes sense now.
I was pointed to the right direction reading #1206.
Maybe docs should be updated to better explain steps to follow when working with `immutable.js`, but I'll agree this is just a personal point of view.

**Comment by gustavohenke** [comment] 2017-02-20 00:25
@andreapier, this is documented. If you look at the Immutable JS example, it's noted that you should be importing from `redux-form/immutable` instead.

However, we see a great deal of issues related to people importing the reducer from the wrong place.
If you see an opportunity to fix the docs, please go ahead.

---

Since this issue is from the 6 RC age, I'll close it, a lot of stuff changed.
Also no updates from the OP were posted and so much confusion happened here.

**Closed by gustavohenke** 2017-02-20 00:25 UTC

**Comment by Meesam** [comment] 2017-03-27 16:24
i also face the same issue, and get resolve to change ` import { reducer } from 'redux-form/immutable'`
to ` import { reducer } from 'redux-form'`

**Comment by aprilmintacpineda** [comment] 2017-12-07 01:17
@steida what happened to your library? I'd love to see it but it gave me a 404 error. I like your values, that's awesome. We share the same thoughts, at least for that matter, minimal libraries that doesn't break the architecture of your code (just like redux-saga), because architecture is very important when it comes to software engineering, it dictates scalability, maintainability and readability, minimal libraries whose functionalities can be replaced as desired, elegant code that looks awesome, doing it right the first time is very important in software engineering, because the further away you are, the harder it is to go back. As for your `npm install` trouble, that can be fixed, that shouldn't be a big deal.

**Comment by aprilmintacpineda** [comment] 2017-12-07 01:18
@Meesam did you managed to solve the problem? If so, can you share it? :-D
