### ISSUE TITLE
File Input did't update on second select

### ISSUE THREAD

**Issue by khakulov** [erikras/redux-form#329] opened 2015-11-24 16:01 UTC
tested on:
http://erikras.github.io/redux-form/#/examples/file

If i select a File first time i can see the name of the file immediately.
If i select again another File i see the name after unfocus file input.

**Comment by erikras** [comment] 2015-11-24 16:07
:pager: @solomonhawk 

So we get the `CHANGE` action, but the value isn't different until `BLUR`? How strange!

**Comment by ooflorent** [comment] 2016-04-29 06:34
I can't reproduce it in v5.2.1. I'm closing it for now.
If the issue is still there, feel free to reopen the issue including a minimal sample to reproduce the bug.

**Closed by ooflorent** 2016-04-29 06:34 UTC
