### ISSUE TITLE
Strange Behavior w/ Capybara fill_in Command

### ISSUE THREAD

**Issue by cwbuecheler** [erikras/redux-form#686] opened 2016-02-25 16:47 UTC
Greets,

I'm using Capybara to run feature tests on my react app, specifically things like filling in fields and submitting forms, then making sure the page responds appropriately. It works well, but I've run into a weird discrepancy with my redux-form-enabled form. Basically, this code:
```
find('#receiver-control-form').fill_in 'label', with: label
```
should *replace* the existing value in the field. Instead, for some reason, it's appending to the existing text. So, for example, if the current input value is set to 'Test Label' and I run:
```
let(:label) { "updated label" }
find('#receiver-control-form').fill_in 'label', with: label
```
instead of getting 'updated label' as my final result, I get 'Test Labelupdated label'

Has anyone else encountered this behavior or have any suggestions for addressing the problem?

**Comment by thom-nic** [comment] 2016-02-26 18:55
To generalize this problem a little more, the following also exhibits unexpected behavior:
```ruby
find('#myForm [name=myField]').value     # => "default value"
find('#myForm [name=myField]').set 'asdf'  # this should clear the input value and replace with 'asdf' 
find('#myForm [name=myField]').value    # => "default valueasdf"
```
We're using the poltergeist (PhantomJS) driver for capybara so this is essentially running on headless chromium.  Capybara isn't manipulating the DOM nodes directly (which you would expect react to not play nicely with) - it emulates user mouse and keybord interactions albeit at computer speeds.  So while I haven't dug into the internals of what specific actions a `set` call executes, I anticipate it is something like a `focus` or `click` event on the input followed by keystroke events.  

I wonder if some event(s) are triggering re-renders by way of redux-form such that after the webdriver clears the input, it is re-rendering with the old state value and causing the new value to be appended instead of replacing it.

I get this same behavior if I run the above commands interactively with 10s of seconds between each operation, so we've ruled out obvious race conditions such as the form being manipulated before react event handlers are bound or while render calls are still settling or somesuch.  It's worth noting that the above previously worked fine with a typical stateful react component with input fields, before we changed it over to redux-form.

Is it possible some race condition could occur if a redux-form input was cleared and then a new value typed in *really* fast?

**Comment by erikras** [comment] 2016-02-28 08:01
> Is it possible some race condition could occur if a redux-form input was cleared and then a new value typed in _really_ fast?

I don't _think_ so. As long as your DOM simulator is firing `onChange` and then waiting for the next process tick for the component to be rerendered after the `value` prop changes. It shouldn't even matter if it does that between "keystrokes", as long as `onChange` is getting fired the final time with the final value.

I'd recommend logging all the redux actions to see what's happening. I bet that, through some quirk of Capybara, clearing the input is never dispatching an action.

**Comment by thom-nic** [comment] 2016-02-28 11:22
Good point, I'll try logging out all the redux actions and see what that reveals. Thanks.

**Comment by thom-nic** [comment] 2016-02-29 20:20
Dug into this further... tl;dr, it seems an upgrade to Poltergeist =>1.8 (from 1.7) resolves this issue.

Since we're using Poltergeist, the behavior is really implemented there, not in Capybara.  So I wrapped the redux-form `onChange` handler in order to capture and inspect the raw browser event(s.)  Poltergeist implements the `set` action by triggering a `focus`, followed by a *single* `change`, then `blur` events, so it's not just emulating keystrokes. However even when inspecting the the raw `change` event, `evt.target.value` was incorrect, suggesting poltergeist wasn't reading/setting the correct value to begin with.  Still no idea how/why redux-form affects this.  But as a sanity check, when I removed the {...myFormField} props passed from redux-form to the input component the issue disappeared.

However as I started digging into Poltergeist and possible causes, I upgraded to the latest release (now v1.9) and that cleared it up. I suspect teampoltergeist/poltergeist#666 is the related issue that was fixed in v1.8.

**Comment by erikras** [comment] 2016-03-01 12:35
Your "edit" made me lol. Good luck!

**Comment by thom-nic** [comment] 2016-03-01 17:54
Yup, CI says we fixed the problem on our end with the Poltergeist update.  Can close this now.

**Closed** 2016-05-17 13:28 UTC

**Comment by asselstine** [comment] 2017-01-31 18:42
I want to add my solution to the mix here, for any of those that are interested:

I was having problems using Capybara's fill_in for a controlled input with a default value.  The entered value was simply being appended to the existing value.

I traced the code and it appeared as @thom-nic said above (at least for webkit); Capybara set the value of the input, then triggers 'change'.

As in 

```javascript
node.value = ''
node.trigger('change')
```

However, the change event wasnt bubbling up and triggering the React listeners.  The webkit change event uses the deprecated Event.initEvent() method (https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent) and doesn't set the target, so I re-implemented fill_in with some additional code to clear the input and trigger an onChange event using the modern way:

```ruby
def react_fill_in(name, with:)
  execute_script(<<-JAVASCRIPT
    var $node = $("[name='#{name}']")
    $node[0].value = ''
    $node[0].dispatchEvent(new Event('input', {
      target: $node[0], bubbles: true
    }))
  JAVASCRIPT
                )
  fill_in name, with: with
end
```

This dispatchEvent will bubble up and trigger the React code.  

I hope this helps someone!

**Comment by rosskevin** [comment] 2017-07-29 15:18
I'm encountering this appending behavior with selenium on some but not all fields.  So far I don't have an explanation.

**Comment by iangreenleaf** [comment] 2017-09-01 20:10
I encountered this behavior too, using capybara-selenium with Chrome headless. I was able to work around it with this:

```ruby
    fill_in 'q', with: 'ABC'
    # ...
    fill_in 'q', with: '' # This line shouldn't be needed, but is
    fill_in 'q', with: 'ABC'
```

We also had a similar bug in this same spec when we were previously using capybara-webkit. In that case, `fill_in 'q', with: 'ABC'` overwrote correctly, but using `fill_in 'q', with: ''` later in the spec to clear the field *didn't* work. So in upgrading from webkit to ChromeDriver we basically traded one bug for another 😥

**Comment by iangreenleaf** [comment] 2017-09-01 20:22
Nope, my previous comment is lightly incorrect about our current situation (capybara-selenium + Chrome headless). It's even weirder:

Overwrite doesn't work:
```ruby
fill_in 'q', with: 'XYZ'
fill_in 'q', with: 'ABC'
# field value is 'XYZABC'
```

Clear + overwrite works:
```ruby
fill_in 'q', with: 'XYZ'
fill_in 'q', with: ''
fill_in 'q', with: 'ABC'
# field value is 'ABC'
```

Clear doesn't work:
```ruby
fill_in 'q', with: 'XYZ'
fill_in 'q', with: ''
# field value is 'XYZ'
```

Double clear doesn't work:
```ruby
fill_in 'q', with: 'XYZ'
fill_in 'q', with: ''
fill_in 'q', with: ''
# field value is 'XYZ'
```

I guess for now we'll stick with our old workaround that successfully clears the field in all situations:

```ruby
fill_in 'q', with: 'XYZ'
find(:fillable_field, 'q').send_keys :backspace, :backspace, :backspace
# field value is ''
```

**Comment by butzopower** [comment] 2017-10-03 15:30
Also experiencing this with capybara and headless chrome :(

**Comment by lucaspiller** [comment] 2017-10-17 14:08
I came across this issue as I've got a similar bug, however we are not using redux-form, just React and Redux on our own components. I haven't investigated exactly what events and actions are being fired, but I'd guess this is more of an issue with the underlying interaction between Selenium and React acting strangely.

**Comment by iangreenleaf** [comment] 2017-10-21 02:24
@lucaspiller let us know if you can track your issues down anywhere further. If this isn't the right place to be tracking the root cause, I'd love to know where to look.

**Comment by seb1441** [comment] 2017-11-17 16:23
I have the same issues. I fixed the clear problem with this:
`find_field('fillable_field').send_keys [:control, 'a'], :backspace`

**Comment by alyssais** [comment] 2017-12-14 10:35
I'm getting this too, using Chrome 63 with Selenium.

**Comment by mockdeep** [comment] 2017-12-24 21:05
Ha, I thought I was doing something vastly wrong. If I am, I guess I'm in good company. The `fill_in 'q', with: ''` approach worked for me. Another alternative, though not quite as lovely:

```ruby
find('input').native.clear
fill_in('input', with: 'whatever')
```

**Comment by geminiyellow** [comment] 2018-03-27 03:31
same error, i think this issue need to reopen.

**Comment by aarkerio** [comment] 2018-06-07 21:12
In my case I have:
    `fill_in 'user_zip', with: '59317'`

but capybara  sets the number:  "93175". I fixed it with:

```
fill_in 'user_zip', with: ''
fill_in 'user_zip', with: '59317'

```

**Comment by CamJN** [comment] 2018-07-11 15:55
I'm seeing this too, React 16.3.2, [material-ui](https://material-ui.com/), headless-chrome, no redux.

**Comment by Jay-Schneider** [comment] 2018-08-07 10:28
Just for the record, same problem here \*bump*.

Chromedriver version: `2.38`
selenium-webdriver `3.11.0`
capybara `2.18.0`
no fancy frontend libraries (just a rails view with simple_form and some jquery)

@iangreenleaf's workaround
```
    fill_in 'q', with: 'XYZ'
    fill_in 'q', with: '' # This line shouldn't be needed, but is
    fill_in 'q', with: 'ABC'
```
 is working for me at the moment but this is rather unsatisfying 😕

**Comment by lvonk** [comment] 2018-10-09 10:07
We are experiencing the same issue. For now adding `find_field(locator).send_keys [:control, 'a'], :backspace` is the workaround.

Filling `with: ''` didn't work.

Capybara, chromedriver testing React pages with Redux.

**Comment by NGMarmaduke** [comment] 2018-11-08 17:57
For anyone else coming here try:

```ruby
fill_in('Foo', with: 'bar', fill_options: { clear: :backspace })
```

It seems the issue is with the default clear method which uses `native.clear`. 

`clear: :backspace` basically sends n number of backspaces, see:
https://github.com/teamcapybara/capybara/blob/9a69cedb49c125f71f78ae3d4a59d6ad4f9b6604/lib/capybara/selenium/node.rb#L220-L223
