### ISSUE TITLE
How to handle dynamic forms which depends on the user action?

### ISSUE THREAD

**Issue by antoaravinth** [erikras/redux-form#612] opened 2016-02-02 13:20 UTC
Hi, 

This is sort of question, rather than an issue. I want to implement an "Dynamic form", I saw a example of it over here: http://erikras.github.io/redux-form/#/examples/dynamic?_k=f4yxmj

But the use case of mine is bit different; The user have a button say `+`, which he/she can click `n` no of times to generate a new textbox. So given this scenario, there can be `n` textbox which we aren't aware of at any given time. So the question is:
1. How we are going to handle this while decorating our component with `reduxForm`?

Thanks for your response. cc @erikras

**Comment by erikras** [comment] 2016-02-03 12:19
You're looking at the wrong example. :smile: You want something like how phone numbers are handled in the [Deep Form](http://erikras.github.io/redux-form/#/examples/deep) example.

```js
reduxForm({
  form: 'myForm',
  fields: ['myTextBox[]']
})
```

Ask a follow-up question if you still need some help.

**Comment by hifilorau** [comment] 2016-02-04 15:46
On a similar note, I am trying to fill the options of a 2nd select box based on the value of the first select box. I feel like maybe i am missing a free-throw. It seems most similar to the Deep Form but not seeing another example. Any ideas on where to look?

**Comment by antoaravinth** [comment] 2016-02-29 11:34
@erikras Sorry for the delay. But it doesnt seems to be working for me. I have the code like this:

```
Form = reduxForm({
    form : 'forms',
    fields : ['tags[]'],
    destroyOnUnmount: false
})(Form);
```

In my `Form` component's `render` method if I do like this:

```
const {fields: { tags}} = this.props;
tags.addField()
```

it throws the error saying: 

`Uncaught TypeError: Cannot read property 'addField' of undefined`

I was just wondering how in my `redux-form` I have given the name as `tags[]` and while getting it from `props`, we still do refer only `tags`, that doesn't look correct to me. Even the [Deep-Form] (http://erikras.github.io/redux-form/#/examples/deep?_k=jxypyo) example shows so. 

Let me know where I'm making mistake.

**Comment by erikras** [comment] 2016-02-29 11:45
Nope, your code is fine. That's a bug. I just created a test to demonstrate it. Thanks!

**Comment by antoaravinth** [comment] 2016-02-29 13:31
@erikras Oh that's my bad time!

**Comment by antoaravinth** [comment] 2016-03-07 08:38
@erikras : Any chances when this will be fixed?

**Comment by antoaravinth** [comment] 2016-03-09 03:41
@erikras ping

**Comment by erikras** [comment] 2016-03-09 08:20
@antoaravinth Sorry for the silence. I'm currently focussing on a pretty major rewrite for `v5` that has already taken this use case into account, but it's still a couple of weeks from beta release. The bug is pretty deep down in the field generation code, but with the test I shared above and the other extensive tests around it, if someone wanted to try to fix the bug in `v4`, they could. But I think my time is better spent getting `v5` out the door.

**Comment by antoaravinth** [comment] 2016-03-09 13:20
@erikras : Thats fine. I guess when I get a free time, I will look into the issue. Probably need your help as well!

**Comment by erikras** [comment] 2016-04-20 16:04
Hey guys. Just wanted to let you know [`v6.0.0-alpha` has been released](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.4)!

**Comment by jayphelps** [comment] 2016-06-02 02:23
@erikras if `{ fields: ['tags[]'] }` w/ `fields.tags.addField()` is suppose to work, what would be the expected behavior? You haven't provided a schema for the expected nested fields and currently the internal `initializeState` function requires those fields fields to be defined, otherwise it ignores the request to add them.

So even if you provide props: `fields.tags.addField({ name: 'Bilbo' })` it wouldn't do anything because you didn't define `{ fields: ['tags[].name'] }`

Side question: should we `console.warn()` when you try to add fields that aren't in the schema, so that it's more obvious to the dev why in general they don't work?

**Comment by danielrob** [comment] 2017-07-31 20:18
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.

**Closed by danielrob** 2017-07-31 20:18 UTC
Labels: bug
