### ISSUE TITLE
Form value setting not working in v6

### ISSUE THREAD

**Issue by sethreidnz** [erikras/redux-form#1832] opened 2016-09-21 10:17 UTC
Hi there. I have got a working version of a sample application using 5.1.0 but when I try to use the guide in the docs for v6 it does not work. Here is an example form I have created:

[from here](https://github.com/justsayno/employee-cv-manager-app/blob/broken-redux-forms/src/routes/EmployeeProfile/components/EmployeeDetailsEdit.js)

``` javascript
import React, { PropTypes } from 'react'
import { reduxForm, Field } from 'redux-form'

import { EMPLOYEE_PROFILE_FORM_NAME } from 'constants/formContants'

const validate = values => {
  const errors = {}
  if (!values.firstName) {
    errors.firstName = 'Required'
  }
  return errors
}

const EmployeeDetailsEdit = ({
  handleSubmit,
  toggleEditMode,
  firstName,
  lastName,
  role,
  team,
  biography,
  avatarUrl,
  initialValues
}) => (
  <form id={EMPLOYEE_PROFILE_FORM_NAME} onSubmit={handleSubmit} className='row employee-details-edit'>
    <div className='profile'>
      <div className='col s12 m4'>
        <div className='col s12 m6 profile-picture'>
          <img src={avatarUrl} alt='' />
        </div>
        <div className='col s12 m6 profile-details'>
          <label>First Name</label>
          <Field name='firstName' component='input' type='text' placeholder='First Name' />
          <label>Last Name</label>
          <Field name='lastName' component='input' type='text' placeholder='Last Name' />
          <label>Role</label>
          <Field name='role' component='input' type='text' placeholder='Role' />
          <label>Team</label>
          <Field name='team' component='input' type='text' placeholder='Team' />
        </div>
      </div>
      <div className='col s12 m8'>
        <h5>Biography</h5>
        <Field name='biography' component='input' type='textarea' placeholder='Biography' />
      </div>
    </div>
    <div className='row'>
      <div className='col s12 m12'>
        <button type='submit' className='btn'>Save</button>
        <a onClick={toggleEditMode} className='btn waves-effect waves-light btn'>Edit</a>
      </div>
    </div>
  </form>
)

EmployeeDetailsEdit.propTypes = {
  handleSubmit: PropTypes.func.isRequired,
  toggleEditMode: PropTypes.func.isRequired,
  firstName: PropTypes.string.isRequired,
  lastName: PropTypes.string.isRequired,
  role: PropTypes.string.isRequired,
  team: PropTypes.string.isRequired,
  biography: PropTypes.string.isRequired,
  avatarUrl: PropTypes.string.isRequired,
  initialValues: PropTypes.object
}

export default reduxForm({
  form: EMPLOYEE_PROFILE_FORM_NAME,
  validate
})(EmployeeDetailsEdit)
```

This was based off the [example here](http://redux-form.com/6.0.0-alpha.4/examples/initializeFromState/) and if I use this exact code but revert to the 5.x it works fine but I get no binding to the Field elements in the example above. 

 You can clone that repo and run it in the `broken-redux-forms` branch  (`npm install` then `npm start`)to see the example. You go to the EmployeeProfile Route by clicking on "View Profile" from the dashboard then clicking on "edit" and you will get the form.

[https://github.com/justsayno/employee-cv-manager-app/tree/broken-redux-forms](https://github.com/justsayno/employee-cv-manager-app/tree/broken-redux-forms)

As you will see all the state is fine redux store knows about the fields. However the fields themselves do not have the values populated. I presume (although not 100% clear in the docs) that the "name" attr on the `Field` component is the key in the form reducer.

Like I said have it working with 5.x but I spent a good 3 hours tring to figure out what was wrong. Tried to run the afformentioned example for Initializing From State and it does not compile or run (windows 10 latest node etc).

Thanks!

**Comment by ppascher** [comment] 2016-09-24 20:13
Might be the same issue [mentioned here](https://github.com/erikras/redux-form/issues/1744#issuecomment-248296445). Try looking at the initialValues object passed to your Field. Does it have the same structure as in the issue linked above?

**Comment by kirstu** [comment] 2016-12-27 09:54
The problem is that `redux-form` assumes that the form state is under `form` key in the redux state. So either change the form reducer to handle `form` key, or provide `getFormState` function to `reduxForm()` (as outlined here http://redux-form.com/6.3.1/docs/api/ReduxForm.md/)

**Comment by danielrob** [comment] 2017-08-03 02:24
Closing this usage issue due to non response.

**Closed by danielrob** 2017-08-03 02:24 UTC
