### ISSUE TITLE
value change doesn't trigger rerender within fieldsarray or it's delayed

### ISSUE THREAD

**Issue by r281GQ** [erikras/redux-form#3281] opened 2017-08-02 00:08 UTC
I know the expected way to add/remove fields or dynamically render something within a form that is decorated with reduxForm is to fetch the  values from the store with like getFormValues.
However as I was trying to find alternative ways, I don't know whether I found a bug or is it expected behaviour or I am doing something terribly wrong.

So from 6.0 only the fields and fieldsarray are connected to the store directly therefore they and their children will rerender on  state changes.

So I have a component like this, reverse order as the build up the component tree. I'm using redux-form 6.8, redux 3.7.2, react 15.6.1, immutable 3.8.1 and node 8.0.0

```
const Conditional = ({ fields: { get }, index, item }) => {
  return get(index).get('marker')
    ? null
    : <FieldArray name={`${item}.sets`} component={SetsFieldArray} />;
};


class Exercise extends Component {
  render() {
  const {fields: {remove}, item, index} = this.props;
    return (
      <ListItem key={index} disabled={true}>
        <NameField item={item} />
        <NoteField item={item} />
        <Field
          name={`${item}.marker`}
          component={Checkbox}
          label="Mark as completed without setting any sets"
        />
        <FlatButton
          onTouchTap={() => remove(index)}
          label={`Remove exercise`}
        />
        <Conditional {...this.props}  index ={index} item = {item}/>
      </ListItem>
    );
  }
}

const ExerciseFieldArray = (props) =>
  <List>
    <ListItem disabled={true}>
      <FlatButton
        onTouchTap={() => {
          props.fields.insert(props.fields.length, fromJS({ marker: false }));
        }}
        label={`Add exercise`}
      />
    </ListItem>

    {props.fields.map((item, index) =>
      <Exercise
        {...props}
        key={index}
        index={index}
        item={item}
      />
    )}
  </List>;


```

It sits in a parent which is a FieldArray. So based on one of the value I want to return null or another, nested FieldArray. I could just simply subscribe to the
store in the main container of the form, map the returned value to this boolean and that works flawlessly.

So instead of passing down the value I wanted to get the value from the FieldArray. However when I tick the checkbox the state change is dispatched to redux but it does not get
rerendered every time. Sometimes I have to click somewhere in the page to dispatch a blur which cause a rerender.

If this boolean value is injected via getFormValues it updates just fine with every line of code being the same except passing down the props.

The props are passed down to this component. My redux store is composed with Immutable.js

I made a short vid about it.

[https://www.youtube.com/watch?v=7nAn204oj6I&feature=youtu.be](https://www.youtube.com/watch?v=7nAn204oj6I&feature=youtu.be)

**Comment by danielrob** [comment] 2017-08-02 03:40
Speaking as someone who read through this carefully, and watched your video at 1/4 speed to make sure I followed, I get what you're saying, but I think you could improve this potential bug report further with some extra investigation. 

The issue seems to be around the relationship between get() calls and renders ordering: are you able to find a more minimal reproduction of the central issue here? 

Also the use of our issue template truly does help readability 📖 :).

**Comment by r281GQ** [comment] 2017-08-02 17:14
Thanks for the reply. Yes, sorry about a format. As soon as I have some time I will recreate the whole thing in vacuum within a clean environment.

**Comment by zmaglica** [comment] 2017-08-07 12:14
@r281GQ  I have almost same issue. I am storing custom data inside store and I pass that data via props. That data is used inside field array for displaying some information (travel distance, time ...). Problem that I have is that in most cases field array component doesn't update. It only updates when I click on element inside FIeld Array or when I change some data...

Did you manage to solve your problem?

**Comment by r281GQ** [comment] 2017-08-07 13:50
@zmaglica No, at least not the way I would have liked to solve it. I created a different setup that only contains this problem, just haven't finished it yet. 
What I did is, I used getFormValues and in mapstatetoprops I mapped the field values to only the values I need to make a decision on the conditional render. This way I avoided unnecessary re renders and also injecting the state directly forces the whole component where the form resides to update.


React container where decorated with reduxForm
```
const mapStateToProps = state => {
  return {
    markerList:
      getFormValues('workoutLog')(state).get('exercises')
        ? getFormValues('workoutLog')(state)
            .get('exercises')
            .map(value => value.get('marker'))
        : Map()
  }
}
```
React container render method: in my FieldsArray I passed this list down like: 

```
            <FieldArray
              name="exercises"
              component={ExerciseFieldArray}
              passedMarkerList={this.props.markerList}
              normalizeMarker = {mapToBoolean}
            />
```
Then I used this prop to make the decision.
It works and doesn't cause more renders than it should, yet I think there is a more natural solution.

**Comment by chrvadala** [comment] 2017-08-08 05:36
I have the same problem. I guess that I've been able to create an example that shows the issue.
I added the line 53 <h5>FirstName: {fields.get(index).firstName}</h5> on the official example
https://codesandbox.io/s/QWBEN8xrq

If you update the first name using the input box, the <h5> title is not synced until you click outside the component

**Comment by zmaglica** [comment] 2017-08-08 05:42
@chrvadala I use almost same  code to display values inside my field array and I have exactly same problem. To update field array you need to click outside of form like @chrvadala mentioned. Did you manage to find any solution for this kind of problem ?

**Comment by chrvadala** [comment] 2017-08-08 06:48
I spent a lot of time debugging, but unfortunately I haven't any workaround yet :(

**Comment by zmaglica** [comment] 2017-08-08 07:24
@chrvadala I managed to display changes in field array by manually triggering field rendering by changing field value inside field array. I used change action to change field value and reset it to existing one. I didn't changed original value but that triggered field array rendering because "form changed".

It is not nice solution but it will do until I found better one.

**Comment by chrvadala** [comment] 2017-08-09 09:02
Fortunately my project is not yet in production. I can wait for a fix, but we need to mark this issue as bug.
@danielrob Does my example published few comments up good for debugging?

**Comment by jpdesigndev** [comment] 2017-08-09 16:31
I'm seeing this issue too. For now, I'm using the `formValueSelector` to explicitly force a re-render for any change to the selected `FieldArray`.

**Comment by nerfologist** [comment] 2017-08-11 13:07
Also experiencing this right now. I'll also use the formValueSelector to force a re-render!

**Comment by rowthan** [comment] 2017-10-15 03:32
It is certain that we can through fromValueSelector to force a re-render, but I do hope that it will be fixed about the problem of fields.get(index), Because it a little bit troublesome use formValueSelector  instead of fields.get(index).
P.S. This problem still remain in V7.1.1 the latest version as far.

**Comment by gustavohenke** [comment] 2017-10-16 02:18
Hi folks, the behaviour you're all experiencing here happens because it's *very* inefficient to rerender on every change.
Before v6 existed, *every* change on *any* field would cause the whole form to rerender. You can imagine all sorts of performance issues we had.

Anyway, there are better ways to force a rerender to your `FieldArray`s.
Please use [`rerenderOnEveryChange`](https://redux-form.com/7.1.1/docs/api/fieldarray.md/#-code-rerenderoneverychange-boolean-code-optional-) prop for this.

**Closed by gustavohenke** 2017-10-16 02:18 UTC
