### ISSUE TITLE
Ability to clear form errors

### ISSUE THREAD

**Issue by psankar** [erikras/redux-form#2895] opened 2017-05-07 08:19 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

```
class MyForm extends Component {

handleSubmit(values) {
   throw new SubmissionError("Some error");
}
render() {
    const {error} = this.props
    return (
            <form onSubmit={handleSubmit(this.handleSubmit.bind(this))}>
                    <Field.....>
                    {this.renderError(error)}
            </form>
           );
}
renderError(error) {
    if (error) {
        return (
                <div className='alert alert-danger alert-dismissable'>
                <div className="close" data-dismiss="alert" aria-label="close">&times;</div>
                {error}
                {/* 
                    <!---- Commented code ---!>
                     <label className='close' data-dismiss='alert' aria-label='close' onClick={
                            () => {
                                console.clear()
                                console.log('can we dismiss the bootstrap message ?', this.props);
                                this.props.clearAsyncError();
                            }
                        } >
                            &times;
                    </label>
               */}
                </div>
               );
    } else {
        return null
    }
}
}
```
I have a redux-form (v6.5.0). I throw a `SubmissionError` from the `handleSubmit` function which gets rendered in the form using a `renderError` function.

I use bootstrap to render the Error as a [dismissable](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp) alert. But nothing happens when I click on the close button. The alert does not get dismissed. I realized that it could be because the error prop in the redux-form is not cleared and that is why the error dialog is not going away.

So I tried adding an onClick listener where I tried to clear the this.props.error of the redux-form (See the commented code in the above snippet). But I get a permission denied error. I cannot use the `this.props.clearAsyncError()` method also because it is not a field-specific error that I want to clear, but a submission error that is form field independent.

So, what is the way to clear the form's error ?

### What is the expected behavior?
An easy way to clear redux-form errors that are field agnostic 

### What's your environment?
   "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-form": "^6.5.0",
    "redux-thunk": "^2.2.0"

Mac OS X, Chrome 57.0.2987.133

### Other information

Stackoverflow link: http://stackoverflow.com/questions/43787740/creating-dismissable-bootstrap-v3-alerts-when-using-redux-form-error-rendering

**Comment by danielrob** [comment] 2017-08-04 10:41
Closing as a duplicate of #2599. Added documentation for `clearSubmitErrors` which should do the trick. Please advise if something missing.

**Closed by danielrob** 2017-08-04 10:41 UTC
Labels: enhancement
