### ISSUE TITLE
No default actions export under /es

### ISSUE THREAD

**Issue by alfonsoperez** [erikras/redux-form#2943] opened 2017-05-19 19:05 UTC
Reading http://redux-form.com/6.7.0/docs/faq/BundleSize.md/, it says

> Action creators are available under actions in order to take advantage of this method. One would import the actions binding and then extract the needed action creators.

Although as I see there is no default actions export, but named exports.

**Comment by huan086** [comment] 2017-05-20 14:29
Duplicate of #2908

**Closed** 2017-05-21 22:49 UTC
