### ISSUE TITLE
v6.0-rc.1 

### ISSUE THREAD

**Issue by FuzzySockets** [erikras/redux-form#1278] opened 2016-07-05 00:01 UTC
I'm getting the following error upon resolving a promise in my submit function:

> Uncaught (in promise) undefined

If I don't resolve the promise, the error goes away.

export function submitSignInForm(values, dispatch) {
```
return new Promise((resolve, reject) => {
    let url = 'http://localhost/api/sign-in';
    request.post(url).send(values).then(body => {
         //resolve(body);
    }).catch(e => {
        console.log(e);
    });
 });
}
```

I attach the submit handler to my form like so:
`<form onSubmit={handleSubmit(submitSignInForm)}>`

**Comment by FuzzySockets** [comment] 2016-07-05 00:18
As an added note, when I submit the request myself and catch it, the error goes away.  If I fail to catch it, the error comes back.  Is this a bug or am I supposed to do something else to accommodate promises?

```
<h1 onClick={() => {
    submitSignInForm({
        email: 'login@login.com',
        password: 'password'
    }).catch(e => {
        console.log(e);
    });
}}>Click Me</h1>
```

**Comment by FuzzySockets** [comment] 2016-07-05 00:45
I'm starting to think this may have something to do with how superagent handles promises.  Let me know if anything looks off with how I configured redux-form though.

**Comment by erikras** [comment] 2016-07-05 08:07
This is a dupe of #1266. Already fixed. Will be in rc2.

**Closed by erikras** 2016-07-05 08:07 UTC

**Comment by FuzzySockets** [comment] 2016-07-05 11:51
@erikras Right on, thank you!
