### ISSUE TITLE
register/unregister on key press v.7

### ISSUE THREAD

**Issue by paibamboo** [erikras/redux-form#3249] opened 2017-07-26 07:50 UTC
### Are you submitting a **bug report** or a **feature request**?

Bugs

### What is the current behavior?

When typing on input, redux-form keeps dispatching register and unregister actions.

![image](https://user-images.githubusercontent.com/13611391/28610157-8de6f8b2-7211-11e7-9d55-3c441c6459d2.png)

### What is the expected behavior?

It should not.

**Comment by danielrob** [comment] 2017-07-26 13:16
Without further investigation I'll assume this is a duplicate of #3211. Please feel to provide more information if you think this is not correct.

**Closed by danielrob** 2017-07-26 13:16 UTC
