### ISSUE TITLE
normalize/parse/format should have access to (meta) props

### ISSUE THREAD

**Issue by akomm** [erikras/redux-form#3588] opened 2017-11-06 14:18 UTC
**feature request**

### What is the current behavior?

Neither parse, nor format or normalize (on Field component) do get information about the underlying input. 

### What is the expected behavior?

All those callbacks should get at least the meta props.

### Why?

There are many cases in which it is either not feasible or tedios to get better control of 1. what is stored and 2. what is displayed depending on inputs state.

For example if you want parse/format to only aplly on blur. 

You might think about something like this:
```jsx
const PriceInput = ({formatter, input: {onFocus, onBlur, onChange, value = undefined}}) => (
  <input
    type="text"
    value={value}
    onChange={e => onChange(e.target.value)}
    onFocus={onFocus}
    onBlur={() => onBlur(formatter ? formatter(value) : value)}
  />
);
```
But this has a flaw. No matter what you do here, parse (float, store) or format (string, display), you either store the displayed value or you display the stored value. You loose the separation view/data, which you have with the implemented Field properties "format", "parse" (and "normalize").

There are other approaches from outside and using action creators & selectors or wrapp the Field component, use refs and remap format/parse/normalize, but all feel like an overkill.

It could be as simple as:

```jsx
<Field
  name="someField"
  component="input"
  type="text"
  parse={(value, {meta}) => {
    if (meta.active) {
      return value;
    }
    // return parsed
  }}
  format={(value, {meta}) => {
    if (meta.active) {
      return value;
    }
    // return formatted
  }}
/>
```

**Comment by gustavohenke** [comment] 2018-01-29 12:13
Duplicate of #2778

**Comment by gustavohenke** [comment] 2018-01-29 12:13
This feature saw little or no interest from other users, so I'm closing it for now.
Feel free to continue the discussion.

**Closed by gustavohenke** 2018-01-29 12:13 UTC
Labels: enhancement

**Comment by akomm** [comment] 2018-01-29 12:37
Why not create a specific label for this instead of closing? Closed means either resolved or invalid request, or whatever.
