### ISSUE TITLE
[v6] initialValues reinitialize ignored when empty string

### ISSUE THREAD

**Issue by dpwrussell** [erikras/redux-form#1306] opened 2016-07-07 17:57 UTC
I have a form which I wish to display blank while the inital values are fetching. Once this data is reduced into my state, mapStateToProps kicks in and updates the form with `enableReinitialize=true`.

``` js
function mapStateToProps(state, ownProps) {
  const { canonical } = ownProps;
  if (canonical) {
    console.log('chebi_id', canonical.chebi_id);
    console.log('----');
  }
  return {
    initialValues: canonical || {chebi_id: 'yo'},
    enableReinitialize: true
  };
}
```

Initially, `canonical` is undefined so initialValues are set with an empty object, although in this case I explicitly initialize `chebi_id` to have a value as it makes it easier to see the problem. The chebi_id field will display 'yo' and correctly be marked as pristine.

Once the async action completes and `mapStateToProps` runs again, `canonical.chebi_id` is an empty string. This seems to update the value of the field, but the initialValue of this field remains as 'yo', and thus it is incorrectly marked as dirty. If `canonical.chebi_id` is not an empty string then everything works as expected.

EDIT: Actually, I just tried this without `enableReinitialize` and that does not seem to explicitly be the culprit. Any initialize seems to suffer:

``` js
function mapStateToProps(state, ownProps) {
  const { canonical } = ownProps;
  // Initially canonical will be undefined and thus the form does not initialize
  // (redux-form/INITIALIZE does not fire until canonical is not undefined)
  return {
    initialValues: canonical,
    batches: getCanonicalBatches(state, ownProps)
  };
}
```

In this case, the value is empty string, but the initial value will be stuck at undefined.

**Comment by zombieJ** [comment] 2016-07-21 02:55
+1
I have 2 initial data fetching. First ajax data is the primary data and second is assist and also very slow. So the first data always need to be as init values and not wait for the second response. But current redux form only support first init. I guess it may extends.

**Comment by dpwrussell** [comment] 2016-07-21 17:27
@zombieJ I'm not sure exactly what you mean by "only supports first init". It definitely works to update the `initialValues` (as long as you set `enableReinitialize=true`) , but it just seems to be getting confused when they are empty strings.

**Comment by bschnelle** [comment] 2016-07-24 16:51
I'm having the same issue and I believe the issue is related to this [line](https://github.com/erikras/redux-form/blob/v6/src/ConnectedField.js#L70).  It looks like `initialize` properly updates the initial values state, but ConnectedField hangs on to the original initial value on this [line](https://github.com/erikras/redux-form/blob/v6/src/ConnectedField.js#L16).  That value only appears to be updated if you change the name of your form ([here](https://github.com/erikras/redux-form/blob/v6/src/Field.js#L34)). 

Maybe @erikras can shed some light on this? =)

**Comment by GuilhermeMedeiros** [comment] 2016-08-10 15:37
Same here :/

**Comment by tb** [comment] 2017-04-26 22:04
This is caused by `&& payload === ''` in reducer.js [CHANGE].
```
    [CHANGE](state, { meta: { field, touch, persistentSubmitErrors }, payload }) {
      let result = state
      const initial = getIn(result, `initial.${field}`)
      if (initial === undefined && payload === '') {
        result = deleteInWithCleanUp(result, `values.${field}`)
      } else if (payload !== undefined) {
        result = setIn(result, `values.${field}`, payload)
      }
```
Simple fix is to set the select field value to '' i.e.
```
<PostListFilter
  initialValues={{category: '', ...resourceList.params.filter}}
  onSubmit={onFilter}
  categories={categories}
</PostListFilter>
```

**Comment by nikaspran** [comment] 2017-08-15 06:55
There's a little more info on this in https://github.com/erikras/redux-form/issues/2597

**Comment by esetnik** [comment] 2018-07-12 20:08
Can this be closed now since https://github.com/erikras/redux-form/issues/2597 is merged?

**Comment by joshsylvester** [comment] 2019-06-04 17:15
I'm still experiencing this issue on 7.3.0 - if a field is initialized with `undefined`, and then the form is re-initialized (with `enableReinitialize=true`), the field is not being re-initialized. For normal string based fields like a text input, this isn't a problem - but in the case of a picklist (where the empty string is the value for "None", or otherwise), the option is not being picked (the value from the `initialValues` being passed into the field so that the proper option can be selected) until the user touches the field. As soon as the focus happens, the field is properly selected / updated.

**Comment by renatoagds** [comment] 2019-06-04 18:03
@joshsylvester If you find the problem into the last version, please feel free to open a new issue.

**Closed by renatoagds** 2019-06-04 18:03 UTC
