### ISSUE TITLE
Add "replace" array manipulator to FieldArray fields prop.

### ISSUE THREAD

**Issue by rosieks** [erikras/redux-form#2961] opened 2017-05-24 16:16 UTC
Please add function `update(index: number, value: any)` to `fields` object. The idea behind that is to support editing item of fields array in separate form like modal dialog. Of course I could use `remove` and `insert` function but it would be nice to have one atomic function to do that, similar like `swap`.

**Comment by danielrob** [comment] 2017-07-25 04:44
I honestly thought we had that. This would be useful in my project. I'd personally call it `replace`. Or, have both and have `update` do an `Object.assign({}, oldValue, newValue)` (if it's an object) for me. This would be ever so nice.

**Comment by danielrob** [comment] 2017-07-25 07:39
What do you know this is an exact duplicate of #2475 besides the function name.

**Closed by danielrob** 2017-07-25 07:39 UTC
Labels: enhancement
