### ISSUE TITLE
Not able to initialize form using redux immutable state

### ISSUE THREAD

**Issue by akashshinde** [erikras/redux-form#1744] opened 2016-09-12 05:42 UTC
This is how I am attaching `state` value to `props`.
![screen shot 2016-09-12 at 10 46 09 am](https://cloud.githubusercontent.com/assets/3337902/18425639/e50cfdb8-78d8-11e6-9f43-6d97490cbe76.png)

And then decorating form with `reduxForm`.
![screen shot 2016-09-12 at 10 46 34 am](https://cloud.githubusercontent.com/assets/3337902/18425640/e5476d4a-78d8-11e6-85e5-a2408caea6e8.png)

Here I can see `INITIALIZE` getting dispatched, but form is not getting rendered.
![screen shot 2016-09-12 at 10 50 02 am](https://cloud.githubusercontent.com/assets/3337902/18425674/20a1a3ce-78d9-11e6-8fa4-8ea658ea3a52.png)

Here form is not getting rendered with initial values but `onSubmit` callback have `initial values`.

**Comment by peteruithoven** [comment] 2016-09-14 11:22
Since v5.3.3 the `props` are given to the `onSubmit` handler, maybe you could use this to inject the initial values into values before submitting them?
https://github.com/erikras/redux-form/releases/tag/v5.3.3

**Comment by akashshinde** [comment] 2016-09-14 11:32
@peteruithoven I am able to get initial values while submitting form,but not getting rendered in form.

**Comment by peteruithoven** [comment] 2016-09-14 12:29
Ah alright. What happens when you switch around the two wrappers / higher order functions (connect and reduxForm)?

**Comment by ppascher** [comment] 2016-09-16 15:38
I have the same issue. I pass an "initialValues" object to my form together with "enableReinitialize". 

Component gets mounted, triggers an api call to load data and I can see in DevTools that "redux-form/INITIALIZE" gets called afterwards and the state in "form -> formname -> values / initial" is populated.
Submitting the form uses those values but they are never rendered.

I use a custom Field component to use react-bootstrap:
```javascript
const InputTextRedux = (props) => {
  return (
    <div>
      <FormGroup
        className={props.groupClassName ? props.groupClassName : ''}
        name={props.name ? props.name : ''}
      >
        <ControlLabel
          className={props.labelClassName ? props.labelClassName : ''}
        >
          {props.label ? props.label : 'Text'}
        </ControlLabel>
        <InputGroup
          className={props.wrapperClassName ? props.wrapperClassName : ''}
        >
          <InputGroup.Addon className="input-group-addon">
            <i className={props.icon ? props.icon : 'fa fa-pencil'} />
          </InputGroup.Addon>
          <FormControl
            disabled={props.disabled ? true : false}
            id={props.id ? props.id : props.name}
            onChange={(event) => {
              props.input.onChange(event.target.value);
            }}
            placeholder={props.placeholder ? props.placeholder : ''}
            type={props.type ? props.type : 'text'}
            value={props.input.value}
          />
          <FormControl.Feedback />
        </InputGroup>
      </FormGroup>
    </div>
  );
};
```

**Comment by bentobenti** [comment] 2016-09-20 12:43
I'm also having the same issue, using immutable. I'm passing the values down using props though.
```
const initialValues = {
    name: 'Hello world',
};

<ReduxForm initialValues={initialValues} />
```

redux-form/INITIALIZE
![2016-09-20-144142_212x227_scrot](https://cloud.githubusercontent.com/assets/11430621/18670474/6c8bd86e-7f40-11e6-9e54-8f9692718732.png)

But nothing gets rendered

**Comment by ppascher** [comment] 2016-09-20 13:09
Looking at the props passed to my form component I noticed:
```
props {
    ....
    initialValues: {
        __altered: false,
        _root: {
            entries: [
                [ 
                    'id',
                    '123456'
                ],
                [
                    'filename',
                    'test.txt'
                ]
            ]
        },
        size: 2
    },
    ....
}
```

If I name one of the form fields 'size' or '__altered' they recieve and render initialValues of '2' and 'false' respectively. It seems as if redux-form is looking at the wrong 'level' of the initialValues object. It should be taking values from "initialValues._root.entries" (hope that makes sense).

**Comment by bentobenti** [comment] 2016-09-20 14:14
@ppascher 
I have the same behavior

**Comment by somghosh** [comment] 2016-09-23 18:38
@ppascher @erikras I have the same issue

**Comment by crazymunky** [comment] 2016-10-03 15:37
Any update on this ? Im facing the same issue.
Values in store get completely messed up after I edit some field.

First render, fields are empty but store shows correct values:
![image](https://cloud.githubusercontent.com/assets/9321946/19043165/6491b8d4-8965-11e6-9580-8b9f4d9934a6.png)

Submitting like this sends the correct values from initial.

After entering "New name" in the name field.
![image](https://cloud.githubusercontent.com/assets/9321946/19043199/8b9c4eda-8965-11e6-9148-2fb7bcdce618.png)

_root has the same structure as @ppascher showed. 
Submitting sends that structure.

**Comment by ppascher** [comment] 2016-10-03 23:02
Thanks @crazymunky. I was also importing the wrong reducer and switching + adding `.toJS()` to my submit functions solved my problem.

**Comment by Marinolinderhof** [comment] 2016-10-07 12:20
Did you get the initialValues working?

![screen shot 2016-10-07 at 14 18 48](https://cloud.githubusercontent.com/assets/3657762/19189581/0e3357fe-8c99-11e6-9317-29fc67698ec7.png)

![screen shot 2016-10-07 at 14 19 07](https://cloud.githubusercontent.com/assets/3657762/19189582/0e365fe4-8c99-11e6-9b5b-841aace74ff8.png)

Both options are not working.

**Comment by pgdejardin** [comment] 2016-10-07 14:38
Finally got it to work (but with a props warning) using `import { reducer as formReducer } from 'redux-form/immutable';` in the `combineReducer({...})` file and using `import { Field, reduxForm } from 'redux-form/immutable';` in my container.

But I had to use a trick too, in my container's reducer, I have my `const initialState = fromJS({ info: false, loading: false, error: false });`.
If I have `info: fromJS({})` to initialize my substate that will contain all the fields data after fetching from api, the initialize action of redux-form is never triggered, but if I do `info: false` in the `initialState` of the reducer, I have the React warning ```Warning: Failed prop type: Invalid prop `initialValues` of type `boolean` supplied to `Form(Profile)`, expected `object`.``` But the values are well initialized from Redux-form and can be edited.

**Comment by kinyat** [comment] 2016-10-11 00:20
The problem to me is that my reducer didn't use `redux-form/immutable`
Pls double check it if you are using immutableJS.
Got stuck for half a day because of this... I feel I am so dumb :(

**Comment by gilesbutler** [comment] 2016-10-20 23:17
Here is my work around: https://github.com/erikras/redux-form/issues/1399#issuecomment-255253588

**Comment by JeroenNelen** [comment] 2016-11-15 13:22
@pgdejardin @kinyat @crazymunky @ppascher 
Is anyone of you working with react-native or otherwise encountered the issue below?

I switched to use the formReducer from redux-form/immutable, but when I then submit a value I get the following errors (I added the .toJS() to the values object that I receive in the handleSubmit function):
```
ExceptionsManager.js:62 One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.handleException 
@ ExceptionsManager.js:62handleError 
@ InitializeJavaScriptAppEngine.js:120reportFatalError 
@ error-guard.js:30guard 
@ MessageQueue.js:47callFunctionReturnFlushedQueue 
@ MessageQueue.js:104onmessage 
@ debuggerWorker.js:44
ExceptionsManager.js:82 
Unhandled JS Exception: One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.reactConsoleError @ ExceptionsManager.js:82console.error @ YellowBox.js:61logIfNoNativeHook @ RCTLog.js:38__callFunction @ MessageQueue.js:234(anonymous function) @ MessageQueue.js:105guard @ MessageQueue.js:45callFunctionReturnFlushedQueue @ MessageQueue.js:104onmessage @ debuggerWorker.js:44
ExceptionsManager.js:82 Warning: performUpdateIfNecessary: Unexpected batch number (current 29, pending 27)
```

I can dismiss the errors and continue but that's not really an option. Anyone any clue?
I'm not using Object.assign anywhere in my own code because I'm working with Immutability...

Kind regards,

**Comment by esbenp** [comment] 2017-01-06 10:30
There was a regression introduced in `6.0.3` around Immutable.js and React Native, which was fixed in `6.4.2` - have you tried upgrading to `6.4.2` or higher?

[I have also added a complete example on React Native, redux-form and immutable.js right here.](https://github.com/esbenp/react-native-redux-form-example/tree/master/src)

[I also wrote an in-depth article about the subject here](http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/)

**Comment by marcpeters2** [comment] 2017-01-24 22:13
I'm also having trouble setting the `initialValues` for a Form using `connect` and Immutable.js .  Looks like there may be an issue with the way that the `ConnectedField` retrieves the `initialState` and `value` for a Field.  See these lines in the source:

https://github.com/erikras/redux-form/blob/4514088e771111013ece24cedd534f66807332fe/src/ConnectedField.js#L210
`const initialState = getIn(formState, `initial.${name}`)`

https://github.com/erikras/redux-form/blob/4514088e771111013ece24cedd534f66807332fe/src/ConnectedField.js#L212
`const value = getIn(formState, `values.${name}`)`

Changing them to the following appears to fix the issue:
```const initialState = getIn(formState.initial, name)
...
const value = getIn(formState.values, name)```

The issue appears to be the dynamic behaviour of `getIn` as defined here: https://github.com/erikras/redux-form/blob/4514088e771111013ece24cedd534f66807332fe/src/structure/immutable/index.js#L15

In this case, `getIn` is reverting to `plainGetIn` because `formState` is not recognized as an `Iterable`.

**Comment by marcpeters2** [comment] 2017-01-25 15:43
I also had this issue.  Solution was to `import { reducer as formReducer } from 'redux-form/immutable'` , previously I was importing the reducer from `redux-form`

**Comment by bonham000** [comment] 2017-04-14 22:31
@marcpeters2 thanks for that comment! Same issue for me, not importing the reducer correctly from `redux-form/immutable`.

**Comment by Bamieh** [comment] 2017-04-19 10:04
i had the same issue, `redux-form/immutable` was the solution as stated before. I believe a warning should be fired if there is some inconsistency when using a mixture between immutable and mutable stuff.

**Comment by gustavohenke** [comment] 2017-12-06 23:28
Because this issue saw almost no activity for a few months, I'm closing it.

**Closed by gustavohenke** 2017-12-06 23:28 UTC
Labels: docs

**Comment by terryc129** [comment] 2018-03-22 09:56
@maxtechera Have been wasted my afternoon trying to figure out why. Thanks for saving my night

**Comment by brneto** [comment] 2018-05-06 23:35
@marcpeters2, Pal you've salved my day with this comment [here](https://github.com/erikras/redux-form/issues/1744#issuecomment-275142556). Very thanks!!!!

**Comment by herarya** [comment] 2018-06-08 03:34
@marcpeters2 thanks brooo, working

**Comment by shravanipl** [comment] 2019-02-05 05:09
But after importing from redux-form/immutable I am getting 

> Module not found: Can't resolve 'immutable' in 'D:\gift_savvy_client\node_modules\redux-form\lib\structure\immutable'
