### ISSUE TITLE
Update redux 4.0.0 peer dependancy

### ISSUE THREAD

**Issue by andrewmclagan** [erikras/redux-form#4068] opened 2018-06-12 06:26 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

Peer dependancy warning for redux `^4.0.0`

`warning " > redux-form@7.3.0" has incorrect peer dependency "redux@^3.0.0".`

### What is the expected behavior?

Clean install without npm warnings.

### Sandbox Link

With redux `^4.0.0`:

https://codesandbox.io/s/gJjDoKYWl

### What's your environment?

N/A

### Other information

We (and I assume others) have been using `redux-form v7.3.x` without issue in combination with `redux v4.0.0` for some time. I believe a peer dependancy bump from `"redux": "^3.0.0"` to `"redux": "^3.0.0 || ^4.0.0"` would be great.

**Comment by gustavohenke** [comment] 2018-06-12 06:40
Duplicate of #4009

**Closed by gustavohenke** 2018-06-12 06:40 UTC

**Comment by andrewmclagan** [comment] 2018-06-12 06:56
Sorry I searched could not find the same issue - thought it might be somewhere
