### ISSUE TITLE
Failed Prop Type for fields property when running "Synchronous Validation" Example

### ISSUE THREAD

**Issue by WoleObayomi** [erikras/redux-form#2493] opened 2017-01-24 03:49 UTC
As the title says, I'm trying to run the  "Synchronous Validation" example, however I get this error showing up in the console:

> Warning: Failed prop type: Invalid prop `fields` of type `array` supplied to `SynchronousValidationForm`, expected `object`

The makes sense since the `fields` declared in the example is an array, but the proptype requires an Object. I'm wondering if there's something obvious that I'm missing.

**Comment by gustavohenke** [comment] 2017-01-24 11:55
I'm not getting this error in this example page: http://redux-form.com/6.4.3/examples/syncValidation/

**Comment by gustavohenke** [comment] 2017-01-24 11:56
(or warning, for the sake of this message)

**Comment by gustavohenke** [comment] 2017-01-25 15:53
By the way, if you could provide us a self-contained example that reproduces your issue, it would be great.

**Comment by danielrob** [comment] 2017-08-07 07:17
Closing issue due to non reproduction and non response.

**Closed by danielrob** 2017-08-07 07:17 UTC
