### ISSUE TITLE
Remove validator validation when a Field is disabled

### ISSUE THREAD

**Issue by raviroshan** [erikras/redux-form#2675] opened 2017-03-09 08:52 UTC
### What is the current behavior?
Validation is NOT removed when Redux-Form Field is disabled

### What is the expected behavior?
Validation should be removed when Redux-Form Field is disabled

### What's your environment?
Redux form v6.5.0

### Other informations

I am using Redux form v6.5.0 and having a requirement of Removing the validation for any Field when the disabled props is passed as true.

I wrote a custom logic to disable the validation inside render() of custom field component, but looks like updateSyncErrors() is not getting called on the form even after updating the values manually. Because of this, syncErrors object is persisting the field validation error.

` if (field.disabled) {`
        `field.meta.invalid = false;`
       ` field.meta.error = undefined;`
       ` field.meta.valid = true;`
    `}`

Can we have some straight forward - simple & better approach which tackles this requirement and fixes this issue?

http://stackoverflow.com/questions/42528514/removing-the-validation-when-redux-form-field-is-disabled

**Comment by danielrob** [comment] 2017-07-24 22:14
Redux-form doesn't really have the concept of a disabled Field, even though form elements do. 

To remove validation from a `Field`, you can remove/change the validation function passed to that Field. The developer does currently have full control over that. 

This makes this an enhancement request for adding the of `Field` disablement into the library. Could you please provide some use cases for a `disabled` prop on the Field, and how you would like it to work?  

Relates to #543

**Comment by danielrob** [comment] 2017-07-24 22:17
Closing as a duplicate of #2398

**Closed by danielrob** 2017-07-24 22:17 UTC
