### ISSUE TITLE
v6 proposal regarding loss of focus when stateless functions are passed to `Field` and `Fields`

### ISSUE THREAD

**Issue by naw** [erikras/redux-form#1555] opened 2016-08-17 16:02 UTC
Regarding these docs:

> You must define the stateless function outside of your render() method, or else it will be recreated on every render and will force the Field to rerender because its component prop will be different. If you are defining your stateless function inside of render(), it will not only be slower, but your input will lose focus whenever the entire form component rerenders.

I understand both the performance and the loss of focus issues that arise when you do something like this:

```javascript
<Field name="address" component={(props) => (
  <input type="text" {...props.input} />
</Field>
```

Nevertheless, this _is_ a nice syntax to have.  At times, defining the stateless function _outside_ of your render function is fairly inconvenient and undesirable because it moves your code out of the immediate cognitive context.  It would be nice to have this syntax, _without_ the performance and loss of focus issues.

The most onerous of the issues is the loss of focus issue, which ultimately is caused because react thinks the functional component is a completely different component each time, which causes react to unmount the old one and mount a new one, rather than just changing the props on the existing one.

The crux of the mounting (and loss of focus) issue is that `redux-form` is treating these functions as _functional components_ (i.e. passing them to `react.createElement`) rather than just arbitrary _functions_ that _return_ elements (i.e. JSX).

**My proposal is that we introduce a lower-level API to `<Field>` and `<Fields>` that allows you to pass a _function_ instead of a _functional component_:**

```javascript
<Field name="address" render={(props) => (
  <input type="text" {...props.input} />
</Field>
```

Note this is _identical_ to the former code, except instead of passing our function as the `component` prop, we're passing it as the `render` prop.  Then, `redux-form` internally would simply _call_ this function  _rather_ than passing it to `react.createElement`.  

This approach allows what I believe was the originally desired syntax for stateless functions, but does _not_ cause the loss of focus issues.  Thoughts?

**Comment by naw** [comment] 2016-08-17 16:10
This ties into the older discussion here https://github.com/erikras/redux-form/issues/961, in particular https://github.com/erikras/redux-form/issues/961#issuecomment-219821050

**Comment by clayne11** [comment] 2016-08-17 16:37
What you're proposing doesn't fix the issue. Every time that `Field` is rendered you're creating a new function and thus `React` is not able to reconcile the render function as the same function **because it isn't the same function**.

There's no way to make this work within React. The way reconciliation works within React makes this impossible.

**Comment by naw** [comment] 2016-08-17 17:03
@clayne11 I believe you've misunderstood the crux of how my solution works.  I'm suggesting _not_ passing the function to `react.createElement`, which means what react is reconciling is what is _returned_ by the function, which is other components which indeed _are the same_.

**Comment by clayne11** [comment] 2016-08-17 17:05
Oh alright. I see what you mean. So within the `Field` render function instead of using `React.createElement` you would simply call `render`.

```javascript
const Field = ({component, render}) => {
  if (render) {
    return render()
  }

  return React.createElement(component)
}
```

That's the gist of it?

**Comment by naw** [comment] 2016-08-17 17:06
Yes, that's the gist of it.

**Comment by naw** [comment] 2016-08-17 17:12
FWIW, it's feasible to build this as a wrapper around `<Field>` in user land, but ever since #961, I've felt `redux-form` lost some elegance.

**Comment by erikras** [comment] 2016-08-17 18:26
This is how `v6` originally treated the function syntax, but in #871, @gaearon convinced me that `createElement()` was the way to go.

Presumably for this "just call the function" syntax to work, `Field` would need to ignore changes to the `render` prop in `shouldComponentUpdate()`, right? That means that you're going to lose any changes to closure variables in your function, which will lead to _very_ confusing bugs.

**Comment by naw** [comment] 2016-08-17 21:08
Yes excellent point about the closures, and for that reason, you _definitely couldn't_ ignore changes to the `render` prop in `shouldComponentUpdate`.

That _does_ mean every field that is constructed using the `render` prop would be re-rendered, so I suppose this is another case of performance vs. convenience.   Arguably, the DOM manipulations are the slowest, so re-rendering identical virtual DOM is hypothetically very fast, although I suppose large forms could suffer, which is why this is a trade-off that people would have to weigh.

I'm sure you know this, but just to be very clear for anyone following the discussion and also to address the subtleties of #871, functions can be treated in two different ways:

1. _functional components_.   If you're passing the function as a _Component_ in the `component` prop, then it definitely it needs to be treated as a component and passed to `createElement` as @gaearon suggested in #871, and things like `propTypes` will work as expected.

2. Regular old JavaScript _functions_ that return a value. If you're passing the function as a _function_ in the `render` prop, then you don't want to pass it through `react.createElement`.  Instead, you want to call it directly. This is fairly analogous to having helper methods in your components that return a portion of your `render()` result:

```javascript
class MyComponent extends Component {
  someChunk() {
    return <p>Some Chunk</p>
  }
  render() {
    return (
      <div>
        <p>Main content</p>
        { this.someChunk() }
      </div>
    )
  }
```

Here there is certainly no expectation that `someChunk` is to be treated as a component or that defining `propTypes` on it would work.

I can see that someone could accidentally pass a functional component to the `render` prop by mistake (instead of the `component` prop) and have unexpected behavior.

The reality is there are intrinsic subtleties to inline functions:

1. closure values
2.  unmounting/remounting if you're using `createElement`

These subtleties are exactly why we have that big warning in the docs about _not_ using inline stateless functional components. 

I don't think there is any way to escape these subtleties, so I suppose what I'm suggesting is rather than warning people _not_ to use inline functions, and rather than avoiding inline functions altogether, warn them that inline functions need to be treated as plain functions (not functional components) and passed to `render` instead of `component`.

You make a good point that performance would be affected.  My proposal is solving the "loss of focus" issue, not the performance issue.

**Comment by naw** [comment] 2016-08-17 21:23
Part of the trouble here is that react is treating a function as a component in a certain cases (i.e. when you pass it to `createElement`), which makes distinguishing regular functions from functional components awfully subtle.  Perhaps it would have been better for functional components to need to be explicitly created as in:

`createFunctionComponent((props) => <p>Render this</p>);`

Too late now.

**Comment by clayne11** [comment] 2016-08-17 22:07
In light of the discussion in #871 it makes sense to me to leave things as they are. Perhaps it would make more sense to have the component as a child to the `Field`, which I saw mentioned in another issue:

```javascript
<Field>
  <MyInput/>
</Field>

**Comment by davidkpiano** [comment] 2016-08-17 22:17
> Perhaps it would make more sense to have the component as a child to the Field, which I saw mentioned in another issue

That's how it works in React-Redux-Form, if you want to look there for implementation details. (more than willing to help!) It's a pattern that seems to work pretty well.

Regarding rendering custom components, V1 is giving the option to have children-as-a-function:

```js
<Field>
{(fieldValue) => <MyInput ... />}
</Field>
```

that provides the field. I know performance is a concern, so there's also a new prop: `<Field dynamic={false}>` that can be set to say "the `children` are pure and will never change" (e.g., no closured variables, no dynamic children, etc.) and this speeds up performance by letting `shouldComponentUpdate` only `shallowEqual` compare for changed props _without_ checking `children`.

What do you think of those patterns? Would be glad to help!

**Comment by erikras** [comment] 2016-08-17 22:18
> This is more idiomatic React

I'm not so sure about that statement, but I have looked at how [`react-redux-form`](https://github.com/davidkpiano/react-redux-form) does it (as you suggest), and there is just something about _cloning_ nodes that reeks, perhaps illogically, to me of performance loss. The word "clone" turns me off.

Of course @davidkpiano would post as I was writing this. :-P (I had already linked to his library before his post showed up)

**Comment by davidkpiano** [comment] 2016-08-17 22:20
@erikras Yeah, cloning is weird but it's working pretty well 😄  I don't prefer it either but I can't really think of a better way that allows for a succinct API.

**Comment by erikras** [comment] 2016-08-17 22:23
> V1 is giving the option to have children-as-a-function

This feels (perhaps it is not, but I'm sharing my many-years-of-xml gut reaction) pretty disgusting. I'm sure you recall back when you had to do `<Provider>{() => <MyApp/>}</Provider>` due to React issues (with context?) with `react-redux`.

It's unclear to me that passing children-as-a-function is less disgusting than prop-as-a-function.

**Comment by davidkpiano** [comment] 2016-08-17 22:27
Got my inspiration from here: https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9#.jw39d4gb6

**Comment by clayne11** [comment] 2016-08-17 22:28
> I'm not so sure about that statement, but I have looked at how react-redux-form does it (as you suggest), and there is just something about cloning nodes that reeks, perhaps illogically, to me of performance loss. The word "clone" turns me off.

I agree with you on that point. I'm not sure if there is actually a performance issue but every time I clone a node I have that same sinking feeling in the pit of my stomach that I'm doing something wrong.

It would be good to get some input from someone more in the know about React performance.

**Comment by davidkpiano** [comment] 2016-08-17 22:34
@clayne11 @erikras To be fair, [`React.cloneElement`](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L313-L392) basically does almost the exact same thing you'd have to do manually in Redux-Form for custom components anyway - copying props over to build a new control.

Also, in V1, the `<Control>` component will be introduced which uses `createElement` for standard controls (e.g., `input`, `textarea`, `select`, etc.) instead of `cloneElement`.

**Comment by naw** [comment] 2016-08-17 22:47
Perhaps this is obvious, but "inline function as a child" vs. "inline function as a prop" is purely cosmetic. 

The child in JSX is just syntactic sugar for the 3rd argument to `createElement`, so whether you put the function in the 3rd argument, or you put it in the 2nd argument, you have exactly the same underlying closure issues and the same underlying performance issues, don't you?

**Comment by clayne11** [comment] 2016-08-17 23:15
You do. I don't think allowing inline function definition is a good pattern at all.

**Comment by davidkpiano** [comment] 2016-08-17 23:26
> I don't think we should allow / encourage it.

Why? In the most common cases (that is, without closures) pure and idempotent functions as children can be optimized, by having `shouldComponentUpdate` skip over them.

I'd like to see Redux-Form's API at a point where there isn't a sizable amount of nuances the developer has to "just know" by reading the docs, such as being forced to define the render function outside the `<Field>` component.

**Comment by naw** [comment] 2016-08-17 23:28
@clayne11 

Interesting. How awkward would HTML be if you could only nest things 2 levels deep, and you always had to define the child before the parent like this:

MyParagraph:
```
<p>
  Hello World
</p>
```

MyBody:
```
<div>
  <MyParagraph>
</div>
```

Final Page:
```
<body>
  <MyBody>
</body>
```

That's how using redux-form without an inline API feels to me, and I'd gladly trade some performance for a less clumsy API.  Just trying to help explain my opinion, definitely OK if you disagree.

**Comment by naw** [comment] 2016-08-17 23:43
I'm not necessarily opposed to using children instead of a function, but you still have the exact same performance and closure issues because the children themselves are inline, and have access to all of the variables in scope. They are rendered every time (just like the function would be rendered every time), so there is no performance benefit.

```javascript
<Field>
  <MyInput/>
    <span someProp={somethingFromScope}>Hello</span>
  </MyInput
</Field>
```

So,  children vs. functions is just a cosmetic issue, not an underlying shift in performance or closure issues.     To the degree that you can optimizing things for one approach, you can optimize them for the other approaches.

The fundamental question here is whether specifying field code inline is a desirable API to have.

**Comment by clayne11** [comment] 2016-08-17 23:48
IMO it's not really like that. I'm essentially saying that for each different type of component you want to support, you have to create a re-usable component.

Presumably you want your forms to be consistent throughout your app, so you need to create one of each:
- text input
- date picker
- checkbox
- radio button
- select field
- switch

and maybe a couple others. I don't think it's particularly onerous to ask you to create these re-usable components before passing them into `redux-form`. You're probably going to be wrapping them with HOCs that will show errors, labels, and perhaps even use a schema to restrict values / pre-populate select fields.

In React in general you're not supposed to create new functional components inline. Also, `redux-form` is solving a particular use-case which is high-performance forms that manage validation and state. In order to get these benefits you're trading off some simplicity and boilerplate.

In general with `redux` you're trading performance / ability to reason about a large app for boilerplate. You have to write a lot of boilerplate with `redux`, which is no different that what's happening here.

Personally, I'll write some extra boilerplate to significantly decrease the number of bugs that I have in my app and to ensure that I can track down performance problems. If you don't like writing boilerplate then you probably shouldn't be looking at `redux`-anything as a solution to your problem.

That's my two cents at least.

**Comment by naw** [comment] 2016-08-18 00:10
Yes I can see (although I don't completely share) your perspective regarding a fairly limited number of reusable form controls.  Personally, probably 90% of mine are pre-defined, whereas 10% might be one-off things where inline would be nice.

How about `<Fields>`, though?

```javascript
<Fields names={['field1', 'field2']} render={({ field1, field2 }) => (
   some condition based on field1 and field2 ? <OneThing /> : <AnotherThing />
)} />
```

Would you move every chunk of logic like that into a pre-defined named component/function?

**Comment by naw** [comment] 2016-08-18 00:23
I think we can agree reducing bugs and tracking down problems are good goals, so really the difference here seems to be what aspects of coding we feel helps us do that, and whether the library itself should encourage or discourage a given approach.

My proposal supports both approaches, so I suppose the ultimate question is whether supporting both approaches is overall good or bad for the library as a whole, and of course that's not my call to make.

My desired API is feasible through user land wrappers; my proposal was based on the assumption that an inline API was generally desirable to the rest of the community too.

**Comment by erikras** [comment] 2016-08-18 06:22
Excellent and thoughtful discussion here, guys. 👍 If only all internet discussions were as well argued and respectful. 😄

Let's define the problem that this issue is trying to address.

---

### Problem

#### It's annoying having to define component render functions outside of `render()`.

---

@naw illustrated this brilliantly with [his HTML analogy](https://github.com/erikras/redux-form/issues/1555#issuecomment-240580309). Having functions inline always makes for more readable code. However, there are many performance issues, and potentially confusing closure bugs, with this.

I think we have concluded the all the options suck in their own unique way, so we have to decide what tradeoff we want to make.

@naw has discovered that just calling the function rather than using `createElement()` to create a functional component solves the focus issue. However, this _does_ result in the `propTypes` problem from #871. How about this:

---

### Proposal

#### `redux-form` could just look at the function to see if there is a `propTypes` property, and if there is, it uses `createElement()`, otherwise it calls the function.

---

What this gets us:

* No need to introduce a new `render` prop; we can use `component`.
* It allows a user to write fat arrow components inline in their `render()` method if they absolutely prefer to trade the performance hit of constant rerendering for "cognitive convenience".
* No closure issues because we're recreating the function on every render.
* Solves the focus issue.
* If you've got `propTypes` defined, you're already not defining the function inline anyway.
* It follows @gaearon's advice: "[You’re generally not supposed to create components inside `render()`](https://github.com/erikras/redux-form/issues/961#issuecomment-219796022)", as it's just a function for how to render, not a component.

The only con I can think of is that it's a bit of a misnomer to have a "not a component, just a how to render" function be passed to a prop called `component`, but I think it's superior to the introduction of another prop.

What do you think?

**Comment by ruiaraujo** [comment] 2016-08-18 10:11
@erikras I like your proposal, as long as 6.0.0 final is cut before. 😄 

 I would say that stabilising redux-form as it stands should be the priority.

**Comment by erikras** [comment] 2016-08-18 10:16
@ruiaraujo That's the thing, though. My proposal would not be a breaking change. If anything, it would _repair_ problems from people misusing the current way.

**Comment by ruiaraujo** [comment] 2016-08-18 13:02
@erikras I know it is not breaking hence it can be worked on after the final cut. 😉

**Comment by clayne11** [comment] 2016-08-18 14:11
@erikras I don't like that solution. A lot of people are moving to use `flow` in place of `propTypes`, and `propTypes` are also not a requirement for a functional component. Personally I like the way things are now and I don't like this change.

I really think it should just stay the way it is now. Defining anything, be it a component or a function, is an anti-pattern in React.

**Comment by naw** [comment] 2016-08-18 15:09
I agree it would be sticky to use `propTypes` as a heuristic for whether a function is meant to be used as a functional component or whether it's meant to be used as a function.  At it's simplest, a function meant to be used as a functional component is indistinguishable from a normal function, and it's difficult to predict how changes in react in the future might cause subtle differences in behavior if a simple functional component were accidentally treated as a plain function.  

Having two props forces users to think about what they're really trying to do; unfortunately, people will still be able to shoot themselves in the foot (which they already doing now, because not everyone reads the warning in the docs).

I think two props is fine (although `render` might not be the best name for the second prop).

I don't think it's an anti-pattern to pass values to anonymous functions --- it's a powerful technique programmers use all the time, and merely being in react (or redux) doesn't fundamentally change that. 

The only reason closures start causing bugs is when you try to cache the function (i.e. ignore it in `shouldComponentUpdate`) --- it's not intrinsically fragile.

It's interesting to me that if we maintain the position that all inline code is discouraged, then every field is isolated in its own component guarded by `shouldComponentUpdate`, which means the lion's share of the performance benefits of v6 are actually achievable in v5 without the separate `connect` calls for each field. Simply moving all field content into separate components so that the main form component "owns" nothing directly achieves most of the performance benefits.

Having content inside a function that is executed on every render is completely equivalent to having that same content directly inside the main form component, from a performance perspective.

For example, suppose you have this in your form:

```javascript
Form = () => (
  <SomeStylingWidget>
    <p>Some extra arbitrary content goes here</p>
  </SomeStylingWidget>
)
```

Every time you rerender the form, you _also_ have to rerender that widget content.   In order to have better performance, you _could_ move that widget stuff into a component guarded by `shouldCompoentUpdate` like this:
```javascript

class WidgetContent extends Component {
  render() {
    <SomeStylingWidget>
      <p>Some extra arbitrary content goes here</p>
    </SomeStylingWidget>
  }
}

Form = () => (
  <WidgetContent />
)
```

However, one of advantages of react is that _it efficiently resolves these differences for you_ so that you don't have to optimize things like this yourself in awkward ways.

First you optimize for the programmer, then you optimize for performance.  In other words, we want to be able to write code that is the most clear and convenient, without being forced into tricks to achieve performance (at least until performance itself becomes the problem).

All of that said, expanding the API of a library has a lot of ramifications, so if you decide it's not the right time to add something like this, I completely understand.

**Comment by clayne11** [comment] 2016-08-18 15:45
> It's interesting to me that if we maintain the position that all inline code is discouraged, then every field is isolated in its own component guarded by shouldComponentUpdate, which means the lion's share of the performance benefits of v6 are actually achievable in v5 without the separate connect calls for each field. Simply moving all field content into separate components so that the main form component "owns" nothing directly achieves most of the performance benefits.

I think the issue with performance in `v5` is that the form itself would re-render on every single change, thus re-rendering every component. Even if every component implemented `shouldComponentUpdate`, the form itself re-rendering becomes expensive if there are a lot of components inside of it.

> Having content inside a function that is executed on every render is completely equivalent to having that same content directly inside the main form component, from a performance perspective.

The issue isn't with having content inside of a function - it's defining a new function on every render pass. That's expensive within the JavaScript VM itself, and you're removing an entire layer of optimizations done by the VM even without accounting for React optimizations.

**Comment by naw** [comment] 2016-08-18 17:31
Yep I agree using inline functions are slower from the VM standpoint, and I agree there is no reliable way to distinguish functions from functions intended as functional components, and I agree @gaearon's input would be welcome here.

**Comment by gaearon** [comment] 2016-08-19 09:56
>redux-form could just look at the function to see if there is a propTypes property, and if there is, it uses createElement(), otherwise it calls the function.

I don't think changing behavior depending on propTypes is a good solution. Some people remove them in production which would change the behavior between dev and prod.

**Comment by gaearon** [comment] 2016-08-19 10:09
I think you could have a heuristic like this:

1. Create an element with component and props (this would trigger propTypes validation)
2. If component has a prototype, return that element
3. If component has contextTypes, return that element
4. Grab resolved props from the element (they would include defaultProps)
5. Return the result of calling component with resolved props

Not sure if it covers all cases but maybe it could work.

**Comment by erikras** [comment] 2016-08-19 10:25
Thanks for that, @gaearon. That seems a little too close to the React metal than I would like. i.e. it feels like something that might break from a non-breaking release of React because it's sidestepping the public API.

Overall this has been a great discussion, but I haven't seen an argument that is so powerful as to overcome the inertia of leaving the API as is. Thank you to you all.

**Closed by erikras** 2016-08-19 10:25 UTC
Labels: discussion
