### ISSUE TITLE
UNREGISTER_FIELD is called when CHANGE is triggered for initialValues

### ISSUE THREAD

**Issue by patrickpoh** [erikras/redux-form#1915] opened 2016-10-06 09:45 UTC
Hi, 
I'm placing my renderField inside the react class because I am using the react state to control the visibility of the field. Everything is working fine but everytime i try to edit the initialisevalues the UNREGISTER_FIELD will get fired. 
Is there a work around?
Thank you!

**Comment by jonahlau** [comment] 2017-01-08 05:45
I'm having this problem too on v6.4.3.  

I am passing state 
```
{
  initialValues: {
  users: [{}]
}
```
On the first `CHANGE` action, all the fields unregister, causing the form to lose focus.  Only happens on the first `CHANGE`, doesn't happen again afterwards. Any help would be appreciated!

**Comment by TeaBough** [comment] 2017-02-16 15:46
I'm having the same problem with v6.5.0 ...

**Comment by gustavohenke** [comment] 2017-06-15 23:34
And can anyone here please provide a working example?

**Comment by patrickpoh** [comment] 2017-06-19 09:22
I kinda solve it. 
https://stackoverflow.com/questions/39908302/how-to-hide-show-field-in-fieldarray-for-redux-form-v6

**Comment by gustavohenke** [comment] 2017-06-19 12:58
Hm, I might see your problem now, @patrickpoh.
v6.8.0 landed with a new prop on field arrays, `rerenderOnEveryChange`. Could be helpful for you.

**Comment by gustavohenke** [comment] 2017-06-23 13:09
Closing, then.

**Closed by gustavohenke** 2017-06-23 13:09 UTC

**Comment by johanarnor** [comment] 2017-09-14 10:22
We were experiencing the same issue, which was caused by an inline stateless function. So we basically followed the advice here https://redux-form.com/7.0.4/docs/api/field.md/#2-a-stateless-function.
