### ISSUE TITLE
Supply `name` to `onChange` etc.

### ISSUE THREAD

**Issue by kevva** [erikras/redux-form#3854] opened 2018-02-22 10:27 UTC
### What is the current behavior?

Currently when passing `onChange` to a field, you get the `event`, `newValue` and `previousValue`. I want to be able to run `event.preventDefault()` and then do some custom logic on the value and save it manually using the `change` action creator. See below for an example:

```jsx
import {change} from 'redux-form';

const handleChange = (e, val) => {
	e.preventDefault();
	// Here I want to access the field name with the form section prefixed so I don't have to know about
	const name = 'section.input';
	change(form, name, val + 'foo');
};

const Section = ({ onChange }) => (
	<FormSection name="section">
		<Field component="input" name="input" type="text" onChange={onChange}/>
	</FormSection>
);

const App = () => (
	<div>
		<Section onChange={handleChange}/>
	</div>
);
```

### What is the expected behavior?

I think we could add the name to the supplied `event` on `event.target.name` like native DOM elements behave. This would apply on `onBlur` etc. too. We could even add the `form` name to `e.target.form` or something too.

I could do a PR with these additions if you're interested.

**Comment by gustavohenke** [comment] 2018-02-22 10:32
Duplicate of #2849

**Closed by gustavohenke** 2018-02-22 10:32 UTC

**Comment by kevva** [comment] 2018-02-22 10:37
@gustavohenke, so what's the consensus on that issue? Is it something you guys want?

**Comment by gustavohenke** [comment] 2018-02-22 11:08
Unless someone contributes with the complete change (including tests + docs), then it's pretty much not happening any time soon.

**Comment by kevva** [comment] 2018-02-22 12:24
I could do it. Was just making sure you'd want it so that I don't do unnecessary work.

**Comment by gustavohenke** [comment] 2018-02-22 22:59
Yes, please! Sorry if I sounded unwelcoming.
