### ISSUE TITLE
Not able to get Datepicker value in Redux Form

### ISSUE THREAD

**Issue by Puneetbh** [erikras/redux-form#3232] opened 2017-07-22 09:29 UTC
I am using datepicker with redux form, but i am not able to take react-datepicker component value in redux form. 

Datepicker component for redux form

import DatePicker from 'react-datepicker'
export const renderDateField = ({ input,showYearFlag, label,onDateChange,selected,classes, placeholder,minDateVal, maxDateVal,showMonthFlag, disabled, meta: { touched, error, warning } }) => {
  return (
    <FormGroup>
      <label>{label}</label>
      <DatePicker
          {...input}
          selected={selected}
          onChange={onDateChange} 
          onChangeRaw={onDateChange} 
          onClick={onDateChange} 
          className={classes.date_picker}
          placeholderText={placeholder} 
          dateFormat='DD/MM/YYYY' 
          showYearDropdown={showYearFlag ? true : false }
          maxDate={maxDateVal}  //maxDate
          minDate={minDateVal}
          autoOk={true}
          dropdownMode="select"
          disabled={disabled} 
          showMonthDropdown={showMonthFlag ? true : false}
      />
      <span className={classes.cal1}><i className="fa fa-calendar" aria-hidden="true"></i></span>
      {touched && ((error && <span className={classes.redColor}>{error}</span>) || (warning && <span>{warning}</span>))}
    </FormGroup>
  );
};

When i add {...input } in component then selected value from date picker doesn't show in input field. I tried adding  onChange event i.e. onChange={(event, value) => input.onChange(value)} but still same issue

below is my code how i used

<Field name="DateOfDeath" type="text" 
                                            component={renderDateField} 
                                            label="Date of Death" placeholderText="dd/mm/yyyy" 
                                            selected={this.state.DateOfDeath}
                                            onDateChange={this.handleChangeDeathDate} 
                                            showYearFlag={true}
                                            showMonthFlag={true}
                                            classes={classes} 
                                            disabled={this.state.death_date_disabled}
                                            minDateVal={this.state.DOB ? moment(this.state.DOB) : ''}
                                            maxDateVal={moment()}
                                        />

**Comment by danielrob** [comment] 2017-07-22 12:33
I'd suggest debugging by starting with a [simple example](https://codesandbox.io/s/1wR4lR28G) and working your way up. Closing this as a duplicate of #1797. Please note the closing comment: 

> This issue doesn't belong to our GitHub issue tracker.
> We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
> *As usual*, don't forget to explain your question well and show what you've got so far!
> 
> This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
> Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.
> 
> Thanks for using Redux Form!

You might also like to refer to #543.

**Closed by danielrob** 2017-07-22 12:33 UTC
Labels: question
