### ISSUE TITLE
fields set by initialValues inherit different state behavior

### ISSUE THREAD

**Issue by lnhrdt** [erikras/redux-form#2677] opened 2017-03-11 04:58 UTC
### Are you submitting a **bug report** or a **feature request**?

I've noticed a discrepancy between the behavior of a field set by initialValues and a field that is not. It has made some of my custom code cumbersome and I believe it may be a bug.

### What is the current behavior?

Given a field that has not been initialized by initialValues
When the field's value is set to ''
Then the field does not appear under values in state

Given a field that has been initialized by initialValues
When the field's value is set to ''
Then the field does appear under values in state as ''

### What is the expected behavior?

In both scenarios when a field's value is set to '', the field should not appear under values in state

### What's your environment?

redux-form 6.5.0

**Comment by danielrob** [comment] 2017-07-07 01:22
Sandbox reproduction. https://codesandbox.io/s/mZRjw05yp

I'm not unconvinced this is by design? initialValues keys should always exist, however I don't want keys for form values that have not had a value specified. 

Can you suggest why this is the expected behaviour?

**Comment by danielrob** [comment] 2017-08-07 05:56
Closing due to non response. Worth linking that this is almost the opposite expected behaviour of #3004.

**Closed by danielrob** 2017-08-07 05:56 UTC
