### ISSUE TITLE
Form not cleared

### ISSUE THREAD

**Issue by zdila** [erikras/redux-form#1407] opened 2016-07-27 15:35 UTC
I've implemented method A of form clearing described at http://redux-form.com/5.3.1/#/faq/how-to-clear but the fields are not cleared. If I focus any of the field afterwards then it gets cleared.

**Comment by erikras** [comment] 2016-07-27 21:42
And you're certain that the action you are listening to (`ACCOUNT_SAVE_SUCCESS` in the example) is getting dispatched?

**Comment by zdila** [comment] 2016-07-28 08:48
Sure. I have logging on every strategic place :-).

Last version of redux-form where it is working is 5.2.4. In 5.2.5 and 5.3.x it doesn't work.

In my componnent I log in `componentWillReceiveProps` values of `nextProps.fields.myField` (mapped by `reduxForm` function) and `nextProps.myForm` (mapped from `getState().form.myForm`). After resetting the form the `nextProps.fields.myField` logged as not being reset and `nextProps.myForm` is logged as undefined (correctly).

And as I mentioned, the field resets (clears) just after I focus it.

**Comment by rkoberg** [comment] 2016-07-28 13:46
(using 6.0.0rc3) I have a similar issue. In my case, on an edit form for an existing record  (/entity/edit/1234), there is a button to add a new record (&lt;Link className="button" to="/entity/new">Add new&lt;/Link>). I call to an HOC on a 'page' component that includes a child redux-form component. The HOC call checks to see if an entity ID is in the params and either dispatches an action to load the entity from an API or create an empty record object (below). So either an existing entity or an empty entity populates initialValues for a redux-form instance. On click of "Add new", the correct data (new blank props, new blank initialValues) are being passed into the component(s) for redux-form, but redux-form does not change. I would figure this is enough to change the form input values from the existing edit form to a blank 'add new' form.  If I add ```enableReinitialize: true,``` to the reduxForm props, then the form input values do change.

What is the proper way to handle the case described above? Shouldn't passing new props cause a re-render? Why is isn't ```enableReinitialize: true,``` the default? I assume it is not the default for a performance benefit, and would prefer to take advantage of that. How or what is the best way?

```
// redux-connect
export default asyncConnect(
  [
    {
      promise: ({ params, store }) => {
        if (!params.id)
          return store.dispatch(actions.regions.getNew());

        return store.dispatch(actions.regions.getById(params.id, apiSelect));
      }
    },
  ],
  (state) => {
    return {
      regions: state.regions,
    };
  },
  {
    createOrUpdate: actions.regions.createOrUpdate,
    remove: actions.regions.remove,
  }
)(Form);
```

**Comment by zdila** [comment] 2016-08-05 09:39
Can you reproduce this?

**Comment by rkoberg** [comment] 2016-08-05 13:34
@zdila , if you are asking me, yes. I can reproduce this in rc4. I need ```enableReinitialize: true,``` to take in the new (empty/blank) values of the location change initialValues.

**Comment by zdila** [comment] 2016-08-08 20:30
I would like this to be fixed in the lates stable (5.3.x). I think it is pretty critical.

**Comment by clayne11** [comment] 2016-08-09 02:16
At this point I would recommend migrating to `v6`. I don't think a lot of `v5` issues are going to be resolved going forward as `v6` is almost fully released.

**Comment by danielrob** [comment] 2017-07-28 13:11
Closing as a duplicate of #1083.

**Closed by danielrob** 2017-07-28 13:11 UTC
