### ISSUE TITLE
Validating single fields using async Field-Level Validation

### ISSUE THREAD

**Issue by twheys** [erikras/redux-form#2344] opened 2016-12-27 18:25 UTC
In my project, I have a form that can be very large and has some complex validation.  Currently, the onChange triggers all of the validators for all of the fields.  In addition to the Field-Level Validation, it would be nice to be able to configure my form to only validate the changed field during the onChange event, rather than the entire form.

**Comment by eligolding** [comment] 2016-12-28 15:11
Validation actually happens right away, even before the `onChange` event fires. There are many other `meta` props you can use to decide whether or not to _show_ a validation error (`dirty`, `touched`, `visited`, etc.), but as far as redux-form is concerned, a field is always being validated.

**Comment by twheys** [comment] 2016-12-28 15:41
My problem is that the validation is an expensive operation for some fields so I'd like to set them to only trigger a validation for themselves rather than the entire form.   This could potentially also be achieved by marking something that has been validated so that it won't be validated again until it is changed.

**Comment by eligolding** [comment] 2016-12-28 16:19
Interesting. Another potential way perhaps is to simply check if the value changed before running the validation on the field.
I'm curious to hear why validation is so expensive. It's usually simple functions that don't actually cause a re-render unless the props actually change. 
Or are you referring to async validation?

**Comment by twheys** [comment] 2016-12-28 16:26
I have some fields that are expressions and validated using a [Jison](http://zaa.ch/jison/) grammar which I wrote.  There are many of them depending on which entities are loaded into the form.

**Comment by erikras** [comment] 2017-01-06 20:47
Would [Async Validation](http://redux-form.com/6.4.3/examples/asyncValidation/) be better for those expensive fields?

**Comment by twheys** [comment] 2017-01-09 16:19
Yes, would it be possible to support Async validation on the Field-Level? http://redux-form.com/6.4.3/examples/fieldLevelValidation/

**Comment by AleksOrl** [comment] 2017-02-28 12:21
@erikras is there any plans to support async validation on Field-Level on next releases?

**Comment by danielrob** [comment] 2017-07-26 04:21
Duplicated by #2763. Closing as a duplicate of #2763.

**Closed by danielrob** 2017-07-26 04:21 UTC
