### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by eventhough** [erikras/redux-form#353] opened 2015-11-30 21:14 UTC
I just updated to the latest version `3.1.1` and started to get an error when initializing my form:

`TypeError: Cannot convert undefined or null to object`

This happens when I call `this.props.initializeForm` with data that contains a null value, for example:

```json
{
  "foo": "hello",
  "bar": null
}
```

Initializing with null values used to work for me but now it seems like null values are being rejected. Was this an addition in the latest update to handle deep forms? If so, maybe the change log should also list null value incompatibility for upgrading?

**Comment by erikras** [comment] 2015-11-30 21:21
This was caused by the inexplicable javascript quirk that `typeof null === 'object'`. Doh!

Fixed in v3.1.3

**Closed by erikras** 2015-11-30 21:21 UTC

**Comment by mtostenson** [comment] 2016-08-17 22:56
👍
