### ISSUE TITLE
validate can't take a function which returns a function

### ISSUE THREAD

**Issue by gtournie** [erikras/redux-form#3208] opened 2017-07-18 23:56 UTC
I'm the author of https://www.npmjs.com/package/redux-form-validators and I noticed a very weird behavior when I tried to upgrade to 7.0.1. 
As you can see in this sample: https://codesandbox.io/s/zmQ2VDnR7, validate doesn't accept a function which returns a function. (give the focus to the field and then click somewhere else)
```
const required1 = function(value) { 
  return value ? undefined : 'Required1'
}
const required2 = function() { 
  return function(value) { return value ? undefined : 'Required2' }
}
const required3 = required2()
```
validate={ [required1] } => WORK
validate={ [required2()] } => DOESN'T WORK
validate={ [required3] } => WORK

This was working with redux-form 6.4.3

**Comment by danielrob** [comment] 2017-07-21 21:59
Related to #3094 / duplicate of #3225?

**Comment by danielrob** [comment] 2017-07-24 19:06
Closing this as a duplicate. See also #3211. 

I also verified that you can change the validator - see https://codesandbox.io/s/ZV7xwYB6E which has the code: 

```
let isA = true
const requiredTwoA = function(value) { return value ? undefined : 'Required2A' }
const requiredTwoB = function(value) { return value ? undefined : 'Required2B' }
const required2 = function() { return (isA === true) ? requiredTwoA : requiredTwoB }
```
You can change the validator by toggling `isA` (which is actually the point of this change). 

However, if you _always_ return a new value, the Field will continuously deregister and re-register, as discussed in #3211.

**Closed by danielrob** 2017-07-24 19:06 UTC
Labels: bug

**Comment by paibamboo** [comment] 2017-07-27 02:32
Any suggestions how we can pass something like `maxCharacters` or `minLength` on the fly?

**Comment by gtournie** [comment] 2017-07-27 03:45
@danielrob: it works with a basic function, but the main purpose of returning a function in a function is to pass some options. 
I don't see how to do that. The code below doesn't work:
```
const requiredTwoA = function(value) { return value ? undefined : (this.msg + ' Required2A') }

const requiredTwoB = function(value) { return value ? undefined : (this.msg + ' Required2B') }

const required2 = function(options) { 
  return (isA === true ? requiredTwoA : requiredTwoB).bind(options)
}
```
Anyway, I guess we have to wait until they fix #3211

**Comment by danielrob** [comment] 2017-07-27 16:24
@gtournie, the resolution of #3211 will probably shortly be close as intended behaviour.

Regarding your case above. The point is, that if you want the validation function to change, you should change what is returned. In your case, if options changes, you change the validation function. Memoization seems ideal for this. The problem with bind is it creates a new function. So on every render your function is changing. 

If you think my answer is insufficient or there is a use case memoization can't solve please add to #3211.

@paibamboo I'll respond on #3211.

**Comment by jedwards1211** [comment] 2018-07-04 14:11
@gtournie
Rob said it right here, but you ignored what he said besides memoization:

> You could perhaps memoize as a workaround if for some reason moving the function outside of render calls is not possible

He said *perhaps* memoize, he did not say it is the only option!

**Comment by jedwards1211** [comment] 2018-07-04 14:21
@gtournie here is a viable solution to your example that doesn't require memoization:
```js
const requiredTwoA = function(value) { return value ? undefined : (this.msg + ' Required2A') }

const requiredTwoB = function(value) { return value ? undefined : (this.msg + ' Required2B') }

const required2 = function(options) { 
  return (isA === true ? requiredTwoA : requiredTwoB).bind(options)
}
const myValidator = required2({isA: true})

// The value will obviously always be the same because it's `const`:
<Field validator={myValidator} />
```

**Comment by jedwards1211** [comment] 2018-07-04 14:23
@gtournie you obviously also missed this point Rob made:

> The problem with bind is it creates a new function. So on every render your function is changing.

**Comment by gtournie** [comment] 2018-07-04 21:35
@jedwards1211 I didn't miss anything. I made the choice to use memoization because I liked the idea of inline validations and didn't want to break the backward-compatibility of redux-form-validators.

That being said, I'll probably add something about memoization & customization functions in the docs.

**Comment by danielrob** [comment] 2018-07-05 05:40
@jedwards1211 thanks for this. Would you mind doing a sanity check on #4017, as this is my latest advice to everyone on this. I've been locking most of these old issues to centralize discussion there, but missed this one. 

@gtournie I just haven't found(/made) a good moment recently to add to the docs - #4017 is maturing up though, so feel free to create a PR based off that if you felt you could contribute! 

Please add further remarks to #4017.
