### ISSUE TITLE
How to batch remove items from FieldArray?

### ISSUE THREAD

**Issue by leojh** [erikras/redux-form#1758] opened 2016-09-13 23:01 UTC
Is there a way to remove multiple items from a FieldArray in a batch? Currently, I'm doing them one by one using the actionCreator `arrayRemove` however this creates a problem because the copy of my FieldArray values and what's in the state get out of sync so finding the index to remove becomes difficult.

**Comment by huan086** [comment] 2016-09-14 06:31
There an arraySplice method at https://github.com/erikras/redux-form/blob/master/src/ConnectedFieldArray.js#L19. No idea why that is not documented

**Comment by leojh** [comment] 2016-09-14 18:45
Yeap, I saw `arraySplice` but didn't think about using it for what I needed. However, it looks like the implementation for `arraySplice` is not the same as the native `splice` in that it does not take multiple values to be added back into the array.

So for example, doing this
`arraySplice('form', 'field', 0, field.length, "bob", "alice", "mary")` should add items "bob", "alice", and "mary" into the array, however only "bob" is added.

**Comment by iyn** [comment] 2016-10-27 19:36
AFAIK, `arraySplice` is not an undocumented feature but simply the action/function name that `array.splice` is mapped to (similarly to `arrayPop` -> `array.pop`). The problem is with the bug in the way `splice` in the `arraySplice` function is implemented, because it takes only first argument to insert and ignores the rest. This is related: https://github.com/erikras/redux-form/issues/2031

Hopefully I'll (or maybe somebody else) get to fix this in the next few days. Right now, my workaround is to use https://github.com/tshelburne/redux-batched-actions to batch `array.removeAll` and multiple `array.inset` calls with the desired items/objects)

**Comment by leojh** [comment] 2016-10-27 20:36
Yeap, the other issue describes the problem more succinctly. I ended up doing multiple `array.insert` calls to get around the issue.

**Comment by danielrob** [comment] 2017-07-25 00:24
Closing this as it is now tracked in a re-formulated issue: - duplicate of #3244

**Closed by danielrob** 2017-07-25 00:24 UTC
