### ISSUE TITLE
If you submit a form with enableReinitialize, but your backend reverses your changes, the redux form state does not get reset

### ISSUE THREAD

**Issue by MrLeebo** [erikras/redux-form#3230] opened 2017-07-21 17:34 UTC
I want to start by saying I'm a big fan of this package! This is an issue I've witnessed a couple of times but never really circled around it enough to figure out what was going on. Until today, that is.

### Bug Report
With `enableReinitialize` set, if the form is backed by an API endpoint that automatically makes corrections to the form (such as trimming whitespace) and you submit a form where the changes are going to be reversed, the form state does not reset. This is because `initialValues` appear to be unchanged, even though the form state itself has actually changed.

### What is the current behavior?
1. Setup a form with a backing store that automatically trims whitespace. Or use [the sample I wrote](https://mrleebo.github.io/redux-form-whitespace/).
2. Initially the form `pristine` state is `true`. When a change happens, it becomes `false`.
3. If you make a change to the form, but your backend API reverses that change, the form will submit successfully, but the form state will not update.
4. `pristine` remains `false` after a successful form submit.

### What is the expected behavior?
1. Since the form submitted successfully, `pristine` should reset to `true` and the form values should match the initial values.

I can work around the issue by intentionally changing the response so that it isn't a complete match to the initial values, such as by adding a timestamp.

### Sandbox Link
https://github.com/MrLeebo/redux-form-whitespace

### What's your environment?
Redux Form v7.0.1
Mac OSX El Capitan
Chrome 59
Node 7.4.0

**Comment by tstirrat15** [comment] 2017-07-24 18:13
What's the behavior that you're after?

`enableReinitialize` has a number of annoying interactions with `touched`/`clean`/`dirty`, but in my experience, they're correct, if just a bit weird.

For your particular case, I have two questions.

First, why do you need `enableReinitialize` here? You can get correct behavior just by removing that. Or is this just a minimal example of the issue as you see it?

Second, why not use a `normalize` function to do the trimming? You'd avoid these issues altogether.

**Comment by MrLeebo** [comment] 2017-07-24 19:28
For cases where there are a legitimate change to the form, you want to enableReinitialize so that the new form state becomes the initial "pristine" state. In our application, there are a couple of features that are based on the state of the form:

- If the form is pristine, disable the save button because the user is already in sync.
- If the form is not pristine and the user attempts to navigate away, display the "You have unsaved changes, are you sure you want to leave?" dialog box.

If you leave `enableReinitialize=false`, then both of these interactions do not work. The save button remains enabled even though you are in sync with the server, and you get a confirmation box about unsaved changes when there are none.

The demo app I prepared showcases this in the Repro notes.

This is kind of a simplified example because we have other cases where the API validates and may "fix" the model for you, but I figured going into those details would be harder to explain and lose focus on the issue. Consider "trimming whitespace" to be a stand-in for any form submit action that might get "reversed" by the backend.

The behavior I'm looking for is when redux-form dispatches the `"@@redux-form/SET_SUBMIT_SUCCEEDED"` action, which signifies that the submit worked; obviously I submitted the form successfully. Per `enableReinitialize`, the form state should return to the pristine state using the new `initialValues` that came back in the server response. However, I think that there is some code lurking in the codebase that looks like:

```
// hypothetical guard clause
if (deepEquals(initialValues, previousInitialValues)) {
  return // no change
}

// reset form state
```

Which prevents redux-form from calculating the new form pristine state, so it gets stale. I think that guard clause should not be there.

In our app, we've worked around the issue by adding a timestamp to the form submit response. The timestamp serves no purpose except to make the response NOT hit that `if (deepEquals(...))` path.

**Comment by MrLeebo** [comment] 2017-07-24 19:31
I was close ;)

https://github.com/erikras/redux-form/blob/8c6f4a2933cb1bc2c81b20244b19d1e761f56fc3/src/createReduxForm.js#L308-L309

**Comment by danielrob** [comment] 2017-08-01 23:04
Intriguing. Good runnable reproduction example, thanks. I think I can't argue with what you're saying: 
If `initialValues` and  `nextIntialValues` are different, you want to update (current behaviour). 
If they are the same, you still want to update (I.e. you want a reset action called).

If you want faster action on this, I'd suggest raising a PR (to remove that deepEquals). You'll probably get a definitive answer much quicker that way. 

Question: is there an alternate workaround to call reset on your form if you get a no-op update like this?

**Comment by danielrob** [comment] 2017-08-02 04:01
Edit: the deepEquals is there to prevent form resets on the update of new non `initialValues` props. If it wasn't there, the form would `initialize` on every props change which is not acceptable. 

This makes me put this in the 'edge case' basket, and probably not something the library should be concerned with, given that there are plenty of mechanisms like normalize to sanitize values before submission. I think your front end and server need to agree on what is the pristine state of your form (aka what is (allowable) in the database). I think this opinionation is actually good: it forces developers to sanitize both on the front and backend.

**Comment by MrLeebo** [comment] 2017-08-06 00:51
Sorry, on mobile. To me, the problem is that this logic is in component lifecycle, but it seems like a reducer decision because the action type is the key information. We have lost track of the action type "submit succeeded" but if we could say "this is a prop change because the submit succeeded" then you would know to reset. I am not sure how to best communicate that to the component, unless we add a timestamp like "lastResetRequiredAt" and skip the deepEquals if it's newer than the last reset.

**Comment by danielrob** [comment] 2017-08-06 22:49
Ok, this and #3136 have got me to thinking: `enableReinitialize` and `initialValues` allow you to reset the forms base state which seems good and clear. But we don't have a way to batch set the values of the form particularly (some other issue (#3055) pointed out that `change` action creator only allows you to set one value). What would you think about more having 'setFormValues' type action? In your case, you could reinitialize & setFormValues, and then you'd be in a pristine state?

**Comment by MrLeebo** [comment] 2017-08-07 12:15
So dispatching a new redux form action off the promise I am already feeding to an existing redux form action (handleSubmit)? Or is this replacing that dispatch? In my opinion, the resolved promise is already a good enough clue that the form values need to be set. This proposal feels like "optimizing the bug" instead of fixing it.

**Comment by duro** [comment] 2017-12-19 07:11
@danielrob Any progress on this? These seems like a big issue, as it's a super common use case to submit the form, then upon response, update the object that was previously used to set initialValues, pass that updated object back into redux-form, and have all values of the form reset to said new initialValues and form go back to pristine. Right now it seems there is no good way to do this.

@MrLeebo Did you ever find a clean way to handle this?

**Comment by duro** [comment] 2017-12-19 07:22
Ooof, don't I feel like an ass. Seems my issue was on my end. My action that stored the saved values that came back from API wasn't actually updating the object used as initialValues in the store. Once I got that resolved, it does now appear to be working as expected.

**Comment by MrLeebo** [comment] 2017-12-19 15:32
My workaround currently is to append a `lastFetchedAt` timestamp to the model. Doesn't matter if you do it server-side or client-side, the timestamp will prevent the equality comparison from being true.

**Comment by gustavohenke** [comment] 2018-02-25 12:14
I'm closing this issue because this kind of logic, although quite common, isn't something we're keen on implementing at the moment.
Understanding `onSubmit` response is probably not worth the trouble.

**Closed by gustavohenke** 2018-02-25 12:14 UTC
