### ISSUE TITLE
SubmissionError in redux-saga

### ISSUE THREAD

**Issue by tobyl** [erikras/redux-form#1713] opened 2016-09-06 20:53 UTC
Seems like a few people are struggling with this, but no clear answer - how are people handling submit validation with redux-saga?

For example, I have:

```
const response = yield call(auth.login, email, password);
...
yield put({ type: REQUEST_ERROR, error: response.error });
```

How can I tie back into redux-form when my logic and API calls are all so separate?

Many thanks in advance.

**Comment by KyKyPy3** [comment] 2016-09-06 21:43
You have two ways to report a error from you sagas:
1. In your submit function you can create promise and pass it to you api call
`
...
submitForm(params) {
    return new Promise((resolve, reject) => {
       this.props.apiRequest({ ...params.toJS(), resolve, reject });
    });
  }
...
`

in you sagas you can reject promise with an error

`reject(new SubmissionError({ _error: error }));`

2. You can dispatch stopSubmit with an error
`stopSubmit('form', errors)`

**Comment by tobyl** [comment] 2016-09-07 11:47
That's awesome! thank you so much, I'll give this a try.

**Comment by tobyl** [comment] 2016-09-07 19:01
I believe I have this basically solved.. In my saga I have the resolve/reject in place:

```
if (response.status_code > 299) {
    reject(new SubmissionError({ _error: 'Some error' }));
  } else {
    yield call(auth.setAuthToken, response.content.token); // save to local storage
    yield put({ type: LOGIN_SUCCESS, token: response.content.token });
    resolve(response.content);
  }
```
And now I can see the error in state in Redux Dev Tools. However, the error doesn't display on screen.

Is it relevant that I'm using immutablejs? I've tried importing `SubmissionError` from `redux-form` and `redux-form/immutable`.

**Comment by KyKyPy3** [comment] 2016-09-08 08:58
Yes, you should use SubmissionError from redux-form/immutable. And we need a bit more of information to understand what the problem is. Make sure that you return the promise from your submit callback and make sure that you layout contain ```javascript {error && <span>{error}</span>} ``` to display an error.

**Comment by ElfenLiedGH** [comment] 2016-11-08 07:56
@tobyl 
```

import {SUBMIT_FAILURE} from '../actions' // some action that meen faild submit
import {stopSubmit} from 'redux-form'

const traceError = (error)=> {
   const stackError = error.error.data;
   if (stackError.кодОшибки === 449) {
      if (stackError.поля) {
         let errors = {};
         // collect fields with error + error messages
         stackError.поля.forEach(elem => {
            errors[elem.имяПоля] = elem.сообщение;
         });
         return errors;
      }
      return stackError
   }
   
   // ather error
}

// waiting for submit error && call stopSubmit
export function* ждатьНеУспешнойОтправкиДанныхФормы() {
   yield* takeEvery(SUBMIT_FAILURE, сообщитьОбНеУспешнойОтправкеДанныхФормы)
}

// take object with field names && error messages and put they to stopSubmit
function* сообщитьОбНеУспешнойОтправкеДанныхФормы(action) {
   yield put(stopSubmit(action.dialogName, traceError(action.error)))
}

```
it work

**Comment by danielrob** [comment] 2017-07-23 16:23
Closing: this usage question is resolved.

**Closed by danielrob** 2017-07-23 16:23 UTC
