### ISSUE TITLE
Field type prop

### ISSUE THREAD

**Issue by poyannabati** [erikras/redux-form#2754] opened 2017-03-29 09:57 UTC
<Field type="checkbox" /> isn't simply passed through to the component, but changes behaviour of field component. Expected behaviour is achieved when using <Field props={{type: 'checkbox'}} />

The docs don't say anything about the type prop being reserved or having special meaning. 

Version 6.4.3

**Comment by gustavohenke** [comment] 2017-03-29 12:08
Closing as a duplicate of #2292.

**Closed by gustavohenke** 2017-03-29 12:08 UTC
Labels: duplicate
