### ISSUE TITLE
Custom props are not being passed into Field's validate function

### ISSUE THREAD

**Issue by wlingke** [erikras/redux-form#2633] opened 2017-02-26 01:34 UTC
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
If I pass a custom prop into a `<Field component={Component} custom={custom} validate={validate}/>`

```
const validate = (value, values, props) => console.log(props.custom) //undefined
```

### What is the expected behavior?
I expected all props to be available in validate.

### What's your environment?
redux form 6.5.0

**Comment by gustavohenke** [comment] 2017-02-27 21:52
> [...] The function will be given the current value of the field, all the other form values, **and any props passed to the form**.

http://redux-form.com/6.5.0/docs/api/Field.md/#-validate-value-allvalues-props-error-optional-

**Comment by wlingke** [comment] 2017-02-27 21:54
So should we not expect custom FIELD props to be passed down? Only custom form props?

**Comment by gustavohenke** [comment] 2017-02-27 23:47
cc @erikras

**Comment by cchrysostomou** [comment] 2017-03-01 16:08
Along the lines of custom FIELD props being passed down, I am trying to validate a Field using a custom array of possible values. 

For example...

```
field.value = 'a'
fieldprops.possibleValues = ['a','b','c']
validfield = fieldprops.possibleValues.indexOf(field.value) > -1
```

If we cannot pass down custom props from the field into a validation function, how would I achieve the above validation?

**Comment by wlingke** [comment] 2017-03-01 16:27
Use a higher order component to create the validate function from your
custom prop.

Be careful that you'll probably want to make the validate function a class
property in the HOC and not generate it in render().

If you create it in render, it might cause some issues with the field since
you'll be creating a new function with a diff reference every time.

**Comment by cchrysostomou** [comment] 2017-03-01 16:35
Sorry Im new to reduxform so I did not completely understand your
suggestion. I am currently using the FieldArray validation prop, and not
the reduxForm validation.

Are you saying to use the higher order component to create a validation
wrapper function, where I then encapsulate the custom prop variable  as a
hardcoded variable, and then pass the wrapped function to my fieldarray
validation prop?

**Comment by wlingke** [comment] 2017-03-01 17:38
Something like this:

```
const createValidateFunction = (options) =>(value) => ////logic here

class MyInput extends Component {
    validate = createValidateFunction(this.props.options)
    render() {
        return <FieldArray ...otherprops validate={this.validate} />
    }
}
```

Note that with this pattern "validate" will not change if your custom props change after initialization. If you need it to change, you'll need to implement `componentWillReceiveProps`

**Comment by cchrysostomou** [comment] 2017-03-01 18:03
Yea OK, thats what I assumed you were saying/ a version of the above.

Thanks!

**Comment by danielrob** [comment] 2017-07-25 18:35
This was duplicated by #2881 but that one has a clearer write up to my eyes, so closing this as a duplicate of #2881.

**Closed by danielrob** 2017-07-25 18:35 UTC
