### ISSUE TITLE
Field data is not removed when a Field has been unmounted

### ISSUE THREAD

**Issue by lauriii** [erikras/redux-form#3176] opened 2017-07-13 17:00 UTC
### Are you submitting a **bug report** or a **feature request**?
Action `@@redux-form/UNREGISTER_FIELD` doesn't delete Field value when a component is unmounted. The problem this causes is that if you have conditional fields, the data is being submitted from fields that have been unmounted.

### What is the current behavior?
Field data is kept after unmounting.

### What is the expected behavior?
Field data should be removed after unmounting has happened. This is the same behavior as what would happen when redux-form is not being used on a form.

### Sandbox Link
https://codesandbox.io/s/PZ19V5Pwy

### What's your environment?
Tested with 6.8.0 and 6.3.0

### Other information
-

**Comment by danielrob** [comment] 2017-07-19 07:08
This is intentional for the Wizard forms use case, where you want to build up your form state across pages, or across field changes.  Even with conditional fields it is a valid use case to want the data to return if the field is re-enabled, so outright scrapping the value is not really an option. 

Since we can't call this a bug, I'm guessing it's a feature request, but I'm not exactly sure what the appropriate feature requested would be here.

If it's an issue of data submission exclusion, this is something that can be solved in user land, by managing the same relevancy rules applied to your form elements inside the submission function. Likely there are libraries for managing relevancy rules like this, even if not, I think it's not something that should live in redux-form itself. 

If it's an issue of nonetheless wanting to be able to force a value to be erased on deregistering, a) do you have another use case than exclusion, and b) if so, it would be interesting to have something similar like a `destroyOnUnregister` which applies at the Field level.

Perhaps you could clarify your needs before I go wandering off into abstract possibilities!

**Comment by danielrob** [comment] 2017-07-25 01:32
Closing this due to non-response, and also it's essentially a duplicate of #2761.

**Closed by danielrob** 2017-07-25 01:32 UTC
