### ISSUE TITLE
Some redux-form props are not set within the propNamespace

### ISSUE THREAD

**Issue by srosset81** [erikras/redux-form#2540] opened 2017-02-01 11:16 UTC
Hello,

I'm using the propNamespace option for `reduxForm()` because I've got complex components which have already too many props.

However I've noticed that some of the props passed by the redux-form HOC are not set within the namespace. In particular I see:

```this.props.autofill
this.props.clearAsyncError
this.props.clearSubmit
this.props.submit
this.props.onSubmit
```

All others props (functions and values) are set in the propNamespace.
Moving the props would create a breaking change but that would make redux-form more coherent.

Thanks!

**Comment by gustavohenke** [comment] 2017-02-03 11:20
Among those, [only `clearAsyncError` is documented](http://redux-form.com/6.5.0/docs/api/Props.md/).

Could you please submit a failing test case or even a complete fix for this?

Even though semver states that a major version comprises "incompatible API changes" (and this is what happens - for a small subset of Redux Form users), I feel like this is a bug - you expected those to be nested inside that `propNamespace`, and this is not happening.

**Comment by jimniels** [comment] 2017-05-22 17:37
Confirming that I see this same issue. Expected all redux-form props to be nested under my value specified in `propNamespace` but they're not.

This can be easily reproduced by going to the ["Simple Form" example](https://codesandbox.io/s/mZRjw05yp) and adding a `propNamespace` prop to `reduxForm()`. See screenshot:

![propnamespace](https://cloud.githubusercontent.com/assets/1316441/26321165/00ea5d20-3ee3-11e7-87af-476936150374.png)

**Comment by RobCherry** [comment] 2017-06-21 20:13
Related, but not necessarily the same issue.  When creating a form with an `onSubmit` function, the props parameter does not respect `propNamespace`.

For example:

If you had `propNamespace: 'form'`, there are a bunch of props correctly namespace (`dirty` is one of them) in your component.  So for example you would use `this.props.form.dirty` in your component.  In the `onSubmit` function, you would have to use `props.dirty` because `props.form` is the name of the form for whatever reason.

**Comment by gustavohenke** [comment] 2017-12-06 23:00
Because this issue saw almost no activity for a few months, I'm closing it.

**Closed by gustavohenke** 2017-12-06 23:00 UTC
Labels: bug
