### ISSUE TITLE
Form submit is not working after using aysnc blur validation.

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [erikras/redux-form#3275] opened 2017-08-01 09:20 UTC
I really have no idea about what went wrong because, the async validation is working well but I am unable to use submit button after that. 
redux-form => 7.0.3

Here is my async method:
 ```
 `import * as api from '../../../tools/apiConfig';
import axios from 'axios';
const asyncValidate =(values, dispatch, props, currentFieldName) => {
  const locale = props.locale.contactinfo;
  return new Promise((resolve, reject) => {
    if (currentFieldName === 'zip') {
      const field1 = {
        postal_code: values.zip
      }
      axios.post(api.VALIDATE_ZIP, field1).then((response) => {
        if (response.data == false) {
         return reject({ zip: locale.postalRemoteValidate });
        }
        else {
         return resolve()
        }
      });
    }
    else if (currentFieldName === 'email') {
      let field2 = {
        email: values.email
      }
      axios.post(api.VALIDATE_EMAIL, field2).then((response) => {
        if (response.data == false) {
         return reject({ email: locale.emailValidation });
        }
        else {
         return resolve()
        }
      })
    }
  })
}

export default asyncValidate;
```

`

**Comment by danielrob** [comment] 2017-08-07 08:47
@Abhijeetjaiswalit thanks for confirming but no need to create a duplicate of #2021.

**Closed by danielrob** 2017-08-07 08:47 UTC
