### ISSUE TITLE
An empty object is returned if a field is undefined when calling getValues

### ISSUE THREAD

**Issue by xcatliu** [erikras/redux-form#383] opened 2015-12-04 10:37 UTC
```js
reduxForm({
  form: 'simple',
  fields: [ 'name' ]
})(SimpleForm);

// action creator
import { getValues } from 'redux-form';

console.log(getValues(getState().form.simple));
// { name: {} }
```

**Comment by erikras** [comment] 2015-12-04 13:02
Thanks. Will investigate. :mag:

**Comment by ooflorent** [comment] 2016-05-11 15:25
I'm unable to reproduce the bug.

```js
it('should ignore undefined fields', () => {
  const state = {
    name: makeFieldValue({}),
  };
  expect(getValuesFromState(state))
    .toBeA('object')
    .toEqual({});
});
```

As expected, the result is `{}`.
@erikras Can we close this one?

**Comment by erikras** [comment] 2016-05-11 15:28
Sure. I never got around to investigating. 😦 

Go ahead and PR that test if you want. You can never have too many tests, especially if they demonstrate functionality reported as buggy.

**Closed by erikras** 2016-05-11 15:28 UTC
Labels: bug
