### ISSUE TITLE
Fieldlevel validation with unrendered fields

### ISSUE THREAD

**Issue by Zombaya** [erikras/redux-form#2451] opened 2017-01-12 15:58 UTC
I have a large form with multiple pages.  I excitedly implemented the new fieldlevel validation and it's working perfectly fine when I'm on the page with the invalid field.  However when I navigate to the second part of the form, the form is said to be valid since the invalid field is not being rendered anymore.

Is there a solution to this except forbidding the user from navigating to another page of the form?

If needed, I can whip up an example to test with.

**Comment by goshakkk** [comment] 2017-01-12 19:34
In a case like this, you'd most certainly want to stop using field-level validation, and validate on the form-level instead. There's no other way to implement the behavior you want with field-level validation alone, because as soon as a field is not rendered, RF will not care about its validations (and rightfully so.)

The redux-form factory accepts a validation function which takes in an object of fields, and is expected to return an object of format `{ fieldName : stringErrorMessage }`, like this

```javascript
const validate = values => {
  return {
    username: !values.username ? 'required' : undefined,
  };
}

export default reduxForm({
  form: 'myCoolForm',
  validate,
})(CoolForm);
```

The factory function reference: http://redux-form.com/6.4.3/docs/api/ReduxForm.md/

So for your form, you can define a big validator function which will check all the fields. No, just because it's big doesn't mean it's bad. Furthermore, having your validations all in one place makes it way easier to understand the data relationships in the form by scanning the single function, as opposed to jumping between several `render` methods and reading into them (and then maybe missing something!)

Fwiw, I do have an article on the subject of field-level validations drafted and may publish it soon-ish.

**Comment by RT-TL** [comment] 2017-01-13 11:55
@Zombaya 
One advice from my side, experiencing the same problem: I did not understand the validation function well enough. If you use form-level validation as suggested by goshakkk (great advice by the way!) then your validation function needs to always validate ALL FIELDS. So if you render different form fields make sure all other form fields are validated as well. If you try to validate only those fields on the current page it will result in props being `{invalid: false, valid: true}` which causes the redux-form to skip validating subsequent fields if they are not touched.

**Comment by Zombaya** [comment] 2017-01-13 11:58
I'm aware of the possibility of using a big validator-function and I agree it is better for validating relationships between fields.  But for simply validating minimum values and date-formats, it's much easier to declare this on the fieldlevel.

In my opinion it is strange that the filled in values which are also not rendered do get saved, but the validation for those fields not.

I do however really like the fact that those values get saved, even though they are not rendered anymore.

**Comment by goshakkk** [comment] 2017-01-13 12:48
@Zombaya it's not strange at all. The field-level validations are kind of "additional data" about the field, and RF only has access to it while the field is rendered. Changing RF to "remember" unmounted fields could lead to unwanted bugs and behavior, which is a huge trade-off just to make a case like yours possible.

I would also argue that if it were to work like this, it would hurt the readability, understandability, and predictability of the form code, since the reader of the code will now have to be aware of other components rendering the same form, the order in which they are rendered, and so on, which will make keeping mental track of the final set of validations exhausting to say the least.

Just move all of that to the form-level validation function.

Another alternative for your case might be to always render all the steps, and using CSS to hide the ones you don't want visible.

**Comment by Zombaya** [comment] 2017-01-13 13:05
I just want to point out that RF already remembers unmounted fields, just not the validation-data of those fields.  

I agree that it will be hard and errorprone for fields that are dependant on other formvalues but for simple validations (like minimumvalue, filled in required fields, ...) this validation would only need to be run when the fields are changed and thus the validation could be remembered just like the value.  This doesn't seem that unreadable or ununderstandable for other readers of the code.

I do agree that using fieldlevel validation that depends on other fields will be hard to understand for others and prone to errors.

I plan to adjust  my code according to what has been said here, but nevertheless do I see value in remembering the validation-state of unrendered fields.

**Comment by sslotsky** [comment] 2017-01-14 13:43
If I might make a suggestion and shamelessly promote myself, I have a validation library that would make it a lot less cumbersome to apply the same validation rule to multiple fields. Here's an example of what it could look like using both built in and custom validations:

```javascript
import { validator, defineValidator } from 'validate-this';

function isValidDate(value) {
  if (value && !DATE_FORMAT.test(value)) {
    return 'date_invalid'
  }
}

defineValidator({
  name: 'lessThan',
  rule: max => value => {
    if (value && value >= max) {
      return 'value_too_large'
    }
  }
})

function validate(values) {
  return validator(values, v => {
    v.validate('first_name', 'last_name').required()
    v.validate('start_date', 'end_date').satisfies(isValidDate)
    v.validate('head_count', 'chair_count').lessThan(25)
  })
}
```

**Comment by dnzyt** [comment] 2017-02-09 20:45
Even you use form-level validation, the validation still doesn't happen on the unmounted fields.

**Comment by danielrob** [comment] 2017-07-20 05:00
Closing this issue since it is a duplicate of #2321 -> this doesn't mean discussion shouldn't continue on this topic!

**Closed by danielrob** 2017-07-20 05:00 UTC
