### ISSUE TITLE
Redux-form 6.0+ change all field values

### ISSUE THREAD

**Issue by MistyKuu** [erikras/redux-form#2306] opened 2016-12-17 09:58 UTC
I am trying to change multiple values in redux-form. I have them in one object so basically I want to override redux-form state values with my object values. One way to accomplish it is to run this.props.reset() followed by multiple this.props.change() events for each property. It works but it sends too many events and is slow. The second thing I tried is to run this.props.initialize(data,false) and this works but validation isn't rerun so I can easily submit the form without validation. Is there a way to run one event to override form state with my object?

**Comment by gustavohenke** [comment] 2016-12-28 12:45
Duplicate of #2118

**Closed by gustavohenke** 2016-12-28 12:45 UTC
Labels: duplicate
