### ISSUE TITLE
Values aren't retained with WizardForm when destroyOnUnmount and initialValues are used in conjunction

### ISSUE THREAD

**Issue by b3njamin** [erikras/redux-form#1549] opened 2016-08-17 05:19 UTC
If I set initialValues on a form that uses destroyOnUnmount, when I return to that form the values are reset.

**Comment by clayne11** [comment] 2016-08-17 16:38
This is a duplicate of https://github.com/erikras/redux-form/issues/1503

**Comment by erikras** [comment] 2016-08-17 16:58
Closing for dupe reason.

**Closed by erikras** 2016-08-17 16:58 UTC
