### ISSUE TITLE
automatically build field list from jsx form

### ISSUE THREAD

**Issue by funkytek** [erikras/redux-form#593] opened 2016-01-26 17:12 UTC
trying to create a form ie:

``` js
<form className='ui form'>
  <input name='name' required />
  <input name='location' required placeholder='San Francisco, CA' />
...
```

inspect the fields and create the `fields` list (and `validator`) for redux-form

I've devised a solution for this but it's a bit jenky, react's limited reflection capabilities (or my knowledge of them) make it tough to get that data 'out of' the parent component I can inspect the children in and into redux-form.  

looking for any thoughts on how you might achieve such a thing, thanks! cc/ @contra

**Comment by erikras** [comment] 2016-01-26 17:54
You mean by looking at the `name` props on the `<input/>`s? The problem is that `redux-form` would still need to add its listeners to each input. The most interesting proposal I've seen for "inline `fields` list generation" was to do something like:
```js
<form>
  <input type="text" {...field('name')}/>
  <input type="text" {...field('location')}/>
```
...but I have not had time to follow it to its conclusion and see if it's really better.

**Comment by gustavohenke** [comment] 2017-05-14 04:30
Closing due to low demand for this feature.

**Closed by gustavohenke** 2017-05-14 04:30 UTC
Labels: enhancement
