### ISSUE TITLE
Simple form example crashing

### ISSUE THREAD

**Issue by sandwichsudo** [erikras/redux-form#4410] opened 2019-03-24 17:46 UTC
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

The simple form example page is not accessible 

### What is the expected behavior?
The page should load

### Sandbox Link

https://redux-form.com/8.1.0/examples/simple/
### What's your environment?

Redux form site

### Other information

The error is in redux-form:

```
Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(ReduxForm(u))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ReduxForm(u))".
    at invariant (https://unpkg.com/redux-form@5.4.0/dist/redux-form.js:1548:16)
    at new Connect (https://unpkg.com/redux-form@5.4.0/dist/redux-form.js:1794:33)
    at constructClassInstance (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:11461:18)
    at updateClassComponent (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:14787:5)
    at beginWork (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:15744:16)
    at performUnitOfWork (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:19412:12)
    at workLoop (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:19452:24)
    at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:143:14)
    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:193:16)
    at invokeGuardedCallback (https://unpkg.com/react-dom@16.8.5/umd/react-dom.development.js:250:31)
```

**Comment by FaresAbu-Khiarah** [comment] 2019-03-25 10:14
This https://redux-form.com/8.1.0/examples/asyncvalidation/ is also crashing

**Comment by zburke** [comment] 2019-03-25 10:26
The issue is likely that release v5.4.0 was inadvertently marked as the latest release (#4407) so the example is using a v8.1.0-compatible form with v5.4.0 of redux-form.

**Comment by AlexVotry** [comment] 2019-03-26 15:38
It's not just the simple form. It is all the forms in the examples route.

**Comment by wilsson** [comment] 2019-03-26 16:22
😢 
<img width="966" alt="Captura de pantalla 2019-03-26 a la(s) 11 21 56" src="https://user-images.githubusercontent.com/4754339/55014681-6abfa780-4fb9-11e9-8515-d1b830151e0f.png">

**Comment by gustavohenke** [comment] 2019-03-26 22:37
It must be fixed now peeps. https://twitter.com/erikras/status/1110563993750593536

**Comment by gustavohenke** [comment] 2019-03-26 22:38
Duplicate of #4408

**Closed by gustavohenke** 2019-03-26 22:37 UTC
Labels: bug, docs
