### ISSUE TITLE
Validate props for Field component

### ISSUE THREAD

**Issue by lutowolk** [erikras/redux-form#1916] opened 2016-10-06 10:37 UTC
I think it will be more comfortable if component field will be have validate property, instead of validate prop for reduxForm

**Comment by SpainTrain** [comment] 2016-10-07 21:19
Possible dupe of:

- #917 
- #1207 
- #1765

**Comment by gustavohenke** [comment] 2017-01-16 23:16
v6.3.0 finally included Field level validation 😎

**Closed by gustavohenke** 2017-01-16 23:16 UTC
