### ISSUE TITLE
Correct jsnext:main or remove it

### ISSUE THREAD

**Issue by swernerx** [erikras/redux-form#1416] opened 2016-07-28 13:08 UTC
When using redux-form with Webpack 2 you might currently experience a problem based on the fact that Webpack 2 respects "jsnext:main" but expects that there is no transpilation required to run the code. What most libraries seem to do is to execute some basic Babel without transpiling ES2015 modules. In your case basically the whole .babelrc without `["transform-es2015-modules-commonjs", { "loose": true }]`. See also: https://github.com/reactjs/redux/issues/1042 for a related issue (which is already closed) in redux.

**Comment by mikekidder** [comment] 2016-07-29 01:37
Looks like straight-forward process as Redux has done.  @swernerx , you going to submit a PR on this?  If not, may take a go at it...

**Comment by swernerx** [comment] 2016-07-29 07:44
I am not working on this. So feel free.

**Comment by swernerx** [comment] 2016-07-29 07:45
Seems like somehow this is already fixed: https://github.com/erikras/redux-form/pull/240#issuecomment-235919346

**Comment by jacobk** [comment] 2016-11-25 14:59
The way immutable is exposed also doesn't work with jsnext:main.

I don't think it's possible to import nested files since that will bypass jsnext:main, see https://github.com/rollup/rollup/issues/126

Another issue is that webpack cannot import es6 modules from es5 modules which happens with e.g. the `es6-error` module, see https://github.com/webpack/webpack/issues/3168

I've made some notes on the subject https://github.com/erikras/redux-form/issues/1637#issuecomment-261806317 and https://github.com/erikras/redux-form/issues/1637#issuecomment-261862792

**Comment by dziamid** [comment] 2016-12-08 08:15
@jacobk i guess we will have to wait for webpack/webpack#3168 to resolve. Is there a temporary fix for this?

**Comment by nktssh** [comment] 2016-12-25 12:55
> The way immutable is exposed also doesn't work with jsnext:main.

That's true.

And this is from mentioned issue tread:
https://github.com/rollup/rollup/issues/126#issuecomment-240076414
> Only real solution if you need to put modules in subfolders and have them work everywhere is probably to publish two separate packages from the same repo (which isn't as bad as it sounds, it's what Lodash does for example).

**Comment by danielrob** [comment] 2017-08-03 13:05
Closing due to six months of inactivity. If there are some actionable outcomes from this issue that could improve redux-form, please advise!

**Closed by danielrob** 2017-08-03 13:05 UTC

**Comment by nickbarry** [comment] 2017-09-12 14:01
Per [my comment here](https://github.com/erikras/redux-form/issues/2211#issuecomment-328862166), is there a recommended workaround, until the issue is fixed?
