### ISSUE TITLE
Dispatching submit after initialize yields wrong form values

### ISSUE THREAD

**Issue by uqee** [erikras/redux-form#3032] opened 2017-06-07 14:28 UTC
### Type
Probably a bug.

### Process
1. Set `onSubmit` to `handleSubmit(data => ...)`.
2. Dispatch an `initialize(FORM_NAME, {})` action to clear `initialValues`.
3. Dispatch a `reset(FORM_NAME)` action to revert to the previously initialized values.
4. Dispatch a `submit(FORM_NAME)` action to submit empty values.

### Current behavior
5. Parameter `data` is a string and equals the `FORM_NAME` value.

### Expected behavior
5. Parameter `data` is an empty object.

### Environment
redux-form@6.4.3

**Comment by gustavohenke** [comment] 2017-06-19 23:38
I think you *might* be forgetting to include some step here.
I recreated them, and it works: https://codesandbox.io/s/ElLmqED3N

**Comment by danielrob** [comment] 2017-07-25 07:10
Closing as probable duplicate of #2818, @gustavohenke when all these actions are called in one synchronous block, the reproduction is achievable. See the extra two buttons at https://codesandbox.io/s/N9D0R2L0K.

**Closed by danielrob** 2017-07-25 07:10 UTC

**Comment by duhseekoh** [comment] 2017-08-14 22:51
This is happening to me on 7.0.3. My scenario is not in one synchronous block.

1. User taps submit button
2. This gets triggered 
```
onClick={props.handleSubmit(vals => {
                  // onSubmit is defined in a wrapper component
                  props.onSubmit(vals, CONTENT_FORM_ACTIONS.PUBLISH);
                })}
```
3. Redux action uses the values to submit to api
4. on return of that api call, an `initialize` is called 
```
dispatch(initialize('content', {
  id: savedItem.id,
  ...vals
}, false);
```
5. At this point, the 'content' redux-form has the *correct* state. `initial` is updated and so is `values`.
6. User types something in the form fields
7. User presses submit again. `initial` is correct and `values` are correct, BUT, the values sent to the handleSubmit method are still the `initial`. They never get set to `values`. The reducer is correctly updating, but handleSubmit does not. It's also worth mentioning that the `dirty` flag is correctly reset from the initialize, but any field modifications after that do not set the `dirty` flag to `true`.

It's like the react component is partially disconnected from redux-form after the initialize. By not doing an initialize, everything stays in sync.

**Comment by urzhumskov** [comment] 2017-12-26 11:33
I'm experiencing exactly the same behavior as @duhseekoh described with 7.2.0: the first submit works correctly, all subsequent ones receive the same stale values.

**Comment by duhseekoh** [comment] 2017-12-26 14:45
@urzhumskov - Since i commented on a closed issue, it probably isn't getting attention. Want to open a new issue? Feel free to copy any of my comments.
