### ISSUE TITLE
Support Redux 4

### ISSUE THREAD

**Issue by MitchLillie** [erikras/redux-form#4029] opened 2018-05-16 21:40 UTC
### Are you submitting a **bug report** or a **feature request**?
* feature request

### What is the current behavior?
```
npm i redux@4
npm i redux-form@7.3.0

warning " > redux-form@7.3.0" has incorrect peer dependency "redux@^3.0.0".
```

### What is the expected behavior?

No warning is displayed.

### Other information
The change from Redux 3 to 4 was minor, and should not have affected much. Should just be a matter of updating peerDependencies.

**Comment by gustavohenke** [comment] 2018-05-17 01:08
Duplicate of #4009 and #4019.

**Closed by gustavohenke** 2018-05-17 01:08 UTC
