### ISSUE TITLE
[v.6]: Idea: validate prop in a Field

### ISSUE THREAD

**Issue by oreqizer** [erikras/redux-form#1207] opened 2016-06-23 16:40 UTC
Putting a `validate` prop directly to the component has the following benefits:
- no need to match object property names with field names
- access to redux store and parent component props

The latter is important mainly when using something like `react-intl`. Instead of making the error be a _message descriptor_ object, then making the Field's component be connected to `intl` like [so](https://github.com/oreqizer/reactizer/blob/develop/src/browser/js/components/TextField.jsx), we could simply do the following:

``` javascript
<Field
    name="yourFieldName"
    component={YourFieldComponent}
    validate={value => yourValidator(value) ? null : props.intl.formatMessage(messages.yourError)}
/>
```

_Note: ignoring the fact that `material-ui` uses `errorText`, and not `error`, but that's just an implementation detail_

**Comment by tacomanator** [comment] 2016-06-23 22:28
Would also indirectly solve #935.

A benefit of the way it's done today is access to all values which is necessary for dependent validations (e.g. field1 must be less than field2). Perhaps this could be addressed in your proposal by passing all values as a second argument:

```jsx
<Field
    name="yourFieldName"
    component={YourFieldComponent}
    validate={(myValue, allValues) => myValue < allValues.field2}
/>
```

or a function that can retrieve a value given the path:

```jsx
<Field
    name="yourFieldName"
    component={YourFieldComponent}
    validate={(myValue, getValue) => myValue < getValue('field2')}
/>
```

**Comment by oreqizer** [comment] 2016-06-24 06:19
I like the idea with all values as a second parameter

**Comment by eliseumds** [comment] 2016-08-20 11:43
Following. It would be indeed very useful.

**Comment by SpainTrain** [comment] 2016-10-07 20:58
dupe of #917 ?

**Comment by gustavohenke** [comment] 2016-12-27 01:02
This was done as of v6.3.0! 🎉

**Closed by gustavohenke** 2016-12-27 01:02 UTC
Labels: enhancement
