### ISSUE TITLE
map is not a function with FieldArray

### ISSUE THREAD

**Issue by sarovin** [erikras/redux-form#3618] opened 2017-11-16 12:11 UTC
Hi, i use FieldArray for add members in to a group.
Now i want edit a group and change the members:

This is my form:
```
class CustomForm extends PureComponent {
  componentWillMount() {
    const { initialValues } = this.props;
    const clone = Object.assign({}, initialValues);

    clone.members = membersSelector(clone.members);

    this.setState({
      initialValues: clone,
    });
  }

  render() {
    const { onSubmit } = this.props;

    return (
        <Form className="form-2" handleSubmit={onSubmit} initialValues={this.state.initialValues}>
          <div className="form-input-group">
            <Field
              name="name"
              component={Input}
              validate={[required, stringWithSpace]}
            />
            <Field
              name="note"
              component={TextArea}
            />
          </div>
          <div className="form-manage">
            <h5 className="title-sidebar">Utenti del team</h5>
            <FieldArray
              name="members"
              component={ArrayField}
            />
          </div>
        </Form>
    );
  }
}
```

and this is my custom filedarray:
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { Field } from 'redux-form';
import { Button } from 'antd';
import Input from './Input';
import { required } from '../validations';
import Message from './Message';

const propTypes = {
  title: PropTypes.string,
  placeholder: PropTypes.string,
  fields: PropTypes.object, // eslint-disable-line react/forbid-prop-types
  meta: PropTypes.shape({
    touched: PropTypes.bool,
    error: PropTypes.string,
  }),
};

class customArrayField extends Component {
  constructor(props) {
    super(props);

    this.onDelete = this.onDelete.bind(this);
    this.onAdd = this.onAdd.bind(this);
    this.handleKeyPress = this.handleKeyPress.bind(this);
  }

  onDelete(index) {
    this.props.fields.remove(index);
  }

  onAdd() {
    const { value } = this.addInput;

    if (value !== '') {
      this.props.fields.push(value);
      this.addInput.value = '';
    }
  }

  handleKeyPress(e) {
    if (e.key === 'Enter') {
      e.preventDefault();
      this.onAdd();
    }
  }

  render() {
    const {
      fields, title, placeholder, meta,
    } = this.props;

    return (
      <ul className="unordered-list-2 w-list-unstyled">
        {fields.map((value, index) => (
          <li key={index} className="list-user">
            <div className="div-block-42">
              <div className="icon-font small"></div>
              <Field
                name={value}
                placeholder={placeholder}
                component={Input}
                validate={[required]}
              />
            </div>
            <button onClick={() => this.onDelete(index)} className="btn-list-action w-button">
              
            </button>
          </li>
        ))}
        <li>
          <h6 className="label-sidebar">{title}</h6>
          <div className="imput-add">
            <input
              type="text"
              ref={(input) => {
                this.addInput = input;
              }}
              className="input-light-bg w-input"
              placeholder={placeholder}
              onKeyPress={this.handleKeyPress}
            />
            <Button className="submit-button w-button" type="button" onClick={this.onAdd}>
              
            </Button>
          </div>
        </li>
        <Message meta={meta} />
      </ul>
    );
  }
}

customArrayField.propTypes = propTypes;

export default customArrayField;

```
### What is the current behavior?
I have this error: `TypeError: (value || []).map is not a function`

### What is the expected behavior?
I want transform the object members to an array and i want pass the array as the initialValue for filedarray.

**Comment by gustavohenke** [comment] 2017-11-17 03:18
Please reproduce your issue using one of the CodeSandbox templates we have, eg https://codesandbox.io/s/gJjDoKYWl or https://codesandbox.io/s/Ww4QG1Wx

**Comment by sarovin** [comment] 2017-11-17 08:35
If i move the componentDidMount in the father component i don't have this problem.
This evening i prepare a more simple example.

**Comment by Sixtease** [comment] 2017-11-17 09:32
Happened to me. The cause in my case was that the initial-values object for the FieldArray was not an array.

**Comment by gustavohenke** [comment] 2017-12-03 00:35
Closing since it's been 16 days without reproduction steps.

**Closed by gustavohenke** 2017-12-03 00:35 UTC
Labels: needs sandbox
