### ISSUE TITLE
Validation errors not passed to fields after re-initialize when enableReinitialize is turned on

### ISSUE THREAD

**Issue by roryp2** [erikras/redux-form#1385] opened 2016-07-22 07:59 UTC
When passing the `enableReinitialize` flag all of the fields are getting being marked as valid even though there are errors present for them. It appears to be that when initialize is called a second time it does not trigger the `redux-form/UPDATE_SYNC_ERRORS` action and as such all of the fields don't get updated with their error state again.

When this flag is passed, I think the `redux-form/UPDATE_SYNC_ERRORS` action always needs to get triggered in this scenario and maybe a change in the logic of `updateSyncErrorsIfNeeded` is needed?

**Comment by roryp2** [comment] 2016-07-22 10:08
I think it is related to the logic here: `https://github.com/erikras/redux-form/blob/v6.0.0-rc.3/src/reduxForm.js#L129`

Due to the syncErrors being the same at the point of the re-intialize, this logic stops the errors being passed back down to the fields: `!plain.deepEqual(syncErrors, nextSyncErrors)`

**Comment by nvelickovic10** [comment] 2016-08-05 09:10
Any new info on this? 
Thanks.

**Comment by jzalucki** [comment] 2016-08-28 13:16
Same issue when your initial values are invalid, you do some changes to fields not require (that won't affect `syncErrors`) and you press `reset`. Then `redux-form/UPDATE_SYNC_ERRORS` event is not triggered because `!plain.deepEqual(syncErrors, nextSyncErrors)` return `false`.

Definitely `updateSyncErrorsIfNeeded`  need to be fixed because its not working in v6.0.1 too.

**Comment by dannymk** [comment] 2016-10-15 02:36
Same here.

**Comment by piotrkl** [comment] 2016-11-10 08:22
Do you have a workaround for this issue?

**Comment by antoinerousseau** [comment] 2016-11-10 08:23
For now I'm adding `keepDirtyOnReinitialize: true` but it's not really the ideal behavior for me

**Comment by piotrkl** [comment] 2016-11-10 09:44
I see it the same way as @roryp2 and @jzalucki. In both cases `redux-form/UPDATE_SYNC_ERRORS` action should be triggered. For me, `keepDirtyOnReinitialize: true` does not solve the problem.

**Comment by osigum** [comment] 2017-01-20 06:50
I guess, things I'm experiencing are related to this issue. An events chronicle:

0) A form starts mounting.
1) The form is validated for the first time -> redux-form/UPDATE_SYNC_ERRORS is called with an error before componentWillMount.
2) The form is initialized with valid values on componentWillMount.
3) The form is validated for the second time ->  redux-form/UPDATE_SYNC_ERRORS is **NOT** called.
4) The form renders, registers it's fields and so on.

**Comment by morulus** [comment] 2017-02-04 16:11
My way to resolve this problem is to call reset() manually when initialValues got changes. But you should not disable `enableReinitialize`, because, without it, component won't receive `initialValues` prop as expected.
```js
componentWillReceiveProps({ random, initialValues }) {
    if (this.props.initialValues && ( initialValues !== this.props.initialValues )) {
      this.props.reset();
    }
}
```
The important condition is to check whether this.props.initialValues is not null, if you are using async initialization.

**Comment by lechneal** [comment] 2017-02-06 13:59
@morulus I still get redux-form/UPDATE_SYNC_ERRORS called after i dispatch RESET...

**Comment by huitre** [comment] 2017-02-06 14:58
@lechneal I had a similar issue that I resolved with this code.
```    
componentWillMount() {
...
  this.props.reset();
  this.props.initialize({
        title,
        description,
        url,
        media,
     });
})
```
```
export default reduxForm({
...
  keepDirtyOnReinitialize: true
});
```

**Comment by lechneal** [comment] 2017-02-06 15:23
@huitre thanks for your help. Unfortunately I require keepDirtyOnReinitialize to be false, causing the subsequent submission to fail: #2427

**Comment by jovinbm** [comment] 2017-02-09 01:00
@piotrkl I had the same issue. I was using `redux-form@6.0.x` two days ago and it was working fine without any hacks. I upgraded yesterday to `redux-form@6.5.0` to get the flexibility of Field-Level validation and started to experience the same issue. Good enough, Field-Level Validation was added since `v6.3.0` and I downgraded to that and it's been working fine since then. There might be an issue in one of the latest releases.

**Comment by jovinbm** [comment] 2017-02-09 01:11
In `v6.5.0` `UPDATE_SYNC_ERRORS` is dispatched **before** `INITIALIZE` causing the errors to be registered in redux. No other `UPDATE_SYNC_ERRORS` is dispatched until a form field is changed. This has also been noticed in [https://github.com/erikras/redux-form/issues/2484](https://github.com/erikras/redux-form/issues/2484) In `v6.3.0` I have noticed that the first dispatch of `UPDATE_SYNC_ERRORS` actually comes after `INITIALIZE` and `REGISTER_FIELD` which should be the desired behaviour as it cleans up errors.

**Comment by rvanlaarhoven** [comment] 2017-02-10 15:30
When debugging this issue I noticed the `props.values` and `nextProps.values` that are passed to `shouldValidate` (https://github.com/erikras/redux-form/blob/master/src/defaultShouldValidate.js) are always the same. Not sure why this happens since `validateIfNeeded` is called on `componentWillReceiveProps`.

Since both values are always the same, `shouldValidate` only returns true when it's an initialRender.

**Comment by rmlevangelio** [comment] 2017-02-23 14:09
Any update with this one?

**Comment by fgiarritiello** [comment] 2017-03-14 21:35
I have the same problem. Any updates on this? Thanks

**Comment by rmlevangelio** [comment] 2017-03-14 23:44
@fgiarritiello The latest update solves the problem.

**Comment by fgiarritiello** [comment] 2017-03-14 23:48
@rmlevangelio v6.5.0 still has the problem. https://github.com/erikras/redux-form/issues/1385#issuecomment-278515813

**Comment by rmlevangelio** [comment] 2017-03-14 23:51
@fgiarritiello The latest update solves the problem.

**Comment by rmlevangelio** [comment] 2017-03-14 23:52
@fgiarritiello try 6.3.0. It works fine on my end

**Comment by fgiarritiello** [comment] 2017-03-14 23:53
@rmlevangelio yes 6.3.0 works fine but that's not the latest update :) (6.5.0 is the latest)

**Comment by rmlevangelio** [comment] 2017-03-14 23:56
@fgiarritiello Oh. Apologies. Did you use some new features of 6.5.0? I think if you're not using the latest features, you can downgrade to 6.3.1.

**Comment by fgiarritiello** [comment] 2017-03-15 00:02
@rmlevangelio No I'm not using any of the new feature of 6.5.0 so I'm ok with downgrading to 6.3.1. I was just asking if this issue had been fixed in the next patch. thanks for the help

**Comment by fenos** [comment] 2017-04-07 15:52
@erikras any update on this? We can't get around this, we have a wizard which whenever you navigate to the previous step, the fields initiated with`initialValues` are invalid, even though they are not

**Comment by fgiarritiello** [comment] 2017-04-07 15:53
@fenos I'm still using 6.3.0 to get around the problem.

**Comment by erikras** [comment] 2017-04-07 20:06
Thanks, @osigum. Your timeline of the bug has really helped in investigating it. 👍

**Closed** 2017-04-07 20:53 UTC
Labels: bug

**Comment by erikras** [comment] 2017-04-13 10:08
Fix published in [`v6.6.3`](https://github.com/erikras/redux-form/releases/tag/v6.6.3).

**Comment by amirtgm** [comment] 2017-04-16 05:12
version 6.6.3 still has the problem. #2814

**Comment by timhwang21** [comment] 2017-04-24 23:50
Hi @erikras, I think #2797 may have caused a regression. There's also a discussion going on in #2838. 

I replicated the steps followed by @bbenezech in his test, then I repeated after changing the version to `6.5.0` and then `6.3.2`. The error described happened for all three versions on code sandbox, contrary to what people have been saying above.

**Comment by abrad45** [comment] 2017-05-06 04:01
I'm still experiencing this now on v6.6.3

This suggestion above by @morulus helped me to work around this issue: https://github.com/erikras/redux-form/issues/1385#issuecomment-277455778

Both aspects of this solution are necessary to resolve the bug.

**Comment by illumimari** [comment] 2017-05-22 03:46
The above work around did not work for me.  I am still seeing this issue in v6.7.0

**Comment by abrad45** [comment] 2017-05-22 04:37
@illumimari I don't have this issue any longer on v6.7.0

**Comment by timhwang21** [comment] 2017-05-22 11:53
@illumimari resolved for me as well. I can try to help if you post some code.

**Comment by illumimari** [comment] 2017-05-22 15:02
Agh, thank @abrad45 and @timhwang21.  I took a second look at my implementation, and there was a simple mix-up in my form logic that gave a false-positive for this error.  Please disregard my previous comment.

**Comment by arman-mukatov** [comment] 2017-06-14 05:49
If the initial data is initialized using the action creator - initialize(in method componentWillMount), rather than using the props initialValues, then when second call initialize - it does not trigger the redux-form/UPDATE_SYNC_ERRORS action and as such all of the fields don't get updated with their error state again.

v6.8.0

**Comment by alexis1990** [comment] 2017-06-15 11:53
any issue ?

**Comment by daniele-bottelli** [comment] 2017-06-23 14:55
v6.8.0 still have this problem; actually I'm using v6.3.0

**Comment by salhotra** [comment] 2017-08-18 21:31
Inside componentWillMount, `reset` the form component and set `destroyOnUnmount` to false. Also Initialize the fields as empty string or whatever you need. 

`componentWillMount() {
    this.props.reset();
  }

const InitializeFromStateForm = reduxForm({
  form: 'login',
  destroyOnUnmount: false,
})(LoginForm);

  connect(
    state => ({
      initialValues: {
        email :_.get(state,'form.values.email', ''),
        password: _.get(state,'form.values.password', ''),
      },
    }),
  )
`

The problem in my case was that when the component unmounted, the formState got destroyed and on reinitialization, the action `redux-form/UPDATE_SYNC_ERRORS` wasn't getting dispatched. Now it's solved.

**Comment by cbrandalise** [comment] 2018-02-27 22:19
renaming `syncErrors` to `errors` fixed it for me.

```
const mapStateToProps = (state) => {
    return {
        initialValues: {
            primary_information: state.store
        },
        errors: getFormSyncErrors('store')(state),
        formValues: getFormValues('store')(state)
    }
}
```
