### ISSUE TITLE
v6: Using bluebird in asyncValidate causes warning

### ISSUE THREAD

**Issue by q42jaap** [erikras/redux-form#1153] opened 2016-06-13 11:16 UTC
When using a bluebird promise in asyncValidate, invalidating a field will cause a warning:

```
Unhandled rejection undefined
```

This is the line that triggers it:
https://github.com/erikras/redux-form/blob/v6/src/asyncValidation.js#L12

The asyncValidate is in the blur handler, this is the line of code that is ignoring the promise.
https://github.com/erikras/redux-form/blob/v6/src/events/createOnBlur.js#L10

I saw that on master, `silencePromise` is used to fix this, however in v6 silencePromise has been removed.

The line https://github.com/erikras/redux-form/blob/v6/src/createFieldProps.js#L46
is missing a silencePromise. I think it's still necessary with Bluebird (since it has a detection system for unhandled rejections).

**Comment by eloytoro** [comment] 2016-06-13 17:13
Read this http://bluebirdjs.com/docs/api/promise.onunhandledrejectionhandled.html

**Comment by eloytoro** [comment] 2016-06-13 17:14
and this https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection

**Comment by q42jaap** [comment] 2016-06-13 22:39
That would be a rather devious way to get around
`asyncValidate.bind(null, name)` not handling the returned promise at the end of the chain.

Point is, that as a library, Promises that are created should always be handled, or they should be able to be handled by user code. Redux-form should not rely on any Promise library's behaviour. Line 46 in createFieldProps lacks handling the promise returned by it's internal asyncValidate function.

The particular rejection from the onBlur point of view is strange, the asyncValidation returned a non-empty error, it's adhering to the api, but along the way, a rejected promise was created (https://github.com/erikras/redux-form/blob/v6/src/asyncValidation.js#L12)

**Comment by chrisrittelmeyer** [comment] 2016-06-24 21:02
@q42jaap I also had this problem and tracked it to https://github.com/erikras/redux-form/blob/v6/src/asyncValidation.js#L12 which is bubbling up to https://github.com/erikras/redux-form/blob/v6/src/asyncValidation.js#L20

If you add, for instance, `.catch(function(e) {});` to the end of the line, the warning stops.

**Comment by eloytoro** [comment] 2016-06-27 01:20
Its my opinion that its ok to expose promises that _could_ be rejected for the client to handle them.
If the library were to catch all the errors the client wouldn't be able to introduce its own handle logic.
And by reading the source code it seems to be doing exactly that, but if the rejection isn't carrying an error payload that should be fixed.
If you define async validation that could fail its in your best interest to define some logic to handle that.
If you dont like the way promises throw errors when unhandled [theres a whole thread in the node repo discussing this](https://github.com/nodejs/node/issues/830).
@chrisrittelmeyer that clears the issue because thats the async equivalent of try/catching something that throws an error, but leaving the catch part empty.

**Comment by chmanie** [comment] 2016-12-05 13:10
I ran into this problem and I agree with you @eloytoro except that I encountered a specific problem that is unsolvable the way things are implemented currently:

Use case

* User fills out the form, which has just one field that includes async validation.
* User does NOT blur this field but clicks on the submit button instead (which is possible!)
* On submit async validation is being run and throws an error. But this time it is run in a different context. It is throwing an error which is going to be unhandled and causes the script to reside in an undefined state. The next time you submit the form it won't work.

You can test this with the examples (I'm using Chrome 54, also tried Firefox).

http://redux-form.com/6.2.0/examples/asyncValidation/

* Type in the password first (!)
* Then choose a username that's taken (e.g. john). DO NOT BLUR THIS FIELD, dismiss autocomplete with ESC if necessary
* Immediately click on Sign up
* An uncaught error will appear in the console
* Now try *any* valid username
* Signup won't work anymore no matter how often you try (you have to refresh the page to make it work again)

You might say, well, in this case it's not a big problem because it's very specific. But it looks quite differently if you have only one form field.

**Comment by danielrob** [comment] 2017-07-27 02:52
@chmanie I followed your reproduction steps  successfully on older versions to produce an uncaught promise exception (thank you for these!), but unsuccessfully on 7.0.3 🎉. 

Would those in this thread be willing to confirm / provide further investigation if needed to clarify the status of this issue?

**Comment by chmanie** [comment] 2017-07-27 18:26
You could reproduce it with the async validation example; I tried with http://redux-form.com/7.0.3/examples/asyncValidation/ and it did not occur. I'm willing to say that it's resolved now.

**Comment by gustavohenke** [comment] 2017-07-27 20:17
Cool, thanks!

**Closed by gustavohenke** 2017-07-27 20:17 UTC
