### ISSUE TITLE
React Hot Loader unmounts form component

### ISSUE THREAD

**Issue by lucian-tanase** [erikras/redux-form#2826] opened 2017-04-19 10:45 UTC
Hi, I have a problem with redux-form 6.6.3 and react-hot-loader 3.0.0-beta.6. When live editing a reduxForm component, the component unmounts losing form state. I know there is destroyOnUnmount: false option, but in my case I don't want to use that.

I have setup a project where this can be replicated: https://github.com/lucian-tanase/redux-form-hot-loader. Whenever render method of src/Form.js component is edited, the redux form loses its state.

**Comment by mojo5000** [comment] 2017-04-29 02:54
This has been driving me nuts too.

See:  https://github.com/erikras/redux-form/issues/623

**Comment by gustavohenke** [comment] 2017-06-18 08:19
I'm closing this one as a duplicate of #623 and #3005.

**Closed by gustavohenke** 2017-06-18 08:19 UTC

**Comment by erikras** [comment] 2017-10-25 20:17
Fix published in [`v7.1.2`](https://github.com/erikras/redux-form/releases/tag/v7.1.2).
