### ISSUE TITLE
syncValidation: on reset doesn't trigger UPDATE_SYNC_ERRORS

### ISSUE THREAD

**Issue by lgraziani2712** [erikras/redux-form#2305] opened 2016-12-17 05:47 UTC
Following the example given in the docs, I tried to edit an input by deleting his validation. This change breaks the action RESET. Instead of dispatching UPDATE_SYNC_ERRORS, does nothing.

![image](https://cloud.githubusercontent.com/assets/15050200/21284687/d735c688-c401-11e6-9712-9f2a036301e8.png)

![image](https://cloud.githubusercontent.com/assets/15050200/21284695/151c7a3c-c402-11e6-8963-d1ee8622f8e2.png)

![image](https://cloud.githubusercontent.com/assets/15050200/21284709/d8f24c7a-c402-11e6-9c27-79f0a57c68fb.png)

Libraries versions:
- react: 15.4.1.
- redux: 3.6.0.
- redux-react: 5.0.1.
- redux-form: 6.3.2.

I hope that makes sense.

Thank you.

**Comment by LucianoGraziani** [comment] 2016-12-17 16:39
I found something more specifically. If the form has an optional field, UPDATE_SYNC_ERRORS will be called only if the required inputs are the only ones being dirty.

**Comment by LucianoGraziani** [comment] 2016-12-18 18:44
Ok... this is crazy. I think I found the source of the error. For some reason UPDATE_SYNC_ERRORS only triggers when something that change returns a different object that the syncErrors has. E.g. a required and empty field is filed.

Instead, when a field without validation is updated, it won't update the syncErrors object. Then, if only an input without validation is filed, when the reset button is pressed, UPDATE_SYNC_ERRORS won't be triggered.

**Comment by LucianoGraziani** [comment] 2016-12-18 18:54
This behavior also happens with optional rules in optional fields. When is filled and the optional rule pass, and then you reset the form, UPDATE_SYNC_ERRORS isn't triggered.

**Comment by 2fort** [comment] 2016-12-20 17:34
Yes! This is exactly what I experienced when trying to use reset method. 

I came to this solution: emulate reset by manually undoing changes on fields:
1) Using method change() to clean field contents, i.e.: 
change('field1', '');
change('field2', '');
change('fieldn', '');

2) Untouch fields with untouch() method:
untouch('field1', 'field2', 'fieldn');

**Comment by amangeot** [comment] 2016-12-22 09:50
I think I'm having the same issue with a component wrapped with `enableReinitialize`: `validate` is being called twice, once with empty values, once with initial values, though `UPDATE_SYNC_ERRORS` is only triggered for the first call, with empty values. This leads to inconsistent errors, though I can't point at the exact problem,

**Comment by zhikin2207** [comment] 2017-01-08 17:52
Did you found any temporary solution?

**Comment by amangeot** [comment] 2017-01-08 18:37
For my issue, the issue is fixed in v6.4.3, try updating if you haven't done it yet.

**Comment by gustavohenke** [comment] 2017-12-06 23:11
Because this issue saw almost no activity for almost a year, I'm closing it.

**Closed by gustavohenke** 2017-12-06 23:11 UTC
