### ISSUE TITLE
[BUG] Decorating components with {...input} breaks when referring components

### ISSUE THREAD

**Issue by wouter-willems** [erikras/redux-form#3845] opened 2018-02-19 14:07 UTC
### What is the current behavior?
Decorating the input component via a function causes weird behaviour with fields. After typing 1 character, it auto blurs for some reason. This means that I can only decorated native input components:

So this works:
```
return (
    <div>
      <label>{label}</label>
      <div>
        <input {...input} placeholder={label} type={type}/>
        {touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
      </div>
    </div>
    )
  }
```

But not this:

```
const Comp = props => (
    <input {...props.input} placeholder={props.placeholder} type={props.type} />
  );
  return (
    <div>
      <label>{label}</label>
      <div>
        <Comp input={input} placeholder={label} type={type} />
        {touched &&
          ((error && <span>{error}</span>) ||
            (warning && <span>{warning}</span>))}
      </div>
    </div>
  );
```

### What is the expected behavior?

I expect that referring a component and annotating it that way, also works along with the redux forms api.

### Sandbox Link
https://codesandbox.io/s/kklr7z4715

### What's your environment?
redux-form 7.2.3

**Comment by gustavohenke** [comment] 2018-02-19 14:11
Duplicate of #1836 

Basically just don't create dynamic fields.

**Closed by gustavohenke** 2018-02-19 14:11 UTC

**Comment by wouter-willems** [comment] 2018-02-19 14:19
Wow, sorry, guess I had tunnelvision. Thank you for the quick reply!
