### ISSUE TITLE
When are UNREGISTER_FIELD and REGISTER_FIELD events dispatched?

### ISSUE THREAD

**Issue by Nilesh3105** [erikras/redux-form#3211] opened 2017-07-19 13:54 UTC
### Are you submitting a **bug report** or a **feature request**?
Just asking info. Might be a bug.

### Why am I asking this?
One of my fields keeps getting unregistered and registered after change or blur event on **any** field. Which destroys the error state and thus forcing me to use `destroyOnUnmount: false ` on my form component.

### What's your environment?
From my package.json
```
"dependencies": {
    "axios": "^0.16.2",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "react-router-dom": "^4.1.1",
    "redux": "^3.7.2",
    "redux-form": "^7.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "semantic-ui-css": "^2.2.11",
    "semantic-ui-react": "^0.71.0"
  }

```
Also the HOCs used on my form component:
```
CreateJobForm = reduxForm({ 
  form: 'createJob',
  destroyOnUnmount: false
})(CreateJobForm);

const selector = formValueSelector('createJob');

CreateJobForm = connect(state => {
  return selector(state, 'device', 'brand', 'model' );
})(CreateJobForm)

export default CreateJobForm;
```

My Feild looks like this: 
```
<Field name="location" type="text" label='Location(Pincode)'
    component={MyFeild}
    Comp={Form.Input}
    validate={[required, number, length(6)]}
/>
```

### Other information
I know this might not be enough to identify the issue but i wanted to understand the problem better first.

**Comment by SpainTrain** [comment] 2017-07-19 18:59
@Nilesh3105 we saw this also when trying to upgrade to v7 (haven't yet gotten around to opening a proper bug report).

If you switch to redux-form 6.8.0 does this work as you expect?

**Comment by SpainTrain** [comment] 2017-07-19 19:51
:+1: Glad that helped and thanks for verifying.

**Comment by hsrobbv** [comment] 2017-07-19 21:55
Also experiencing this issue since updating to 7.0.0

**Comment by hsrobbv** [comment] 2017-07-19 22:06
It seems this issue may be fixed in v7.0.1: https://github.com/erikras/redux-form/releases/tag/v7.0.1

**Comment by HarrisGri** [comment] 2017-07-20 07:06
Hi there, getting the same error as soon as the connected component that is containing the redux fields is rerendered. Is still not fixed with 7.0.1 (6.8.0 is working)

**Comment by Nilesh3105** [comment] 2017-07-20 12:07
7.0.1 doesn't fix it for me.

**Comment by SpainTrain** [comment] 2017-07-20 12:23
7.0.1 does have bug fixes, but not for this one.  We did our testing with 7.0.1.

**Comment by SBRK** [comment] 2017-07-20 14:29
7.0.1 doesn't fix for me either. Did a duplicate here before realising it was related to unregister/register #3211

**Comment by SBRK** [comment] 2017-07-20 14:47
Reverting #3094 fixed it for me. I think I get what's going on, I have a wrapper around my fields that creates the `validate` function, so it changes after every render, which prompts the Field to unregister/register because the `validate` has changed. I'll use a class instead of a stateless component to get around this for now.

**Comment by SpainTrain** [comment] 2017-07-20 21:24
So this may not be a bug but a feature :-). Thanks for the insight @SBRK !

**Comment by SBRK** [comment] 2017-07-21 08:28
I'm pretty sure this will generate a lot of issue reports in the future, but yeah it's the intended behavior :D

**Comment by synchu** [comment] 2017-07-25 19:26
I have a wizard type form and up to 6.7.0 it was working fine with fields on the pages getting registered when the page is rendered (i.e. redux-form/REGISTER_FIELD fired). After changing a value in a field redux-form/CHANGE and redux-form/BLUR were dispatched. When you go to the next page you get redux-form/UNREGISTER_FIELD and everything was nice and shiny.

Now, I have to click twice for a field to get focus (as some intermediate re-rendering of the whole page happens) and when I change a field value, I only get redux-form/CHANGE and every field on the respective wizard page gets UNREGISTERED and then REGISTERED again- and yes the whole page renders again (seems weird, esp. with animations :) ), not only the field changed.
So I am destined to some hair pulling tonight...

**Comment by danielrob** [comment] 2017-07-27 16:48
Thank you to @SBRK for clarifying this. I've added the docs label, as a short paragraph 'guide' will no doubt help. PR's welcome, perhaps something like below: 

The point of this update is that you can now change the validate function. The flipside is:  

You need to be careful to change the validator only and exactly when desired, and for example, not on every render. Anonymous functions, or higher-order validator functions which return a new function each call will cause reregistering on every render, because the validation function will have changed. To avoid this, you can move your validator functions outside the render method (e.g. as a class method), or use concepts like memoization to return the same function each time, unless the (config) values passed in have actually changed.  

It may be that this introduces new issues. Please raise new issues to track those. @synchu please raise a new issue with reproduction steps.

**Comment by synchu** [comment] 2017-07-28 06:09
Thanks @danielrob, will do in the next few days or so.

**Closed** 2017-07-31 20:32 UTC
Labels: docs

**Comment by synchu** [comment] 2017-08-02 19:21
Turns out my problem with the form re-rendering is the century old 'make sure you know your instances, s#@#id' :)
I used a wrapper for some positioning switching with const f = (stuff) => {return otherstuff} inside one of the render methods called by the main render(), i.e.
`renderSomething = (params) => {
   const F = (stuff) => {return otherstuff}
  return (
  <div>
   <F {...stuff} />
  <...........>
 </div>
 )
}`
Then renderSomething is called within the main render() of the component.
Once I moved the F outside of the Component class to a true stateless func - bum, sun shines bright again.
Thought it may help someone.

**Comment by danielrob** [comment] 2017-08-02 21:16
@synchu yep, that's a classic. React docs are pretty clear about that now though which is nice: https://facebook.github.io/react/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method
