### ISSUE TITLE
isValid throws  getFormState is not a function

### ISSUE THREAD

**Issue by dlebedynskyi** [erikras/redux-form#2255] opened 2016-12-09 22:06 UTC
both lib and es version have getFormState as undefined. 

![image](https://cloud.githubusercontent.com/assets/1182917/21066091/a4bd9cc4-be31-11e6-9b25-47f8d31e4216.png)

on latest 6.3.2
rollback to 6.2.1 is all good

**Comment by jackspaniel** [comment] 2016-12-09 22:50
Same problem here, and 6.2.1 solved the problem. This was a fun one - people with fresh installs were seeing the problem due to ^6.2.1 in package.json. Unfortunately this issue is too new to appear on google either.

**Comment by dtipson** [comment] 2016-12-12 04:15
Same regression for me.

**Comment by theKashey** [comment] 2016-12-12 05:35
Someone just dont understand meaning and burden of "API".

**Comment by theKashey** [comment] 2016-12-13 23:57
4 days pass, nothing changes :(

**Comment by mpolichette** [comment] 2016-12-15 22:54
Same issue, seems like it was broken in this commit:
https://github.com/erikras/redux-form/commit/d84aa7f055f54ed7a7e0c1eabc7b5b1ec769d331#diff-5e8b85edd99ba7a51fd49b5e5895a159L6

A temporary fix could be replacing with the original default param:
`state => getIn(state, 'form')`  

@erikras I am happy to do a PR if the approach is to simple replace that default param.  Just say make it so! :)

**Comment by AlexGrs** [comment] 2016-12-19 10:16
Hi Guys,

Any chance to merge this in a 6.3.3 ?

Regards.

**Comment by diegohaz** [comment] 2016-12-19 11:10
PR: #2270

**Comment by diegohaz** [comment] 2016-12-25 07:35
This can be closed @erikras @dlebedynskyi

**Comment by gustavohenke** [comment] 2016-12-25 15:49
Thanks for the heads up @diegohaz, I'm closing it 😃

**Closed by gustavohenke** 2016-12-25 15:49 UTC
Labels: bug
