### ISSUE TITLE
how to add validation for array property like awards here(Deep Form Demo)

### ISSUE THREAD

**Issue by playwolf719** [erikras/redux-form#1552] opened 2016-08-17 11:53 UTC
![image](https://cloud.githubusercontent.com/assets/6240382/17735266/cdcb8130-64b3-11e6-80aa-f341352c2deb.png)
![image](https://cloud.githubusercontent.com/assets/6240382/17735344/343b5ce2-64b4-11e6-8367-27367eca7b96.png)

**Comment by erikras** [comment] 2016-08-18 06:45
Dupe of #1553.

**Closed by erikras** 2016-08-18 06:45 UTC
