### ISSUE TITLE
peerDependency about react-redux change from ^4.3.0 to 4.3.0 ?

### ISSUE THREAD

**Issue by kinglywork** [erikras/redux-form#2348] opened 2016-12-28 10:38 UTC
redux-form@6.3.2:
`"peerDependencies": {
  "react": "^15.0.0",
  "react-redux": "^4.3.0 || ^5.0.0-beta",
  "redux": "^3.0.0"
}`
redux-form@6.4.0 :
`"peerDependencies": {
    "react": "15.0.0",
    "react-redux": "4.3.0 || ^5.0.0-beta",
    "redux": "3.0.0"
}`

the peerDependency about react-redux change from ^4.3.0 to 4.3.0
this will cause npm(version 3+) err while react-redux version between 4.3.0+ and 5.0.0-beta:
`npm ERR! peerinvalid The package react-redux@4.4.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-form@6.4.1 wants react-redux@4.3.0 || ^5.0.0-beta`

**Comment by gustavohenke** [comment] 2016-12-28 10:58
Duplicate of #2338.

**Closed by gustavohenke** 2016-12-28 10:58 UTC
Labels: duplicate
