### ISSUE TITLE
Form submit failed when using <select> and history.pushState

### ISSUE THREAD

**Issue by isomoar** [erikras/redux-form#321] opened 2015-11-22 12:38 UTC
I'm building an application with dynamic forms and my app has the next workflow: user clicks on "submit" button, redux-form's `handleSubmit` function is called and current route changes from `/step/0` to `step/1`. It's all OK except the case if form has the `<select>` tag. If user submits the form with `<select>` tag `Uncaught TypeError: Cannot set property 'initialValue' of null` error occurs. 

![app](https://cloud.githubusercontent.com/assets/5099105/11323760/4231fb04-912d-11e5-9686-2fb29c13d125.gif)

So this error breaks the further execution. I have looked into redux-form's source code and have noticed that if comment `touch(...fields);` (line 8) call in `handleSubmit.js` file this error disappears. But I can't figure out how to fix this issue.

**Form.js**
```js
import React, { PropTypes } from 'react';
import {reduxForm} from 'redux-form';

class Form extends React.Component {
  renderFields(data, fields) {
    if (data.type === 'text') {
      return (
        <div>
          <label>{data.name}</label>
          <input type="text" name={data.name} placeholder={data.placeholder} {...fields[data.name]} />
        </div>
      )
    } else if (data.type === 'radio') {
      return data.answers.map((answer, index) => {
        return (
        <div key={answer.label + index}>
          <label>{answer.label}</label>
          <input type="radio" name={answer.name}  {...fields[answer.name]} />
        </div>
        )
      });
    } else if (data.type === 'dropdown') {
      const options =  data.answers.map(answer => {
        return <option  key={answer.value} value={answer.value}>{answer.label}</option>;
      });
      return <select  {...fields[data.name]}>{options}</select>;
    }
  }
  render () {
    const { data, fields, handleSubmit } = this.props;
    return (
      <form onSubmit={handleSubmit}>
        {::this.renderFields(data, fields)}
        <button onClick={handleSubmit}>Submit</button>
      </form>
    );
  }
}

Form.propTypes = {
  data: PropTypes.object.isRequired,
  fields: PropTypes.object.isRequired,
  handleSubmit: PropTypes.func.isRequired
}

export default reduxForm({form: 'dynamic'})(Form);
```
**FormContainer.js**
```js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { PropTypes as RouterPropTypes } from 'react-router';
import Form from './Form';

class FormContainer extends Component {
  componentWillReceiveProps(nextProps) {
    const { step: nextStep } = nextProps.params;
    if (typeof nextStep === 'undefined') return;
    
    const pNextStep = parseInt(nextStep);
    
    if (this.props.index !== pNextStep) {
      this.props.dispatch({
        type: 'NEXT',
        step: pNextStep,
      });
    }
  }
  handleSubmit(data) {
    this.context.history.pushState(null, `/step/${this.props.index + 1}`);
  }
  render() {
    const { steps, index } = this.props;
    return (
      <div>
        <Form 
          fields={['firstName', 'state', 'lastName', 'income']}
          data={steps[index]}
          onSubmit={::this.handleSubmit}
           />
      </div>
    );
  }
}

FormContainer.contextTypes = { 
  history: RouterPropTypes.history,
};

function con(state) {
  return {
    steps: state.main.steps,
    index: state.main.index
  }
}
export default connect(con)(FormContainer);
```

**Comment by erikras** [comment] 2015-11-23 14:26
First of all, _excellent_ issue report, with full code and screencast. :clap: 

It's unclear to me _where_ exactly this error is occurring. I'd like to see the stacktrace. Is it in the reducer, when the `touch(...fields)` is trying to touch a field that does not exist?

It seems that if you are controlling which fields are shown from your container, you could possibly just do this, and let the form think it only has one field.

```js
<Form 
  fields={[steps[index].name]}
  data={steps[index]}
  onSubmit={::this.handleSubmit}
/>
```
That _might_ make a difference...?

**Comment by ev-g** [comment] 2015-11-23 21:34
@erikras Thank you for attempt to solve this issue, but that's not the point. Sorry I didn't tell you that this error is occurring in `ReactDOMSelect.js:158`. Anyway, I just realised that my code in **FormContainer** consistently dispatches  two "NEXT" actions in `componentWillReceiveProps()` instead of one. So I added one more condition: 

**FormContainer.js**
```js
  componentWillReceiveProps(nextProps) {
   ...
    if (this.props.index !== pNextStep && nextProps.index !== pNextStep) {
    ...
    }
  }
```

After dispatching single "NEXT" action this error is still occurring, but now application is working! I don't know what piece of code actually calls this error, but I think I can normally live with it now.

**Comment by isomoar** [comment] 2015-11-24 10:21
@erikras Thank you for attempt to solve this issue, but that's not the point. Sorry I didn't tell you that this error is occurring in ReactDOMSelect.js:158.

**Comment by erikras** [comment] 2015-11-30 19:22
The code around these features has changed a bit in `v3.1.1`. Can you upgrade and confirm that this problem still exists?

**Comment by isomoar** [comment] 2015-12-11 20:23
@erikras 
Unfortunately yes, still exists with `v3.1.7`.

**Comment by browniefed** [comment] 2016-02-02 19:09
Running into this issue now as well. When dealing with changing routes but rendering into the same container but a select was previously mounted is no longer mounted.

I'm not using redux-form (however I am using redux). There has been recent changes around select/option.

Looking at the code I unfortunately see nothing that stands out, I am passing stuff via props, and I was maybe thinking there was an issue with the owner instances or something. But that doesn't appear to be your problem? Maybe redux-form is doing it. I tried doing a repro here but couldn't get it https://jsbin.com/larafazoda/4/edit?html,js,console,output

I'll keep working at it, run the stack trace and see where the issue is coming from.

**Comment by browniefed** [comment] 2016-02-02 21:11
@isomoar My issue was seemingly that I was calling `unmountComponentAtNode` in `componentDidUpdate` that was unmounting I guess during flushing of actions but from a different container. Pretty complicated scenario, but removing the `unmountComponentAtNode` and letting the subsequent `render` call to the same container works.

**Comment by ooflorent** [comment] 2016-04-29 15:21
I'm closing this issue since it seems to be a React bug (https://github.com/facebook/react/issues/5968).

**Closed by ooflorent** 2016-04-29 15:21 UTC
