### ISSUE TITLE
Failed submission due to SubmissionError disabling submit until a Field changes

### ISSUE THREAD

**Issue by c10b10** [erikras/redux-form#1884] opened 2016-09-29 11:46 UTC
This seems useful for most cases, but there are some edge cases where you would want to resubmit even though the fields haven't changed. 

For example when you have the signup and login forms within the same `redux-form` component. I manage the change between them through state which determines which handleSubmit function to call on submission.

Is there any way to work around this behaviour or is my approach of managing this through state wrong?

**Comment by c10b10** [comment] 2016-09-29 14:58
It seems this can be done by dispatching an `redux-form/UPDATE_SYNC_ERRORS` action when the form tab is changed but it seems hacky. Is there a better way?

**Comment by c10b10** [comment] 2016-09-29 15:15
That last solution seems to render `validate` inactive, so it seems that the question stands.

**Comment by dmason30** [comment] 2016-09-29 15:43
+1 

cc @erikras

**Comment by cjbell** [comment] 2016-09-30 00:32
I've been looking into this a bit more this evening, it looks like when the form fails to submit with the global `_error` on `SubmissionError` any subsequent attempts to submit the form won't succeed as `valid` is never true.

If `_error` isn't set everything works as expected.

**Comment by lama-pacos** [comment] 2016-09-30 06:11
+1

@erikras

**Comment by webholics** [comment] 2016-09-30 07:10
I have the exakt same problem at the moment.

**Comment by mschipperheyn** [comment] 2016-10-05 11:55
It's also wrong bc:
1. a field can be correct and fail bc a remote server is temporarily offline.
2. The error field does not necessarily have to be the field with an error. For instance in a login form, we assign a password error to the username field with something like "your username or password is incorrect"

**Comment by jampy** [comment] 2016-10-05 13:20
@mschipperheyn 

> a field can be correct and fail bc a remote server is temporarily offline or there is some kind of networking error.

To be exact, [that's not what `SubmittionError` is for](http://redux-form.com/6.0.0-alpha.4/docs/api/SubmissionError.md/)

>SubmissionError
>A throwable error that is used to return submit validation errors from onSubmit. The purpose being to distinguish promise rejection **because of validation errors** from promise rejection because of AJAX I/O problems or other server errors.


see also #1898

**Comment by webholics** [comment] 2016-10-05 13:27
@jampy but case 2...

> 2. The error field does not necessarily have to be the field with an error. For instance in a login form, we assign a password error to the username field with something like "your username or password is incorrect"

...is a totally valid point. We have the exact same problem.

**Comment by mschipperheyn** [comment] 2016-10-06 12:36
Yeah, I hope this gets resolved quickly. Is there a way for this to be disabled on a per form or per field basis? It's essentially a performance optimization that is now a blocker.

**Comment by mschipperheyn** [comment] 2016-11-01 13:03
Any update on this @erikras ?
It seems to be that what we need is a way to disable the functionality that a resubmit requires the failing field to be dirtied.

**Comment by jampy** [comment] 2016-11-08 16:20
Can you please check with redux-form 6.2.0 or newer? The problem [seems to have gone away](https://github.com/erikras/redux-form/issues/1898#issuecomment-258285956).

**Comment by r-f-j-thomas** [comment] 2016-11-11 10:46
I'll have to double-check, but that issue appears to only refer to `_error`, and field-specific errors still prevent form submission. This is the real problem, as far as I am concerned.

The issue is the assumption that all field errors returned from the server are something that requires editing the field to resolve. When all the validation occurs server-side, I don't think the client should make assumptions about why a field is invalid and what is required to resolve it.

The main use case is this, where editing one field resolves errors in another field:
```
{ "field1": "field1 or field2 is required",
"field2": "field1 or field2 is required" }
```

Or perhaps a field with time-based validation, which could resolve itself without any input change:
`{"timefield": "Time must not be in the future"}`

**Comment by mschipperheyn** [comment] 2016-11-11 17:19
@jampy 6.2.0 does not resolve it. 

@r-f-j-thomas yes, where my case is a variation of your first one, where

     { "username": "username or password is wrong"}

So, when I change the password, redux-form doesn't remove the error against the username because it's waiting for it to be changed. And thereby prevents resubmission

**Comment by jampy** [comment] 2016-11-11 21:30
@mschipperheyn strange - I'm using 6.2.0 and in my `async` handleSubmit() I have a simple `throw new SubmissionError({_error: "whatever"});`.

For some reason I can resubmit the form without the need to change any field.

**Comment by r-f-j-thomas** [comment] 2016-11-11 21:45
For `_error` that is true, but the problem is field errors. Change it to `throw new SubmissionError({myfield: "whatever"});` and the form won't submit until `myfield` is edited

**Comment by mschipperheyn** [comment] 2016-11-15 16:03
So, is there a workaround? Of course, in stead of just removing the error, you want to keep the error (message) but prevent blocking resubmission. I guess this could be a form or field specific property

**Comment by flanamacca** [comment] 2016-11-17 00:13
I'm also stuck in this situation.

If someone changes one field, but you have a form of 30 fields.  It will block resubmission for until EVERY field has been changed.

This is particularly painful when using a form with multiple tabs.

**Comment by mschipperheyn** [comment] 2016-11-20 13:05
For me, this is becoming a nightmare and a blocker in various scenarios. When is there going to be a fix or a workaround?

**Comment by r-f-j-thomas** [comment] 2016-11-26 09:37
It's a blocker for me as well - currently sitting on v5.

I need to try this out when I get a chance, but having a quick look at the code it appears as though `persistentSubmitErrors` might provide a workaround due to the line `if (valid || persistentSubmitErrors) {` in handleSubmit.js.

Obviously setting `persistentSubmitErrors` has other effects, but this may be workable for me.

**Comment by jampy** [comment] 2016-11-26 15:28
@erikras could you please leave a sign of life?

**Comment by r-f-j-thomas** [comment] 2016-12-12 11:48
Looks like this might be fixed in 6.3.1!

**Comment by gustavohenke** [comment] 2017-12-06 23:07
Because this issue saw almost no activity for almost a year, I'm closing it.

**Comment by biomassives** [comment] 2017-12-06 23:08
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:33751 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1eMinU-002Ori-Vs
	for greg@biomassiv.es; Wed, 06 Dec 2017 17:08:13 -0600
Date: Wed, 06 Dec 2017 15:07:33 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1512601653;
	bh=knb16MgzmnwHpE57c/uzVLEQ0wvtXIOq4NqMWNyMqNY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=k7cjZO7ERfqXDvxlfO9sf7kkAdy9IoR6MfO23RNJ/qn1eOWKvZ50iELousD+jXt++
	 bjkh625UI+gaYScByktz2cSZEfa/bSjvoHd6r7ADnqnvyXLxV9ErRdLXkL9qUZHZ00
	 bNy/eOINOa01A/IGUs1FF+qxR/4pLjK1a0y/1x7s=

**Comment by biomassives** [comment] 2017-12-06 23:08
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:42067)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eMinV-002OsJ-AW
	for greg@biomassiv.es; Wed, 06 Dec 2017 17:08:13 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0bpsgvoPJDJq0QU8eGXEGwd4JVY=; b=LFi22XxC9vDYTk7a
	9OraIUqeDQTRHTEOst/pHwSGpbERupFTmjPuAiKojIfjEiFMQYcNbgUFZ9wY5BhE
	CbUS2tuu54YLe336SddxMid4l1x+GmPutgc82Qcan92sgoqOKWCXNSh8doAE3Yz+
	FGjZEUTKubSGye5LlJufJbrx/uY=
Received: by filter0005p1iad2.sendgrid.net with SMTP id filter0005p1iad2-26207-5A287836-4
        2017-12-06 23:07:34.121793133 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 1MS-i7W2QduOgxaTJHOZuw
	for <greg@biomassiv.es>; Wed, 06 Dec 2017 23:07:34.049 +0000 (UTC)
Date: Wed, 06 Dec 2017 23:07:34 +0000 (UTC)

**Closed by gustavohenke** 2017-12-06 23:07 UTC
