### ISSUE TITLE
Remote submit doesn't support wrapping submit function in handleSubmit

### ISSUE THREAD

**Issue by abroder** [erikras/redux-form#2925] opened 2017-05-13 22:59 UTC
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
A minimal example of the form that I'm implementing

```js
const submit = data => console.log(data)

const Form = ({handleSubmit}) => (
  <form onSubmit={handleSubmit(submit))>
     ...
  </form>

export default reduxForm({form: 'test'})(Form)
)
```

Can provide more detailed example if it would be helpful!

* When this form is submitted via a submit button in the form, the `submit` function is called correctly.
* When the form is submitted remotely (by dispatching `submit('test')`) and the submit function is passed in as a prop to `reduxForm` (e.g. `onSubmit: submit`), the `submit` function is called correctly.
* When the form is submitted remotely and the submit function is passed into handleSubmit as in the above example, there is an error `Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop`. (additional stack trace below)

### What is the expected behavior?
Expected identical behavior in all three of the above examples (i.e. the form submits successfully regardless of how the form is submitted & the submit function defined).

### What's your environment?

redux-form version: 6.7.0
affects Chrome and Safari

### Other information

```
checkSubmit	@	createReduxForm.js:137
submit	@	createReduxForm.js:570
submitIfNeeded	@	createReduxForm.js:263
componentWillReceiveProps	@	createReduxForm.js:362
(anonymous)	@	ReactCompositeComponent.js:611
measureLifeCyclePerf	@	ReactCompositeComponent.js:75
updateComponent	@	ReactCompositeComponent.js:610
receiveComponent	@	ReactCompositeComponent.js:547
receiveComponent	@	ReactReconciler.js:125
_updateRenderedComponent	@	ReactCompositeComponent.js:754
_performComponentUpdate	@	ReactCompositeComponent.js:724
updateComponent	@	ReactCompositeComponent.js:645
performUpdateIfNecessary	@	ReactCompositeComponent.js:561
performUpdateIfNecessary	@	ReactReconciler.js:157
runBatchedUpdates	@	ReactUpdates.js:150
perform	@	Transaction.js:140
perform	@	Transaction.js:140
perform	@	ReactUpdates.js:89
flushBatchedUpdates	@	ReactUpdates.js:172
closeAll	@	Transaction.js:206
perform	@	Transaction.js:153
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
batchedUpdates	@	ReactUpdates.js:97
dispatchEvent	@	ReactEventListener.js:147
```

**Comment by jgreubel** [comment] 2017-08-03 22:48
Seeing this issue too, also does not work with a ref remote submit either:

FormComponent.js
```js
function formComponent({handleSubmit, formRef}) {
  localOnSubmit(values) {
    console.log('values: ', values)
  }

  return (
    <form ref={formRef} onSubmit={handleSubmit(localOnSubmit)}>
      ...
    </form>
  ) 
}

export default reduxForm({form: 'testForm'})(formComponent)
```

ParentComponent.js
```js
function parentComponent() {
  return (
    <div>
      <FormComponent formRef={(el => this.formRef = el)}/>
      <button onClick={() => this.formRef.submit()}/>
    </div>
  )
}
```

This one does not produce an error, but it does not prevent the submit event and does a full page reload and adds the fields as query params to the url.  Also, it does not call `localOnSubmit`

redux: 3.7.2
redux-form: 7.0.3

**Comment by gustavohenke** [comment] 2017-08-04 01:19
Duplicate of #2095.

You must use the `Form` component for this; also see https://github.com/erikras/redux-form/issues/2095#issuecomment-287896000

**Closed by gustavohenke** 2017-08-04 01:19 UTC
