### ISSUE TITLE
handleSubmit ignores validation errors on unmounted fields

### ISSUE THREAD

**Issue by Pongetti** [erikras/redux-form#1520] opened 2016-08-11 19:05 UTC
Hello,

I've just noticed that if I return an error from my validation function for a field which is not currently mounted, the error is ignored and the form is allowed to submit anyway.

The following code snippet isn't a great use case example but it proves the behaviour:

```
@reduxForm({
    form: 'simple',
    validate:   (values) => ({
        firstName:  !values.get('firstName') ? 'required' : undefined,
        lastName:   !values.get('lastName') ? 'required' : undefined,
    }),
    onSubmit:   () => alert('submitting')
})
class SimpleForm extends React.Component {

    render() {
        return  <div>
                    <Field name="firstName" component="input" type="text" />
                    <button type="submit" onClick={this.props.handleSubmit}>Submit</button>
                </div>
    }
}

```

This form should actually never submit as there is never a value for lastName.  But it seems that because lastName doesn't exist as a <Field> component, its errors are ignored and the form is allowed to submit as long as firstName is filled in. Add a lastName field and the issue goes away.

I would expect any error I return to prevent form submission.  An error is an error.  The <Field> components I have mounted are display logic only, the data in the store is the source of truth.

My particular use case is that I have a form composed of multiple tabs.  With this behaviour, validation is effectively run only for the fields which are on the currently active tab.

Another use case would be hidden fields.  I consider < input type="hidden" > to be obsolete now that I'm using redux.  My hidden fields are in the store so there's no need to have them in the DOM.

Any thoughts?  Thanks

**Comment by clayne11** [comment] 2016-08-11 19:49
This is by design. Imagine you have a wizard-style multi-part form with a total of 20 fields. Each section of the overall form is 5 fields. After completing each of the 5 fields you click "Next", which validates the currently mounted section of the form, then continues on to the next section.

If you were to check validity over the entire form while you were entering in the first 5 fields you would never be able to move on to the next 5 because the form would never be valid.

**Comment by Pongetti** [comment] 2016-08-12 19:44
Hmmm...  that seems like a complex and arbitrary solution to a single problem.

In my eyes, the form is either valid or it is not valid.  The rest is an implementation detail that should be left to the programmer.
A wizard should be accomplished either by using multiple forms or by writing my own logic for partial validation.

Wouldn't this work?
```
validate = (values, props) => {
	if (props.step ==  1) {
		return validateStep1(values)
	} else if (props.step ==  2) {
		return validateStep2(values)
	} else if (props.step == 3) {
		return validateStep3(values)
	}
}
```

onSubmit should behave in one of two ways upon a submission attempt:
1) Always run regardless of validation, leave it up to the programmer to figure out the rest
2) Run only if no validation errors were returned

Anything in between is unpredictable.  The behaviour "_Do this if all fields currently in the DOM are valid_" is unpredictable, opinionated and wierd.

**Comment by clayne11** [comment] 2016-08-13 14:36
That's a fair point. I don't fully agree, but I do think you make some good points. I still think adding a flag to validate all vs validate only the mounted fields is a good way to handle all cases and to be backwards compatible with the large community of people currently working `v5` which works based on mounted fields.

**Comment by Pongetti** [comment] 2016-08-15 15:59
This has turned into a similar discussion as in  #1453.  I'll add more generic thoughts there.

I'm ok with a config flag for the sake of backwards compatibility.  I'd go further than just validate though.  That other thread implies that touched and dirty also rely on registered/unregistered too, another behaviour I was unaware of.

So a validateAll flag still wouldn't fix my use case with Tabs as switching from tab to tab also clears out information about which fields have been touched.

It would be better to have a flag that makes redux-form work one way or another.  I either want redux-form to act as the sole truth or I want it to work based on this DOM assumption.  Setting this flag to true would effectively mean that any value in your form's store is automatically placed into a registered state and UNREGISTER_FIELD is never run upon unmounting a Field component in the form.

**Comment by jbmeslin** [comment] 2016-10-28 14:28
I have the same issue, but we can check if there are some errors and add global message error with _error.
However when we change tab after a submit, components which can be in error should be mount/register with the touched flag (of course if destroyOnUnmount equal true else second page of real wizard form will be on error on init).

**Comment by etiennedilocker** [comment] 2016-11-01 18:10
Hi @erikras ,

first of all thank you for this amazing project and all the time you invest in it. I've started using reduxForm when v5 was the most recent one and the change to v6 has been phenomal. Individually connected Fields are such a performance boost.

As the others here, I'm also having some issues with unmounted fields not being validated on submit. I, too, am using Tabs inside the form. Currently I am using a very ugly workaround: I'm simply letting all tabs mounted at all times and hiding the inactive ones using CSS. I'd love do this properly though.

Is there a chance we could get a {unregisterOnUnmount: false} option or something similar? If I can help just let me know, I'd love to create a PR and add such an option. However, I'd like to talk to you first about whether there is something conceptually wrong with our approach. I am aware of your Wizard example. However my client isn't interested in validating the tab on tabSwitch. Instead the whole form should be validated on submit.

I'd love to contribute! Big thanks from Germany.

**Comment by clayne11** [comment] 2016-11-01 19:18
I think the better solution is to allow validation on all fields rather than not unmounting fields. There's a couple reasons for this:

1. All the fields may never have been mounted, so it still won't solve the issue of validating all fields.
2. The issue you're trying to solve is that all fields must be validated. That's only peripherally related to whether or not they're mounted.

The direct approach is to add a prop like `validateMountedFieldsOnly` (defaults to `true`) which will switch between validating all fields and validating only mounted fields.

It seems like a reasonable change to me.

**Comment by etiennedilocker** [comment] 2016-11-01 20:43
Thanks for your very quick resopnse. Yeah, you're absolutely right. That would be the most direct approach. I'll look into it and create a PR if I have a good solution.

**Comment by Pongetti** [comment] 2016-11-02 15:36
If anybody's curious, I ended getting around this problem using my own custom class which wraps reduxForm and injects its own handleSubmit function.  This custom handleSubmit function makes sure to call validate once more on the values received (it gets all values) and rejects the promise if it finds errors.  I then just import this custom reduxForm class instead of the stock class in all of my code.

Its ended up being a useful approach for a lot of my error handling actually.

(Also, I'm curious, do the Register/Unregister actions have any purpose beyond this partial validation?  It seems like a performance drag to have 50 actions dispatched when I open up a page, but I'm too timid to make my reducer ignore these actions)

**Comment by clayne11** [comment] 2016-11-02 15:41
The only purpose of the actions is the know which fields are currently mounted. I think we can fix the performance issue by batching the calls to the reducer, though. If we use a debounced function to only call the reducer after the last register / unregister action has been called more than 1 tick apart we can fix the performance issues of firing all the actions sequentially.

**Comment by lustoykov** [comment] 2016-11-22 18:26
Hi @Pongetti , I'm stuck with the same problem. Can you elaborate a little bit more on your approach? Do you first call validator and then if no errors delegate to handleSubmit?

**Comment by Pongetti** [comment] 2016-11-22 19:04
@lustoykov I guess I over-complicated my response as I had created my own decorator to generalize it for all my forms and to accomplish some additional tasks as well.

When it comes down to it though, redux-form includes your validate function as a prop to your component, so there's nothing stopping you from calling the validate function yourself before actually submitting your data.

```
onSubmit = values => {
    return new Promise( (resolve, reject) => { 				
	const errors = this.props.validate ? this.props.validate(values, this.props) : {};
	
	if (!errors) {
		try {
			var submitResult = postValues(values);
		} catch(e) {
			return reject(e);
		}
	} else {
		return reject(new SubmissionError(errors));
	}
    }
}
```

I don't remember all the details as I go through my code, but I think you'll want to return a promise and reject it if there are errors, otherwise redux-form will see the submission as successful.

Also, I've simplified the above code by just having if (!errors) but you may have to do some processing of the errors to detect yes or no depending on what you actually return from your validate function.

**Comment by Anarios** [comment] 2016-12-22 23:06
@Pongetti 's workaround helps, but all field-level validation has to be re-written into a single validation function, not so great :(

**Comment by clayne11** [comment] 2016-12-23 02:00
We should definitely batch the actions for register / unregister to mitigate the performance issue.

**Comment by bmeyers22** [comment] 2017-04-12 02:17
@Pongetti  Are you still using your custom solution, I'm assuming that a PR has not been made and merged, and I am struggling with a similar issue.  And while I'm here thanks for everyone maintaining and contributing to this project, it has made life with React so much easier when it comes to forms.

**Comment by Pongetti** [comment] 2017-04-13 08:36
@bmeyers22 Yes, I'm still using my solution.  As Anarios pointed out, it only works with form level validation functions, not field level.  Works for me and the way I wrap my head around forms but isn't a complete solution.

**Comment by tommmyy** [comment] 2017-04-21 09:47
I did use this solution:
```
onSubmit: (values, _, { errors }) => {
	if (R.isEmpty(errors)) {
		// submit
	} else {
		// still errors
	}
}
```

**Comment by grovesNL** [comment] 2017-07-05 15:44
I have the same issue as the tab examples described above.

I have many collapsible components and wanted to avoid mounting their contents if they are collapsed. This is different than the wizard example described above, because the user may complete a section of the form and then collapse just that section (causing the field to be unregistered). However this will bypass validation. Instead I would like to leave the components registered until the point at which validation succeeds/submit.

I'm using form level validation for the majority of these cases now although I'd like to use field level validation where possible.

**Comment by timhwang21** [comment] 2017-07-05 16:08
@grovesNL I have ran into something similar. I would recommend hiding the collapsed components via CSS instead of unmounting them (though, I'm not sure our use cases align 100%). It'll help you reduce mount / unmount cycles, which will improve render performance as well, and will still cause sync validation to trigger.

**Comment by grovesNL** [comment] 2017-07-05 17:08
@timhwang21 Thanks! I've been trying that method out for a while in another area of my application too. The issue in my case is that many of the form components could be very detailed so it takes a very long time to mount everything, even if many components will never be expanded/visible.

**Comment by pawarvijay** [comment] 2017-07-28 06:58
Nice solutions above
But I figured Out other hacky way
If redux-form is not detecting unmounted fields (In case of TABS)
then 
you can access that validation data in redux state 

![screen shot 2017-07-28 at 12 22 11 pm](https://user-images.githubusercontent.com/5990947/28705911-89462178-738f-11e7-97c3-5506b0797133.png)

UserbusinessInfo -> is Forms Name
SyncError -> fields that contain validation error and also unmounted

Code : 

```
UserBusinessInfo.propTypes = {
    dispatch: PropTypes.func.isRequired,
    userBusinessInfo: PropTypes.array.isRequired,
}

function mapStateToProps(state, ownProps) {
    return {
        userBusinessInfo: state.rootReducer.userBusinessInfo,
        formDataInRedux: state.form.UserBusinessInfo
    }
}

let createReduxForm = reduxForm(
    {
        form: 'UserBusinessInfo',
        destroyOnUnmount: false,        // <------ preserve form data
        forceUnregisterOnUnmount: false,  // <------ unregister fields on unmount
    }
)

UserBusinessInfo = createReduxForm(UserBusinessInfo)


export default connect(mapStateToProps)(UserBusinessInfo)
```

**Comment by danielrob** [comment] 2017-07-28 14:38
This issue was duplicated by #2321. The problem statement there was slightly clearer so closing as a duplicate of #2321.

**Closed by danielrob** 2017-07-28 14:38 UTC

**Comment by ManyStylez** [comment] 2017-08-02 15:25
I have had a similar situation where I wanted to execute different validation rules for different user actions across a multipart form (think along the line of drafting), without blocking the user from visiting other parts of the form

This really doesn't play well if you are using a multipart form and you are mounting each tab of the form in turn, based on some routing implementation.

The solution I used was to show and hide each tab using CSS, thus all fields are mounted and can be reached by the ```SubmissionError``` and adjust the field and give the user feedback on its validity.
