### ISSUE TITLE
v6 — initalStates do not work in immutable version of redux-form

### ISSUE THREAD

**Issue by avin** [erikras/redux-form#1213] opened 2016-06-24 06:14 UTC
i'm using 6.0.0-alpha.15 and I can not use initalStates in redux-form/immutable.
I'm sending initalStates as plainObject, and it converts it to Immtable.Map
if I send Immutable.Map as initalStates it's still not working.

**Comment by timothyallan** [comment] 2016-06-25 01:04
I'm using immutable and this works for me with a15

```
export default (
  connect(mapStateToProps, mapDispatchToProps)(
    reduxForm({
      form: 'loginForm', validate,
      initialValues: {
        email: 'my@email.com',
        password: '12345678',
      }
    })(LoginPage)));

```

**Comment by ooflorent** [comment] 2016-06-25 06:22
As @timothyallan said, it works as expected and the issue is related to your setup (I guess). I'm closing for this reason. However I may be wrong and I suggest you investigate further. If it still looks like a bug to you, feel free to add a simple reproducing sample to highlight the problem and reopen the issue. Thanks!

**Closed by ooflorent** 2016-06-25 06:22 UTC

**Comment by avin** [comment] 2016-07-09 20:36
sorry, my bad. Forgot to replace imports of redux-form at all place :(
_import { reducer as formReducer } from 'redux-form/immutable'_

Works absolutly fine! TY for great lib!
