### ISSUE TITLE
Fields are not getting registered in React 15

### ISSUE THREAD

**Issue by zwug** [erikras/redux-form#4072] opened 2018-06-13 15:59 UTC
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?

With react 15 there are no actions `@@redux-form/REGISTER_FIELD`. That leads to errors with some form properties like [valid](https://redux-form.com/7.4.0/docs/api/props.md/#-code-valid-boolean-code-) because [validation checks](https://github.com/erikras/redux-form/blob/master/src/selectors/isValid.js#L37) only registered fields.

### What is the expected behavior?

I've made some research and found that the reason of not dispatching necessary actions is this [refactoring](https://github.com/erikras/redux-form/pull/4051/files#diff-ca0d4d55e50da37455f88ffb85da436bR40) of lifecycle methods. Seems like all the old React lifecycle methods are not calling methods they should.
Since redux-form still supports react 15 there should be a workaround to use `componentWillMount` to register fields.

### Sandbox Link
https://codesandbox.io/s/j4lx76v98v
No `@@redux-form/REGISTER_FIELD` actions here

### What's your environment?

redux-form: 7.4.0
react: 15.6.2

**Comment by vladhd93** [comment] 2018-06-13 19:10
also i have a lot of bugs with 7.4.0, in general form init and validators not workingat all (react 15.6.2 and redux-form 7.4.0)

**Comment by JoshMock** [comment] 2018-06-13 20:34
I believe this is a duplicate issue to #4069, or at least has the same root cause.

**Comment by danielrob** [comment] 2018-06-15 07:41
Agreed, this is almost certainly a duplicate of #4069. Thank you for the well reported issue.

**Closed by danielrob** 2018-06-15 07:41 UTC

**Comment by erikras** [comment] 2018-06-15 09:43
Published fix in [`v4.7.1`](https://github.com/erikras/redux-form/releases/tag/v7.4.1). Please confirm.

**Comment by erikras** [comment] 2018-06-15 12:44
Published _ACTUAL_ fix in [`v7.4.2`](https://github.com/erikras/redux-form/releases/tag/v7.4.2).
