### ISSUE TITLE
props submitting not working

### ISSUE THREAD

**Issue by martinsojak** [erikras/redux-form#1721] opened 2016-09-07 12:01 UTC
Props submitting not working, always is false.

**Comment by GeniusWigga** [comment] 2016-09-12 10:24
I came across the same issue.

**Comment by gustavohenke** [comment] 2017-01-14 15:58
Please provide a working demo of your issue, and perhaps more details as well.

**Comment by renanbandeira** [comment] 2017-01-19 11:42
I'm facing the same issue. Basically I have various forms in my application, some with promise, some without it. Whether they have or not, the isSubmitting('form') comes always false.

**Comment by gustavohenke** [comment] 2017-01-19 11:49
@renanbandeira and do you mind providing a working demo of it?

**Comment by renanbandeira** [comment] 2017-01-19 12:25
So, I have this selector:
```
export const isLoading = () => createSelector(
  isSubmitting('settings'),
  isSubmitting('login'),
  isSubmitting('loadRoute'),
  (submittingSettings, submittingLogin, submittingLoadRoute) =>
  submittingSettings || submittingLogin || submittingLoadRoute
);
```

In my page, I have a mapDispatchToProps and I define it just like the others selectors I have. On render method, when I try to use it, it comes false everytime. Detail: this page is the root page that will render all the other pages. Basically I want to create a modal for everytime any form is submitting

**Comment by danielrob** [comment] 2017-07-23 16:20
I'm closing this issue as I cannot reproduce: go to http://redux-form.com/7.0.1/examples/simple/, open up dev tools, and submit the form. The `submitting` flag is set to true, and then undefined successively. Also probable dup of #1238.

@renanbandeira if you can come up with a sandbox reproduction of this issue we'll reinvestigate further.

**Closed by danielrob** 2017-07-23 16:20 UTC
