### ISSUE TITLE
Uncaught TypeError: Cannot read property 'wrapped' of undefined

### ISSUE THREAD

**Issue by qq645381995** [erikras/redux-form#1821] opened 2016-09-20 02:48 UTC
Uncaught TypeError: Cannot read property 'wrapped' of undefined

**Comment by kevinzwhuang** [comment] 2016-09-20 05:09
Can you give some more details on how you got this error? Any steps on how to reproduce it?

**Comment by zettadam** [comment] 2016-09-22 11:16
If you follow [Getting Started](http://redux-form.com/6.0.5/docs/GettingStarted.md/) guide, you should see this error

Seems to me reduxForm wrapper needs to be 'connected', like this:

```
export default connect(
  state => ({
    prop: state.prop
  })
)(reduxForm({...})
```

**Comment by swashcap** [comment] 2016-09-27 01:44
I’m also seeing this. Here’s a stack trace:

```
Uncaught TypeError: Cannot read property 'wrapped' of undefined
  get @ reduxForm.js:645
  (anonymous function) @ makeAssimilatePrototype.js:44
  updateStoredPrototype @ makeAssimilatePrototype.js:43
  assimilatePrototype @ makeAssimilatePrototype.js:62
  patchReactClass @ makePatchReactClass.js:40
  makeHot @ makeMakeHot.js:33
  makeExportsHot @ makeExportsHot.js:44
  (anonymous function) @ form-add-consortium.js:142
  (anonymous function) @ form-add-consortium.js:142
  (anonymous function) @ form-add-consortium.js:143
  (anonymous function) @ bundle.js:4373
  __webpack_require__ @ bundle.js:557
  fn @ bundle.js:88
  (anonymous function) @ form-add-consortium-controller.js:17
  (anonymous function) @ form-add-consortium-controller.js:112
  (anonymous function) @ form-add-consortium-controller.js:113
  (anonymous function) @ bundle.js:4367
  __webpack_require__ @ bundle.js:557
  fn @ bundle.js:88(anonymous function) @ routes.js:45
  (anonymous function) @ routes.js:88
  (anonymous function) @ routes.js:89
  (anonymous function) @ bundle.js:4469
  __webpack_require__ @ bundle.js:557
  fn @ bundle.js:88
  (anonymous function) @ index.js:35
  (anonymous function) @ index.js:68
  (anonymous function) @ index.js:69
  (anonymous function) @ bundle.js:4463
  __webpack_require__ @ bundle.js:557
  fn @ bundle.js:88
  (anonymous function) @ multi_main:3
  (anonymous function) @ bundle.js:587
  __webpack_require__ @ bundle.js:557
  (anonymous function) @ bundle.js:580
  (anonymous function) @ bundle.js:583
```

This is from simply decorating with `reduxForm` as prescribed in the v6 docs. `connect`-ing resolves the issue.

**Comment by grrseguin** [comment] 2016-09-27 19:39
This fix works for me : #1655.

**Comment by BerkeleyTrue** [comment] 2016-10-18 17:40
I'm also running into this. Switching back to version 5 for now.

**Comment by dbertella** [comment] 2017-03-27 15:11
As mentioned in #1655, #1262 and, I guess, in other older issues the first solution is updating `react-hot-loader`. Connecting the component works as well indeed but `react-hot-loader` v 1.x is not longer maintained.

**Comment by danielrob** [comment] 2017-08-07 08:31
Closing as this issue has been resolved. It is a duplicate of #1655.

**Closed by danielrob** 2017-08-07 08:31 UTC
