### ISSUE TITLE
Create Accordion or Collapsible section form FieldArray

### ISSUE THREAD

**Issue by rasheedqadar** [erikras/redux-form#4395] opened 2019-03-08 23:39 UTC
**feature request**
When Adding many FieldArray( Member), Can we define each FieldArray under an Accordion or Collapsible.

### What is the current behavior?

In FieldArray example as mentioned in https://redux-form.com/8.1.0/examples/fieldarrays/, member are keep adding in the array.

### What is the expected behavior?
Can we use any existing Library to put FieldArray(Member ) under Accordion or Collapsible. I tried once but when adding Hobbies, DOM is not rendering.

Please advise.

### Sandbox Link

https://redux-form.com/8.1.0/examples/fieldarrays/

**Comment by gustavohenke** [comment] 2019-03-11 05:17
Your question is a bit unclear. You didn't provide a sandbox nor sample code, so it's more difficult to help you.

However, keep in mind that this is usage question, not a bug report/feature request, so I'll just close it. This kind of issue is better suited to StackOverflow.

**Closed by gustavohenke** 2019-03-11 05:17 UTC
