### ISSUE TITLE
Sync validation not triggered after reset

### ISSUE THREAD

**Issue by HiroAgustin** [erikras/redux-form#3284] opened 2017-08-02 16:22 UTC
### Bug Report
Sync validation is not triggered after a form is reset.

### What is the current behavior?
1. Focus on username field.
2. Hit Tab.
3. Error message is shown.
4. Reset form.
5. Focus on username field.
6. Hit Tab.
7. Error is not shown under the user field.

### What is the expected behavior?
Sync validation should happen even tho the form was previously reset.

### Sandbox Link
[Reproduction Code](https://codesandbox.io/s/5yKZ0q4lX)

### What's your environment?
* Redux Form: 7.0.3
* OS: macOS Sierra 10.12.6
* Browser: Chrome 60

### Other information
Looks very similar to #2838

**Comment by danielrob** [comment] 2017-08-02 16:33
Thank you, though your expected and actual are the same? Validation is running, but it's also passing in your reproduction steps. If I add `required` to age for example, submit is prevented?

**Comment by HiroAgustin** [comment] 2017-08-02 16:37
Just updated the comment. After focusing out of the username field the second time (after the form has been reset). The error is not shown beneath it.

**Comment by asonni** [comment] 2017-08-02 17:21
I have the same problem with my own project :(

**Comment by SpearThruster** [comment] 2017-08-02 17:24
Yep, same problem...

**Comment by slavik-m** [comment] 2017-08-02 17:54
Same behavior when mount/unmount form.

Current behavior:
1 Mounted form
2 Submit
3 Error message is shown
4 Unmount form (for example form in modal)
5 Mount form
6 Submit
7 Error is not shown under the user field and "@@redux-form/SET_SUBMIT_SUCCEEDED"; 
value is {};
props .dirty == false

**Comment by HiroAgustin** [comment] 2017-08-02 18:31
A simple fix is having the reset button disabled if the form is `pristine`. For some reason that solves it.

**Comment by bitstrider** [comment] 2017-08-03 01:23
This one might be an easy fix: `@@redux-form/UPDATE_SYNC_ERRORS` should be dispatched after `@@redux-form/RESET`

_state when form is first initialized_
![image](https://user-images.githubusercontent.com/143295/28901686-fcbbf380-77c7-11e7-9e0a-e9c41cb45d25.png)

_state diff after form is reset_
![image](https://user-images.githubusercontent.com/143295/28901745-64baf3dc-77c8-11e7-9c36-aedeafa7738a.png)

as you can seee, `form.fieldLevelValidation.syncErrors` gets cleared

**Comment by danielrob** [comment] 2017-08-05 03:05
Closing as a duplicate of #2971. This seems a legitimate bug, PR's welcomed!

**Closed by danielrob** 2017-08-05 03:05 UTC
Labels: bug
