### ISSUE TITLE
Nested names for inputs break async validation in 7.2.1

### ISSUE THREAD

**Issue by sergioatvandebron** [erikras/redux-form#3785] opened 2018-01-26 14:07 UTC
### Are you submitting a **bug report** or a **feature request**?
bug report.

### What is the current behavior?

Async validation doesn't work on fields with names that point to a nested property.

### What is the expected behavior?
It should work.

### Sandbox Link

https://codesandbox.io/s/j4mylknxr9

The example works if `Field`'s name prop is only one level, e.g. `username`. It breaks if you add a second level, e.g. `username.name`.

### What's your environment?

All OSs, browsers, etc are affected.

**Comment by dagstuan** [comment] 2018-01-31 19:31
I believe this was introduced with #3755 which is a breaking change in how `asyncErrors` and `submitErrors` should be structured. I'm not sure if it was intended to be a breaking change yet, but #3802 should make it consistent at least.

**Comment by dagstuan** [comment] 2018-02-02 10:02
@sergioatvandebron can you post a sandbox where it works the way you expect it to? I couldnt get your sandbox to work by downgrading redux-form.

**Comment by gustavohenke** [comment] 2018-02-02 11:44
I created one that didn't work: https://codesandbox.io/s/20pxj6q6ly

This is now fixed with v7.2.2.

**Closed by gustavohenke** 2018-02-02 11:44 UTC
Labels: bug
