### ISSUE TITLE
dipatching initialize after form successfull submission breaks pristine

### ISSUE THREAD

**Issue by aplanchamp** [erikras/redux-form#4008] opened 2018-04-26 09:49 UTC
**bug report** 
This is related to #1994 
I also have the need to reset the prisine after a successfull submission form.

### What is the current behavior?
I have a form that is submitted using the `handleSubmit` prop from redux form `<form onSubmit={handleSubmit(onSubmit)}>`.
The submission goes well and I want to re-initialize my form (so with pristine).
here is my code : 
```export default connect(mapStateToProps, mapDispatchToProps)(
  reduxForm<ManageQuotingCriteriaFormData, ManageQuotingCriteriaFormProps>({
    form: Forms.QuotingCriteriaForm,
    enableReinitialize: true,
    onSubmitSuccess: (_result: any, dispatch: DispatchRedux<any>, props: any) => {
      dispatch(initialize(Forms.QuotingCriteriaForm, props.values));
    }
  })(ManageQuotingCriteriaForm)
);
```

This actually works since it initializes my form and resets pristine to true. But it also breaks pristine (or dirty by the way) because then is it always equal to true even if a keep updating my form. It just does not do its job anymore. 
### What is the expected behavior?
Pristine should be reset to true after submission and should then be set to false if i re-update my form.

Any idea where the problem is ? I tried removing `enableReinitialize: true` the problem is the same. If I use`reset` i don't have a problem, but reset is not what I want to achieve...

Thanks a lot

**Comment by gustavohenke** [comment] 2018-04-26 12:09
Very likely a duplicate of #3362

**Comment by aplanchamp** [comment] 2018-04-26 12:25
Indeed thanks, but i need the `enableReinitialize` and it did not seem to solve the issue :/.
Anyway, I decided to update the initial values through my result from API instead of using  dispatch(initialize). It works well that way.

**Comment by gustavohenke** [comment] 2018-04-27 11:25
Duplicate of #3362

**Comment by gustavohenke** [comment] 2018-04-27 11:25
Duplicate of #3729

**Closed by gustavohenke** 2018-04-27 11:25 UTC
