### ISSUE TITLE
[v6.5.0] Wizard Form - validating a view which is not currently being rendered

### ISSUE THREAD

**Issue by sbkn** [erikras/redux-form#2705] opened 2017-03-18 21:10 UTC
So I've got a multi-page wizard form.

What I want to achieve is a navigation bar which is aware of the status of every view of the wizard in order to be able to set navigation links to pages to active / inactive appropriately.

Is there any way for a redux-form wizard to validate a view which is currently not being rendered? Can I distinguish to which view which field belongs?

**Comment by danielrob** [comment] 2017-07-24 21:00
Duplicate of #2321. Well, you raise even larger issues, but #2321 will mostly cover this.

**Closed by danielrob** 2017-07-24 21:00 UTC
