### ISSUE TITLE
[v6 rc4] Radio buttons not working if type is omitted on Field

### ISSUE THREAD

**Issue by jervi** [erikras/redux-form#1450] opened 2016-08-03 15:38 UTC
If you have a custom radio button component, e.g. this simple example:

``` jsx
const RadioButton = ({ input, id, children }) =>
    <div>
        <input
          {...input}
          id={id}
          type="radio"/>
        <label htmlFor={id}>{children}</label>
      </div>
```

Note that `type="radio"` is set on the input.

When you render it, value is not being set:

``` jsx
<Field name="sex" component={RadioButton} id="radioMale" value="male">Male</Field>
<Field name="sex" component={RadioButton} id="radioFemale" value="female">Female</Field>
```

It renders as

``` html
<div>
    <input type="radio" name="sex" value="" id="radioMale">
    <label for="radioMale">Male</label>
</div>
<div>
    <input type="radio" name="sex" value="" id="radioFemale">
    <label for="radioFemale">Female</label>
</div>
```

If you add `type="radio"` to the `Field`, then it works:

``` jsx
<Field name="sex" component={RadioButton} type="radio" id="radioMale" value="male">Male</Field>
<Field name="sex" component={RadioButton} type="radio" id="radioFemale" value="female">Female</Field>
```

**Comment by erikras** [comment] 2016-08-03 16:24
Hmm... This is because of the fundamentally different way in which radio buttons work than other inputs. Redux Form has to know if it's a radio button or not, and the only real way is to look at the `type` prop. I suppose that you could [do the mapping from `value` to `checked`](https://github.com/erikras/redux-form/blob/v6/src/createFieldProps.js#L16-L22) yourself...

...or you could pass `type="radio"` into `Field`.

**Comment by jervi** [comment] 2016-08-03 18:22
I'll just go with the second option then. Thanks a lot, and good luck on the release :)

**Comment by rkoberg** [comment] 2016-08-07 22:17
This does not work as expected, even on http://redux-form.com/6.0.0-alpha.4/examples/initializeFromState/
Should the "employed" field be checked? It has an initialState value of true. The ```<Field/>``` component sets its type="checkbox".

To work around this, I need to reach back to initialValues (which, thankfully, is in the this.props) and set checked on the Field component:
```
  handleChild(field) {
    const { initialValues } = this.props;
    switch (field.type) {
      case 'boolean':
        return <formItems.Boolean {...field} checked={initialValues[field.name]} />;
      case 'checkbox':
        return <formItems.Checkbox {...field} checked={initialValues[field.name]} />;
```

**Comment by oyeanuj** [comment] 2016-08-31 00:04
@jervi What was your final solution here? 

I am running into the opposite problem where if I don't pass in the `type="radio"`, then I see the value coming through from the `ConnectedField` and the radio button works. If I add `type='radio'`, then `checked=false` and the radio buttons don't seem to work..

**Comment by jervi** [comment] 2016-08-31 19:12
@oyeanuj My final "solution" was to just pass `type="radio"` to `Field`. That works for me. But I don't use the `checked` attribute, but rather `value`. I believe `checked` is meant for checkboxes, not radio buttons.

**Comment by Aaronius** [comment] 2016-10-06 02:49
This is the suck. I'm trying to create an adapter layer for a component library that has a radio button component. I figured the following should work for mapping redux-form props to my radio component's props:

```
  (
    {
      meta, // eslint-disable-line no-unused-vars
      input,
      ...props
    }
  ) => (
    {
      ...props,
      ...input,
      checked: Boolean(input.value === props.value)
    }
  )
```

And then using the radio component with Field would look like this:

```
<Field
  name="elementSpecificity"
  component={ Radio }
  value="specific"
>
  specific elements
</Field>
<Field
  name="elementSpecificity"
  component={ Radio }
  value="any"
>
  any element
</Field>
```

The problem is that `props.value` is `undefined`. Redux-form doesn't pass `value` through in `props`, but I think it should. `input.value` would be the currently selected value for the redux-form field, while `props.value` would be the "value" for that particular radio button. That way, I could determine whether that particular radio button should be checked by comparing the two (hence, `Boolean(input.value === props.value)`).

I really don't want to tell consumers of my adapter layer than they must specify `type="radio"` any time they want to use a radio. That's nasty.

**Comment by M3lkior** [comment] 2016-10-21 12:36
I faces the same problem. @erikras , here is a way to apply your `processProps = function processProps(type, props, _value)` (in createFieldProps.js) to direct child element (which could be a wrapped component like @Aaronius sample) ?
If not, is it possible to pass `_value` (or another prop name) to the child element ? this way, @Aaronius (and me) could manipulate current radio value (`input.value`) with initial radio value (`_value`)

**Comment by danielrob** [comment] 2017-07-25 06:11
@Aaronius, although you can't pass `value` down (feel free to raise an issue for this separately), you can pass it in the props prop: 

```
const renderRadio = ({ value, input, meta }) => {
 console.log(value) // male
  return (
    <input type="radio" {...input} value={value} />
  )
}

<Field name="sex" component={renderRadio} props={{ value: "male" }} />
``` 

I'm closing this because OP's question was answered and resolved, and one issue per github issue is the way to manageability. Please raise separate issues for any outstanding issues as required.

**Closed by danielrob** 2017-07-25 06:11 UTC
