### ISSUE TITLE
Please add support for button with name and value.

### ISSUE THREAD

**Issue by 0rangeT1ger** [erikras/redux-form#2314] opened 2016-12-20 04:56 UTC
Tried this in a Field but didn't work.
```
<button type='submit' name='action' value='save' />
```

Now I'm using 
```
let action_ = 'save'
.
.
.
<button
  onClick={() => {
    action_ = 'submit'
    handleSubmit()
  }}
>submit</button>
.
.
.
connect(_, {
  onSubmit: (form, dispatch) => handlePostInfo({...form, action: action_}, dispatch),
})(SomeForm)
```

**Comment by gustavohenke** [comment] 2016-12-22 17:11
In the first example, what exactly is the expected behavior?

**Comment by 0rangeT1ger** [comment] 2016-12-23 02:47
Suppose we have two submit button, one for remote save, one for actual submit.
Both submit actions use one URL and backend distinguish them by a field named 'action'.
If you click the button above in my example, the form submit data with a field named 'action' and its value is 'save'.

**Comment by 0rangeT1ger** [comment] 2016-12-23 02:48
If you try that in a html form, you'll know the use of a button's name and value.

**Comment by erikras** [comment] 2017-01-06 20:49
Does [this answer](http://stackoverflow.com/a/37173842/103690) help?

**Comment by 0rangeT1ger** [comment] 2017-01-10 02:09
But wouldn't be better if redux-form support button with name and value?
It will look better and more clean.

**Comment by gustavohenke** [comment] 2017-11-20 22:56
Duplicate of #3622

**Closed by gustavohenke** 2017-11-20 22:56 UTC
Labels: enhancement
