### ISSUE TITLE
Submit validation with dynamic fields

### ISSUE THREAD

**Issue by jhsimms** [erikras/redux-form#2039] opened 2016-10-28 00:17 UTC
You can reproduce this issue as follows:
1. Make a form with a field that always shows and submit validation set up.
2. Make a field that only shows after clicking a button.  Add validation on this field.
3. Submit the empty form before clicking the button to add the new field.
4. The validation error will show on the single field.
5. Click the button to add the new field.
6. Submit the form.  The new field will not have validation run against it.

Similarly, if you click to add the field before submitting for the first time, it will validate it.

The issue here is that redux form will not run the submit hook if the form is in an invalid state.  You can work around this by setting persistentSubmitErrors to true, but that plenty of negative side effects on its own.

**Comment by sethomas** [comment] 2017-01-31 03:00
Had the same issue, after it re renders from the button, I wasn't seeing anything in `syncErrors`.

I was doing this:
```
{someCondition ?
  <Field
    ...
  />
:
  <Field
    ...
  />
}
```

And am now doing:
```
{someCondition ?
  <CustomFieldThatHasFieldTagInIt
    ...
  />
:
  <Field
    ...
  />
}
```
I turned one `<Field>` into it's own React component and placed the `<Field>` in there and it was resolved. Oddly enough it worked with just wrapping the `<Field>` in a `<div>`. No idea why.

**Comment by danielrob** [comment] 2017-08-07 08:41
I'm reasonably sure this was duplicated by #3276. Closing as a duplicate of #3276 but please advise if I've missed something.

**Closed by danielrob** 2017-08-07 08:41 UTC
