### ISSUE TITLE
Field name is not updated correctly when FormSection name changes

### ISSUE THREAD

**Issue by SBRK** [erikras/redux-form#3228] opened 2017-07-21 13:30 UTC
Much like the `formValues` update problem I described in #3202, I'm getting some `Field` inside my `FormSection` that do not use the good `sectionPrefix`. Problem is, I'm getting the bug on the first render, when FormSection name has already been updated from `arr[-1]` to `arr[0]`. My formValues have the right value, but the `Field`s inside of my `FormSection` still have `arr[-1].myProperty` as their `name`.

I looked at `createField.js` and though I found the culprit, `componentWillReceiveProps` did not take `nextContext` (and therefore, `sectionPrefix`) into account, so I fixed it, but I'm still getting the bug.  I then tried to fiddle with `shouldComponentUpdate`, but then again, no cigar.

What could cause the context to not update in children ? Could it be a bug of React where when the context gets changed at the same time as the first render of a child, that child gets the previous context ?

**Comment by SBRK** [comment] 2017-07-25 12:42
I ended up not using `FormSection` and `formValues`, and passing the prefix myself to my `Field` components, because I can't find a fix for now :(

**Comment by danielrob** [comment] 2017-07-27 03:15
Closing this issue as a duplicate of #2948. Both issues have clear write ups.

**Closed by danielrob** 2017-07-27 03:15 UTC

**Comment by SBRK** [comment] 2017-08-03 10:21
It seems with the React 16 beta I'm no longer having the context update issue, so as I suspected, I think it's a problem on React's side. I haven't done deep testing yet, so it might be a side effect of something else.
