### ISSUE TITLE
Enhancement: Key ids for FieldArray items

### ISSUE THREAD

**Issue by EnoahNetzach** [erikras/redux-form#1458] opened 2016-08-04 10:44 UTC
I see an anti-pattern used in `FieldArray`: [index as a key](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318#.5ykbufd53).  
This could bring either to [render glitches](https://github.com/erikras/redux-form/issues/1169) or to unnecessary re-renders.

My proposal is to wrap each array value in an array, like with es6 [`Map`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map#Description), e.g.:

``` es6
[ uniqueKey, field ]
```

where the key is unique in the context of that particular `FieldArray`, i.e. an item added after one other is removed doesn't get the removed key (as it happens right now), but the next never used before.

The proposed use could be (taken from the [example](http://redux-form.com/6.0.0-rc.4/examples/fieldArrays/)):

``` es6
const renderMembers = ({ fields }) => (
  <ul>
    {fields.map(([index, member]) =>
      <li key={index}>
        ...
      </li>
    )}
  </ul>
)
```

**Comment by erikras** [comment] 2016-08-04 21:37
Calling it `index` seems misleading. What if it were a unique id, e.g. 
```js
`fieldName[${++counter}]`
```
where `counter` was a "global" variable that was unique for every iteratee over the history of the web page?

I do agree that it needs to be differentiated from the second parameter, `index`, which is what you use to call `remove(index)`. The array structure had not occurred to me, but with destructuring, it hardly matters.

**Comment by EnoahNetzach** [comment] 2016-08-05 08:10
Yesterday I was experimenting exactly on this idea, like:

```es6
fields.map(([key, member], index) => ...)
```

I think, although I don't know the project thoroughly yet, all the work could be done in [createFieldArrayProps.js](https://github.com/erikras/redux-form/blob/v6/src/createFieldArrayProps.js).

**Comment by EnoahNetzach** [comment] 2016-08-05 08:24
I'm not exactly sure which version could be more appropriate/understandable:

```es6
fields.map(([ key, member ], index) => ...) // 1

fields.map((member, key, index) => ...) // 2

fields.map(({ key, member }, index) => ...) // 3
```

The least convincing and unconventional is **[2]**;  
The most conventional (see [`Map`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map)) is **[1]**, although I don't really like positional APIs, but that's just personal preference..

**Comment by huan086** [comment] 2017-01-18 02:55
Probably not needed as we have `fields.get(index)` now

**Comment by danielrob** [comment] 2017-07-27 23:43
This issue was duplicated by #2735, closing as a duplicate of #2735.

**Closed by danielrob** 2017-07-27 23:43 UTC
Labels: enhancement
