### ISSUE TITLE
`formValueSelector` in `redux-form/immutable` returns `List` instead of array for values in `FieldArray`

### ISSUE THREAD

**Issue by kinyat** [erikras/redux-form#1982] opened 2016-10-18 05:14 UTC
``` javascript
import {formValueSelector} from 'redux-form/immutable'

const selector = formValueSelector('payPackageForm')

export function calculatePayPackageFieldsSelector (state) {
  // Redux-Form does not do deep convert
  return selector(
    state,
    'a',
    'b',
    'c',
    'd'
  )
}
```

it will return something like belows

```
Object {a: "aaaa", b: "bbbb", c: List}
```

where field c is a `FieldArray`. I think I should expect an `array` here instead of `List`.

Thanks for all the helps

**Comment by Zombaya** [comment] 2016-11-23 15:27
I believe it is correct to give back a List since you want immutable objects (because you used 'redux-form/immutable').

You can transform a list to an array with `List.toJS()`

**Comment by danielrob** [comment] 2017-08-06 19:47
Yes, closing this as intended behaviour. It is also partially documented under FieldArray. fields.getAll() method. PR's for clearer documentation always appreciated! Thanks for reporting!

**Closed by danielrob** 2017-08-06 19:47 UTC
