### ISSUE TITLE
No name and value prop on 3rd party Radio component

### ISSUE THREAD

**Issue by tpinne** [erikras/redux-form#3676] opened 2017-12-08 11:58 UTC
### Are you submitting a **bug report** or a **feature request**?
**bug report** or incomplete/incorrect docs

### What is the current behavior?
If one is using a 3rd party component library for form elements, especially radio buttons, (like https://github.com/Semantic-Org/Semantic-UI-React in our example) are not behaving correctly, because they are missing the name and value props.

Have a look at: https://codesandbox.io/s/43oj52ol7x

As stated in the docs:

> **props : object [optional]**
> Object with custom props to pass through the Field component into a component provided to component prop. This props will be merged to props provided by Field itself. This may be useful if you are using TypeScript. **This construct is completely optional; the primary way of passing props along to your component is to give them directly to the Field component**, but if, for whatever reason, you prefer to bundle them into a separate object, you may do so by passing them into props.

and

> These are props that Field will pass to your wrapped component. The props provided by redux-form are divided into input and meta objects.
> **Any custom props passed to Field will be merged into the props object on the same level as the input and meta objects.**

This is not the case for custom components as it seems. Everything works fine for normal dom elements. But the Radio components in the given codesandbox example do not get the name nor the value prop passed along. Which results in the problem that you can check both radio buttons, because they are missing the name. And because of the missing value prop you can not pass the correct value onClick/onChange back to reduxForm.

The name property could be extracted from `input.name` prop and passed down to the component. But the `input.value` is null or an empty string. So one would have to use the special `props`prop to pass that along as seen in the working radio buttons in the sandbox.

### What is the expected behavior?
Either that the name and value prop are always passed down to the desired component or that the docs get updated to state this in more detail, if it is intended behaviour how it currently behaves.

### Sandbox Link
https://codesandbox.io/s/43oj52ol7x

### What's your environment?
All the latest versions. See sandbox

**Comment by gustavohenke** [comment] 2018-04-24 11:56
Hello @tpinne, sorry for this incredible delay.

Your example is quite broken, but I managed to get it _working_.

What happens is that you should always define the `type` prop, or Redux Form will treat the components as `<input type="text">` by default.

Basically, this is a duplicate of #2292.

**Closed by gustavohenke** 2018-04-24 11:56 UTC
