### ISSUE TITLE
Regression: Async validation failing causes Uncaught promise error (6.6.1)

### ISSUE THREAD

**Issue by kongakong** [erikras/redux-form#2771] opened 2017-04-04 11:00 UTC
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Yes. In 6.6.1

To reproduce:

1) Go to

http://redux-form.com/6.6.1/examples/asyncValidation/

2) Submit

3) Inspect the Dev tools 

It is actually a regression of https://github.com/erikras/redux-form/issues/1297 which is already closed.

### What is the expected behavior?
No uncaught exception

### What's your environment?

"redux": "3.6.0"

### Other informations

![image](https://cloud.githubusercontent.com/assets/40389/24653519/7b8db4a8-1979-11e7-8a12-695c1887c97c.png)

**Comment by nivek91** [comment] 2017-05-10 21:16
+1 same happening here

**Comment by Viral-Inc** [comment] 2017-05-26 17:51
+1

**Comment by danielrob** [comment] 2017-07-25 00:04
I'm going to close this as a duplicate of #1297 and re-open that issue.

**Closed by danielrob** 2017-07-25 00:04 UTC
