### ISSUE TITLE
Field level validation access to props

### ISSUE THREAD

**Issue by theKashey** [erikras/redux-form#2745] opened 2017-03-28 01:21 UTC
PR https://github.com/erikras/redux-form/pull/2431 adds new parameters to a field-level validator - props.
But goal was to add Form props, to make validation API consistent.
I think - it was a bit wrong. 

> On field-level validation you should have field-level props.

I am talking about meta information, which Field will pass into component. That props - state of autoflll, pristine/dirty of one field, not all form, should be passed into validator.
But form level information also useful for local validator.
PS: And for global one - too. 
My own case was to mark as invalid all !prestine and !autofilled. And there is no access to initial values, field-level pristine flag, and even no selector for autofilled flag. 
So as view - I have a lot of data. As brains - I dont have anything.

Good solution might be pass both form and field props inside validator. But it will break API.

Thats why I am creating issue, not PR.
I hope someone will found correct way to solve this issue.

**Comment by danielrob** [comment] 2017-07-25 18:41
This was duplicated by #2881. Closing as duplicate of #2881.

**Closed by danielrob** 2017-07-25 18:41 UTC
