### ISSUE TITLE
Error is undefined

### ISSUE THREAD

**Issue by tonyxiao** [erikras/redux-form#1912] opened 2016-10-05 23:40 UTC
According to http://redux-form.com/6.0.5/docs/api/Props.md/

`error` should contain promise rejection from `onSubmit`. However when I reject the promise, I see that the `submisionFailed` field gets properly set to false, but `error` is still undefined. When would that be the case?

**Comment by babsonmatt** [comment] 2016-10-13 17:04
+1

**Comment by Ethaan** [comment] 2016-10-25 03:17
+1

**Comment by Ethaan** [comment] 2016-10-25 03:17
@tonyxiao did you get a solution for this?

**Comment by por** [comment] 2017-01-24 15:17
From the [documentation](http://redux-form.com/6.0.5/docs/api/Props.md/#-handlesubmit-eventorsubmit-function-):

> If there is an error that is not specific to any field, but applicable to the entire form, you may pass that as if it were the error for a field called _error, and it will be given as the error prop.

So this works:

```js
throw new SubmissionError({ _error: 'Your error here' });
```

**Comment by kylanhurt** [comment] 2017-02-19 09:28
I seem to be having the same issue. Need a solution for this. @por, I have tried using the new SubmissionError() but it did not work.

**Comment by gustavohenke** [comment] 2017-02-20 12:32
@kylanhurt please provide a working example. Start here: https://jsfiddle.net/gustavohenke/48814zsq/

**Comment by SwatiMaheshwari** [comment] 2017-02-23 05:46
any solution. I am also facing the same issue?

**Comment by paulruescher** [comment] 2017-04-29 06:24
If anyone comes across this issue, I found that you need to return a promise in your `onSubmit` function.

E.g

```
import Login from './components/Login'

class LoginScreen extends React.Component {
  render() {
    const { dispatch } = this.props
    const onSubmit = ({username, password}) => {
      return dispatch(loginUser(username, password))
    }

    return (
      <Login onSubmit={onSubmit} />
    )
  }
}

// components/Login.js
const Login = ({ handleSubmit, error }) => {
  return (
    <div>
      <form onSubmit={handleSubmit}>
        <Field name="username" component="input" type="text" />
        <Field name="password" component="input" type="password" />
        {error && <strong>{error}</strong>}
        <button type="submit">Login</button>
      </form>
    </div>
  )
}

Login.propTypes = {
  handleSubmit: PropTypes.func
}

export default reduxForm({
  form: 'login'
})(Login);

```

**Comment by tonyxiao** [comment] 2017-04-29 10:11
@Ethaan nope. Though I don't remember the context anymore.

**Comment by MindfulBell** [comment] 2017-06-07 18:53
Has anyone confirmed any solution for this? I have exact same issue.

**Comment by Ethaan** [comment] 2017-06-07 19:05
@MindfulBell yes, @paulruescher answer its correct.

Seems like inside the `onSubmit` handler a promise should be returned, basically the following.

```
const onSubmitHandler = () => (
 store.dispatch(myActions.onSubmitHandler(...params);
)
```

**Comment by MindfulBell** [comment] 2017-06-07 23:14
Hmm @Ethaan I am pretty sure we are returning a promise. Still does not work.

**Comment by gustavohenke** [comment] 2017-06-23 13:12
Again: anyone able to create a reproducible example of the issue, please?

**Comment by danielrob** [comment] 2017-07-24 19:16
It's been one month, and no-one has provided a reproducible example of this issue, while people have provided accurate working examples. Closing. If an example is provided we'll re-open.

**Closed by danielrob** 2017-07-24 19:16 UTC

**Comment by danielrob** [comment] 2017-07-24 19:19
@MindfulBell note that returning a promise isn't enough, the rejection of this promise must pass a SubmissionError with an _error key, and any other field specific errors under keys with names corresponding to field names. As per https://github.com/erikras/redux-form/issues/1912#issuecomment-274832955 above.

**Comment by barcher** [comment] 2017-12-07 19:41
@por wrapping the error in `SubmissionError` did not work for me (perhaps that API changed?). However, the following did: e.g. `..catch(err => { throw { _error: 'My error' } })`.

**Comment by vinhtq** [comment] 2018-01-04 07:33
```
import React from 'react';
import { Field, reduxForm } from 'redux-form';

const validate = values => {
  const errors = {};

  if (!values.email) {
    errors.email = 'Required';
  } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
    errors.email = 'Invalid email address';
  }

  if (!values.password) {
    errors.password = 'Required';
  }

  return errors;
}

const renderField = ({
  input,
  type,
  icon,
  placeholder,
  meta: { touched, error }
}) => (
  <div className="field">
    <div className="ui left icon input">
      <i className={[icon, "icon"].join(" ")} />
      <input {...input} placeholder={placeholder} type={type} />
    </div>
    {touched && error && <div className="ui negative message">
      <div className="header">
        {error}
      </div>
    </div>}
  </div>
)

let LoginForm = props => {
  const { handleSubmit, submitting, error } = props;
  
  return (
    <form className="ui form" onSubmit={handleSubmit}>
      <div className="ui stacked segment">

        <Field component="input" type="text" name="email" placeholder="E-mail address" icon="mail" component={renderField} />

        <Field component="input" type="password" name="password" placeholder="Password" icon="user" component={renderField} />

        {error && <strong>{error}</strong>}

        <button type="submit" className="ui fluid large teal submit button" disabled={submitting}>Login</button>
      </div>
    </form>
  );
}

LoginForm = reduxForm({
  // a unique name for the form
  form: 'login',
  validate
})(LoginForm);

export default LoginForm;
```
You will see that the error in props always return undefined

**Comment by trifox** [comment] 2018-01-15 17:39
same issue here, strangely enough the error is correctly stored in the state
reduxstate.form.myform.submitErrors contains the correct field names, but the rendered field component receives field.meta.errors=undefined, but field.meta.submitFailed is True ...

**Comment by trifox** [comment] 2018-01-16 13:13
in my case i figured it out:

- i had dot syntax named field e.g. 'data.email'

WRONG:
{
'data.email':'invalid email'
}

CORRECT (using object notation
{'data':{'email':'invalid email'}}

which gets correctly delivered to the field

*note perhaps include it in the submission error documentation how to handle dot notation?

**Comment by nvma** [comment] 2018-03-20 19:36
I'm utterly confused by now. Is this how it should work?
```
handleSubmit = values => {
  return axios({
    method: 'POST',
    url: '/login',
    data: values,
    responseType: 'json',
  }).catch(() => {
    throw new SubmissionError({
      _error: 'Login failed for reasons I rather not disclose to the end user',
    });
  });
}

<form onSubmit={handleSubmit(this.handleSubmit)}>
  ...
</form>
```
Apparently not, because `error` prop is undefined, but that's how documentation suggests to implement it. Is it a bug or do I miss something?

**Comment by NickStefan** [comment] 2018-06-14 18:01
I think I may have identified this as a webpack / babel issue. This would explain why reproducing this in a jsfiddle is hard:

Basically, if in your app you do:
``` 
import { SubmissionError } from 'redux-form';
...
throw SubmissionError({_error: "Bob"});
```

The instance of fails here:
![screen shot 2018-06-14 at 11 47 21 am](https://user-images.githubusercontent.com/6600333/41429520-87269106-6fca-11e8-9f7c-4dceba5b11e0.png)

_SubmissionError2.default !== the SubmissionError imported to user land! This issue about babel seems to highlight this: https://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node

**Comment by kotmatpockuh** [comment] 2018-07-18 14:31
@NickStefan  any updates?

**Comment by NickStefan** [comment] 2018-07-18 17:12
I cant exactly remember the details, but one of our front end engineers figured out that there's an Immutabe SubmissionError we were supposed to be importing... So I was only half right. The instance was incorrect, but it wasn't strictly babel's fault.
