### ISSUE TITLE
import { Field, reduxForm } from 'redux-form/immutable' throw : Super expression must either be null or a function, not object

### ISSUE THREAD

**Issue by kopax** [erikras/redux-form#2211] opened 2016-12-02 12:59 UTC
I am trying to follow the documentation here : http://redux-form.com/6.2.1/examples/immutable/

But with redux-form 6.2.1, when I do this import :

    import { Field, reduxForm } from 'redux-form/immutable'

I have the following error : 

    SubmissionError.js:17Uncaught (in promise) TypeError: Super expression must either be null or a function, not object(…)

Is it me or is it just me ?

**Comment by javatask** [comment] 2016-12-03 07:13
+1

**Comment by carlos-peru** [comment] 2016-12-07 00:56
@kopax I have a simple basic example integrating react-boilerplate and redux-form: https://github.com/carlos-peru/react-boilerplate-redux-form

**Comment by kopax** [comment] 2016-12-07 03:34
@carlos-peru , in fact, your example bring me here.
I was too lazy after this error to continue integrating using your example.
I can see your whole app working, but I am still wondering how you get there.

**Comment by dziamid** [comment] 2016-12-07 10:17
Started experiencing this as well. Running debugger reveals that SubmissionError constructor is being called with an object `{default: function ExtendableError() }` while _inherits checks that is should be a function or null

```
// SubmissionError.js
var SubmissionError = function (_ExtendableError) {
  _inherits(SubmissionError, _ExtendableError); 
  
  function SubmissionError(errors) {
    _classCallCheck(this, SubmissionError);

    var _this = _possibleConstructorReturn(this, (SubmissionError.__proto__ || Object.getPrototypeOf(SubmissionError)).call(this, 'Submit Validation Failed'));

    _this.errors = errors;
    return _this;
  }

  return SubmissionError;
}(_es6Error2.default);
```

**Comment by dziamid** [comment] 2016-12-07 12:54
My best guess is that there is something wrong in the way es6-errror is being imported here: 
https://github.com/dziamid/redux-form/blob/master/src/SubmissionError.js
Basically the module gets imported without `__esModule` flag and the module is being imported using 'jsnext:main' directive:
https://github.com/bjyoungblood/es6-error/blob/master/package.json

In fact if you remove `jsnext:main` setting in the source of es6-error package, the error is gone. 

Any ideas how to address this without forking redux-form?

**Comment by dziamid** [comment] 2016-12-08 08:19
I think we can close this thread as a duplicate of https://github.com/erikras/redux-form/issues/1416

**Comment by danielrob** [comment] 2017-08-03 13:03
Closing as a duplicate of #1416.

**Closed by danielrob** 2017-08-03 13:03 UTC

**Comment by nickbarry** [comment] 2017-09-12 14:00
Is there a recommended workaround until this is fixed? I'm running into this problem on redux-form versions 6.1.1 and 7.0.4. Is the answer "don't use immutablejs + redux-form", or are other people doing that successfully somehow?
