### ISSUE TITLE
React 15.6.0 + Redux-form has broken radio buttons

### ISSUE THREAD

**Issue by tstirrat15** [erikras/redux-form#3087] opened 2017-06-20 22:28 UTC
### What is the current behavior?
A component that demonstrates it:
```javascript
const dummy = () => (
  <div>
    <fieldset>
      <Field name="foo" component="input" type="radio" value="a" />
      <Field name="foo" component="input" type="radio" value="b" />
      <Field name="foo" component="input" type="radio" value="c" />
      <Field name="foo" component="input" type="radio" value="d" />
    </fieldset>
  </div>
);

const decoratedDummy = reduxForm({
  form: 'dummy',
})(dummy);
```

Package.json versions:
```
"react": "15.6.0",
"redux-form": "6.8.0"
```

I've verified that redux-form version doesn't matter, and that `15.5.4` works but `15.6.0` doesn't for react. Perhaps it's related to facebook/react#8575 ?

What happens in the broken case is that the `blur` and `focus` events fire, but the `change` event never fires. I'm not familiar enough with either the React or Redux-form internals to understand what isn't working.

This behavior could have been what was seen in #2526 as well.

### What is the expected behavior?
Being able to select the radio button

### Sandbox Link
https://codesandbox.io/s/M8lXj4vRR

Oddly, I wasn't able to reproduce this in the sandbox. Is there something about Babel or Webpack that could be screwing things up?

### What's your environment?

Browsers: both firefox and chrome
Redux-form version: 6.8.0
React version: 15.6.0
Babel core version: 6.17.0
Webpack version: 2.3.3
Node version: 6.7.0

### Other information
I'm kind of at a loss for what other information could be pertinent/useful. In the meantime we'll downgrade to React 15.5.4 and keep running, but this struck me as very odd.

**Comment by donysukardi** [comment] 2017-06-26 11:38
Experiencing exactly the same issue here

**Comment by lothisoft** [comment] 2017-07-11 15:52
I experienced the same issues as well.  It might be related this "fix" introduced in 15.6.0: https://github.com/facebook/react/pull/8575

**Comment by dmitru** [comment] 2017-07-20 23:21
I've got the same issue with `react@^15.6.0`; rolling back `react` and `react-dom` to `15.5.4` did help.

**Comment by buvinghausen** [comment] 2017-07-26 14:57
JavaScript Jenga! 

Add a +1 to the list of 15.5.4 did the trick

**Comment by geekuality** [comment] 2017-07-27 10:23
Experiencing this also, rolling back is not an option for us. :(

**Comment by marcneander** [comment] 2017-08-14 08:09
Any updates on this?

**Comment by donysukardi** [comment] 2017-08-14 10:11
Just update to the latest redux-form, it works fine on 7.0.3. It should have been fixed somehow.

**Comment by lothisoft** [comment] 2017-08-14 14:19
As you can see in https://codesandbox.io/s/G6zR5o3P8, it hasn't been fixed.

**Comment by karaschee** [comment] 2017-08-23 06:57
Same issue, roll back to 15.5.4 now

**Comment by leaky** [comment] 2017-08-23 11:17
Rolling back `react` and `react-dom` to 15.5.4 fixes this issue.

**Comment by justo** [comment] 2017-08-31 19:22
It must be caused by the `onChange` event changes in 15.6: https://facebook.github.io/react/blog/2017/06/13/react-v15.6.0.html#improving-inputs

**Comment by andoq** [comment] 2017-08-31 20:12
It's probably the interaction with the new changes, but I've also tracked it down to the fix for #2444

If i comment out the fix fro that issue in ConnectedField.js, then things seem to work for me.

**Comment by andoq** [comment] 2017-08-31 20:40
actually, that's not quite right - if I comment out those lines, my UI state changes, but the onChange event is still not fired for the input and the value doesn't change.\.

However, if I get rid of the onBlur event handler entirely from the constructed react component (comment out line 245), then things work.

**Comment by erikras** [comment] 2017-09-06 08:28
Here's a forked version of @lothisoft's sandbox. It was broken with `react@15.6.0`, but appears to be working with `react@15.6.0`, probably due to https://github.com/facebook/react/pull/9960. Closing.

[![Edit Redux Form - The Radio Button onChange handler is called only once](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rrl72px92n)

**Comment by lauterry** [comment] 2017-09-06 08:31
Hello I'm using react 15.6.1 and I still have this issue

**Comment by erikras** [comment] 2017-09-06 08:34
You are correct. It is not fixed in 15.6.1. Apologies. Reopening.

**Comment by erikras** [comment] 2017-09-06 08:50
Here's a super-simple radio button sandbox I coded up using pure React state, which does imply that the bug is with `redux-form` somehow.

[![Edit React Radio Buttons](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kmoq8o8v1v)

I will investigate. 🔍

**Comment by lauterry** [comment] 2017-09-06 09:14
As a workaround, I used onClick instead of onChange in my <input/>.

What do you think ?

**Comment by erikras** [comment] 2017-09-06 14:39
Okay, this seems to be an implementation problem. On [@lothisoft's sandbox](https://codesandbox.io/s/G6zR5o3P8), he is not passing a `checked` prop to the `<input/>`. If the `Field` was given `type="radio"`, `redux-form` would generate that for him in `field.input`, by calculating if the `value` prop passed to `Field` is `===` the value for the field in the form. Additionally confusing matters, he has chosen to use `radioButtonValue` instead of `value`. [I have fixed his implementation](https://codesandbox.io/s/rrl72px92n) by adding a single l line:

```jsx
checked={radioButtonValue === field.input.value}
```

This is what `redux-form` attempts to do for you if you don't bypass the `value` prop, and specify `type="radio"`.

[_This_ is the real solution](https://codesandbox.io/s/l477120lq7).

1. `Field` given `type="radio"` so that it knows to managed the `checked` prop for you*
2. Each call to `RadioButton` is given a `value` prop which gets passed along to `Field` so that it can do that work for you.

*Granted, this isn't documented very well. Perhaps something about this should go into the `Field` docs.

Does this make sense to everyone? If not, please ask questions.

**Closed by erikras** 2017-09-06 14:39 UTC
Labels: bug

**Comment by pebf** [comment] 2017-10-25 09:12
@erikras your "real solution" is not working now

**Comment by webmobiles** [comment] 2018-02-18 06:55
@erikras example solution does not produce value

**Comment by Gtosta96** [comment] 2018-02-28 21:36
news?

**Comment by buvinghausen** [comment] 2018-02-28 21:54
use final-form?

**Comment by acontreras89** [comment] 2018-06-25 14:56
I thought I was having this issue, then I realized all html inputs were receiving the same id and, thus, all labels were being associated with the first radio button.

Now it's working fine for me. Just let `Field` know it's a radio button.

**Comment by ggregoire** [comment] 2018-08-22 19:29
Just wasted 1 hour on this: **if you pass a number as value, it is not automatically converted to string and it breaks the input radio.** (The value is correctly set in the reduxform store, but the input doesn't appear selected)

So you need to convert it to string by yourself:

```
<Field
  name="user"
  component="input"
  type="radio"
  value={user.id.toString()}
/>
```

Note that passing a number as value to a React input radio works. I guess that's what confused me.

Hope it can help!

**Comment by dmitru** [comment] 2018-12-18 07:33
For me the problem was with BrowserSync configuration (wasted 1.5 hours figuring it out).
See this answer: https://github.com/erikras/redux-form/issues/3369#issuecomment-334777876

**Comment by benjaminhyw** [comment] 2019-02-12 01:30
For me, my issue was the Field name prop didn't match up.  I thought they had to be different.. they have to be same for your radios to work.

**Comment by alexteg** [comment] 2019-05-10 07:34
Or alternatively to the great solution by @ggregoire the input value may be parsed as a number:
```jsx
<Field
  name="user"
  component="input"
  type="radio"
  value={user.id}
  parse={Number}
/>
```
