### ISSUE TITLE
unregistered field is still returned in getFormValues selector

### ISSUE THREAD

**Issue by henryqdineen** [erikras/redux-form#2658] opened 2017-03-06 19:33 UTC
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?

Mount a form, enter data in a field then hide (unregister) that field.

`getFormValues` selector will return an object containing that data that was in that field 

### What is the expected behavior?

Docs say that `getFormValues` simply "returns form values" but I would not consider that unregistered field as part of the form.

### What's your environment?

redux-form 6.2.0, chrome latest

### Other informations

I'm thinking that `getFormValues` should filer out fields that aren't in `registeredFields`

**Comment by danielrob** [comment] 2017-07-25 07:18
Closing as a duplicate of #2761. This is presently intended behaviour due to wizard form scenarios.

**Closed by danielrob** 2017-07-25 07:18 UTC
