### ISSUE TITLE
Composition characters break with react-redux@5 and redux-form-material-ui

### ISSUE THREAD

**Issue by Eiryyy** [erikras/redux-form#2622] opened 2017-02-22 15:55 UTC
### Are you submitting a **bug report** or a **feature request**?
A bug report.

### What is the current behavior?
![rr-5 mov](https://cloud.githubusercontent.com/assets/2590137/23213290/bfe199cc-f94d-11e6-8749-7898401084fd.gif)

Japanese character 'さ' is from Roma-ji 's' and 'a'. But with `react-redux@5`, first 's' was fixed without return key.

### What is the expected behavior?
![rr-4 mov](https://cloud.githubusercontent.com/assets/2590137/23213538/a8c74f56-f94e-11e6-9916-c8ca4f5cba13.gif)

With `react-redux@4`, 'さ' was inserted exactly.

### What's your environment?

+ redux-form 6.5.0
+ react-redux 5.0.2
+ material-ui 0.17.0
+ redux-form-material-ui 4.1.2
+ macOS 10.12.3
+ Chrome 56.0.2924.87
+ Google IME

**Comment by erikras** [comment] 2017-02-22 16:37
Interesting. Are you using an out-of-the box `redux-form-material-ui` component? Can you share what your `<Field/>` code looks like?

**Comment by Eiryyy** [comment] 2017-02-22 16:51
Really simple.

```
import React from 'react'
import { Field, reduxForm } from 'redux-form'
import { TextField } from 'redux-form-material-ui'

const Form = ({ handleSubmit }) => (
  <form onSubmit={handleSubmit}>
    <div>
      <Field name="name"
        component={TextField}
        hintText="Name"
        floatingLabelText="Name"
      />
    </div>
  </form>
)

export default reduxForm({
  form: 'example'
})(Form)
```

**Comment by CoderNie** [comment] 2017-02-23 16:22
This problem comes to Chinese input,too.Could dear erikras help me?

**Comment by jiexishede** [comment] 2017-04-13 13:34
This problem comes to Chinese input, too.Could dear erikras help me?   The same to me.  I face the same problem!

**Comment by JuoCode** [comment] 2017-04-15 04:54
@jiexishede This may be caused by input method

**Comment by jiexishede** [comment] 2017-04-15 11:29
@JuoCode  Do you know how to solve this problem?

**Comment by Eiryyy** [comment] 2017-07-04 05:33
@erikras @CoderNie @jiexishede 
Now, with `redux-form@6.8.0`, `redux-form-material-ui@4.2.0`, `redux@3.7.1`, `react-redux@5.0.5`, this problem doesn't happen.

**Comment by erikras** [comment] 2017-07-04 13:24
I'm closing this based on @Eiryyy's comment.

**Closed by erikras** 2017-07-04 13:24 UTC
