### ISSUE TITLE
[V6] Using material-ui's DatePicker

### ISSUE THREAD

**Issue by oallouch** [erikras/redux-form#1221] opened 2016-06-27 09:42 UTC
I can't use a DatePicker in a V6 form:

- I need to click twice before the DatePicker's Dialog appears (with the wrong width)
- the date isn't output in the TextField

Do you have any working example ?

**Comment by masenius** [comment] 2016-06-27 17:02
I also have a problem with this. All text fields works using redux-form-material-ui but I can't get the DatePicker to work. I am using 6.0.0-alpha.15.  I have tried three different ways:

`import DatePicker from 'material-ui/DatePicker';`

First:
`<Field name="date" style={inputStyle} component={DatePicker} hintText="Date" autoOk={true} />`

Second:
```
const renderDatePicker = props => (
  <DatePicker {...props} />
)

<Field name="date" style={inputStyle} component={renderDatePicker} hintText="Date" autoOk={true} />
```

Third:
```
const renderDatePicker = props => (
  <DatePicker errorText = {props.touched && props.error} {...props} onChange = {(event, index, value) => {console.log(value); props.onChange(value)}} />
)

<Field name="date" style={inputStyle} component={renderDatePicker} hintText="Date" autoOk={true} />
```

The log output on the last one is undefined.

**Comment by erikras** [comment] 2016-06-27 17:41
[Looks like](http://www.material-ui.com/#/components/date-picker) the value is the _second_ parameter to `onChange`.

![date picker - material-ui 2016-06-27 19-40-40](https://cloud.githubusercontent.com/assets/4396759/16389626/0b1c739c-3c9f-11e6-8575-461e1e97c936.jpg)

**Comment by oallouch** [comment] 2016-06-27 17:42
That would be a great addition to the (very nice) library redux-form-material-ui .

**Comment by oallouch** [comment] 2016-06-27 17:47
@masenius And do you have the other symptom ? ("I need to click twice before the DatePicker's Dialog appears")

**Comment by masenius** [comment] 2016-06-27 18:18
@erikras Thank you! This has bugged me all weekend.
@oallouch No, opens on first click.

**Comment by ooflorent** [comment] 2016-06-28 09:45
I'm closing this since it is not a bug but a usage question.

When integrating Redux Form with a 3rd party component, the component must respect Redux Form contract:

- **MUST** read the value through `value`
- **MUST** notify changes using `onChange(value)`
- **MAY** call `onFocus()`
- **MAY** call `onBlur()`

**Closed by ooflorent** 2016-06-28 09:45 UTC

**Comment by ooflorent** [comment] 2016-06-28 09:47
> @oallouch 
> That would be a great addition to the (very nice) library redux-form-material-ui

You could submit a feature request or a PR! I'm sure Erik will be pleased to review it!

**Comment by erikras** [comment] 2016-06-28 14:28
@oallouch `redux-form-material-ui` has a `DatePicker` now.
