### ISSUE TITLE
Nav Button not working on firefox nightly  and initReact is not defined

### ISSUE THREAD

**Issue by fredericksilva** [erikras/redux-form#2482] opened 2017-01-19 19:07 UTC
###### Nav button not working
<img width="492" alt="screen shot 2017-01-19 at 17 02 48" src="https://cloud.githubusercontent.com/assets/410689/22121064/8b11ec50-de69-11e6-8a18-557bb1bf870a.png">

##### IntiReact Error
<img width="489" alt="screen shot 2017-01-19 at 17 03 20" src="https://cloud.githubusercontent.com/assets/410689/22121065/8b134d8e-de69-11e6-976c-ea73084154d4.png">

**Comment by gustavohenke** [comment] 2017-01-19 19:12
duplicate of #1808

**Closed by gustavohenke** 2017-01-19 19:12 UTC

**Comment by fredericksilva** [comment] 2017-01-23 00:24
Thanks @gustavohenke  :D
