### ISSUE TITLE
Changing 'form' prop on mounted form does not initialise correctly

### ISSUE THREAD

**Issue by Malax** [erikras/redux-form#2192] opened 2016-11-30 16:58 UTC
Today, I ran into an issue. I am not sure if this is intentional, but it sure bit me hard.

I have a form that will get its _form_ property at runtime, based on the id of the entity the the form is supposed to edit. I am using react-router (who doesn't?) and in my case, the user can switch between the edited entity easily, causing the form not to be mounted again, but rather have its props changed (_form_ and _initialValues_). 

In that case, there is no new form created in the redux store and the displayed form is just broken. (Does not allow inputs as the reducer cannot put the edits into the store because a form with the given name does not exist and the initial values are also not set at all.)

I tried passing _enableReinitialize_ at "design time" to enable proper behaviour, but to no avail. When I pass the _form_ prop also at "design time" (so it is the same for all instances of that form) it works perfectly.

My assumption is that there is no support for changing the _form_ prop after the form has been mounted. Is that intentional? What is the proper way to deal with this issue as I have the case where multiple instances of the same form are mounted on one page, but for different entities, which is not supported when I have a fixed form property for all instances.

Tested with version **6.2.0** and **6.2.1**

**Comment by xiankai** [comment] 2016-12-06 09:53
I encountered the same issue as well, as I have a registration form for multiple participants in which you can jump between each participant with ease.

With redux 5 it was a non-issue as changing the `formKey` prop updated the form as expected. but with redux 6, this doesn't work anymore.

[Looking at the code](https://github.com/erikras/redux-form/blob/v6.2.1/src/reduxForm.js#L526), it seems that the initial form prop is bound to the action creators, instead of using the context prop (which is always updated).

For now I have resorted to keeping multiple instances of the form on the page, but only showing the currently active one and hiding the others. Obviously this is not ideal however.

**Comment by MikeBarnhardt** [comment] 2016-12-12 15:16
Sorry, I only half read your problem, but try adding `key` (not `formKey`) with the entity ID as a prop as well. This should cause React to re-render the component correctly.

Usually, you get a warning from React if you don't use this in a loop or map function, but you can add it only a single component and get the same result.

**Comment by danielrob** [comment] 2017-08-01 21:45
Closing this due to non response/age. If this is still an issue please request a re-open with reproduction steps / reproduction sandbox.

**Closed by danielrob** 2017-08-01 21:45 UTC
