### ISSUE TITLE
7.2.0 asyncValidate trigger bug

### ISSUE THREAD

**Issue by lama-pacos** [erikras/redux-form#3687] opened 2017-12-13 01:36 UTC
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
asyncValidate when input trigger onChange events

### What is the expected behavior?
only blur trigger asyncValidate

### Sandbox Link
no

### What's your environment?
redux-form: 7.2.0

### Other information
defaultShouldAsyncValidate.js
```
    case 'blur':
    case 'change':
      // blurring
      return true
```

**Comment by gustavohenke** [comment] 2018-01-29 12:18
Duplicate of #3645

**Comment by gustavohenke** [comment] 2018-01-29 12:18
Fixed in v7.2.1.

**Closed by gustavohenke** 2018-01-29 12:18 UTC
Labels: bug
