### ISSUE TITLE
[v6 rc3] scroll to error on submit and scroll to next error on next submit

### ISSUE THREAD

**Issue by rluiten** [erikras/redux-form#1336] opened 2016-07-13 06:10 UTC
What I am trying to achieve is scroll to first error on form so its visible when submit is clicked and errors are encountered.

Its working fine for the first time I submit and get back validation errors from submit I get the errors back from my post fail and they are set against redux-form using throw new SubmissionError and appear on form.  Then in the onSubmitFail handler I get errors parameter and can find one and scroll to it fine.

After fixing the first error if the user presses submit again I would like to scroll to the next error if any remain. At the moment onSubmitFail() is called again if you press submit and errors still remain but but the errors parameter is undefined so I cant use it to find next error.

The intention is after fix error and submit again series one of the submits will actually cause a round trip to the server and it will succeed.

I was trying to find a list of errors still active on the form in properties passed to wrapped form or in a handler or event somewhere.

An alternate model idea.

Maybe I need to capture the errors and provide navigation for all at capture time.
If so how do I check that the errors I have captured have been fixed by user as he does them so the form may not show an error but my list needs to be updated after each if fixed ?

Thanks for any input or advice.
Robin

**Comment by andrewmclagan** [comment] 2016-07-21 07:25
also struggling with this behaviour

**Comment by BryIsAZombie** [comment] 2016-08-12 19:25
@rluiten @andrewmclagan either of you find a relatively pain-free way of doing this?

**Comment by rluiten** [comment] 2016-08-12 22:32
@BryIsAZombie I am using something similar in concept to what I've done in another solution with other technologies in past using jQuery to find error classes and then scrolling to them.

I am rendering a class in my DOM structure for each field to display error states visually 'field-error', that's likely to be pretty common for most people. 
To this DOM element with the error class I added a data-error attribute that contained the name of the field it was an error for with "Error" suffix.
I also render an Element component from react-scroll for each field in error that has the same name as the value I write to the data-error tag in a logical location to scroll to display the field when scrolled to.

When a user clicks on submit I search for the first element with that class on page using jquery and extract the data-error value and use react-scroll's scrollTo() method to scroll to the error field. I have a small 200 msec delay before searching for the error on the page because the first time you validate on submit the fields have to re-render with the async error states displayed. It covers the bases of the behavior I need and isn't huge or complex. The lookup and scrolling logic is in the redux-form onSubmitFail handler.

I don't I like having to include jQuery in my project but I may look at a smaller more minimal library to replace jQuery down path.

The only case this may not cover cleanly at the moment is async validation where the 200 msec delay I am using won't cover it the errors to be on page, in my case this isn't an issue.

**Comment by BryIsAZombie** [comment] 2016-08-15 01:54
@rluiten Came to the same conclusion as you. Just using a has-error class and document.getElementsByClassName('has-error')[0] on the click event of the submit button and scrolling to it.

**Comment by igorbarbashin** [comment] 2016-11-01 19:23
Here's how we done it.

We're using `react-scroll` to place scroll position markers on every Field component.

In the wrapper component we add react-scroll Element:
```jsx
<div>
  {name && <Element name={`position-${name}`} />}
  <Input
    name={name}
    . . .
  />
</div>
```

Add `onSubmitFail` to redux-form:
```jsx
MyForm = reduxForm({
  form: 'MyForm',
  validate,
  onSubmitFail: (errors) => scrollToFirstError(errors),
})(MyForm);
```

Scroll to first error implementation
```jsx
export function scrollToFirstError(errors) {
  const errorFields = getErrorFieldNames(errors);

  // Using breakable for loop
  for (let i = 0; i < errorFields.length; i++) {
    const fieldName = `position-${errorFields[i]}`;
    // Checking if the marker exists in DOM
    if (document.querySelectorAll(`[name="${fieldName}"]`).length) {
      scroller.scrollTo(fieldName, { offset: -200, smooth: true });
      break;
    }
  }
}
```

Our `errors` object is not quite clean. It contains a lot of `undefined`s (it means the field is valid). So we need a helper function that traverses the errors object and outputs an array of all invalid field names. (It would be cool if something like that was built-in into redux-form):

```jsx
function getErrorFieldNames(obj, name = '') {
  const errorArr = [];
  errorArr.push(Object.keys(obj).map((key) => {
    const next = obj[key];
    if (next) {
      if (typeof next === 'string') {
        return name + key;
      }
      // Keep looking
      if (next.map) {
        errorArr.push(next.map((item, index) => getErrorFieldNames(item, `${name}${key}[${index}].`)).filter(o => o));
      }
    }
    return null;
  }).filter(o => o));
  return flatten(errorArr);
}

function flatten(arr) {
  return arr.reduce((flat, toFlatten) => flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten), []);
}
```

It takes an object like this:
```jsx
{
  users: [
    {
      name: undefined,
      email: undefined
    },
    {
      name: 'Name is too short',
      email: undefined
    },
    {
      name: undefined,
      email: 'Invalid email'
    }
  ]
}
```

And returns an array like this:
```jsx
['users[1].name', 'users[2].email']
```

I hope this helps

**Comment by tamerelsayed** [comment] 2017-02-10 08:40
Found this solution compatible with < V6 
https://statusok200.wordpress.com/2016/12/23/redux-forms-scroll-to-form-field-containing-error-message/

**Comment by enjoitheburger** [comment] 2017-03-01 23:38
I thought I would share a low-friction solution I came up with that may be of use to someone.

This is a generic function you can place in util file. It only requires that your inputs have the attribute `name` with the field name as the value.
``` Javascript
export function submitFailure(fieldList) {
    return (errors) => {
        // Field Error(s). We need to step through fieldList to guarantee ordering (since redux-form returns an errors object)
        fieldList.find((field) => {
            if (errors[field]) {
                const elem = document.querySelector(`input[name=${field}], select[name=${field}]`);
                if (!elem) {
                    // continue stepping through fieldList
                    return;
                }
                elem.focus();
                return true;
            }
        });
    }
}
```

Then your component can look like this:
``` Javascript
const fieldList = [
    'field1',
    'field2',
    'field3'
]

export default reduxForm({
    form: 'myForm',
    fields: fieldList,
    onSubmitFail: submitFailure(fieldList)
})(SimpleForm)
```

Not sure if it will help those taking advantage of the new `Field` component, but maybe it will help someone else!

**Comment by justin-hackin** [comment] 2017-03-15 21:16
My form values are not static as I have many forms being generated through a HOC so I reworked @enjoitheburger's solution to support nested error message object through recursion.

```
const scrollIntoView = require('scroll-into-view');

// adapted from code in https://github.com/erikras/redux-form/issues/1336
function onSubmitFail(errors) {
  const errorEls = [];
  const collectErrEls = function collectErrElsRec(fieldPrefix, target, errEls) {
    Object.keys(target).forEach((innerKey) => {
      if (typeof target[innerKey] === 'string') {
        const nameVal = `${fieldPrefix}${innerKey}`;
        const selectorStr = `input[name="${nameVal}"], select[name="${nameVal}"]`;
        const elem = document.querySelector(selectorStr);
        if (elem) { errEls.push(elem); }
      } else {
        const prefixPre = fieldPrefix === '' ? '' : `${fieldPrefix}.`;
        collectErrElsRec(`${prefixPre}${innerKey}.`, target[innerKey], errorEls);
      }
    });
  };

  collectErrEls('', errors, errorEls);
  const firstErrElement = errorEls.reduce((firstErrEl, errEl) => {
    if (firstErrEl === null || nodeBefore(errEl, firstErrEl)) {
      return errEl;
    }
    return firstErrEl;
  });

  if (firstErrElement) {
    scrollIntoView((firstErrElement.type === 'hidden') ? firstErrElement.parentElement : firstErrElement);
    return true;
  }
  return false;
}
```

**Comment by haroldcb** [comment] 2017-03-22 16:30
@justin-hackin, thank you for your answer, but could you give the code for the nodeBefore function please?
Thanks in advance

**Comment by efimweb** [comment] 2017-03-23 06:47
@haroldcb, `nodeBefore` can be implemented this way
```
function nodeBefore(errEl, firstErrEl) {
  return firstErrEl.compareDocumentPosition(errEl) === 2;
}
```

**Comment by piotrkosytorz** [comment] 2017-04-11 14:25
@igorbarbashin - good working solution, but unfortunately when trying to obtain elements from `document` I get an empty array (`scroller.scrollTo` uses `document.getElementById(name)` to obtain elements, and it returns always `[]`). What helped was getting the `offsetTop` value from the first element and passing it by to `animateScroll`. 

Here's the whole modified solution:

instead of `scroller`:
```es6
import { animateScroll } from 'react-scroll';
```
```es6
const scrollToFirstError = (errors) => {

    const errorFields = getErrorFieldNames(errors);
    // Using breakable for loop
    for (let i = 0; i < errorFields.length; i++) {
        const fieldName = `position-${errorFields[i]}`;
        // Checking if the marker exists in DOM
        const elements = document.querySelectorAll(`[name="${fieldName}"]`);
        if (elements.length) {
            animateScroll.scrollTo(elements[0].offsetTop - 50); // animate directly to the right position
            break;
        }
    }
}

const getErrorFieldNames = (obj, name = '') => {
    const errorArr = [];
    errorArr.push(Object.keys(obj).map((key) => {
        const next = obj[key];
        if (next) {
            if (typeof next === 'string') {
                return name + key;
            }
            // Keep looking
            if (next.map) {
                errorArr.push(next.map((item, index) => getErrorFieldNames(item, `${name}${key}[${index}].`)).filter(o => o));
            }
        }
        return null;
    }).filter(o => o));
    return flatten(errorArr);
}

const flatten = (arr) => {
    return arr.reduce((flat, toFlatten) => flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten), []);
}
```

and in the `reduxFrom` configuration:
```es6
onSubmitFail: (errors) => scrollToFirstError(errors)
```

Cheers!

**Comment by gustavohenke** [comment] 2017-08-25 20:35
Since this issue is very UI specific, it's not a concern of Redux Form, therefore I'm closing it.
It's also a duplicate of #2365.

Feel free to continue the discussion, though.

**Closed by gustavohenke** 2017-08-25 20:35 UTC
Labels: discussion

**Comment by I-O-O-I** [comment] 2018-12-14 08:16
Its much more easier...

`export default reduxForm({
    form: 'myForm',
    fields: fieldList,
    onSubmitFail: scrollToFirstError
})(SimpleForm)`

`export function scrollToFirstError(errors) {
  const firstError = Object.keys(errors)[0];
  const el = document.querySelector(`[name="${firstError}"]`);
  const position = el.getBoundingClientRect().top + document.documentElement.scrollTop;

  const offset = -200;

  window.scrollTo({ top: position - offset, behavior: 'smooth' });
}`

**Comment by ivangrga** [comment] 2019-01-23 13:11
Here is my solution for nested forms.

```javascript
function nextField(field, key, it) {
  if (!field) {
    return key;
  }

  if (Array.isArray(it)) {
    return field + "[" + key + "]";
  }
  return field + "." + key;
}

function getErrorElement(errors, field, it) {
  if (!(it instanceof Object)) {
    return document.getElementsByName(field)[0];
  }

  const key = Object.keys(it)[0];

  return getErrorElement(errors, nextField(field, key, it), it[key]);
}

function scrollIntoFirstError(errors) {
  const element = getErrorElement(errors, "", errors);

  if (element && element.scrollIntoView) {
    element.scrollIntoView({ block: "center" });

    return;
  }

  window.scroll(0, 0);
}
```

**Comment by maharjanaman** [comment] 2019-02-01 11:04
is there something like this for react native?

**Comment by blaisax** [comment] 2019-02-06 15:36
@I-O-O-I Love your answer due to its simplicity. I think there's a typo on offset as it should be positive (or shouldn't be substracted from position later), or you will scroll past the element.  

(Note: scroll behavior isn't supported by Edge and Safari).

**Comment by blaisax** [comment] 2019-02-06 15:41
@I-O-O-I Love your answer due to its simplicity. I think there's a typo on offset as it should be positive (or shouldn't be substracted from position later), or you will scroll past the element.

(Note: scroll behavior isn't supported by Edge and Safari).

**Comment by HarshaDW** [comment] 2020-08-21 05:13
After reading through manny forums found a really easy solution.

I use redux-form. Urgo mapped redux-from fieldToClass. Upon error I navigate to the first error on the list of syncErrors. 

**_No refs. No third party modules_**. Just simple **querySelector** & **scrollIntoView**

    handleToScroll = (field) => {

    const fieldToClass = {
      'vehicleIdentifier': 'VehicleIdentifier',
      'locationTags': 'LocationTags',
      'photos': 'dropzoneContainer',
      'description': 'DescriptionInput',
      'clientId': 'clientId',
      'driverLanguage': 'driverLanguage',
      'deliveryName': 'deliveryName',
      'deliveryPhone': 'deliveryPhone',
      "deliveryEmail": 'deliveryEmail',
      "pickupAndReturn": "PickupAndReturn",
      "payInCash": "payInCash",
    }

    document?.querySelector(`.${fieldToClasses[field]}`).scrollIntoView({ behavior: "smooth" })

**Comment by indidud** [comment] 2020-09-17 14:27
Updated @igorbarbashin solution to support nested errors. My structure looks like this:
```
const errors = {
  questions: [
    {
      options: {
        0: {
          title: 'Required',
        },
      },
    },
  ],
}
```
Here is the solution:
```
import isObject from 'lodash/isObject'
import { scroller } from 'react-scroll'

const getErrorFieldNames = (errors, name = '', resultArray = []) => {
  Object.keys(errors).forEach((k) => {
    const value = errors[k]
    if (typeof value === 'string') {
      resultArray.push(name + k)
    }
    if (isObject(value)) {
      Object.keys((value)).forEach((idx) => {
        const innerValue = value[idx]
        if (!innerValue) return
        const nextName = `${name + k}[${idx}].`
        getErrorFieldNames(innerValue, nextName, resultArray)
      })
    }
  })

  return resultArray
}

export function scrollToFirstError(errors) {
  const errorFields = getErrorFieldNames(errors)

  scroller.scrollTo(errorFields[0], { offset: -200, smooth: true })
}

```

Hope this will help

**Comment by alisajidcs** [comment] 2021-02-10 11:04
> I thought I would share a low-friction solution I came up with that may be of use to someone.
> 
> This is a generic function you can place in a util file. It only requires that your inputs have the attribute `name` with the field name as the value.
> 
> ```js
> export function submitFailure(fieldList) {
>     return (errors) => {
>         // Field Error(s). We need to step through fieldList to guarantee ordering (since redux-form returns an errors object, not array or map)
>         fieldList.find((field) => {
>             if (errors[field]) {
>                 const elem = document.querySelector(`input[name=${field}], select[name=${field}]`);
>                 if (elem) {
>                     elem.focus();
>                     return true;
>                 }
>             }
>             // continue stepping through fieldList
>             return false;
>         });
>     }
> }
> ```
> 
> Then your component can look like this:
> 
> ```js
> const fieldList = [
>     'field1',
>     'field2',
>     'field3'
> ]
> 
> export default reduxForm({
>     form: 'myForm',
>     fields: fieldList,
>     onSubmitFail: submitFailure(fieldList)
> })(SimpleForm)
> ```
> 
> Not sure if it will help those taking advantage of the new `<Field>` component, but maybe it will help someone else!

This Made my day. Love u... :bat:
#alisajidcs
