### ISSUE TITLE
[6.0.1] Ignoring the validation when you change the fields in the form

### ISSUE THREAD

**Issue by ViZhe** [erikras/redux-form#1631] opened 2016-08-26 17:00 UTC
This is a continuation issue #1528. The issue is relevant to version 6.0.1

Example: https://github.com/ViZhe/redux-form-issue
For start:

```
npm i
npm start
```

Open http://0.0.0.0:3000

**Following in the steps:**
1) When entering the form loads the template "A", resulting in `INITIALIZE` and `REGISTER_FIELD` for fields: "f1", "f2". These fields don't have validation, so when the submit event, I get `SET_SUBMIT_SUCCEEDED` - OK
2) I change the template to "B"
3) Form do `REGISTER_FIELD` for "f3", "f4" and "f5". "f3" is required, but on submit, i get `SET_SUBMIT_SUCCEEDED` - BAD, _because ignore validate for field "f3_
4) I change the template to "C"
5) The following actions occur:
- `INITIALIZE`
- `UNREGISTER_FIELD` for f1
- `REGISTER_FIELD` **for f3**
- `UNREGISTER_FIELD` for f2
- `REGISTER_FIELD` **for f5**
- `UNREGISTER_FIELD` **for f3**
- `REGISTER_FIELD` for f6
- `UNREGISTER_FIELD` for f4
- `UNREGISTER_FIELD` **for f5**
- `UPDATE_SYNC_ERRORS`

Let me know if you need more information.

**Comment by erikras** [comment] 2016-08-26 18:53
Well reported. So adding additional fields needs to `UPDATE_SYNC_ERRORS`. Will investigate... 🔍

**Comment by tan31989** [comment] 2016-09-21 09:34
Facing this problem over redux-form with validation. The first focus, will allow to enter the data into the field (only one character) and then the unregistered event gets triggered and gets registered again. 
Looses focus once the first letter is typed.

I have 7 fields, so at inital, 7 UNREGISTER_FIELD followed by REGISTER_FIELD

Logs from redux-logger:
```
action @ 15:01:11.457 redux-form/FOCUS 
action @ 15:01:11.932 redux-form/CHANGE 
action @ 15:01:11.978 redux-form/UPDATE_SYNC_ERRORS 
action @ 15:01:11.983 redux-form/UNREGISTER_FIELD 
action @ 15:01:11.988 redux-form/UNREGISTER_FIELD 
action @ 15:01:11.993 redux-form/UNREGISTER_FIELD 
action @ 15:01:11.998 redux-form/UNREGISTER_FIELD 
action @ 15:01:12.007 redux-form/UNREGISTER_FIELD 
action @ 15:01:12.013 redux-form/UNREGISTER_FIELD 
action @ 15:01:12.019 redux-form/UNREGISTER_FIELD 
action @ 15:01:12.029 redux-form/REGISTER_FIELD 
action @ 15:01:12.036 redux-form/REGISTER_FIELD 
action @ 15:01:12.052 redux-form/REGISTER_FIELD 
action @ 15:01:12.059 redux-form/REGISTER_FIELD 
action @ 15:01:12.069 redux-form/REGISTER_FIELD 
action @ 15:01:12.076 redux-form/REGISTER_FIELD 
action @ 15:01:12.083 redux-form/REGISTER_FIELD 
action @ 15:01:13.970 redux-form/FOCUS 
action @ 15:01:14.435 redux-form/CHANGE 
action @ 15:01:15.341 redux-form/CHANGE 
action @ 15:01:15.733 redux-form/CHANGE 
```

**Comment by tan31989** [comment] 2016-09-21 10:06
Got it fixed, I was using a class based form, once I used a function with return value, the input fields were retaining the focuses.

**Comment by sunnysingh** [comment] 2016-10-21 15:11
Had the same issue but fixed it thanks to @tan31989's comment, essentially moving my "renderField" into a method of the class. Even if this isn't considered a bug, it should be documented somewhere.

**Comment by danielrob** [comment] 2017-08-05 04:07
I think we should close this out as duplicate of (albeit duplicated by) #3276. Any complaints?

**Comment by gustavohenke** [comment] 2018-01-29 06:08
> Any complaints?

Doesn't sound like 😄

**Closed by gustavohenke** 2018-01-29 06:08 UTC
