### ISSUE TITLE
Input number errors on invalid character

### ISSUE THREAD

**Issue by RHavar** [erikras/redux-form#1382] opened 2016-07-21 21:27 UTC
Creating a form with:

`<input type="number" {...blah} />`

works fine, until a person types an invalid number  (e.g.  "133e" ), when they hit the `e` the browser returns:

```
The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
DOMPropertyOperations.js?930e:140 The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
```

And the field gets cleared to ""

**Comment by RHavar** [comment] 2016-07-21 22:02
Trying with 6.0.0-rc.3,  typing  "133" in an input works, and then when you hit "e" it will clear it too

**Comment by burtyish** [comment] 2016-07-26 13:38
I get the same behavior.
The value stored in the redux state is `NaN`.

(react-redux v5.3.1)

**Comment by staab** [comment] 2016-08-10 18:48
I get the same thing on 5.3.1. When I keep typing after I get NaN, it gives me the following error:
```
Error: A state mutation was detected between dispatches, in the path `form.StoreSettingsForm.salesTax.value`. This may cause incorrect behavior. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)
```

**Comment by staab** [comment] 2016-08-16 18:03
The issue behind this is that either React's or redux-form's validation appears to be at odds with browser validation of number inputs, and doesn't respond well when the browser parses invalid numbers and changes the field. This is contrary redux's assumptions that things won't change. It seems to me that redux should relax the immutability requirement when the input is of a kind that has built-in browser validation, although I guess that's not something redux-form has access to in the first place.

My current workaround is to add my own validation function that duplicates browser parsing functionality, but implements the change by passing the new value to the `onChange` function. This is a pain, because there's no guarantee my code is right, as parsing floats is a pretty subjective matter as far as what is valid. Here's some code:

```
const parseFloatString = (value, fallback="0") => {
  value = value.replace(parseFloatString.DOT_REGEXP, '.').trim()

  // Empty strings are not floats
  const isFloat = value && value.search(parseFloatString.FLOAT_REGEXP) !== -1

  return isFloat ? value : fallback
}

parseFloatString.DOT_REGEXP = new RegExp(/\.+/)
parseFloatString.FLOAT_REGEXP = new RegExp(/^\d*\.?\d*$/)

// Return some jsx
<input type="number" min=0 {...field} onChange={evt => field.onChange(parseFloatString(evt.target.value))} />
```

I just whipped this up, so I'm sure there are bugs, but it's a start.

**Comment by jeremy-putt** [comment] 2016-09-14 02:20
Internally, redux form will call `parseFloat(value)` on all inputs of type number or range:

```
// V5
if (type === 'number' || type === 'range') {
      return parseFloat(value);
    }
```

When you have no value, i.e. you tab over the field, you end up calling `parseFloat('')` which returns `NaN`.

And on checking out the getValue.js code in version six, it looks like this has been resolved, just not applied to version five.

```
// V6
if (value !== '' && (type === 'number' || type === 'range')) {
      return parseFloat(value)
    }
```

**Comment by jchiellini** [comment] 2016-09-19 17:11
Has any progress been made on this issue? I am using Version 6.0.0-rc.4. It still seems to be occurring. Just as described above. I have an input with the type set to 'number'. Typing '123e' will result in the fields value being invalid and clearing the form's field. Is there any chance we can get a redux form fix for this?

**Comment by jeremy-putt** [comment] 2016-09-20 00:58
Interestingly, 'e' is a mathematical constant and a valid value for an input field. 
I have a form running 5.3.[something] and putting in 'e' will work, e.g. 123e = 1234, 2e2 = 200.

If you look at the form example here: http://redux-form.com/6.0.5/examples/syncValidation/
The number control does exactly what you describe. But the validation here is the problem:

```
else if (isNaN(Number(values.age))) { <----- this guy..
    errors.age = 'Must be a number'
  }
```

`Number(123e) --> NaN`
`parseFloat('123e') --> 123`

`Number(123e2) --> 12300`
`parseFloat('123e2') --> 12300`

According to the Number function, it is only valid if a number comes after 'e' but redux-form validates after every key press so this validation doesn't let the number get to a valid state.

You may need to re-jig your validation?

Does any of this help? :)

**Comment by jchiellini** [comment] 2016-09-21 14:04
Sadly, I'm not even validating the field like that. So there is nothing for me to tinker around with. I was relying on the number type on the input to get the job done.

**Comment by dmt0** [comment] 2016-11-03 14:40
On version 5.3.2, I actually can't enter '-' into the field, getting this message:

`bundle.js:201505 The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`

The regex says basically that there has to be a number after the minus. When I enter the number first and than left arrow back and put a minus, things work. But I can't start with the minus.

**Comment by Masterchoc** [comment] 2017-02-26 10:33
@dmt0 I got the same exact issue when i want to try this on input of type numbers.
For example, set the step attribute with a comma, and then try to edit and type : 0.01.
I tried to change the regex of the input with the "pattern" attribute, but it doesn't seems to work :(

**Comment by danielrob** [comment] 2017-07-28 14:14
Still reproducible on 7.0.3.

**Comment by gustavohenke** [comment] 2017-12-06 23:26
Because this issue saw almost no activity for a few months, I'm closing it.

**Closed by gustavohenke** 2017-12-06 23:26 UTC
Labels: bug
