### ISSUE TITLE
Validation breaks after unmounting of a duplicated field

### ISSUE THREAD

**Issue by jedrzej-bridgemaker** [erikras/redux-form#3688] opened 2017-12-13 11:26 UTC
### Are you submitting a **bug report** or a **feature request**?
This is a bug.

### What is the current behavior?
When two fields for the same form value are rendered, then one of these fields is unmounted, validation stops to work.
For the provided sandbox:
1. check that the validation is working for the field
2. add another field (+ button) - validation is still working
3. remove a field (- button) - validation is broken

In a more real-world scenario it occured to me when a part of the form was being re-rendered in a different branch of the DOM tree - 'new' fields get registered before old ones get unregistered, causing the error to occur.

### What is the expected behavior?
Validation should work if there's a field rendered that requires it

### Sandbox Link
https://www.webpackbin.com/bins/-L0ES7_aTU4kA-O9gsgc

### What's your environment?
react 16,
redux-form 7.2.0

### Other information
Probably need to check the count of the fields before removing the validators?
https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L585

**Comment by jedwards1211** [comment] 2018-01-15 16:55
This is happening to me too due to animation.  I have an animated transition in a wizard form between steps for entering single values and a final step where the user can review the entered values in a table. during the transition between the final step and the table, a duplicate of the field mounts before the field from the final step unmounts.

**Closed** 2018-01-16 15:44 UTC

**Comment by erikras** [comment] 2018-01-18 17:05
Published fix in [`v7.2.1`](https://github.com/erikras/redux-form/releases/tag/v7.2.1).
