### ISSUE TITLE
[v5.3.2] Mismatch between store and render when using removeField()

### ISSUE THREAD

**Issue by alextaylor000** [erikras/redux-form#1518] opened 2016-08-11 17:05 UTC
Hi,
Thanks for all your work on this library! I'm attempting to debug the following issue when using `removeField`, which can be reproduced in the Deep Form example (GIF below):
1. Add a field and enter input
2. Add another field but leave its inputs blank
3. Remove the first field
4. It will appear as if the second field was removed, and the first field remains with its text. However, as soon as you enter one of the first fields, the values will disappear.

This seems to happen in 5.3.2 as well.

![redux_form_bug](https://cloud.githubusercontent.com/assets/7259082/17597511/f6de5bf0-5faa-11e6-87cc-c1c1dda294e1.gif)

From what I can tell, the store is getting updated correctly, but the props passed down to the component remain incorrect until one of the fields is entered.

**Comment by naw** [comment] 2016-08-11 17:17
This is the kind of behavior you get in react when you have sibling elements who don't have a `key` , or when you use index as the key.  react needs a way to distinguish the elements so it knows which one to remove. Removing the first one means the second one actually gets reassigned to the 0th index, which means react "thinks" it was the 2nd one that was removed.  

The solution is _not_ to use `index` as the `key` prop.

**Comment by alextaylor000** [comment] 2016-08-11 19:40
@naw I thought that was the case at first, although I believe it's deeper than that.

I logged the incoming props in `componentWillReceiveProps`, and after the field has been deleted, the props being passed down from the store don't actually match what's in the store until one of the fields is entered. I'll try to post an example of it later. It may be a similar issue, however, since the fields are stored by index in the store as well (so the `1th` field becomes the `0th` field after the `0th` field is deleted).

**Comment by naw** [comment] 2016-08-11 22:58
@alextaylor000  Yes, I stand corrected. it _is_ an issue with redux-form not overriding the original 0th child with the (undefined) values of the new 0th child.  Since the fields for the new 0th child have not yet been visited, the store doesn't have keys for those fields. redux-form then uses the previous 0th child's values for those keys.  In essence, redux-form is merging the new 0th child's values into the old 0th child's values, which means you can actually get a mismatch of values from the old or new, depending on which particular subfields you've visited on the child.

Here is the code in question:

https://github.com/erikras/redux-form/blob/bd1cecfa6b8b8e16d909a9b61df1a86ce3f99e21/src/readField.js#L149

I would agree this is unexpected behavior.

**Comment by danielrob** [comment] 2017-07-31 20:07
Closing with bulk close of v5 issues. If this issue still requires action and/or also affects v6/7, please request a reopen with details or raise a new issue. v5 PR's are still welcomed.

**Closed by danielrob** 2017-07-31 20:07 UTC
