### ISSUE TITLE
Feature request: `Fields` component validate prop

### ISSUE THREAD

**Issue by scottdickerson** [erikras/redux-form#3809] opened 2018-02-02 16:45 UTC
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

It would be nice for the Fields component to support a validate prop like the Field component to allow me to associate an array of validation functions.

### What is the expected behavior?
See the Field component for an example of Field-level validation support.

**Comment by CGamesPlay** [comment] 2018-03-14 00:40
To extend this a bit, Fields doesn't support `validate`, `warn`, or `normalize`. It looks like `normalize` is being replaced by `parse`/`format`, which I would also love to see support an identical API to this proposal:

```
<Fields
  names={[ 'a', 'b' ]}
  component={MyComponent}
  validate={{
    a: [ validateRequired, validateA ],
  }}
  normalize={{
    b: normalizeB,
  }}
/>
```

Specifically, the keys in the `validate`/`warn`/`normalize`/`parse`/`format` prop passed to `Fields` correspond to field names and work identically to the same-named prop on the `Field` element.

As an aside, it seems likely that https://github.com/erikras/redux-form/blob/master/src/createFields.js#L47 is a bug because it is missing a call to `prefixName(context, name)`. I don't know the significance of this, I just saw it in the code.

**Comment by danielrob** [comment] 2018-05-05 12:49
Closing as a duplicate of #3492, notify if I'm mistaken.

**Closed by danielrob** 2018-05-05 12:49 UTC
