### ISSUE TITLE
Uncontrolled input warning when using React 15

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#735] opened 2016-03-14 06:35 UTC
Same as [this issue](https://github.com/erikras/redux-form/issues/703).

Since the fix was reverted, is there a way, we can fix this to remove the warning ?

**Comment by erikras** [comment] 2016-03-14 15:29
As I understand it, something like this should fix it. Please confirm:

Change
```js
<input {...this.props.fields.firstName}/>
```
to
```js
<input {...this.props.fields.firstName} value={this.props.fields.firstName.value || ''}/>
```

**Comment by VladShcherbin** [comment] 2016-03-14 16:03
So, when I use

```jsx
<input {...fields.priority} value={fields.priority.value || ''}/>
```

there are no warnings. But, when I set _initial value_:

```js
export default reduxForm({
  form: 'citiesForm',
  fields,
  initialValues: {
    priority: 1
  }
})(CitiesForm)
```

it gives the warning: 
```terminal
Warning: Input elements must be either controlled or uncontrolled (specify
either the value prop, or the defaultValue prop, but not both). Decide between
using a controlled or uncontrolled input element and remove one of these props. 
More info: https://fb.me/react-controlled-components
```

**Comment by erikras** [comment] 2016-03-14 17:26
Thanks for that. :+1:

All `redux-form` inputs should be __controlled__, so I think that means that we need to never set `defaultValue` or `defaultChecked`, as those are only props for __uncontrolled__ components.

**Comment by erikras** [comment] 2016-03-14 17:28
Can you also confirm that the problem goes away (aside from the `defaultValue` warning) with `v4.2.1`?

**Comment by VladShcherbin** [comment] 2016-03-14 18:00
Okay, I double checked, here are the results with 4.2.1

```jsx
<input {...fields.priority} value={fields.priority.value || ''} />
// or
<input {...fields.priority} value="hey" />
// or
<input {...fields.priority} />
```
No initialValues - no warnings
With initialValues - 3 warnings, same as with  4.2.2

**Comment by VladShcherbin** [comment] 2016-03-14 19:06
@erikras Here is a quick [sandbox repo](https://github.com/VladShcherbin/redux-form-test), version is 4.2.1. The [form element](https://github.com/VladShcherbin/redux-form-test/blob/master/src/Form.js) to change.

**Comment by rasmuswoelk** [comment] 2016-04-05 17:03
I'm also experiencing this issue. My form is working even though the error in console. Would be great with a fix. Love this library by the way :+1:

**Comment by erikras** [comment] 2016-04-08 16:35
React v15 support released with [`redux-form v5.0.0`](https://github.com/erikras/redux-form/releases/tag/v5.0.0).

**Comment by tiagoengel** [comment] 2016-04-08 17:27
Is this supposed to solve the problem with initialValues too? 'Cause I'm testing with v5.0.0 and I'm still getting the same warning when using initialValues

**Comment by erikras** [comment] 2016-04-08 17:34
@tiagoengel No.

**Comment by Aman725** [comment] 2016-04-15 15:00
+1

**Comment by ooflorent** [comment] 2016-04-28 12:57
What's the state of this issue? I can no longer reproduce it.

**Comment by VladShcherbin** [comment] 2016-04-29 21:11
@ooflorent I'm using v6 and there is no error.

Can someone using v5 (as it is a current stable version) confirm there is also no error so we can close this?

**Comment by rafaelsales** [comment] 2016-04-30 06:58
@VladShcherbin I do have the same warning in 5.2.1 and 5.2.3 when value is `null`. Making it `undefined` or `''`  solves the warning, but I really don't want to write a "normalizer" to convert `null => undefined` when rendering response from my API into a form...

**Comment by ooflorent** [comment] 2016-04-30 13:16
I have a big application (more than 50 forms) using Redux Form 5.2.3 and React 15 and there is no warning about uncontrolled inputs...

@rafaelsales could you setup a simple JSBin to reproduce the issue?

**Comment by tiagoengel** [comment] 2016-04-30 17:34
I tested with v5.2.3 and there's no more warnings about uncontrolled inputs, works even with initialValues.

**Comment by rafaelsales** [comment] 2016-04-30 17:37
I think we're talking about different scenarios. My one happens when I set
a field value as null in the initializeForm - it's how I populate the form
from API response. I'll try to setup an example that shows the warning in
5.2.3

On Saturday, April 30, 2016, Tiago Henrique Engel <notifications@github.com>
wrote:

> I tested with v5.2.3 and there's no more warnings about uncontrolled
> inputs, works even with initialValues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/735#issuecomment-215982665>
>


-- 
*Rafael Sales*

**Comment by rafaelsales** [comment] 2016-05-01 05:24
@tiagoengel Here we go: http://jsbin.com/tuzubu/edit?js,console,output

If you replace `email: null` by `email: undefined`, the warning is gone.

**Comment by erikras** [comment] 2016-05-01 08:12
So the conclusion is that `null` should be treated the same as `undefined` when defaulting to `''`?

**Comment by tiagoengel** [comment] 2016-05-01 13:35
@erikras I think so. See [this](https://github.com/facebook/react/issues/2533) React thread. TLDR, undef/null always means an uncontrolled input, so I think for redux-form these values should always defaults to an empty string.

**Comment by Skhoshhal** [comment] 2016-10-13 07:40
I have the same problem when I checked the checkbox my code is like so: 
<input
                                type="checkbox" className="mdl-checkbox__input"
                                checked={self.state.filterValues[col] &&
                                    self.state.filterValues[col][termString(bindings.resource)]}
                                onChange={self.onFilterChange.bind(null, {binding: col, value: bindings.resource})}
                            />

the warning is:

warning.js:36 Warning: ResourceList is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components.

**Comment by iyn** [comment] 2016-10-27 12:09
@Skhoshhal I think that the problem is when you don't have default value set for the checkbox, so the undefined/null value is passed and React assumes uncontrolled input. You can either set default/initial value or pass `false` when the field is not checked (but this may depend on your business logic). Related: https://github.com/erikras/redux-form/issues/1993

**Comment by saisgs** [comment] 2017-02-16 16:11
I am getting this warning..
any one have any idea how to fix this?
Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.

**Comment by estermer** [comment] 2017-04-07 14:06
Anyone seeing this warning on a checkbox input?

I posted a question about my problem here on [StackOverflow](http://stackoverflow.com/questions/43280134/reduxform-v5-3-1-uncontrolled-controlled-warning-on-checkbox)

**Comment by jdelafon** [comment] 2017-05-22 12:07
@estermer I had it and it was because the `checked` attribute could be null or undefined, so it was interpreted as uncontrolled. As soon as I added `!!` like this it worked fine:

    checked = {!!this.state.checked}

It is probably the same with the `value` attribute.

**Comment by danielrob** [comment] 2017-07-24 17:47
As there are no reports of this in v6/7, I'm closing this issue. PR's for v5 are welcome.

**Closed by danielrob** 2017-07-24 17:47 UTC
Labels: bug
