### ISSUE TITLE
Toggle not working correctly since v6.7.0

### ISSUE THREAD

**Issue by mlarcher** [erikras/redux-form#3148] opened 2017-07-04 12:36 UTC
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
When switching a Toggle component to turn it off, the validation fails because the returned value is not a boolean.

### code sample
```javascript
import React, { Component, PropTypes }      from 'react'
import { reduxForm, Field }     from 'redux-form'
import { Toggle }                from 'redux-form-material-ui'
import Joi from 'joi-browser'

class MyForm extends Component {
    render() {
        return (
            <Field
                name="mySwitch"
                component={Toggle}
            />
        )
    }
}

export default reduxForm({
    form:     'myForm',
    validate: validate(Joi.object().keys({
        mySwitch:       Joi.boolean().label('My switchl').default(false)
    }), { allowUnknown: true }),
})(MyForm)
```
### What is the expected behavior?
The value of the Toggle should be `false` and let validation of a boolean type work as exepected.

### What's your environment?
"redux-form": "6.7.0",
"redux-form-material-ui": "4.2.0",
"material-ui": "0.18.4",
"joi-browser": "9.1.0",
linux, 
chrome 59,
node v7

### Other information
Our code was working fine up to v6.6.3, and broke with v6.7.0

**Comment by erikras** [comment] 2017-07-04 13:22
This sounds like it will be fixed by #3081 in `v7.0.0`, which is coming soon.

**Comment by mlarcher** [comment] 2017-07-04 15:40
Might be :)
Shouldn't it be fixed in the v6.x.x too in order to preserve semver compatibility, as 6.7 introduced a non retro-compatible change ?

**Comment by danielrob** [comment] 2017-07-25 04:35
Closing this as a duplicate of #3162, though the most heated discussion continues in #2857.

**Closed by danielrob** 2017-07-25 04:35 UTC
