### ISSUE TITLE
Support for nested fields.

### ISSUE THREAD

**Issue by asaf** [erikras/redux-form#55] opened 2015-09-06 13:38 UTC
Hey,

I was wondering how hard it would be to support nested forms,

Something like react-form's `children` section:

http://prometheusresearch.github.io/react-forms/examples/family-editor.html

Thanks.

**Comment by erikras** [comment] 2015-09-07 14:29
The answer I've been giving to this question is that your form value _could_ be an array of other information, and you could handle mutating that array yourself before calling `handleBlur` or `handleChange`. But you're not going to get all the `dirty`/`visited`/`touched` flags for each of those sub-form inputs, so it remains a little hacky.

Another alternative would be to make each subform a separate form, e.g. `form: 'profile.children', formKey: '0'`, and merge all the form data later on submit.

If there's an elegant way to do arbitrary nesting, I haven't thought of it yet.

**Comment by vincentfretin** [comment] 2015-09-12 11:20
I'm trying to implement dynamic nested forms. So far, the solution I took is to have a separate form for each subform with formKey being:

    formKey={ formKey + '[' + field.name + '][' + String(idx) + ']' }

have my own getValues that normalize the form from this:

    form:
      _submitting: true
      Lieu:
        value: 'Lille'
    form.etablissements.0:
      _active: false
      organisme:
        value: 3

To:

    form[Lieu]: 'Lille'
    form[etablissements][0][organisme]: 3

and then using toObj function from form-data-to-object package (come initially from formsy-react) to have a nested structure like this:

    form:
      Lieu: 'Lille',
      etablissements: [{
          organisme: 3}]

Here is some code I'm currently using:
```javascript
    import { toObj } from 'form-data-to-object'

    function createStoreShape() {  // there is no way to import it from redux
      return PropTypes.shape({
        subscribe: PropTypes.func.isRequired,
        dispatch: PropTypes.func.isRequired,
        getState: PropTypes.func.isRequired
      })
    }

    const storeShape = createStoreShape(PropTypes)

    function getValues(form, fieldsInfo) {
      const values = Object.keys(form).reduce((accumulator, formKey) =>
        ({ ...accumulator,
           ...Object.keys(form[formKey]).reduce((acc, fieldName) => {
             return fieldName[0] === '_' || (fieldsInfo[fieldName] && fieldsInfo[fieldName].type === 'List') ? acc : {
               ...acc,
               [formKey + '[' + fieldName + ']']: form[formKey][fieldName].value
             }
           }, {})
         }
        ), {})
      return values
    }

    class Form extends Component {
      static propTypes = {
        dispatch: PropTypes.func.isRequired,
        fields: PropTypes.object.isRequired,
        fieldsInfo: PropTypes.object.isRequired,
        formKey: PropTypes.string.isRequired,
        handleSubmit: PropTypes.func.isRequired,
        onSubmit: PropTypes.func.isRequired,
        prefix: PropTypes.string.isRequired, // this is actually formName
        values: PropTypes.object.isRequired,
        submitting: PropTypes.bool.isRequired,
      }

      static contextTypes = {
        store: storeShape
      }

      constructor(props, context) {
        super(props, context)
        this.store = context.store
      }

      onSubmit() {
        const form = this.store.getState().form[this.props.prefix]
        let values = getValues(form, this.props.fieldsInfo)
        values = toObj(values)
        this.props.onSubmit(values)
      }

      render() {
        const { fields, prefix, formKey, fieldsInfo, handleSubmit } = this.props  // passed in by redux-form

        return (
          <form onSubmit={ handleSubmit(this.onSubmit.bind(this)) } method="post">
            <div>
              { Object.keys(fields).map(fieldName =>
                <Field
                  formName={ prefix } formKey={ formKey }
                  key={ fieldName } field={ fields[fieldName] }
                  fieldInfo={ fieldsInfo[fieldName] }
                />)
              }
              <div className="formControls">
                <input
                  id="form-buttons-save"
                  name="form.buttons.save"
                  value="Save"
                  type="submit"
                  disabled={ this.props.submitting }
                />
              </div>
            </div>
          </form>
        )
      }
    }

    export default class DynamicForm extends Component {
      static propTypes = {
        formName: PropTypes.string,
        formKey: PropTypes.string,
        fieldsInfo: PropTypes.object.isRequired,
        onSubmit: PropTypes.func.isRequired,
      }

      static defaultProps = {
        formName: 'form',
        formKey: 'form',
      }

      render() {
        const {
          formName, formKey, fieldsInfo, onSubmit,
         } = this.props
        const fieldsNeeded = Object.keys(fieldsInfo)

        // connect Form to Redux and decorate with redux-form
        const params = { form: formName,
                         formKey: formKey,
                         fields: fieldsNeeded,
                       }
        const DecoratedForm = connectReduxForm(params)(Form)

        // render connected and decorated form
        // we can't use formName prop, it's not given to the composed Form
        return (
          <DecoratedForm
            fieldsInfo={ fieldsInfo }
            onSubmit={ onSubmit }
            prefix={ formName }
            formKey={ formKey }
          />
        )
      }
    }
```
In Field component, if fieldInfo.type === 'List', I generate a dynamic connected reduxForm with a specific formKey (lots of additional code I didn't paste here).

I had a real performance issue where I had a 1sec hang each time I typed a character. I fixed it by writing my own shouldComponentUpdate, see the code here: https://github.com/erikras/redux-form/issues/61#issuecomment-139747712

@erikras can you expose formName too here https://github.com/erikras/redux-form/blob/2c53243631930d38dcc6b16d2b18a0b90326132d/src/reduxForm.js#L258 like you do for formKey ? I had to use another prop name (prefix is the code above) to get the formName

**Comment by idolize** [comment] 2015-09-12 23:06
+1 this would be extremely useful. Basically the only reason I'm not using the library right now.

**Comment by asaf** [comment] 2015-09-14 14:17
@erikras 
I think we can come up with something, without making the API more complicated (well, nesting is complex by nature but we can reduce complexity in case user just wants a flat form),

What if every field has a path, with a separator such: `a.b.c`, for flat forms, this stays the same.

Then, in the reducer, instead of merging the new field by [key]: value, we can use [setIn](https://facebook.github.io/immutable-js/docs/#/Map/setIn) (or in this lib case we'll just have to come up with an equivalent method)

It's up to the form to provide the correct field names.

Nothing changes and we earn nesting for free :-)

I haven't read every line of code so I may be wrong, let me know if I am missing anything,


Related:
https://github.com/erikras/redux-form/issues/21

**Comment by erikras** [comment] 2015-09-14 14:19
Yes, i've been thinking about some sort of dot notation like that. Sounds possible.

**Comment by asaf** [comment] 2015-09-14 14:50
Ok, ill give it a shot!

**Comment by ntucker** [comment] 2015-09-16 01:13
For inspiration: https://github.com/christianalfoni/formsy-react/issues/120

Basically they ended up doing something like name="patient[addresses_attributes][0][id]"

Seems like a decent idea

**Comment by bdefore** [comment] 2015-09-30 14:46
+1 for this feature

**Comment by maarekj** [comment] 2015-10-19 21:13
+1 for this feature

**Comment by dbrans** [comment] 2015-10-20 22:05
+1

**Comment by erikras** [comment] 2015-10-20 22:26
Does anyone know a good "dot notation" library? I mean something like this:
```js
const order = {
  client: {
    name: 'Whatever',
    billing: {
      street: '123 Main St.',
      city: 'Anytown'
    },
    shipping: {
      street: '566 Downtown Ave.',
      city: 'Big City'
    },
    phone: '555-555-555'
  };
const {get, set} = dotNotation('client.billing.street');

const billingStreet = get(account); // 123 Main St.
set(account, '998 Some Other Dr.'); // sets the value deep in account
```

**Comment by dbrans** [comment] 2015-10-20 22:28
@erikras lodash get/set? https://lodash.com/docs#get

**Comment by erikras** [comment] 2015-10-20 22:33
@dbrans Yep, that's what I want. Thanks. I thought the ES6 functional stuff had obsoleted lodash, but apparently not.

**Comment by yesmeck** [comment] 2015-10-25 15:59
I'm wondering can we generate field dynamically, so that the API can more simple and support nested fields can more easily.

```javascript
import React, { Component } from 'react';
import { connectReduxForm } from 'redux-form';

@connectReduxForm({
  form: 'user'
})
class UserForm extends Component {
  static propTypes = {
    field: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired
  }

  saveForm(data) {
    // data will be like:
    // {
    //   name: 'Whatever',
    //   billing: {
    //     street: '123 Main St.',
    //     city: 'Anytown'
    //   },
    //   shipping: {
    //     street: '566 Downtown Ave.',
    //     city: 'Big City'
    //   },
    //   phone: '555-555-555'
    // }
  }

  render() {
    const { field } = this.props

    return (
      <form onSubmit={handleSubmit(this.saveForm)}>
        <label>Name</label>
        <inputtype="text" field('name')  />

        <label>Billing Street</label>
        <input type="text" field('billing.street')  />

        <label>Billing City</label>
        <input type="text" field('billing.city')  />

        <label>Shipping Street</label>
        <input type="text" field('shipping.street')  />

        <label>Shipping City</label>
        <input type="text" field('shipping.city')  />

        <label>Phone</label>
        <inputtype="text" field('phone')  />

        <button type="submit">Save</button>
      </form>
    );
  }
}
```

**Comment by erikras** [comment] 2015-10-26 02:21
That's very interesting, @yesmeck. It would still need to keep an array of the fields it knows about to be able to "touch" them all on submit. And it simplifies the API nicely.

**Comment by yesmeck** [comment] 2015-10-26 10:00
@erikras I implement this on my fork based on 2.4.5 https://github.com/erikras/redux-form/compare/master...yesmeck:dynamic-fields, and I just see that you released 3.0.0-beta, do you like this idea? If yes, will you implement it on 3.0? Maybe I can help.

**Comment by erikras** [comment] 2015-10-26 10:58
I'm not sure. One of the big moves in v3.0 was to cache all the field objects, only regenerating them if the `fields` array changes. Generating them on the fly on every render was causing performance issues, yet your design will go back to generating them on the fly again. Perhaps if they were cached? I'm undecided as to whether or not your API is superior.

**Comment by yesmeck** [comment] 2015-10-26 15:03
Ok, how about this https://github.com/erikras/redux-form/compare/master...yesmeck:nested-fields, just allow declare fields by path, so that we can write nested fileds like this.

```javascript
import React, { Component } from 'react';
import { connectReduxForm } from 'redux-form';

@connectReduxForm({
  form: 'user',
  fields: ['name', 'billing.street', 'billing.city', 'shipping.street', 'shipping.city', 'phone']
})
class UserForm extends Component {
  static propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired
  }

  saveForm(data) {
    // data will be like:
    // {
    //   name: 'Whatever',
    //   billing: {
    //     street: '123 Main St.',
    //     city: 'Anytown'
    //   },
    //   shipping: {
    //     street: '566 Downtown Ave.',
    //     city: 'Big City'
    //   },
    //   phone: '555-555-555'
    // }
  }

  render() {
    const { fields } = this.props

    return (
      <form onSubmit={handleSubmit(this.saveForm)}>
        <label>Name</label>
        <input type="text" {...fields['name']}  />

        <label>Billing Street</label>
        <input type="text"  {...fields['billing.street']} />

        <label>Billing City</label>
        <input type="text" {...fields['billing.city']}  />

        <label>Shipping Street</label>
        <input type="text" {...fields['shipping.street']}  />

        <label>Shipping City</label>
        <input type="text" {...fields['shipping.city']}  />

        <label>Phone</label>
        <input type="text" {...fields['phone']}  />

        <button type="submit">Save</button>
      </form>
    );
  }
}
```
It's still easy to implement and backward compatible.

**Comment by erikras** [comment] 2015-10-26 15:42
Nice. So they could still live under `shipping.name` keys in the reducer, but the thing producing the `values` structure and [receiving errors](https://github.com/erikras/redux-form/blob/master/src/readFields.js#L58) (you forgot that part) would need to know how to convert to and from a deep tree structure. I'm liking this.

It's nested _fields_, not nested _forms_, which some people are asking for, but your billing and shipping inputs could share a common "address" component that just knew how to prefix your fields.

If you add some tests, I'd be very interested in a PR.

**Comment by ingro** [comment] 2015-10-26 17:11
Looking forward to this, actually I'm using a solution based on what @ntucker suggested, using [form-data-to-object](https://github.com/christianalfoni/form-data-to-object) and field names like `proposals[0][price]`, the problem is that I have to manually convert from and to object while initializing and while submitting the form, so an automated way would be better. I can help to test if you need it.

**Comment by yesmeck** [comment] 2015-10-27 08:56
@erikras After implement nest fields, nested forms can be implement by wrting a HOC form, example: https://github.com/yesmeck/redux-form/blob/gh-pages/src/examples/HighOrderNestedForm.js and https://github.com/yesmeck/redux-form/blob/gh-pages/src/examples/NestedForm.js

**Comment by asaf** [comment] 2015-10-28 13:47
Can we come up into some draft ?

@erikras Are you okay with the approach of @yesmeck implementation ?
+1 for this approach (I suggested it from the first place) as it doesn't break none nested fields.

Thanks.

**Comment by TossShinHwa** [comment] 2015-10-30 03:07
@yesmeck, Great.

But in your solution, how to resolve it if fields have a array-object?

**Comment by yesmeck** [comment] 2015-10-30 03:29
@TossShinHwa Check this example https://github.com/yesmeck/redux-form/blob/gh-pages/src/examples/HighOrderNestedForm.js#L67-L70 https://github.com/yesmeck/redux-form/blob/gh-pages/src/examples/NestedForm.js#L55-L77

**Comment by asaf** [comment] 2015-10-30 11:32
@erikras I would really love to see this merged, how can we make this happen? new test available and all existing tests pass just fine.

**Comment by bdefore** [comment] 2015-11-02 20:36
I'd like to see this merged as well. Currently @yesmeck 's branch is forked off of 3.0.0-beta4, which means those on 2.x won't be able to drop in without updating to the new API. Mine, for example, failed since `TypeError: _reduxForm.connectReduxForm is not a function` ... but a quick rename of all `connectReduxForm` to `reduxForm` fixed that.

**Comment by jnarowski** [comment] 2015-11-04 18:51
+1 for nested fields!

**Comment by morgante** [comment] 2015-11-06 09:43
+1, this functionality will make this library much more useful.

**Comment by rogeriochaves** [comment] 2015-11-06 13:01
+1, I'm only waiting for this to use

**Comment by olimsaidov** [comment] 2015-11-06 13:33
+1

**Comment by asaf** [comment] 2015-11-07 12:04
@erikras This blocks us all and we hate forks :-)
Please, just give your comment about this so we can plan accordingly.

Thanks!

**Comment by erikras** [comment] 2015-11-07 16:43
I plan on looking into this and implementing something (maybe this exact implementation) over the next two weeks.

**Comment by jpierson** [comment] 2015-11-10 21:48
I have a situation where I would like to separate a progressive disclosure section of a form that has it's own separate _save_ button into a separate React component using redux-form. The original outer form is part of a different larger flow that really deserves it's own form and submit button. Regardless of the design principles what I'm running into is that it would be nice to have some way of handling nested forms. I'm curious if any of the changes discussed here or elsewhere would allow for a way of handling cases like this. I've noticed some other react related libraries out there with nested forms being discussed like [formsy-react](https://github.com/christianalfoni/formsy-react) but it's not clear well if at all these solutions would work with redux/redux-form.

**Comment by slybridges** [comment] 2015-11-19 17:28
If I may also +1ify this one :-)

**Comment by slybridges** [comment] 2015-11-24 09:11
I tried  @yesmeck's fork using branch `nested-fields-npm` and it works great when using a static array of nested fields (:+1: @yesmeck). 

However I haven't found a way to use it when the array size is dynamic and depending on the user input.

For example, I'd like to be able to work with something like this, where the number of `stops` is dynamic (the user can add and remove them):

```javascript
@reduxForm(
  { form: 'trip',
    fields: [
      'transport',
      'travelers',
      'stops[?].location',      // <- number of stops depends on user input
      'stops[?].arrivalDate',
      'stops[?].departureDate'
   ], 
   validate: validateTrip
})
```
Then, I would like to be able to use for instance:
```javascript
<input type="text"  {...fields[`stops[5].location`} />
```
...and if the field is `undefined`, to dynamically initialize it with `redux-form` attributes and methods

Does anybody has a solution for that kind of use case ?

**Comment by erikras** [comment] 2015-11-24 11:03
That is very similar to the API I'm working on at the moment, @slybridges. It might be another week, though.

**Comment by slybridges** [comment] 2015-11-24 13:23
Awesome, thanks @erikras ! Happy to help test the beast once there.

**Comment by yesmeck** [comment] 2015-11-24 15:21
@slybridges You can generate these fields [dynamically](http://erikras.github.io/redux-form/#/examples/dynamic?_k=vdabg7).

**Comment by tomduncalf** [comment] 2015-11-25 10:24
I'm also trying to solve a similar problem - my form contains a dynamic number of sub-forms, and I want to submit them all in one go.

The approach that makes the most sense to me is to create the sub-forms as separate `ReduxForm` instances, and then when I submit the main form, first call submit on all the sub-forms and gather their data (along the lines of what @erikras said at the top as I understand it, "Another alternative would be to make each subform a separate form, e.g. form: 'profile.children', formKey: '0', and merge all the form data later on submit").

However, I can't find a way to call "submit" on the sub-forms from the parent. My initial thinking (which I understand is something of an anti-pattern in React) was to expose a `submit()` method, which would call `this.props.handleSubmit` in the child component and return the validated result. However, I can't access methods on the child component from outside, as they are replaced with `<ConnectedForm/>` components which do not seem to expose the actual component they wrap. I might try @erikras's suggestion from https://github.com/erikras/redux-form/issues/173, but it seems pretty messy!

The other alternative I am thinking of, which seems to be along the lines of what is being discussed here, is to dynamically generate the list of all fields including the subfields using the ID to make sure field names are unique (e.g. `SubForm_123456-1234.name`) and then pass the relevant subset of fields into the component which renders the sub-form components, but this seems messier to my mind, especially when thinking about validation and so on.

**Comment by jsheetzati** [comment] 2015-11-27 02:13
+1 for this feature.  Thanks @erikras!

**Comment by jalet** [comment] 2015-11-27 08:45
+1 for this

**Comment by erikras** [comment] 2015-11-28 15:29
Come and get it! [`v3.1.0`](https://github.com/erikras/redux-form/releases/tag/v3.1.0)

**Closed by erikras** 2015-11-28 15:29 UTC
Labels: enhancement

**Comment by rogeriochaves** [comment] 2015-11-28 23:44
Awesome! Nice job @erikras :D

**Comment by ingro** [comment] 2015-11-30 10:03
Great work!

**Comment by tomduncalf** [comment] 2015-11-30 10:10
This is brilliant and literally right as I needed it, thanks very much @erikras - and thanks for this excellent library! :+1:

**Comment by tomduncalf** [comment] 2015-11-30 11:01
@erikras, should this work with `initialValues`? I have just been playing with the example code while evaluating whether to change my homegrown solution to use this or not, and they don't seem to work as expected:

Modifying the export in `DeepForm.js` to 

```
export default reduxForm({
  form: 'deep',
  fields,
  initialValues: {
    name: 'Tom',
    shipping: {
      city: 'London',
      phones: [
        '123',
        '456'
      ]
    }
  }
})(DeepForm);
```

The name and city get populated as expected, but no phone number inputs are created:

![image](https://cloud.githubusercontent.com/assets/5458070/11469838/3e4d3b0a-9751-11e5-80bc-6d83161456ac.png)

and the values are not returned by the form:

![image](https://cloud.githubusercontent.com/assets/5458070/11469848/4ee2699a-9751-11e5-9431-4db477a74c50.png)

and it seems that the `values.phones` prop is an empty array:

![image](https://cloud.githubusercontent.com/assets/5458070/11469833/3110808c-9751-11e5-8c7c-e4c46afdece8.png)

However, if I add a few phone number inputs, these values appear in the first two:

![image](https://cloud.githubusercontent.com/assets/5458070/11469855/5f13522a-9751-11e5-81b6-7036884c67dc.png)

but still do not populate the values unless I "touch" them first:

![image](https://cloud.githubusercontent.com/assets/5458070/11469868/6aabdfc6-9751-11e5-8764-fa5f4921aaa8.png)

Additionally, trying to add `children` to the initial values like:

```
    children: [
      {
        'name': 'Tom Jr',
        'age': '123',
        'awards': []
      }
    ]
```

causes the page load to fail with console errors:

![image](https://cloud.githubusercontent.com/assets/5458070/11469912/9e1f0ebe-9751-11e5-8e53-5075ec01797a.png)
![image](https://cloud.githubusercontent.com/assets/5458070/11469918/a316eb12-9751-11e5-80b5-7a176ef24748.png)

Would be great to get your input on this, I only briefly looked at this so may be doing something stupid!

Thanks,
Tom

**Comment by slybridges** [comment] 2015-11-30 11:33
It's a bug, see #345

**Comment by tomduncalf** [comment] 2015-11-30 11:35
Ah thank you @slybridges, I should have checked the issues first!

**Comment by erikras** [comment] 2015-11-30 14:41
Initialization bug fixed in `v3.1.1`.

**Comment by iNikNik** [comment] 2015-12-01 21:42
@erikras wow!!! That's awesome!! THANK YOU)

**Comment by asaf** [comment] 2015-12-04 10:56
:)

**Comment by soundyogi** [comment] 2017-07-09 18:24
Hiya, does this still work? There is no example anymore :) thanks

**Comment by binshu2013** [comment] 2018-01-10 02:37
Does anybody know where I can find the source code for this DeepForm example, or maybe other coding example for nested form? Thanks!
