### ISSUE TITLE
Get values/states in FormSection

### ISSUE THREAD

**Issue by zmaglica** [erikras/redux-form#3168] opened 2017-07-11 13:16 UTC
Hello,

I started to learn redux and redux-forms few days ago. For my project I used latest Redux form and i split original form into multiple FormSections. Inside user registration "FormSection" I want to dynamically add new fields based on field/state values. Problem is that I can't get values of current form section.

 I tried all I could find but I didn't find any solution.

Is there way to get form values inside FormSections?

Here is Form Section code I use:

```jsx
class BookerInformation extends FormSection {

    static defaultProps = {
        name: "booker"
    }
    handleEmailBlur(event){

        //triggers error that state is empty/undefined
        //fetchUser(this.state.email);
        const ItemList = formValues('booker.name')(BookerInformation)
        const ItemList2 = formValues({name: 'name'})(BookerInformation)
        const ItemList3 = formValues('busRentForm')(BookerInformation)

        //outputs original code of formValues

        console.log(ItemList);
        console.log(ItemList2);
        console.log(ItemList3);
    }

    render() {
        return <div className="booker-form">
            <div className="thumbnail thumbnail-full cardbox booker-info">
                <div className="caption">
                    <h4>Booker information</h4>
                    <div className="row">
                        <Field name="name" validate={[required, maxLength15]} classname="col-md-4" type="text"
                               icon="icon-User" component={renderInput}
                               label="Full Name"/>
                        <Field name="phone" classname="col-md-4" validate={[required]} type="text"
                               component={renderInput} icon="icon-Phone"
                               label="Phone"/>

                    </div>
                    <div className="row">

                        <Field name="email" onBlur={this.handleEmailBlur} classname="col-md-4"
                               validate={[required, email]} type="email" component={renderInput} icon="icon-Email"
                               label="E-mail"/>
                    </div>

                    <div className="row text-center">
                        <button type="button" className="btn btn-continue waves-effect waves-light">Continue</button>
                    </div>

                </div>
            </div>
        </div>
    }
```

**Comment by danielrob** [comment] 2017-07-25 04:17
@zmaglica, thanks for this. A current solution which you can use now, and and a proposal to make this easier than the current solution is available at https://github.com/erikras/redux-form/issues/3182#issue-242856265. You will need to add an HOC that can use the prefixed name prop, and inject it for you. I'm closing this issue as a duplicate of #3182.

**Closed by danielrob** 2017-07-25 04:17 UTC
