### ISSUE TITLE
destroyForm cannot be called from parent

### ISSUE THREAD

**Issue by LiranBri** [erikras/redux-form#775] opened 2016-03-31 12:50 UTC
Hello,

In the [Wizard example](http://redux-form.com/4.2.0/#/examples/wizard?_k=sagtdm) it is written that we must call **DestroyForm** manually after a successful submit.

The problem is that we handle the submit in the parent, so we can't call it because it is a prop belong to the form (the child) and not the parent.

if the child form could somehow know when a successful submit occurred, then it could call it.
I could only find ** submitFailed** prop so I guess what I am missing is something like **submitSuccedd** so I can handle the success case as well where i can call **DestroyForm**.

thanks

**Comment by erikras** [comment] 2016-03-31 13:55
You'll have to dispatch it yourself.

```js
import { destroy } from 'redux-form';
...
dispatch(destroy('myForm'));
```

It can be done after the `handleSubmit` promise resolves like this. https://github.com/erikras/redux-form/issues/527#issuecomment-170980950

**Comment by LiranBri** [comment] 2016-03-31 14:44
thanks. might be a good idea to explain it in the Wizard example. in the example they also handle the submit from the parent, so this part is missing for having a complete example.

in general, it would be great if the examples could be added to github

**Comment by erikras** [comment] 2016-03-31 14:48
They are in github, read the top of [the Examples page](http://redux-form.com/4.2.0/#/examples), but yes, for `v5`, I plan on moving them into the `master` branch.

**Comment by LiranBri** [comment] 2016-04-13 13:59
@erikras i tried following your suggestion, but even when my onHandle method returns a rejected promise, the handleSubmit's promise is fulfilled - so as a result, the form state is getting destroyed even if there was a server-side validation error. any thoughts on that?

**Comment by ooflorent** [comment] 2016-04-28 12:39
I'm closing this issue since @erikras gave you indications about the resolution. If you haven't solved your issue yet, please use StackOverflow. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

Feel free to post a link to the StackOverflow question with a sample to reproduce your case, and I’ll be happy to try to answer it.

**Closed by ooflorent** 2016-04-28 12:39 UTC
