### ISSUE TITLE
shouldComponentUpdate wrong behaviour (pure: true / false)

### ISSUE THREAD

**Issue by ms88privat** [erikras/redux-form#2833] opened 2017-04-20 07:58 UTC
### Are you submitting a **bug report** or a **feature request**?
Bug report.

### What is the current behavior?
If I pass `pure: true` to `reduxForm` it doesn't re-render if the data did only change by reference.
If I pass `pure: false` it always re-renders.

### What is the expected behavior?
If I pass `pure: true` to `reduxForm` it should re-render the component if something did change by shallow equal.
If I pass `pure: false` it should only re-render if the data has changed by deepEqual means.

### Sandbox Link
This code doesn't make sense to me. Why it will compare deepEqual if the option is passed as pure?
```js
shouldComponentUpdate(nextProps) {
            if (!this.props.pure) return true
            return Object.keys(nextProps).some(prop => {
              // useful to debug rerenders
              // if (!plain.deepEqual(this.props[ prop ], nextProps[ prop ])) {
              //   console.info(prop, 'changed', this.props[ prop ], '==>', nextProps[ prop ])
              // }
              return !~propsToNotUpdateFor.indexOf(prop) && !deepEqual(this.props[prop], nextProps[prop])
            })
          }
```

### What's your environment?
v6.6.3

### Other information
I did something like this:

reduxConnectHOC -> PureComponentHOC -> reduxFormHOC

if reduxConnect will return a new reference, the PureComponent afterwards will update, but not reduxForm. This leads to a Bug in my application later on. What I can do now is to pass `pure: false` to it and wrap it always in a PureComponent... but this looks so wrong

**Comment by ms88privat** [comment] 2017-04-20 08:02
related, but different case: https://github.com/erikras/redux-form/issues/2456

**Comment by ms88privat** [comment] 2017-04-20 08:04
Ah, now I think I understand how this should be used. Basically I did it already. If I pass `pure: true` it means, that I have to use a PureComponent for my form by myself instead of reduxForm is doing this one for me. That should be fine.

**Comment by danielrob** [comment] 2017-07-24 20:12
@ms88privat In the react ecosystem `false` purity implies that you should just always re-render. That is intended behaviour here. Note that `pure = true` is the default behaviour and that appears to be what you're after. 

However it's true that the documentation states regarding pure: 

> If true, implements `shouldComponentUpdate` and **shallowly** compares only the Redux-connected props

Yet indeed [deepEquals](https://github.com/erikras/redux-form/blob/master/src/structure/plain/deepEqual.js) is being called when [`pure` is true ](https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L490). 

This is probably a documentation error.

**Comment by danielrob** [comment] 2017-07-24 20:22
@ms88privat I'm eagerly closing this because the current behaviour you stated is correct.

**Closed by danielrob** 2017-07-24 20:22 UTC
