### ISSUE TITLE
Still receive deprecations warnings for PropTypes even i use all most recent versions.

### ISSUE THREAD

**Issue by georgearrowwood** [erikras/redux-form#3419] opened 2017-09-16 13:38 UTC
i receive these warnings when i import redux-form in to project:

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

I am on Mac, use Webpack, use all almost  most recent versions:

"prop-types": "^15.5.10",
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-redux": "5.0.6",
    "react-router": "4.2.0",
    "react-router-dom": "4.2.2",
    "react-router-redux": "5.0.0-alpha.6",

**Comment by gustavohenke** [comment] 2017-09-17 00:58
Duplicate of #3385

**Closed by gustavohenke** 2017-09-17 00:58 UTC

**Comment by erikras** [comment] 2017-10-06 14:56
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
