### ISSUE TITLE
v7.0.4 Jest console warnings

### ISSUE THREAD

**Issue by hvolschenk** [erikras/redux-form#3391] opened 2017-09-07 20:16 UTC
### What is the current behavior?
When using `v7.0.3` I can run Jest tests without any warnings being logged to the console.

### What is the expected behavior?
To upgrade to `v7.0.4` without the console warnings appearing.

### Sandbox Link
Unfortunately none available right now.

### What's your environment?
**OS**: Any (Tested on Ubuntu/MacOS)
**Node**: v8.2.1
**NPM**: 5.3.0

### Other information
The errors that started appearing in the console are as follows:

```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

and

```
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

If I look at [the diff between v7.0.3 and v7.0.4](https://github.com/erikras/redux-form/compare/v7.0.3...v7.0.4) I see there are a few introductions of `import * as React from 'react'` which it seems is causing the error(s) as this is importing everything (including PropTypes) from the 'react' package.

These warnings do not appear in the browser, and only in the console when running Jest tests.

**Comment by gustavohenke** [comment] 2017-09-07 20:50
Duplicate of #3385

**Closed by gustavohenke** 2017-09-07 20:50 UTC

**Comment by hvolschenk** [comment] 2017-09-07 20:52
Thanks @gustavohenke

**Comment by hvolschenk** [comment] 2017-10-06 21:09
Thanks a lot @erikras
