### ISSUE TITLE
onSubmit function is executed even with validation errors

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#2988] opened 2017-05-30 23:27 UTC
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
In this example - http://redux-form.com/6.7.0/examples/syncValidation/, validation function returns errors object. If you remove the fields or change their names, there will be still errors, but `onSubmit` function will be executed.

### What is the expected behavior?
`onSubmit` should not be executed if `validate` returns errors

### Sandbox Link
- [codesandbox field names changed](https://codesandbox.io/s/Ro1gBnG1E)
- [codesandbox fields removed](https://codesandbox.io/s/X6yKWn7qA)
- [bug demo repo link](https://github.com/VladShcherbin/redux-form-bug)

### What's your environment?
mac os 10.12.5
node 7.10.0
npm 4.2.0

"react": "^15.5.3"
"react-dom": "^15.5.3"
"react-redux": "^5.0.4"
"redux": "^3.6.0"
"redux-form": "6.7.0"

**Comment by VladShcherbin** [comment] 2017-05-30 23:39
Here is the [repo with the bug](https://github.com/VladShcherbin/redux-form-bug).

The only thing was changed - [field names were changed](https://github.com/VladShcherbin/redux-form-bug/commit/228538f6a72903dd29853c816a517238177273c5).

**Comment by VladShcherbin** [comment] 2017-05-31 04:44
Reproduced on codesandbox. First one is with field names changed, second one is form with fields removed.

- [codesandbox field names changed](https://codesandbox.io/s/Ro1gBnG1E)
- [codesandbox fields removed](https://codesandbox.io/s/X6yKWn7qA)

**Comment by VladShcherbin** [comment] 2017-06-03 04:53
Okay, `isValid` function has [syncErrors here](https://github.com/erikras/redux-form/blob/master/src/selectors/isValid.js#L22), but the are irrelevant [here](https://github.com/erikras/redux-form/blob/master/src/selectors/isValid.js#L31-L45) if:

- there are no `registeredFields` (no fields in the form) or
- `registeredFields` are not the same as `syncErrors`

So, for example if `syncErrors` is `{ age: 'Required' }` and the form doesn't have `age` field - it is valid.

cc @erikras

**Comment by VladShcherbin** [comment] 2017-06-06 09:51
cc @gustavohenke Can you have a look why it is designed to omit errors?

**Comment by gustavohenke** [comment] 2017-06-07 09:33
I could help by debugging and looking at the history of the Git repo, but @erikras is probably the best person to answer this. I'm not doing code changes at all, just managing the issues.

IMO, I think the behavior is good as it currently stands.

P.S.: Nice investigation skills, I dream about the day every bug report is like this one 💭

**Comment by VladShcherbin** [comment] 2017-06-17 04:42
Oh, I guess it's a [known bug (or a feature)](https://github.com/erikras/redux-form/issues/1520) for at least a year. Maybe a form prop `validateUnmounted` or similar can help this.

**Comment by danielrob** [comment] 2017-07-21 22:15
Thanks @VladShcherbin - so it looks like this is a self-proclaimed duplicate of #1520? Please don't hesitate to correct me if I've misunderstood!

**Closed by danielrob** 2017-07-21 22:15 UTC
