### ISSUE TITLE
radio, checkbox, and select form elements returning 'undefined' values onSubmit

### ISSUE THREAD

**Issue by amituuush** [erikras/redux-form#2313] opened 2016-12-20 04:32 UTC
I have a form where all my text inputs work correctly onSubmit, but my radio, checkbox, and select form elements return 'undefined' values when I console.log the props that are handed to the action creator that's called onSubmit.

I've been digging through github issues but can't seem to find an issue that has figured this out. Any help would be greatly appreciated! 

Here's what my code looks like:

```jsx
import React, { Component } from 'react';
const  { DOM: { input, select, textarea } } = React
import { Field, reduxForm } from 'redux-form';
import { Button, Form, Message, Select } from 'semantic-ui-react';
import { submitUserOnboardForm } from '../../redux/actions';

const genders = [
  { text: 'Male', value: 'male' },
  { text: 'Female', value: 'female' },
  { text: 'I would prefer not to share', value: 'none' },
];

class UserOnboardForm extends Component {

  render() {
    const { fields: { firstName, lastName, location, gender, websiteUrl, notifications, codingQuestions}, handleSubmit} = this.props;

    return (
      <Form onSubmit={handleSubmit(data => this.props.submitUserOnboardForm(data))}>

        <Form.Field>
          <label>First Name</label>
          <input placeholder="First Name" {...firstName} />
          {firstName.touched && firstName.error ?
            <Message>
               {firstName.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field>
          <label>Last Name</label>
          <input placeholder="Last Name" {...lastName} />
          {lastName.touched && lastName.error ?
            <Message>
               {lastName.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field>
          <label>Location</label>
          <input placeholder="Where are you?" {...location} />
          {location.touched && location.error ?
            <Message>
               {location.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field>
          <Select placeholder='Select your country' options={genders} placeholder="Gender" {...gender} />
          {/* <Form.Select label="Gender" name="gender" options={genders} placeholder="Gender" {...gender} /> */}
          {gender.touched && gender.error ?
            <Message>
               {gender.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field>
          <label>Personal Website</label>
          <input placeholder="Let others see what you've built!" {...websiteUrl} />
          {websiteUrl.touched && websiteUrl.error ?
            <Message>
               {websiteUrl.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field>
          <label>I want to receive desktop notifications when I match with someone!</label>
          <Form.Group inline {...notifications}>
            <Form.Radio
              inline label="Yes!"
              name="notifications"
              value="yes"
            />
            <Form.Radio
              inline label="Not at this time, but thanks!"
              name="notifications"
              value="no"
            />
          </Form.Group>
          {notifications.touched && notifications.error ?
            <Message>
               {notifications.error}
           </Message> : ''}
        </Form.Field>

        <Form.Field {...codingQuestions}>
          <label>Check whatever you've done before</label>
          <Form.Group grouped>
            <Form.Checkbox
              label="I just started coding"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="I know the basics"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="I'm in a coding bootcamp"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="I finished a coding bootcamp and am looking for a job"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="1-2 years of professional experience"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="3-4 years of professional experience"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="5-10 years of professional experience"
              name="shippingOptions"
              value="temp"
            />
            <Form.Checkbox
              label="10+ years of professional experience"
              name="shippingOptions"
              value="temp"
            />
          </Form.Group>
          {codingQuestions.touched && codingQuestions.error ?
            <Message>
               {codingQuestions.error}
           </Message> : ''}
        </Form.Field>
        <Button type="submit">Submit</Button>
      </Form>
    )
  }
}

function validate(formProps) {
  const errors = {};

  if (!formProps.firstName) {
    errors.firstName = "Enter your first name";
  }

  if (!formProps.lastName) {
    errors.lastName = "Enter your last name";
  }

  if (!formProps.location) {
    errors.location = "Tell us where you are!";
  }

  // if (!formProps.gender) {
  //   errors.gender = "Please enter a gender.";
  // }

  // if (!formProps.notifications) {
  //   errors.notifications = "Let us know if you want to receive notifications.";
  // }
  //
  // if (!formProps.codingQuestions) {
  //   errors.codingQuestions = "We need to know a little more about you before moving on!";
  // }

  return errors;
}

export default reduxForm({
  form: 'UserOnboardForm',
  fields: ['firstName', 'lastName', 'location', 'gender', 'websiteUrl', 'notifications', 'codingQuestions'],
  validate
}, null, { submitUserOnboardForm })(UserOnboardForm);
```

**Comment by MeterSoft** [comment] 2017-01-11 17:58
hi, have same problem with select.

If submit form without any change on select then value is undefinded

my select

`<Field name="category_id" component={Input} label="Category" componentClass="select" >
                {
                  categories.data.map((category) => {
                    return <option value={category.id}">{category.title}</option>
                  })
                }
              </Field>`

`class Input extends Component {
  
  render () {
    const {
      feedbackIcon,
      input,
      label,
      type,
      meta: { error, warning, touched },
      ...props
    } = this.props;

    let message;
    const validationState = (touched && ( error && "error" )) || ( warning && "warning" ) || null;

    if ( touched && ( error || warning ) ) {
      message = <span className="help-block">{ error || warning }</span>;
    }
  
    return (
      <FormGroup validationState={ validationState }>
        <ControlLabel>{ label }</ControlLabel>
        <FormControl { ...input }
                     type={ type }
                     { ...props } />
        { feedbackIcon ? <FormControl.Feedback>{ feedbackIcon }</FormControl.Feedback> : null }
        { message }
      </FormGroup>
    );
  }
}`

**Comment by MeterSoft** [comment] 2017-01-11 18:26
@erikras any idea?

**Comment by erikras** [comment] 2017-01-18 14:05
@amituuush You are clearly using `v5`, but for some reason you are importing `Field`, which was introduced in `v6`. Can you confirm that you are really using `redux-form@5.x.x`?

**Comment by MeterSoft** [comment] 2017-01-18 14:22
i use "redux-form": "^6.4.3",

**Comment by erikras** [comment] 2017-01-18 15:08
@MeterSoft You have to initialize the value to the default if you want there to be a value when you submit without touching the `<select>`.

`redux-form` can't know what the first `<option>` you have placed inside your `<select>` is.

```jsx
reduxForm({
  form: myForm,
  initialValues: {
    category_id: categories.data[0].id // if you want it to default to the first one
  }
})
```

**Comment by amituuush** [comment] 2017-01-31 00:02
I am using "redux-form": "^6.3.2"

**Comment by danielrob** [comment] 2017-07-25 18:44
This was largely duplicated by #3226. Closing as a duplicate of #3226.

**Closed by danielrob** 2017-07-25 18:44 UTC
