### ISSUE TITLE
redux-form@6.0.0-alpha.4 can not compatible with webpack2

### ISSUE THREAD

**Issue by zhuzhenzhen** [erikras/redux-form#875] opened 2016-04-27 10:58 UTC
redux-form@6.0.0-alpha.4 can not compatible with webpack2

**Comment by zhuzhenzhen** [comment] 2016-04-27 10:58
redux-form@6.0.0-alpha.4 can not compatible with webpack2

**Comment by erikras** [comment] 2016-04-27 13:01
Can you explain? Error messages?

**Comment by anaibol** [comment] 2016-04-28 12:50
I am using it with webpack@2.1.0-beta.5 and it seems to work very good!

**Comment by aight8** [comment] 2016-04-29 13:38
Works here too.

**Comment by ooflorent** [comment] 2016-04-29 13:42
I'm closing this issue bacause we are not able to reproduce it.
If the problem persists, could you please reopen it and join your `package.json` and the error log?

**Closed by ooflorent** 2016-04-29 13:42 UTC
