### ISSUE TITLE
Upgrade to v8+ cause infinite loop

### ISSUE THREAD

**Issue by sashberd** [erikras/redux-form#4521] opened 2019-08-14 13:16 UTC
Hi,
We started to upgrade our app libs and faced with issue with your lib. When we upgraded  from v7.3.0 to 8.2.6 we get infinite loop from redux form. We are isolated this  issue and we know that it caused by redux form.

Below provided our code example from one of our redux form:

```
render() { const { t, handleSubmit, theme: { axisPalette }, submitting, pristine, } = this.props; return (
<form autoCapitalize="none" autoCorrect="off" onSubmit={handleSubmit(this.submitForm)}>

    <div className="input-wrapper">
        <Field label={`${t(`${FULL_NAME}`)}*`} name={FULL_NAME} component={renderInput} disabled={submitting} />
    </div>

    <div className="input-wrapper email-field">
        <Field label={`${t(`${EMAIL}`)}*`} name={EMAIL} component={renderInput} disabled={submitting} nativeInputProps={{ style: isRtl ? { textAlign: 'left', direction: 'ltr' } : {}, }} type="email" />
    </div>
    
    <div className="input-wrapper">
        <Field label={`${t(`${ABOUT_YOU}`)}`} name={ABOUT_YOU} component={renderTextArea} disabled={submitting} showMultilineUnderline={true} focusedUnderlineColor={axisPalette.accentColor} rows={1} enableInputTopMargin={true} />
    </div>

    <div className="checkbox">
        <Field name={NEWSLETTER} component={renderCheckBox} //disabled={submitting} withError={true} />
        <span className="checkbox-label">{t(`${NEWSLETTER}`)}</span>

    </div>
    <Field component={renderInput} type="hidden" name={HIDDEN_INPUT} style={{ display: 'none' }} />
</form>


const enhance = compose(
  translate(),
  withTheme(),
  reduxForm({
    form: 'EditUserForm',
    validate: (values, props) => {
      const errors = {};
      const { t } = props;

      errors[`${EMAIL}`] = t(validateEmailField(values[`${EMAIL}`]));
      errors[`${ABOUT_YOU}`] = t(verifyInputLength(values[`${ABOUT_YOU}`], MAX_LENGTH_ABOUT_YOU));
      errors[`${FULL_NAME}`] = t(verifyInputLength(values[`${FULL_NAME}`], MAX_LENGTH_FULL_NAME));
      if (!values[`${FULL_NAME}`]) errors[`${FULL_NAME}`] = t('requiredField');

      return errors;
    },
    onSubmitFail: (errors) => scrollToError(requiredFieldList)(errors),
    onSubmitSuccess: (result, dispatch, props) => {
      props.handleSubmitSuccess(true);
    },
    enableReinitialize: true,
    destroyOnUnmount: false,
  })
);

```
To this form passed initalValues from upper component

```
    let initialValuesMyDetails = {
      [`fullName`]: fullName,
      [`email`]: email,
      [`aboutYou`]: locale.iso === 'lv' ? currentUser.oldAboutMe : currentUser.oldAboutMeEn,
      [`newsletter`]: isSubscribedToNewsletter || false,
    };
```

The error that we get is:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate

And the stack trace points to disabled={submitting}prop in first Field

### What's your environment?
"react": "16.9.0",
"react-redux": "7.1.0",
"redux": "4.0.4",
"redux-form": "8.2.6",

If you need any another information we will glad to provide it to you in order to solve this, as we  think, issue

**Comment by renatoagds** [comment] 2019-08-14 13:57
@sashberd could help us providing a [`codesandbox`](https://codesandbox.io/dashboard) that reproduce this problem?

**Comment by x8lucas8x** [comment] 2019-08-21 13:38
I've also experienced the same error/exception on:

"react": "16.8.6",
"react-redux": "7.1.0",
"redux": "4.0.4",
"redux-form": "8.2.6",

**Comment by renatoagds** [comment] 2019-08-22 14:46
@x8lucas8x Could u help and provide a `sandbox`? I need an code example so I could work in a fix.

**Comment by renatoagds** [comment] 2019-09-25 16:14
@eldar-gamisoniya I wasn't able to get any error from your sandbox.

**Comment by renatoagds** [comment] 2019-09-25 16:14
I'm closing this issue since I couldn't reproduce, if someone returns with some workable sandbox example I'll be happy to reopen it.

**Closed by renatoagds** 2019-09-25 16:14 UTC
Labels: bug, needs sandbox

**Comment by eldar-gamisoniya** [comment] 2019-09-25 16:17
@renatoagds it doesn't throw any errors, the test is just running indefinitely, unable to finish.

**Comment by renatoagds** [comment] 2019-09-25 16:27
@eldar-gamisoniya Thanks for your example, but I couldn't extract any idea about what is happening from it. If you could create something more reachable I'll be awesome.

**Comment by sashberd** [comment] 2019-10-17 09:57
@renatoagds 
HI after deep investigation and help from our third party partner we found that this infinite loop was the result of our programming. However, this code did not provided such infinite loop with old lib version.
Our old configuration was:
 "redux": "^4.0.0",
 "redux-form": "^7.3.0",
Our new configuration is:
"redux": "^4.0.4",
"redux-form": "^8.2.6",

The code issue was in next pattern:
```
<SwipeableViews
          index={this.state.slideIndex}
          onChangeIndex={this.handleChange}
          enableMouseEvents={true}
          disableLazyLoading={true}>
          {sections.map((section, index) => (
            <div
              **key={Date.now() + index}**
              style={{
                ...slideStyles,
                ...section.styles,
                maxHeight: index === this.state.slideIndex ? '' : 'calc(100vh - 132px)',
                minHeight: index === this.state.slideIndex ? 'calc(100vh - 132px)' : '',
              }}>
              {React.cloneElement(section.content,)}
            </div>
          ))}
        </SwipeableViews>
```
Let me explain some of vars here:
sections - is an array of Components that has content prop with Component to render
The issue was in parent div with its key property (bolded) that is defined as Date.now() + index. 
I understand that such key is not acceptable anyway and such code is beneath every review, however, in version 7.3.0 it did not provide any loop and worked perfect. 
May be in old version you had some defence from such coding errors that in new version was removed or upgraded.
FYI guys
Hope this will help to someone

**Comment by doge-lord** [comment] 2019-10-25 05:20
I'm also encountering this with the same example provided by  @eldar-gamisoniya 

I think the issue here is caused by `forwardRef` having circular structure. Similar to using JSON.stringify on it (at least stringify will throw an error), the default serializer config will try to serialize an infinite loop.

**Work-around when using 'enzyme-to-json' **
I modified the enzyme serializer instead to remove `forwardedRef` on certain json.type patterns

`
import { createSerializer } from 'enzyme-to-json';

function mapJson(json) {
  // Fix snapshot error when mounting redux-form components due to circular structure
  if (json.type === 'Connect(ConnectedField)' || /Connect\(Form\(\w+\)\)/.test(json.type)) {
    return {
      ...json,
      props: {
        ...json.props,
        forwardedRef: undefined
      }
    };
  }

  return json;
}

expect.addSnapshotSerializer(createSerializer({ map: mapJson }));
`
