### ISSUE TITLE
In this environment, the sources for assign MUST be an object

### ISSUE THREAD

**Issue by Seeker93** [erikras/redux-form#3298] opened 2017-08-08 07:59 UTC
Hi guys

I keep getting this error when following the article suggested in the docs : 

> In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

I have followed the steps until step 3, and no amount of fiddling has helped me. Any suggestions would be more than welcome. 

Article : http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/

My Stackoverflow link : https://stackoverflow.com/questions/45561845/redux-form-in-this-environment-the-sources-for-assign-must-be-an-object

**Comment by gustavohenke** [comment] 2017-08-17 11:37
Since I have no way to test react native at the moment, I summon... @esbenp, our jedi in this platform!

**Comment by beornborn** [comment] 2017-08-26 10:49
workaround

```javascript
<NativeInput
      {...other}
      value={input.value.value}
      onChangeText={(v: string) => input.onChange({value: v})} />
```

**Comment by esbenp** [comment] 2017-08-29 07:18
I was unable to reproduce this using `react-native 0.47.2` and `redux-form` v6 and v7. What version are you using?

<details>
   <summary>This is the code I used</summary>

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View
} from 'react-native';
import { createStore } from 'redux'
import { combineReducers } from 'redux-immutablejs'
import { reducer as formReducer } from 'redux-form/immutable'
import { fromJS } from 'immutable'
import { Provider } from 'react-redux'
import { Field, reduxForm } from 'redux-form/immutable'

const reducer = combineReducers({
  form: formReducer
})

const store = createStore(reducer, fromJS({}))

export default class reduxFormTest extends Component {
  render() {
    return (
      <Provider store={store}>
        <View style={{marginTop: 50}}>
          <Form />
        </View>
      </Provider>
    );
  }
}

const submit = values => {
  console.log('submitting immutable form', values.toJS())
}

const renderInput = ({ input: { onChange, ...restInput }}) => {
  return <TextInput style={styles.input} onChangeText={onChange} {...restInput} />
}

let Form = props => {
  const { handleSubmit } = props

  return (
    <View style={styles.container}>
      <Text>Email:</Text>
      <Field name="email" component={renderInput} />
      <TouchableOpacity onPress={handleSubmit(submit)}>
        <Text style={styles.button}>Submit</Text>
      </TouchableOpacity>
    </View>
  )
}

Form = reduxForm({
  form: 'immutable'
})(Form)

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  input: {
    borderColor: 'black',
    borderWidth: 1,
    height: 37,
    width: 250
  }
});

AppRegistry.registerComponent('reduxFormTest', () => reduxFormTest);
```
</details>

The error occurs because somewhere in the code `Object.assign` is used and the `target` argument is not an object. See more here https://github.com/facebook/react-native/blob/c404425d0fc5bb9a0a18b73695ec4a3f04ee8890/Libraries/polyfills/Object.es6.js#L26

**Comment by beornborn** [comment] 2017-08-29 11:10
@esbenp 

react-native@0.46.4
redux-form@7.0.3
redux@3.7.2

I didn't use immutable stuff:
```
import ... from 'redux'
import ... from 'redux-form'
```

**Comment by esbenp** [comment] 2017-08-29 12:47
Hmmm.. I have tried without immutable - still works here. I have added this repo https://github.com/esbenp/redux-form-issue-3298/blob/master/index.ios.js

Feel free to see if you can clone it into a non-working demo so I have a reproducable example

**Comment by ValentinBlokhin** [comment] 2017-08-29 18:43
I have the same issue.
I don't use immutable.
"redux-form": "7.0.3",
"react-native": "0.47.2",
 "redux": "3.6.0"

It's falling on 
https://github.com/erikras/redux-form/blob/master/src/ConnectedField.js
lineNumber: 106

Because value that TextInput send is not a plain object, it fails on this statement.

**Comment by esbenp** [comment] 2017-08-31 11:46
Alright, well that makes sense. `{...event, preventDefault: () => {}}` translates into `Object.assign(event, {preventDefault: () => {})` I suppose? The `Object.assign` polyfill in React Native cannot take targets that are objects or functions, so if event is neither Object or Function then the method will fail. I am not super familiar with `redux-form`, maybe someone else can take a stab at a PR? Ping @gustavohenke

**Comment by otajor** [comment] 2017-10-16 15:50
Fixed in v7.1.0: 
https://github.com/erikras/redux-form/issues/3153#issuecomment-334778589

**Comment by gustavohenke** [comment] 2017-10-17 19:47
> I am not super familiar with redux-form, maybe someone else can take a stab at a PR? Ping @gustavohenke

Neither am I 😄 I do mainly issue triaging!

@Seeker93 @ValentinBlokhin @beornborn @esbenp can you please confirm this is fixed?

**Comment by gustavohenke** [comment] 2018-01-29 05:56
Will consider the silence as an yes. 👆

**Closed by gustavohenke** 2018-01-29 05:56 UTC

**Comment by Luckygirlllll** [comment] 2018-02-22 11:27
I got the same error, how to fix it?

**Comment by gustavohenke** [comment] 2018-02-22 11:29
The answer is just above: https://github.com/erikras/redux-form/issues/3298#issuecomment-336930367

**Comment by beornborn** [comment] 2018-02-22 11:32
@Luckygirlllll you can check example here https://github.com/beornborn/closies-app/blob/master/app/components/__shared/TextInput.js

привет из Киева ))

**Comment by Luckygirlllll** [comment] 2018-02-22 11:34
@gustavohenke  Comment #3298 is "Will consider the silence as an yes.". You mean, that I need to upgrade redux-form to the v7.1.0 ?

**Comment by Luckygirlllll** [comment] 2018-02-22 11:42
@beornborn I have such Field, what should I change in  onChange() in order not to have  error?   

```
  <Field
                    name = 'paymentMethod'
                    component={PaymentMethodInput}
                    validate={[validation.required]}
                    type="flat"
                    style={StyleSheet.halfMarginTop}
                    placeholder={_('paymentMethod')}
                    disabled={this.props.editMode}
                    value={this.state.eventDetails.paymentMethod}
                    onChange={(paymentMethod) => {
                      if(paymentMethod === 'app' || paymentMethod === 'unrestricted') {
                        this.props.onSelectAppPayments()
                      }
                      this.setEventData({paymentMethod})
                    }}
                  >
```
И тебе привет с Киева! :)

**Comment by Luckygirlllll** [comment] 2018-02-22 12:05
Updating to the latest version of `redux-form` solved the problem.

**Comment by nandorojo** [comment] 2019-01-04 21:21
I got this error by using `...StyleSheet.absoluteFill` in my stylesheet. Took a long time to find that as the cause. Any idea why that's happening? `...StyleSheet.absoluteFillObject` fixed it.
